// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([35.328578, 139.350082], [35.402149, 139.533220]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "0605_files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(35.402149, 139.533218, 66, "2026/06/05", "07:08:51", 0, "戸塚駅前をスタート！", "0605_files/IMG_20260605_070851_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.397663, 139.530640, 74, "2026/06/05", "07:19:20", 0, "戸塚宿　澤渡本陣跡", "0605_files/IMG_20260605_071920.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.380379, 139.512253, 99, "2026/06/05", "07:46:20", 0, "原宿一里塚跡", "0605_files/IMG_20260605_074620.jpg", "", "今は何もない、、、", ""));
	waypoints.push(new MarkerInfo(35.349426, 139.490250, 73, "2026/06/05", "08:21:35", 0, "藤沢宿 遊行寺一里塚", "0605_files/IMG_20260605_082135.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.346409, 139.487381, 47, "2026/06/05", "08:28:36", 0, "藤沢宿交流館", "0605_files/IMG_20260605_082836.jpg", "", "ゴール後に見学", ""));
	waypoints.push(new MarkerInfo(35.347637, 139.482773, 44, "2026/06/05", "08:37:09", 0, "藤沢宿 蒔田本陣跡", "0605_files/IMG_20260605_083709.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.345699, 139.447830, 53, "2026/06/05", "09:14:37", 0, "一里塚跡", "0605_files/IMG_20260605_091437_1.jpg", "", "この斜めの木が一里塚の木？", ""));
	waypoints.push(new MarkerInfo(35.333569, 139.407104, 26, "2026/06/05", "09:52:02", 0, "茅ヶ崎一里塚", "0605_files/IMG_20260605_095202.jpg", "", "ここは立派な松が残っていた", ""));
	waypoints.push(new MarkerInfo(35.329906, 139.350266, 47, "2026/06/05", "10:49:52", 0, "平塚駅前", "0605_files/IMG_20260605_104952.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.329815, 139.350082, 47, "2026/06/05", "10:51:15", 0, "ゴール！", "0605_files/IMG_20260605_105115.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(35.401788, 139.533220, 0.000, 18, 0, 0, "Fri Jun 5 2026 07:10:57"));
	track[0].push(new TrackPoint(35.401743, 139.533092, 0.013, 18, 0, 0, "Fri Jun 5 2026 07:11:11"));
	track[0].push(new TrackPoint(35.401666, 139.533013, 0.024, 17, 0, 0, "Fri Jun 5 2026 07:11:20"));
	track[0].push(new TrackPoint(35.401335, 139.532467, 0.086, 18, 0, 0, "Fri Jun 5 2026 07:12:11"));
	track[0].push(new TrackPoint(35.401339, 139.532388, 0.093, 18, 0, 0, "Fri Jun 5 2026 07:12:21"));
	track[0].push(new TrackPoint(35.401485, 139.532162, 0.120, 20, 0, 0, "Fri Jun 5 2026 07:12:43"));
	track[0].push(new TrackPoint(35.401545, 139.532202, 0.128, 21, 0, 0, "Fri Jun 5 2026 07:12:51"));
	track[0].push(new TrackPoint(35.401548, 139.532165, 0.131, 21, 0, 0, "Fri Jun 5 2026 07:12:54"));
	track[0].push(new TrackPoint(35.401506, 139.532114, 0.138, 20, 0, 0, "Fri Jun 5 2026 07:12:59"));
	track[0].push(new TrackPoint(35.401328, 139.532037, 0.160, 18, 0, 0, "Fri Jun 5 2026 07:13:13"));
	track[0].push(new TrackPoint(35.401280, 139.532029, 0.166, 18, 0, 0, "Fri Jun 5 2026 07:14:02"));
	track[0].push(new TrackPoint(35.401121, 139.531934, 0.186, 19, 0, 0, "Fri Jun 5 2026 07:14:14"));
	track[0].push(new TrackPoint(35.401053, 139.531922, 0.194, 20, 0, 0, "Fri Jun 5 2026 07:14:19"));
	track[0].push(new TrackPoint(35.400881, 139.531965, 0.214, 20, 0, 0, "Fri Jun 5 2026 07:14:28"));
	track[0].push(new TrackPoint(35.400763, 139.531923, 0.227, 21, 0, 0, "Fri Jun 5 2026 07:14:37"));
	track[0].push(new TrackPoint(35.400647, 139.531952, 0.241, 20, 0, 0, "Fri Jun 5 2026 07:14:44"));
	track[0].push(new TrackPoint(35.400593, 139.531997, 0.248, 20, 0, 0, "Fri Jun 5 2026 07:14:49"));
	track[0].push(new TrackPoint(35.400520, 139.531944, 0.257, 20, 0, 0, "Fri Jun 5 2026 07:14:55"));
	track[0].push(new TrackPoint(35.400431, 139.531836, 0.271, 20, 0, 0, "Fri Jun 5 2026 07:15:01"));
	track[0].push(new TrackPoint(35.400316, 139.531666, 0.292, 21, 0, 0, "Fri Jun 5 2026 07:15:08"));
	track[0].push(new TrackPoint(35.400224, 139.531594, 0.304, 21, 0, 0, "Fri Jun 5 2026 07:15:13"));
	track[0].push(new TrackPoint(35.400201, 139.531557, 0.308, 22, 0, 0, "Fri Jun 5 2026 07:15:15"));
	track[0].push(new TrackPoint(35.400182, 139.531417, 0.321, 23, 0, 0, "Fri Jun 5 2026 07:15:21"));
	track[0].push(new TrackPoint(35.400101, 139.531382, 0.331, 24, 0, 0, "Fri Jun 5 2026 07:15:27"));
	track[0].push(new TrackPoint(35.399979, 139.531404, 0.345, 23, 0, 0, "Fri Jun 5 2026 07:15:35"));
	track[0].push(new TrackPoint(35.399861, 139.531395, 0.358, 22, 0, 0, "Fri Jun 5 2026 07:15:42"));
	track[0].push(new TrackPoint(35.399725, 139.531414, 0.373, 21, 0, 0, "Fri Jun 5 2026 07:15:49"));
	track[0].push(new TrackPoint(35.399477, 139.531324, 0.402, 20, 0, 0, "Fri Jun 5 2026 07:16:07"));
	track[0].push(new TrackPoint(35.399309, 139.531288, 0.422, 18, 0, 0, "Fri Jun 5 2026 07:16:20"));
	track[0].push(new TrackPoint(35.399273, 139.531240, 0.428, 18, 0, 0, "Fri Jun 5 2026 07:16:26"));
	track[0].push(new TrackPoint(35.398950, 139.531195, 0.464, 15, 0, 0, "Fri Jun 5 2026 07:16:50"));
	track[0].push(new TrackPoint(35.398841, 139.531123, 0.478, 15, 0, 0, "Fri Jun 5 2026 07:16:59"));
	track[0].push(new TrackPoint(35.398841, 139.531100, 0.480, 15, 0, 0, "Fri Jun 5 2026 07:17:00"));
	track[0].push(new TrackPoint(35.398734, 139.531026, 0.494, 16, 0, 0, "Fri Jun 5 2026 07:17:09"));
	track[0].push(new TrackPoint(35.398635, 139.530996, 0.506, 17, 0, 0, "Fri Jun 5 2026 07:17:18"));
	track[0].push(new TrackPoint(35.398468, 139.530871, 0.528, 19, 0, 0, "Fri Jun 5 2026 07:17:35"));
	track[0].push(new TrackPoint(35.398349, 139.530849, 0.541, 20, 0, 0, "Fri Jun 5 2026 07:17:44"));
	track[0].push(new TrackPoint(35.398322, 139.530811, 0.546, 20, 0, 0, "Fri Jun 5 2026 07:17:48"));
	track[0].push(new TrackPoint(35.398157, 139.530808, 0.564, 20, 0, 0, "Fri Jun 5 2026 07:18:00"));
	track[0].push(new TrackPoint(35.397958, 139.530678, 0.589, 20, 0, 0, "Fri Jun 5 2026 07:18:22"));
	track[0].push(new TrackPoint(35.397723, 139.530624, 0.616, 20, 0, 0, "Fri Jun 5 2026 07:18:44"));
	track[0].push(new TrackPoint(35.397627, 139.530617, 0.627, 21, 0, 0, "Fri Jun 5 2026 07:19:23"));
	track[0].push(new TrackPoint(35.397625, 139.530601, 0.629, 21, 0, 0, "Fri Jun 5 2026 07:20:28"));
	track[0].push(new TrackPoint(35.397498, 139.530565, 0.643, 21, 0, 0, "Fri Jun 5 2026 07:20:41"));
	track[0].push(new TrackPoint(35.397073, 139.530526, 0.691, 19, 0, 0, "Fri Jun 5 2026 07:21:02"));
	track[0].push(new TrackPoint(35.397022, 139.530536, 0.697, 19, 0, 0, "Fri Jun 5 2026 07:21:06"));
	track[0].push(new TrackPoint(35.396605, 139.530429, 0.744, 18, 0, 0, "Fri Jun 5 2026 07:21:28"));
	track[0].push(new TrackPoint(35.396411, 139.530343, 0.767, 19, 0, 0, "Fri Jun 5 2026 07:21:40"));
	track[0].push(new TrackPoint(35.396235, 139.530315, 0.787, 19, 0, 0, "Fri Jun 5 2026 07:21:48"));
	track[0].push(new TrackPoint(35.395852, 139.530141, 0.832, 19, 0, 0, "Fri Jun 5 2026 07:22:09"));
	track[0].push(new TrackPoint(35.395672, 139.530090, 0.853, 18, 0, 0, "Fri Jun 5 2026 07:22:18"));
	track[0].push(new TrackPoint(35.395456, 139.530066, 0.877, 17, 0, 0, "Fri Jun 5 2026 07:22:28"));
	track[0].push(new TrackPoint(35.395240, 139.530139, 0.902, 17, 0, 0, "Fri Jun 5 2026 07:22:38"));
	track[0].push(new TrackPoint(35.394999, 139.530038, 0.930, 17, 0, 0, "Fri Jun 5 2026 07:23:06"));
	track[0].push(new TrackPoint(35.394841, 139.529867, 0.954, 16, 0, 0, "Fri Jun 5 2026 07:23:21"));
	track[0].push(new TrackPoint(35.394694, 139.529823, 0.971, 16, 0, 0, "Fri Jun 5 2026 07:23:29"));
	track[0].push(new TrackPoint(35.394612, 139.529720, 0.984, 16, 0, 0, "Fri Jun 5 2026 07:23:35"));
	track[0].push(new TrackPoint(35.393941, 139.529473, 1.062, 21, 0, 0, "Fri Jun 5 2026 07:24:13"));
	track[0].push(new TrackPoint(35.393840, 139.529399, 1.076, 21, 0, 0, "Fri Jun 5 2026 07:24:19"));
	track[0].push(new TrackPoint(35.393591, 139.529310, 1.105, 18, 0, 0, "Fri Jun 5 2026 07:24:32"));
	track[0].push(new TrackPoint(35.393403, 139.529181, 1.129, 16, 0, 0, "Fri Jun 5 2026 07:24:42"));
	track[0].push(new TrackPoint(35.393330, 139.529057, 1.143, 16, 0, 0, "Fri Jun 5 2026 07:24:47"));
	track[0].push(new TrackPoint(35.393315, 139.528960, 1.152, 17, 0, 0, "Fri Jun 5 2026 07:24:51"));
	track[0].push(new TrackPoint(35.393247, 139.528776, 1.171, 17, 0, 0, "Fri Jun 5 2026 07:25:01"));
	track[0].push(new TrackPoint(35.393215, 139.528369, 1.208, 20, 0, 0, "Fri Jun 5 2026 07:25:19"));
	track[0].push(new TrackPoint(35.393197, 139.528322, 1.213, 20, 0, 0, "Fri Jun 5 2026 07:25:22"));
	track[0].push(new TrackPoint(35.393190, 139.528079, 1.235, 21, 0, 0, "Fri Jun 5 2026 07:25:32"));
	track[0].push(new TrackPoint(35.393095, 139.527756, 1.266, 21, 0, 0, "Fri Jun 5 2026 07:25:47"));
	track[0].push(new TrackPoint(35.393060, 139.527706, 1.272, 21, 0, 0, "Fri Jun 5 2026 07:25:50"));
	track[0].push(new TrackPoint(35.392970, 139.527384, 1.303, 20, 0, 0, "Fri Jun 5 2026 07:26:06"));
	track[0].push(new TrackPoint(35.393015, 139.526857, 1.352, 20, 0, 0, "Fri Jun 5 2026 07:26:25"));
	track[0].push(new TrackPoint(35.392994, 139.526677, 1.368, 20, 0, 0, "Fri Jun 5 2026 07:26:33"));
	track[0].push(new TrackPoint(35.392849, 139.525805, 1.450, 20, 0, 0, "Fri Jun 5 2026 07:27:44"));
	track[0].push(new TrackPoint(35.392631, 139.525207, 1.509, 23, 0, 0, "Fri Jun 5 2026 07:28:13"));
	track[0].push(new TrackPoint(35.392532, 139.525007, 1.531, 25, 0, 0, "Fri Jun 5 2026 07:28:25"));
	track[0].push(new TrackPoint(35.392459, 139.524905, 1.543, 26, 0, 0, "Fri Jun 5 2026 07:28:32"));
	track[0].push(new TrackPoint(35.392455, 139.524860, 1.547, 26, 0, 0, "Fri Jun 5 2026 07:28:34"));
	track[0].push(new TrackPoint(35.392177, 139.524381, 1.601, 31, 0, 0, "Fri Jun 5 2026 07:29:04"));
	track[0].push(new TrackPoint(35.391839, 139.524033, 1.651, 36, 0, 0, "Fri Jun 5 2026 07:29:33"));
	track[0].push(new TrackPoint(35.391242, 139.523499, 1.733, 39, 0, 0, "Fri Jun 5 2026 07:30:20"));
	track[0].push(new TrackPoint(35.391001, 139.523098, 1.779, 42, 0, 0, "Fri Jun 5 2026 07:30:46"));
	track[0].push(new TrackPoint(35.390909, 139.523018, 1.792, 42, 0, 0, "Fri Jun 5 2026 07:30:55"));
	track[0].push(new TrackPoint(35.390767, 139.522962, 1.808, 43, 0, 0, "Fri Jun 5 2026 07:31:03"));
	track[0].push(new TrackPoint(35.390465, 139.522709, 1.850, 48, 0, 0, "Fri Jun 5 2026 07:31:25"));
	track[0].push(new TrackPoint(35.390259, 139.522604, 1.875, 52, 0, 0, "Fri Jun 5 2026 07:31:42"));
	track[0].push(new TrackPoint(35.390232, 139.522507, 1.885, 53, 0, 0, "Fri Jun 5 2026 07:31:51"));
	track[0].push(new TrackPoint(35.389885, 139.522129, 1.937, 53, 0, 0, "Fri Jun 5 2026 07:32:20"));
	track[0].push(new TrackPoint(35.389851, 139.522117, 1.941, 53, 0, 0, "Fri Jun 5 2026 07:32:22"));
	track[0].push(new TrackPoint(35.389720, 139.521974, 1.960, 52, 0, 0, "Fri Jun 5 2026 07:32:33"));
	track[0].push(new TrackPoint(35.389538, 139.521832, 1.985, 52, 0, 0, "Fri Jun 5 2026 07:32:47"));
	track[0].push(new TrackPoint(35.389323, 139.521629, 2.015, 53, 0, 0, "Fri Jun 5 2026 07:33:04"));
	track[0].push(new TrackPoint(35.389255, 139.521582, 2.023, 53, 0, 0, "Fri Jun 5 2026 07:33:09"));
	track[0].push(new TrackPoint(35.389134, 139.521467, 2.041, 54, 0, 0, "Fri Jun 5 2026 07:33:19"));
	track[0].push(new TrackPoint(35.388877, 139.521254, 2.075, 55, 0, 0, "Fri Jun 5 2026 07:33:38"));
	track[0].push(new TrackPoint(35.388746, 139.521110, 2.095, 57, 0, 0, "Fri Jun 5 2026 07:33:49"));
	track[0].push(new TrackPoint(35.388669, 139.520999, 2.108, 57, 0, 0, "Fri Jun 5 2026 07:33:57"));
	track[0].push(new TrackPoint(35.388501, 139.520633, 2.146, 58, 0, 0, "Fri Jun 5 2026 07:34:18"));
	track[0].push(new TrackPoint(35.388450, 139.520489, 2.161, 58, 0, 0, "Fri Jun 5 2026 07:34:26"));
	track[0].push(new TrackPoint(35.388405, 139.520243, 2.184, 58, 0, 0, "Fri Jun 5 2026 07:34:39"));
	track[0].push(new TrackPoint(35.388272, 139.519801, 2.227, 58, 0, 0, "Fri Jun 5 2026 07:35:12"));
	track[0].push(new TrackPoint(35.388197, 139.519622, 2.245, 57, 0, 0, "Fri Jun 5 2026 07:35:21"));
	track[0].push(new TrackPoint(35.387857, 139.519179, 2.300, 56, 0, 0, "Fri Jun 5 2026 07:35:48"));
	track[0].push(new TrackPoint(35.387702, 139.518912, 2.330, 60, 0, 0, "Fri Jun 5 2026 07:36:03"));
	track[0].push(new TrackPoint(35.387479, 139.518656, 2.364, 62, 0, 0, "Fri Jun 5 2026 07:36:19"));
	track[0].push(new TrackPoint(35.387343, 139.518542, 2.383, 62, 0, 0, "Fri Jun 5 2026 07:36:27"));
	track[0].push(new TrackPoint(35.386980, 139.518312, 2.429, 63, 0, 0, "Fri Jun 5 2026 07:37:11"));
	track[0].push(new TrackPoint(35.386937, 139.518240, 2.437, 64, 0, 0, "Fri Jun 5 2026 07:37:16"));
	track[0].push(new TrackPoint(35.386800, 139.518097, 2.457, 63, 0, 0, "Fri Jun 5 2026 07:37:26"));
	track[0].push(new TrackPoint(35.386655, 139.518065, 2.474, 60, 0, 0, "Fri Jun 5 2026 07:37:34"));
	track[0].push(new TrackPoint(35.386542, 139.518167, 2.490, 58, 0, 0, "Fri Jun 5 2026 07:37:42"));
	track[0].push(new TrackPoint(35.386485, 139.518253, 2.500, 56, 0, 0, "Fri Jun 5 2026 07:37:48"));
	track[0].push(new TrackPoint(35.386321, 139.518234, 2.519, 52, 0, 0, "Fri Jun 5 2026 07:38:09"));
	track[0].push(new TrackPoint(35.386349, 139.517937, 2.547, 55, 0, 0, "Fri Jun 5 2026 07:38:31"));
	track[0].push(new TrackPoint(35.386313, 139.517800, 2.560, 56, 0, 0, "Fri Jun 5 2026 07:38:38"));
	track[0].push(new TrackPoint(35.386261, 139.517708, 2.570, 56, 0, 0, "Fri Jun 5 2026 07:38:44"));
	track[0].push(new TrackPoint(35.386067, 139.517569, 2.595, 57, 0, 0, "Fri Jun 5 2026 07:38:58"));
	track[0].push(new TrackPoint(35.385845, 139.517370, 2.626, 59, 0, 0, "Fri Jun 5 2026 07:39:13"));
	track[0].push(new TrackPoint(35.385517, 139.517098, 2.670, 57, 0, 0, "Fri Jun 5 2026 07:39:34"));
	track[0].push(new TrackPoint(35.385200, 139.516773, 2.716, 58, 0, 0, "Fri Jun 5 2026 07:39:55"));
	track[0].push(new TrackPoint(35.385000, 139.516478, 2.751, 62, 0, 0, "Fri Jun 5 2026 07:40:16"));
	track[0].push(new TrackPoint(35.384765, 139.515924, 2.808, 61, 0, 0, "Fri Jun 5 2026 07:40:42"));
	track[0].push(new TrackPoint(35.384699, 139.515710, 2.829, 61, 0, 0, "Fri Jun 5 2026 07:40:52"));
	track[0].push(new TrackPoint(35.384607, 139.515520, 2.849, 60, 0, 0, "Fri Jun 5 2026 07:41:02"));
	track[0].push(new TrackPoint(35.384503, 139.515363, 2.867, 60, 0, 0, "Fri Jun 5 2026 07:41:11"));
	track[0].push(new TrackPoint(35.384351, 139.515214, 2.889, 61, 0, 0, "Fri Jun 5 2026 07:41:22"));
	track[0].push(new TrackPoint(35.384090, 139.515055, 2.921, 63, 0, 0, "Fri Jun 5 2026 07:41:40"));
	track[0].push(new TrackPoint(35.383386, 139.514777, 3.004, 70, 0, 0, "Fri Jun 5 2026 07:42:21"));
	track[0].push(new TrackPoint(35.382764, 139.514469, 3.078, 65, 0, 0, "Fri Jun 5 2026 07:42:59"));
	track[0].push(new TrackPoint(35.382656, 139.514461, 3.091, 66, 0, 0, "Fri Jun 5 2026 07:43:05"));
	track[0].push(new TrackPoint(35.382541, 139.514401, 3.104, 67, 0, 0, "Fri Jun 5 2026 07:43:12"));
	track[0].push(new TrackPoint(35.382398, 139.514372, 3.121, 69, 0, 0, "Fri Jun 5 2026 07:43:19"));
	track[0].push(new TrackPoint(35.382320, 139.514269, 3.133, 70, 0, 0, "Fri Jun 5 2026 07:43:25"));
	track[0].push(new TrackPoint(35.382174, 139.514150, 3.153, 71, 0, 0, "Fri Jun 5 2026 07:43:35"));
	track[0].push(new TrackPoint(35.381976, 139.513921, 3.183, 73, 0, 0, "Fri Jun 5 2026 07:43:51"));
	track[0].push(new TrackPoint(35.381929, 139.513789, 3.196, 73, 0, 0, "Fri Jun 5 2026 07:43:58"));
	track[0].push(new TrackPoint(35.381630, 139.513273, 3.254, 73, 0, 0, "Fri Jun 5 2026 07:44:25"));
	track[0].push(new TrackPoint(35.381466, 139.513108, 3.277, 73, 0, 0, "Fri Jun 5 2026 07:44:36"));
	track[0].push(new TrackPoint(35.381222, 139.512811, 3.316, 72, 0, 0, "Fri Jun 5 2026 07:44:53"));
	track[0].push(new TrackPoint(35.381111, 139.512649, 3.335, 70, 0, 0, "Fri Jun 5 2026 07:45:03"));
	track[0].push(new TrackPoint(35.380319, 139.511911, 3.446, 65, 0, 0, "Fri Jun 5 2026 07:46:33"));
	track[0].push(new TrackPoint(35.380000, 139.511359, 3.508, 61, 0, 0, "Fri Jun 5 2026 07:47:05"));
	track[0].push(new TrackPoint(35.379762, 139.510799, 3.565, 61, 0, 0, "Fri Jun 5 2026 07:47:36"));
	track[0].push(new TrackPoint(35.379744, 139.510717, 3.573, 61, 0, 0, "Fri Jun 5 2026 07:47:40"));
	track[0].push(new TrackPoint(35.379565, 139.510409, 3.608, 59, 0, 0, "Fri Jun 5 2026 07:48:01"));
	track[0].push(new TrackPoint(35.379237, 139.509616, 3.689, 55, 0, 0, "Fri Jun 5 2026 07:48:42"));
	track[0].push(new TrackPoint(35.379131, 139.509396, 3.712, 54, 0, 0, "Fri Jun 5 2026 07:48:52"));
	track[0].push(new TrackPoint(35.379096, 139.509231, 3.728, 53, 0, 0, "Fri Jun 5 2026 07:48:59"));
	track[0].push(new TrackPoint(35.378848, 139.508871, 3.771, 54, 0, 0, "Fri Jun 5 2026 07:49:17"));
	track[0].push(new TrackPoint(35.378655, 139.508504, 3.810, 51, 0, 0, "Fri Jun 5 2026 07:49:36"));
	track[0].push(new TrackPoint(35.378416, 139.508107, 3.855, 51, 0, 0, "Fri Jun 5 2026 07:49:57"));
	track[0].push(new TrackPoint(35.377742, 139.506665, 4.006, 51, 0, 0, "Fri Jun 5 2026 07:51:09"));
	track[0].push(new TrackPoint(35.377488, 139.506178, 4.059, 53, 0, 0, "Fri Jun 5 2026 07:51:34"));
	track[0].push(new TrackPoint(35.377424, 139.506009, 4.076, 53, 0, 0, "Fri Jun 5 2026 07:51:42"));
	track[0].push(new TrackPoint(35.377125, 139.505595, 4.126, 50, 0, 0, "Fri Jun 5 2026 07:52:16"));
	track[0].push(new TrackPoint(35.377007, 139.505526, 4.141, 50, 0, 0, "Fri Jun 5 2026 07:52:59"));
	track[0].push(new TrackPoint(35.376931, 139.505445, 4.153, 50, 0, 0, "Fri Jun 5 2026 07:53:05"));
	track[0].push(new TrackPoint(35.376872, 139.505350, 4.163, 50, 0, 0, "Fri Jun 5 2026 07:53:10"));
	track[0].push(new TrackPoint(35.376842, 139.505254, 4.173, 50, 0, 0, "Fri Jun 5 2026 07:53:15"));
	track[0].push(new TrackPoint(35.376807, 139.505205, 4.179, 49, 0, 0, "Fri Jun 5 2026 07:53:18"));
	track[0].push(new TrackPoint(35.376568, 139.505013, 4.210, 47, 0, 0, "Fri Jun 5 2026 07:53:33"));
	track[0].push(new TrackPoint(35.376382, 139.504906, 4.233, 46, 0, 0, "Fri Jun 5 2026 07:53:44"));
	track[0].push(new TrackPoint(35.375882, 139.504540, 4.298, 47, 0, 0, "Fri Jun 5 2026 07:54:13"));
	track[0].push(new TrackPoint(35.375103, 139.504034, 4.396, 47, 0, 0, "Fri Jun 5 2026 07:54:59"));
	track[0].push(new TrackPoint(35.373604, 139.503078, 4.585, 51, 0, 0, "Fri Jun 5 2026 07:56:30"));
	track[0].push(new TrackPoint(35.373356, 139.502938, 4.615, 51, 0, 0, "Fri Jun 5 2026 07:56:45"));
	track[0].push(new TrackPoint(35.372501, 139.502344, 4.724, 52, 0, 0, "Fri Jun 5 2026 07:57:35"));
	track[0].push(new TrackPoint(35.372446, 139.502320, 4.731, 52, 0, 0, "Fri Jun 5 2026 07:57:38"));
	track[0].push(new TrackPoint(35.371727, 139.501820, 4.823, 50, 0, 0, "Fri Jun 5 2026 07:58:21"));
	track[0].push(new TrackPoint(35.371361, 139.501548, 4.870, 52, 0, 0, "Fri Jun 5 2026 07:58:46"));
	track[0].push(new TrackPoint(35.370927, 139.501288, 4.924, 53, 0, 0, "Fri Jun 5 2026 07:59:12"));
	track[0].push(new TrackPoint(35.370593, 139.501129, 4.964, 52, 0, 0, "Fri Jun 5 2026 07:59:31"));
	track[0].push(new TrackPoint(35.370300, 139.500936, 5.001, 53, 0, 0, "Fri Jun 5 2026 07:59:48"));
	track[0].push(new TrackPoint(35.370007, 139.500774, 5.037, 52, 0, 0, "Fri Jun 5 2026 08:00:06"));
	track[0].push(new TrackPoint(35.369695, 139.500570, 5.076, 51, 0, 0, "Fri Jun 5 2026 08:00:24"));
	track[0].push(new TrackPoint(35.369124, 139.500322, 5.143, 53, 0, 0, "Fri Jun 5 2026 08:01:03"));
	track[0].push(new TrackPoint(35.368912, 139.500191, 5.170, 54, 0, 0, "Fri Jun 5 2026 08:01:21"));
	track[0].push(new TrackPoint(35.368748, 139.500143, 5.189, 54, 0, 0, "Fri Jun 5 2026 08:01:32"));
	track[0].push(new TrackPoint(35.368530, 139.499999, 5.217, 54, 0, 0, "Fri Jun 5 2026 08:01:59"));
	track[0].push(new TrackPoint(35.368522, 139.499953, 5.221, 54, 0, 0, "Fri Jun 5 2026 08:02:04"));
	track[0].push(new TrackPoint(35.368339, 139.499836, 5.244, 53, 0, 0, "Fri Jun 5 2026 08:02:15"));
	track[0].push(new TrackPoint(35.368240, 139.499809, 5.255, 53, 0, 0, "Fri Jun 5 2026 08:02:20"));
	track[0].push(new TrackPoint(35.367282, 139.499310, 5.372, 55, 0, 0, "Fri Jun 5 2026 08:03:15"));
	track[0].push(new TrackPoint(35.365943, 139.498445, 5.540, 54, 0, 0, "Fri Jun 5 2026 08:04:40"));
	track[0].push(new TrackPoint(35.365802, 139.498375, 5.557, 55, 0, 0, "Fri Jun 5 2026 08:04:48"));
	track[0].push(new TrackPoint(35.365303, 139.498038, 5.620, 57, 0, 0, "Fri Jun 5 2026 08:05:18"));
	track[0].push(new TrackPoint(35.364823, 139.497762, 5.679, 58, 0, 0, "Fri Jun 5 2026 08:05:47"));
	track[0].push(new TrackPoint(35.364684, 139.497709, 5.695, 58, 0, 0, "Fri Jun 5 2026 08:05:55"));
	track[0].push(new TrackPoint(35.364458, 139.497568, 5.724, 58, 0, 0, "Fri Jun 5 2026 08:06:08"));
	track[0].push(new TrackPoint(35.364229, 139.497389, 5.754, 58, 0, 0, "Fri Jun 5 2026 08:06:23"));
	track[0].push(new TrackPoint(35.364092, 139.497347, 5.769, 57, 0, 0, "Fri Jun 5 2026 08:06:30"));
	track[0].push(new TrackPoint(35.363947, 139.497330, 5.786, 57, 0, 0, "Fri Jun 5 2026 08:06:37"));
	track[0].push(new TrackPoint(35.363552, 139.497102, 5.834, 57, 0, 0, "Fri Jun 5 2026 08:07:03"));
	track[0].push(new TrackPoint(35.363473, 139.497021, 5.846, 58, 0, 0, "Fri Jun 5 2026 08:07:09"));
	track[0].push(new TrackPoint(35.363307, 139.496901, 5.867, 59, 0, 0, "Fri Jun 5 2026 08:07:19"));
	track[0].push(new TrackPoint(35.362883, 139.496505, 5.926, 57, 0, 0, "Fri Jun 5 2026 08:07:46"));
	track[0].push(new TrackPoint(35.361773, 139.495539, 6.078, 53, 0, 0, "Fri Jun 5 2026 08:09:02"));
	track[0].push(new TrackPoint(35.361217, 139.494979, 6.158, 56, 0, 0, "Fri Jun 5 2026 08:09:40"));
	track[0].push(new TrackPoint(35.361110, 139.494919, 6.171, 56, 0, 0, "Fri Jun 5 2026 08:09:47"));
	track[0].push(new TrackPoint(35.360854, 139.494723, 6.205, 55, 0, 0, "Fri Jun 5 2026 08:10:05"));
	track[0].push(new TrackPoint(35.360121, 139.494366, 6.293, 54, 0, 0, "Fri Jun 5 2026 08:10:50"));
	track[0].push(new TrackPoint(35.359923, 139.494226, 6.318, 56, 0, 0, "Fri Jun 5 2026 08:11:03"));
	track[0].push(new TrackPoint(35.358799, 139.493662, 6.454, 58, 0, 0, "Fri Jun 5 2026 08:12:11"));
	track[0].push(new TrackPoint(35.358504, 139.493495, 6.490, 58, 0, 0, "Fri Jun 5 2026 08:12:28"));
	track[0].push(new TrackPoint(35.358199, 139.493450, 6.524, 58, 0, 0, "Fri Jun 5 2026 08:12:43"));
	track[0].push(new TrackPoint(35.357928, 139.493366, 6.555, 57, 0, 0, "Fri Jun 5 2026 08:12:59"));
	track[0].push(new TrackPoint(35.357644, 139.493245, 6.588, 57, 0, 0, "Fri Jun 5 2026 08:13:16"));
	track[0].push(new TrackPoint(35.357439, 139.493134, 6.613, 57, 0, 0, "Fri Jun 5 2026 08:13:28"));
	track[0].push(new TrackPoint(35.356830, 139.492922, 6.684, 56, 0, 0, "Fri Jun 5 2026 08:14:03"));
	track[0].push(new TrackPoint(35.356541, 139.492851, 6.716, 56, 0, 0, "Fri Jun 5 2026 08:14:20"));
	track[0].push(new TrackPoint(35.356274, 139.492764, 6.747, 56, 0, 0, "Fri Jun 5 2026 08:14:37"));
	track[0].push(new TrackPoint(35.355920, 139.492613, 6.789, 54, 0, 0, "Fri Jun 5 2026 08:14:55"));
	track[0].push(new TrackPoint(35.355809, 139.492583, 6.801, 54, 0, 0, "Fri Jun 5 2026 08:15:01"));
	track[0].push(new TrackPoint(35.355458, 139.492371, 6.845, 54, 0, 0, "Fri Jun 5 2026 08:15:22"));
	track[0].push(new TrackPoint(35.355251, 139.492300, 6.869, 55, 0, 0, "Fri Jun 5 2026 08:15:35"));
	track[0].push(new TrackPoint(35.354728, 139.491985, 6.934, 56, 0, 0, "Fri Jun 5 2026 08:16:06"));
	track[0].push(new TrackPoint(35.354581, 139.491886, 6.952, 56, 0, 0, "Fri Jun 5 2026 08:16:20"));
	track[0].push(new TrackPoint(35.354548, 139.491844, 6.958, 56, 0, 0, "Fri Jun 5 2026 08:16:26"));
	track[0].push(new TrackPoint(35.354204, 139.491641, 7.000, 54, 0, 0, "Fri Jun 5 2026 08:16:47"));
	track[0].push(new TrackPoint(35.353627, 139.491405, 7.068, 50, 0, 0, "Fri Jun 5 2026 08:17:19"));
	track[0].push(new TrackPoint(35.353339, 139.491249, 7.103, 49, 0, 0, "Fri Jun 5 2026 08:17:35"));
	track[0].push(new TrackPoint(35.353116, 139.491168, 7.129, 48, 0, 0, "Fri Jun 5 2026 08:17:47"));
	track[0].push(new TrackPoint(35.352917, 139.491035, 7.154, 47, 0, 0, "Fri Jun 5 2026 08:17:59"));
	track[0].push(new TrackPoint(35.352586, 139.490897, 7.193, 48, 0, 0, "Fri Jun 5 2026 08:18:15"));
	track[0].push(new TrackPoint(35.352275, 139.490852, 7.228, 48, 0, 0, "Fri Jun 5 2026 08:18:31"));
	track[0].push(new TrackPoint(35.352251, 139.490828, 7.232, 48, 0, 0, "Fri Jun 5 2026 08:18:33"));
	track[0].push(new TrackPoint(35.352111, 139.490805, 7.247, 48, 0, 0, "Fri Jun 5 2026 08:18:41"));
	track[0].push(new TrackPoint(35.351962, 139.490817, 7.264, 48, 0, 0, "Fri Jun 5 2026 08:18:48"));
	track[0].push(new TrackPoint(35.350581, 139.490702, 7.418, 50, 0, 0, "Fri Jun 5 2026 08:20:02"));
	track[0].push(new TrackPoint(35.350434, 139.490650, 7.435, 50, 0, 0, "Fri Jun 5 2026 08:20:10"));
	track[0].push(new TrackPoint(35.350295, 139.490573, 7.452, 49, 0, 0, "Fri Jun 5 2026 08:20:18"));
	track[0].push(new TrackPoint(35.350110, 139.490524, 7.473, 47, 0, 0, "Fri Jun 5 2026 08:20:30"));
	track[0].push(new TrackPoint(35.349991, 139.490450, 7.488, 46, 0, 0, "Fri Jun 5 2026 08:20:36"));
	track[0].push(new TrackPoint(35.349131, 139.490018, 7.593, 39, 0, 0, "Fri Jun 5 2026 08:23:06"));
	track[0].push(new TrackPoint(35.348598, 139.489626, 7.662, 36, 0, 0, "Fri Jun 5 2026 08:23:39"));
	track[0].push(new TrackPoint(35.348228, 139.489291, 7.714, 33, 0, 0, "Fri Jun 5 2026 08:24:02"));
	track[0].push(new TrackPoint(35.348075, 139.489190, 7.733, 30, 0, 0, "Fri Jun 5 2026 08:24:09"));
	track[0].push(new TrackPoint(35.347815, 139.489046, 7.765, 26, 0, 0, "Fri Jun 5 2026 08:24:25"));
	track[0].push(new TrackPoint(35.347124, 139.488517, 7.857, 15, 0, 0, "Fri Jun 5 2026 08:25:09"));
	track[0].push(new TrackPoint(35.346681, 139.488151, 7.920, 13, 0, 0, "Fri Jun 5 2026 08:25:52"));
	track[0].push(new TrackPoint(35.346802, 139.488277, 7.938, 14, 0, 0, "Fri Jun 5 2026 08:26:10"));
	track[0].push(new TrackPoint(35.346851, 139.488198, 7.948, 14, 0, 0, "Fri Jun 5 2026 08:27:17"));
	track[0].push(new TrackPoint(35.346695, 139.488020, 7.972, 13, 0, 0, "Fri Jun 5 2026 08:27:30"));
	track[0].push(new TrackPoint(35.346596, 139.487950, 7.985, 13, 0, 0, "Fri Jun 5 2026 08:27:36"));
	track[0].push(new TrackPoint(35.346512, 139.487852, 7.998, 13, 0, 0, "Fri Jun 5 2026 08:27:42"));
	track[0].push(new TrackPoint(35.346354, 139.487772, 8.017, 12, 0, 0, "Fri Jun 5 2026 08:27:51"));
	track[0].push(new TrackPoint(35.346252, 139.487737, 8.029, 12, 0, 0, "Fri Jun 5 2026 08:27:57"));
	track[0].push(new TrackPoint(35.346273, 139.487642, 8.038, 11, 0, 0, "Fri Jun 5 2026 08:28:01"));
	track[0].push(new TrackPoint(35.346355, 139.487463, 8.057, 11, 0, 0, "Fri Jun 5 2026 08:28:10"));
	track[0].push(new TrackPoint(35.346427, 139.487413, 8.066, 11, 0, 0, "Fri Jun 5 2026 08:28:21"));
	track[0].push(new TrackPoint(35.346427, 139.487353, 8.071, 10, 0, 0, "Fri Jun 5 2026 08:28:28"));
	track[0].push(new TrackPoint(35.346409, 139.487316, 8.075, 10, 0, 0, "Fri Jun 5 2026 08:28:35"));
	track[0].push(new TrackPoint(35.346446, 139.487285, 8.081, 10, 0, 0, "Fri Jun 5 2026 08:28:46"));
	track[0].push(new TrackPoint(35.346473, 139.487319, 8.086, 10, 0, 0, "Fri Jun 5 2026 08:29:18"));
	track[0].push(new TrackPoint(35.346538, 139.487118, 8.106, 9, 0, 0, "Fri Jun 5 2026 08:30:13"));
	track[0].push(new TrackPoint(35.346549, 139.487038, 8.113, 8, 0, 0, "Fri Jun 5 2026 08:30:20"));
	track[0].push(new TrackPoint(35.346494, 139.486984, 8.121, 7, 0, 0, "Fri Jun 5 2026 08:30:28"));
	track[0].push(new TrackPoint(35.346208, 139.486463, 8.178, 8, 0, 0, "Fri Jun 5 2026 08:31:11"));
	track[0].push(new TrackPoint(35.346213, 139.486400, 8.184, 9, 0, 0, "Fri Jun 5 2026 08:31:18"));
	track[0].push(new TrackPoint(35.346243, 139.486366, 8.189, 9, 0, 0, "Fri Jun 5 2026 08:31:22"));
	track[0].push(new TrackPoint(35.346236, 139.486310, 8.194, 10, 0, 0, "Fri Jun 5 2026 08:31:25"));
	track[0].push(new TrackPoint(35.346262, 139.486283, 8.198, 10, 0, 0, "Fri Jun 5 2026 08:31:31"));
	track[0].push(new TrackPoint(35.346249, 139.486257, 8.203, 10, 0, 0, "Fri Jun 5 2026 08:32:01"));
	track[0].push(new TrackPoint(35.346292, 139.486236, 8.208, 11, 0, 0, "Fri Jun 5 2026 08:32:04"));
	track[0].push(new TrackPoint(35.346423, 139.486052, 8.230, 12, 0, 0, "Fri Jun 5 2026 08:32:20"));
	track[0].push(new TrackPoint(35.346470, 139.486026, 8.236, 12, 0, 0, "Fri Jun 5 2026 08:32:23"));
	track[0].push(new TrackPoint(35.346581, 139.485875, 8.255, 11, 0, 0, "Fri Jun 5 2026 08:32:35"));
	track[0].push(new TrackPoint(35.346595, 139.485810, 8.261, 11, 0, 0, "Fri Jun 5 2026 08:32:38"));
	track[0].push(new TrackPoint(35.346635, 139.485741, 8.269, 11, 0, 0, "Fri Jun 5 2026 08:32:44"));
	track[0].push(new TrackPoint(35.346662, 139.485643, 8.278, 11, 0, 0, "Fri Jun 5 2026 08:32:52"));
	track[0].push(new TrackPoint(35.346680, 139.485651, 8.280, 11, 0, 0, "Fri Jun 5 2026 08:32:54"));
	track[0].push(new TrackPoint(35.346682, 139.485591, 8.287, 11, 0, 0, "Fri Jun 5 2026 08:33:14"));
	track[0].push(new TrackPoint(35.346830, 139.485334, 8.316, 10, 0, 0, "Fri Jun 5 2026 08:33:44"));
	track[0].push(new TrackPoint(35.346936, 139.484985, 8.351, 12, 0, 0, "Fri Jun 5 2026 08:34:15"));
	track[0].push(new TrackPoint(35.347055, 139.484758, 8.376, 14, 0, 0, "Fri Jun 5 2026 08:34:35"));
	track[0].push(new TrackPoint(35.347163, 139.484572, 8.397, 14, 0, 0, "Fri Jun 5 2026 08:34:47"));
	track[0].push(new TrackPoint(35.347325, 139.484134, 8.440, 14, 0, 0, "Fri Jun 5 2026 08:35:11"));
	track[0].push(new TrackPoint(35.347326, 139.484061, 8.447, 14, 0, 0, "Fri Jun 5 2026 08:35:14"));
	track[0].push(new TrackPoint(35.347355, 139.484017, 8.452, 14, 0, 0, "Fri Jun 5 2026 08:35:19"));
	track[0].push(new TrackPoint(35.347311, 139.483953, 8.460, 15, 0, 0, "Fri Jun 5 2026 08:35:26"));
	track[0].push(new TrackPoint(35.347343, 139.483749, 8.479, 13, 0, 0, "Fri Jun 5 2026 08:35:38"));
	track[0].push(new TrackPoint(35.347491, 139.483398, 8.515, 13, 0, 0, "Fri Jun 5 2026 08:35:58"));
	track[0].push(new TrackPoint(35.347508, 139.483260, 8.528, 13, 0, 0, "Fri Jun 5 2026 08:36:04"));
	track[0].push(new TrackPoint(35.347534, 139.483223, 8.532, 13, 0, 0, "Fri Jun 5 2026 08:36:08"));
	track[0].push(new TrackPoint(35.347574, 139.483008, 8.553, 13, 0, 0, "Fri Jun 5 2026 08:36:31"));
	track[0].push(new TrackPoint(35.347707, 139.482633, 8.593, 14, 0, 0, "Fri Jun 5 2026 08:37:57"));
	track[0].push(new TrackPoint(35.347736, 139.482623, 8.596, 14, 0, 0, "Fri Jun 5 2026 08:38:19"));
	track[0].push(new TrackPoint(35.347879, 139.482153, 8.642, 14, 0, 0, "Fri Jun 5 2026 08:39:03"));
	track[0].push(new TrackPoint(35.347874, 139.482000, 8.656, 14, 0, 0, "Fri Jun 5 2026 08:39:10"));
	track[0].push(new TrackPoint(35.347934, 139.481578, 8.695, 12, 0, 0, "Fri Jun 5 2026 08:39:37"));
	track[0].push(new TrackPoint(35.347958, 139.481201, 8.730, 11, 0, 0, "Fri Jun 5 2026 08:39:54"));
	track[0].push(new TrackPoint(35.347922, 139.480756, 8.770, 12, 0, 0, "Fri Jun 5 2026 08:40:22"));
	track[0].push(new TrackPoint(35.347896, 139.480593, 8.785, 12, 0, 0, "Fri Jun 5 2026 08:40:30"));
	track[0].push(new TrackPoint(35.347866, 139.480495, 8.795, 12, 0, 0, "Fri Jun 5 2026 08:40:36"));
	track[0].push(new TrackPoint(35.347871, 139.480335, 8.810, 12, 0, 0, "Fri Jun 5 2026 08:40:48"));
	track[0].push(new TrackPoint(35.347849, 139.480308, 8.814, 12, 0, 0, "Fri Jun 5 2026 08:41:04"));
	track[0].push(new TrackPoint(35.347824, 139.480198, 8.824, 13, 0, 0, "Fri Jun 5 2026 08:41:10"));
	track[0].push(new TrackPoint(35.347801, 139.479861, 8.855, 14, 0, 0, "Fri Jun 5 2026 08:41:29"));
	track[0].push(new TrackPoint(35.347708, 139.479538, 8.886, 14, 0, 0, "Fri Jun 5 2026 08:41:43"));
	track[0].push(new TrackPoint(35.347705, 139.479426, 8.896, 14, 0, 0, "Fri Jun 5 2026 08:41:47"));
	track[0].push(new TrackPoint(35.347722, 139.479313, 8.907, 14, 0, 0, "Fri Jun 5 2026 08:41:53"));
	track[0].push(new TrackPoint(35.347685, 139.478991, 8.937, 12, 0, 0, "Fri Jun 5 2026 08:42:08"));
	track[0].push(new TrackPoint(35.347692, 139.478848, 8.950, 12, 0, 0, "Fri Jun 5 2026 08:42:22"));
	track[0].push(new TrackPoint(35.347729, 139.478766, 8.958, 12, 0, 0, "Fri Jun 5 2026 08:42:32"));
	track[0].push(new TrackPoint(35.347713, 139.478744, 8.961, 13, 0, 0, "Fri Jun 5 2026 08:42:34"));
	track[0].push(new TrackPoint(35.347733, 139.478666, 8.971, 13, 0, 0, "Fri Jun 5 2026 08:43:07"));
	track[0].push(new TrackPoint(35.347718, 139.478410, 8.994, 14, 0, 0, "Fri Jun 5 2026 08:43:17"));
	track[0].push(new TrackPoint(35.347641, 139.478150, 9.020, 16, 0, 0, "Fri Jun 5 2026 08:43:29"));
	track[0].push(new TrackPoint(35.347602, 139.477799, 9.052, 17, 0, 0, "Fri Jun 5 2026 08:43:45"));
	track[0].push(new TrackPoint(35.347532, 139.477676, 9.066, 17, 0, 0, "Fri Jun 5 2026 08:43:53"));
	track[0].push(new TrackPoint(35.347538, 139.477512, 9.081, 17, 0, 0, "Fri Jun 5 2026 08:44:00"));
	track[0].push(new TrackPoint(35.347473, 139.477226, 9.108, 17, 0, 0, "Fri Jun 5 2026 08:44:14"));
	track[0].push(new TrackPoint(35.347418, 139.477132, 9.118, 17, 0, 0, "Fri Jun 5 2026 08:44:20"));
	track[0].push(new TrackPoint(35.347342, 139.476693, 9.159, 17, 0, 0, "Fri Jun 5 2026 08:44:37"));
	track[0].push(new TrackPoint(35.347210, 139.476132, 9.212, 18, 0, 0, "Fri Jun 5 2026 08:45:03"));
	track[0].push(new TrackPoint(35.347137, 139.475947, 9.231, 18, 0, 0, "Fri Jun 5 2026 08:45:13"));
	track[0].push(new TrackPoint(35.347129, 139.475856, 9.239, 18, 0, 0, "Fri Jun 5 2026 08:45:17"));
	track[0].push(new TrackPoint(35.347024, 139.475566, 9.268, 19, 0, 0, "Fri Jun 5 2026 08:45:32"));
	track[0].push(new TrackPoint(35.346983, 139.475406, 9.284, 18, 0, 0, "Fri Jun 5 2026 08:45:39"));
	track[0].push(new TrackPoint(35.346939, 139.475327, 9.292, 17, 0, 0, "Fri Jun 5 2026 08:45:42"));
	track[0].push(new TrackPoint(35.346774, 139.474215, 9.395, 15, 0, 0, "Fri Jun 5 2026 08:46:30"));
	track[0].push(new TrackPoint(35.346727, 139.473694, 9.443, 14, 0, 0, "Fri Jun 5 2026 08:46:52"));
	track[0].push(new TrackPoint(35.346723, 139.473446, 9.465, 13, 0, 0, "Fri Jun 5 2026 08:47:02"));
	track[0].push(new TrackPoint(35.346696, 139.473252, 9.483, 13, 0, 0, "Fri Jun 5 2026 08:47:09"));
	track[0].push(new TrackPoint(35.346706, 139.472975, 9.509, 13, 0, 0, "Fri Jun 5 2026 08:47:21"));
	track[0].push(new TrackPoint(35.346678, 139.472620, 9.541, 14, 0, 0, "Fri Jun 5 2026 08:47:36"));
	track[0].push(new TrackPoint(35.346697, 139.472295, 9.571, 14, 0, 0, "Fri Jun 5 2026 08:47:49"));
	track[0].push(new TrackPoint(35.346679, 139.472196, 9.580, 14, 0, 0, "Fri Jun 5 2026 08:47:53"));
	track[0].push(new TrackPoint(35.346759, 139.471814, 9.616, 14, 0, 0, "Fri Jun 5 2026 08:48:10"));
	track[0].push(new TrackPoint(35.346835, 139.471321, 9.662, 17, 0, 0, "Fri Jun 5 2026 08:48:32"));
	track[0].push(new TrackPoint(35.346881, 139.470878, 9.702, 15, 0, 0, "Fri Jun 5 2026 08:48:51"));
	track[0].push(new TrackPoint(35.347020, 139.470401, 9.748, 15, 0, 0, "Fri Jun 5 2026 08:49:13"));
	track[0].push(new TrackPoint(35.347092, 139.470083, 9.778, 14, 0, 0, "Fri Jun 5 2026 08:49:27"));
	track[0].push(new TrackPoint(35.347250, 139.469695, 9.818, 14, 0, 0, "Fri Jun 5 2026 08:49:48"));
	track[0].push(new TrackPoint(35.347289, 139.469538, 9.833, 14, 0, 0, "Fri Jun 5 2026 08:50:02"));
	track[0].push(new TrackPoint(35.347347, 139.469362, 9.854, 14, 0, 0, "Fri Jun 5 2026 08:51:06"));
	track[0].push(new TrackPoint(35.347398, 139.469244, 9.866, 14, 0, 0, "Fri Jun 5 2026 08:51:12"));
	track[0].push(new TrackPoint(35.347442, 139.469186, 9.873, 14, 0, 0, "Fri Jun 5 2026 08:51:15"));
	track[0].push(new TrackPoint(35.347613, 139.468528, 9.936, 12, 0, 0, "Fri Jun 5 2026 08:51:44"));
	track[0].push(new TrackPoint(35.347665, 139.468242, 9.963, 12, 0, 0, "Fri Jun 5 2026 08:51:58"));
	track[0].push(new TrackPoint(35.347817, 139.467738, 10.012, 13, 0, 0, "Fri Jun 5 2026 08:52:21"));
	track[0].push(new TrackPoint(35.347880, 139.467415, 10.042, 14, 0, 0, "Fri Jun 5 2026 08:52:35"));
	track[0].push(new TrackPoint(35.347861, 139.467188, 10.063, 12, 0, 0, "Fri Jun 5 2026 08:52:45"));
	track[0].push(new TrackPoint(35.347750, 139.467061, 10.080, 10, 0, 0, "Fri Jun 5 2026 08:52:52"));
	track[0].push(new TrackPoint(35.347629, 139.466969, 10.096, 9, 0, 0, "Fri Jun 5 2026 08:53:00"));
	track[0].push(new TrackPoint(35.347502, 139.466828, 10.115, 9, 0, 0, "Fri Jun 5 2026 08:53:09"));
	track[0].push(new TrackPoint(35.347472, 139.466676, 10.129, 8, 0, 0, "Fri Jun 5 2026 08:53:17"));
	track[0].push(new TrackPoint(35.347470, 139.466445, 10.150, 9, 0, 0, "Fri Jun 5 2026 08:53:28"));
	track[0].push(new TrackPoint(35.347426, 139.466057, 10.186, 11, 0, 0, "Fri Jun 5 2026 08:53:47"));
	track[0].push(new TrackPoint(35.347388, 139.465476, 10.239, 12, 0, 0, "Fri Jun 5 2026 08:54:13"));
	track[0].push(new TrackPoint(35.347313, 139.465160, 10.269, 13, 0, 0, "Fri Jun 5 2026 08:54:27"));
	track[0].push(new TrackPoint(35.347257, 139.465008, 10.284, 13, 0, 0, "Fri Jun 5 2026 08:54:35"));
	track[0].push(new TrackPoint(35.346931, 139.464449, 10.347, 18, 0, 0, "Fri Jun 5 2026 08:55:08"));
	track[0].push(new TrackPoint(35.346750, 139.464178, 10.379, 19, 0, 0, "Fri Jun 5 2026 08:55:25"));
	track[0].push(new TrackPoint(35.346682, 139.464008, 10.396, 19, 0, 0, "Fri Jun 5 2026 08:55:34"));
	track[0].push(new TrackPoint(35.346638, 139.463389, 10.454, 14, 0, 0, "Fri Jun 5 2026 08:56:03"));
	track[0].push(new TrackPoint(35.346656, 139.463221, 10.469, 14, 0, 0, "Fri Jun 5 2026 08:56:10"));
	track[0].push(new TrackPoint(35.346721, 139.463007, 10.490, 13, 0, 0, "Fri Jun 5 2026 08:56:20"));
	track[0].push(new TrackPoint(35.346764, 139.462826, 10.507, 13, 0, 0, "Fri Jun 5 2026 08:56:28"));
	track[0].push(new TrackPoint(35.347142, 139.461807, 10.609, 15, 0, 0, "Fri Jun 5 2026 08:57:17"));
	track[0].push(new TrackPoint(35.347171, 139.461654, 10.624, 16, 0, 0, "Fri Jun 5 2026 08:57:24"));
	track[0].push(new TrackPoint(35.347250, 139.461531, 10.638, 16, 0, 0, "Fri Jun 5 2026 08:57:30"));
	track[0].push(new TrackPoint(35.347301, 139.461373, 10.653, 16, 0, 0, "Fri Jun 5 2026 08:57:39"));
	track[0].push(new TrackPoint(35.347328, 139.461225, 10.667, 16, 0, 0, "Fri Jun 5 2026 08:57:46"));
	track[0].push(new TrackPoint(35.347379, 139.461089, 10.681, 16, 0, 0, "Fri Jun 5 2026 08:57:53"));
	track[0].push(new TrackPoint(35.347465, 139.460512, 10.734, 16, 0, 0, "Fri Jun 5 2026 08:58:28"));
	track[0].push(new TrackPoint(35.347487, 139.460432, 10.742, 16, 0, 0, "Fri Jun 5 2026 08:58:33"));
	track[0].push(new TrackPoint(35.347535, 139.459980, 10.783, 15, 0, 0, "Fri Jun 5 2026 08:58:52"));
	track[0].push(new TrackPoint(35.347573, 139.459832, 10.797, 15, 0, 0, "Fri Jun 5 2026 08:58:58"));
	track[0].push(new TrackPoint(35.347651, 139.459298, 10.847, 14, 0, 0, "Fri Jun 5 2026 08:59:22"));
	track[0].push(new TrackPoint(35.347653, 139.459121, 10.863, 14, 0, 0, "Fri Jun 5 2026 08:59:30"));
	track[0].push(new TrackPoint(35.347631, 139.459012, 10.873, 14, 0, 0, "Fri Jun 5 2026 08:59:34"));
	track[0].push(new TrackPoint(35.347647, 139.458980, 10.877, 14, 0, 0, "Fri Jun 5 2026 08:59:36"));
	track[0].push(new TrackPoint(35.347709, 139.458954, 10.884, 14, 0, 0, "Fri Jun 5 2026 08:59:39"));
	track[0].push(new TrackPoint(35.347711, 139.458705, 10.907, 15, 0, 0, "Fri Jun 5 2026 08:59:50"));
	track[0].push(new TrackPoint(35.347689, 139.458586, 10.918, 16, 0, 0, "Fri Jun 5 2026 08:59:56"));
	track[0].push(new TrackPoint(35.347681, 139.458388, 10.936, 18, 0, 0, "Fri Jun 5 2026 09:00:04"));
	track[0].push(new TrackPoint(35.347619, 139.458058, 10.967, 19, 0, 0, "Fri Jun 5 2026 09:00:19"));
	track[0].push(new TrackPoint(35.347444, 139.457502, 11.021, 16, 0, 0, "Fri Jun 5 2026 09:00:45"));
	track[0].push(new TrackPoint(35.347258, 139.456986, 11.073, 17, 0, 0, "Fri Jun 5 2026 09:01:20"));
	track[0].push(new TrackPoint(35.347164, 139.456965, 11.084, 17, 0, 0, "Fri Jun 5 2026 09:02:00"));
	track[0].push(new TrackPoint(35.347122, 139.456891, 11.092, 17, 0, 0, "Fri Jun 5 2026 09:02:06"));
	track[0].push(new TrackPoint(35.347025, 139.456565, 11.124, 19, 0, 0, "Fri Jun 5 2026 09:02:29"));
	track[0].push(new TrackPoint(35.346889, 139.455638, 11.211, 17, 0, 0, "Fri Jun 5 2026 09:03:33"));
	track[0].push(new TrackPoint(35.346757, 139.455171, 11.256, 17, 0, 0, "Fri Jun 5 2026 09:04:34"));
	track[0].push(new TrackPoint(35.346757, 139.455126, 11.260, 17, 0, 0, "Fri Jun 5 2026 09:04:40"));
	track[0].push(new TrackPoint(35.346736, 139.455074, 11.265, 17, 0, 0, "Fri Jun 5 2026 09:04:46"));
	track[0].push(new TrackPoint(35.346729, 139.454933, 11.278, 18, 0, 0, "Fri Jun 5 2026 09:04:56"));
	track[0].push(new TrackPoint(35.346679, 139.454824, 11.290, 17, 0, 0, "Fri Jun 5 2026 09:05:04"));
	track[0].push(new TrackPoint(35.346659, 139.454667, 11.304, 17, 0, 0, "Fri Jun 5 2026 09:05:14"));
	track[0].push(new TrackPoint(35.346534, 139.454199, 11.349, 17, 0, 0, "Fri Jun 5 2026 09:05:48"));
	track[0].push(new TrackPoint(35.346511, 139.454057, 11.362, 18, 0, 0, "Fri Jun 5 2026 09:05:58"));
	track[0].push(new TrackPoint(35.346283, 139.453497, 11.419, 18, 0, 0, "Fri Jun 5 2026 09:06:40"));
	track[0].push(new TrackPoint(35.346080, 139.453011, 11.469, 18, 0, 0, "Fri Jun 5 2026 09:07:15"));
	track[0].push(new TrackPoint(35.346012, 139.452578, 11.509, 18, 0, 0, "Fri Jun 5 2026 09:07:46"));
	track[0].push(new TrackPoint(35.345971, 139.452059, 11.557, 20, 0, 0, "Fri Jun 5 2026 09:08:20"));
	track[0].push(new TrackPoint(35.345980, 139.451899, 11.572, 19, 0, 0, "Fri Jun 5 2026 09:08:30"));
	track[0].push(new TrackPoint(35.346067, 139.451426, 11.616, 17, 0, 0, "Fri Jun 5 2026 09:09:01"));
	track[0].push(new TrackPoint(35.346255, 139.450627, 11.692, 15, 0, 0, "Fri Jun 5 2026 09:09:52"));
	track[0].push(new TrackPoint(35.346287, 139.450217, 11.729, 16, 0, 0, "Fri Jun 5 2026 09:10:21"));
	track[0].push(new TrackPoint(35.346277, 139.449816, 11.766, 16, 0, 0, "Fri Jun 5 2026 09:10:46"));
	track[0].push(new TrackPoint(35.346207, 139.449456, 11.800, 15, 0, 0, "Fri Jun 5 2026 09:11:07"));
	track[0].push(new TrackPoint(35.346133, 139.449261, 11.819, 14, 0, 0, "Fri Jun 5 2026 09:11:20"));
	track[0].push(new TrackPoint(35.345780, 139.448702, 11.883, 15, 0, 0, "Fri Jun 5 2026 09:11:52"));
	track[0].push(new TrackPoint(35.345940, 139.448573, 11.907, 16, 0, 0, "Fri Jun 5 2026 09:12:46"));
	track[0].push(new TrackPoint(35.345817, 139.448398, 11.928, 17, 0, 0, "Fri Jun 5 2026 09:12:56"));
	track[0].push(new TrackPoint(35.345733, 139.448324, 11.940, 17, 0, 0, "Fri Jun 5 2026 09:13:04"));
	track[0].push(new TrackPoint(35.345471, 139.447922, 11.987, 18, 0, 0, "Fri Jun 5 2026 09:13:46"));
	track[0].push(new TrackPoint(35.345486, 139.447922, 11.990, 18, 0, 0, "Fri Jun 5 2026 09:14:24"));
	track[0].push(new TrackPoint(35.345440, 139.447821, 12.001, 18, 0, 0, "Fri Jun 5 2026 09:15:40"));
	track[0].push(new TrackPoint(35.345314, 139.447609, 12.024, 17, 0, 0, "Fri Jun 5 2026 09:15:53"));
	track[0].push(new TrackPoint(35.345172, 139.447441, 12.047, 17, 0, 0, "Fri Jun 5 2026 09:16:03"));
	track[0].push(new TrackPoint(35.344978, 139.447016, 12.091, 18, 0, 0, "Fri Jun 5 2026 09:16:24"));
	track[0].push(new TrackPoint(35.344906, 139.446906, 12.104, 18, 0, 0, "Fri Jun 5 2026 09:16:31"));
	track[0].push(new TrackPoint(35.344762, 139.446584, 12.137, 18, 0, 0, "Fri Jun 5 2026 09:17:05"));
	track[0].push(new TrackPoint(35.344666, 139.446444, 12.154, 17, 0, 0, "Fri Jun 5 2026 09:17:13"));
	track[0].push(new TrackPoint(35.344478, 139.445726, 12.223, 17, 0, 0, "Fri Jun 5 2026 09:17:46"));
	track[0].push(new TrackPoint(35.344437, 139.445659, 12.230, 17, 0, 0, "Fri Jun 5 2026 09:17:49"));
	track[0].push(new TrackPoint(35.344413, 139.445523, 12.243, 17, 0, 0, "Fri Jun 5 2026 09:17:55"));
	track[0].push(new TrackPoint(35.344328, 139.445248, 12.270, 15, 0, 0, "Fri Jun 5 2026 09:18:08"));
	track[0].push(new TrackPoint(35.344280, 139.444903, 12.302, 16, 0, 0, "Fri Jun 5 2026 09:18:23"));
	track[0].push(new TrackPoint(35.344235, 139.444751, 12.317, 16, 0, 0, "Fri Jun 5 2026 09:18:30"));
	track[0].push(new TrackPoint(35.344195, 139.444279, 12.360, 14, 0, 0, "Fri Jun 5 2026 09:18:51"));
	track[0].push(new TrackPoint(35.344181, 139.443407, 12.440, 14, 0, 0, "Fri Jun 5 2026 09:19:31"));
	track[0].push(new TrackPoint(35.343973, 139.442339, 12.540, 16, 0, 0, "Fri Jun 5 2026 09:20:23"));
	track[0].push(new TrackPoint(35.343879, 139.442137, 12.561, 15, 0, 0, "Fri Jun 5 2026 09:20:33"));
	track[0].push(new TrackPoint(35.343781, 139.441844, 12.590, 16, 0, 0, "Fri Jun 5 2026 09:20:47"));
	track[0].push(new TrackPoint(35.343713, 139.441554, 12.618, 17, 0, 0, "Fri Jun 5 2026 09:21:00"));
	track[0].push(new TrackPoint(35.343607, 139.441228, 12.650, 18, 0, 0, "Fri Jun 5 2026 09:21:17"));
	track[0].push(new TrackPoint(35.343519, 139.440852, 12.685, 19, 0, 0, "Fri Jun 5 2026 09:21:34"));
	track[0].push(new TrackPoint(35.343378, 139.440446, 12.726, 18, 0, 0, "Fri Jun 5 2026 09:21:54"));
	track[0].push(new TrackPoint(35.343115, 139.439977, 12.778, 16, 0, 0, "Fri Jun 5 2026 09:22:28"));
	track[0].push(new TrackPoint(35.343059, 139.439827, 12.793, 16, 0, 0, "Fri Jun 5 2026 09:22:35"));
	track[0].push(new TrackPoint(35.342685, 139.439301, 12.857, 13, 0, 0, "Fri Jun 5 2026 09:23:07"));
	track[0].push(new TrackPoint(35.342355, 139.438951, 12.905, 14, 0, 0, "Fri Jun 5 2026 09:23:29"));
	track[0].push(new TrackPoint(35.342035, 139.438513, 12.959, 18, 0, 0, "Fri Jun 5 2026 09:23:57"));
	track[0].push(new TrackPoint(35.341908, 139.438377, 12.978, 18, 0, 0, "Fri Jun 5 2026 09:24:08"));
	track[0].push(new TrackPoint(35.341796, 139.438277, 12.993, 18, 0, 0, "Fri Jun 5 2026 09:24:15"));
	track[0].push(new TrackPoint(35.341604, 139.437947, 13.031, 15, 0, 0, "Fri Jun 5 2026 09:24:33"));
	track[0].push(new TrackPoint(35.341241, 139.437425, 13.093, 16, 0, 0, "Fri Jun 5 2026 09:25:01"));
	track[0].push(new TrackPoint(35.341110, 139.437318, 13.111, 15, 0, 0, "Fri Jun 5 2026 09:25:09"));
	track[0].push(new TrackPoint(35.340953, 139.437117, 13.136, 14, 0, 0, "Fri Jun 5 2026 09:25:21"));
	track[0].push(new TrackPoint(35.340937, 139.437064, 13.141, 13, 0, 0, "Fri Jun 5 2026 09:25:23"));
	track[0].push(new TrackPoint(35.340430, 139.436375, 13.226, 14, 0, 0, "Fri Jun 5 2026 09:26:04"));
	track[0].push(new TrackPoint(35.340183, 139.436105, 13.262, 16, 0, 0, "Fri Jun 5 2026 09:26:22"));
	track[0].push(new TrackPoint(35.340103, 139.435971, 13.278, 16, 0, 0, "Fri Jun 5 2026 09:26:29"));
	track[0].push(new TrackPoint(35.339849, 139.435611, 13.321, 17, 0, 0, "Fri Jun 5 2026 09:26:51"));
	track[0].push(new TrackPoint(35.339775, 139.435537, 13.332, 16, 0, 0, "Fri Jun 5 2026 09:26:56"));
	track[0].push(new TrackPoint(35.339590, 139.435246, 13.365, 15, 0, 0, "Fri Jun 5 2026 09:27:12"));
	track[0].push(new TrackPoint(35.339530, 139.435188, 13.374, 15, 0, 0, "Fri Jun 5 2026 09:27:16"));
	track[0].push(new TrackPoint(35.339486, 139.435105, 13.383, 15, 0, 0, "Fri Jun 5 2026 09:27:21"));
	track[0].push(new TrackPoint(35.339355, 139.435084, 13.397, 15, 0, 0, "Fri Jun 5 2026 09:27:27"));
	track[0].push(new TrackPoint(35.339274, 139.435014, 13.408, 15, 0, 0, "Fri Jun 5 2026 09:27:32"));
	track[0].push(new TrackPoint(35.339260, 139.434960, 13.413, 15, 0, 0, "Fri Jun 5 2026 09:27:34"));
	track[0].push(new TrackPoint(35.338960, 139.434453, 13.471, 15, 0, 0, "Fri Jun 5 2026 09:28:03"));
	track[0].push(new TrackPoint(35.338884, 139.434388, 13.481, 15, 0, 0, "Fri Jun 5 2026 09:28:08"));
	track[0].push(new TrackPoint(35.338816, 139.434199, 13.500, 14, 0, 0, "Fri Jun 5 2026 09:28:15"));
	track[0].push(new TrackPoint(35.338623, 139.433926, 13.533, 12, 0, 0, "Fri Jun 5 2026 09:28:30"));
	track[0].push(new TrackPoint(35.338424, 139.433574, 13.572, 12, 0, 0, "Fri Jun 5 2026 09:28:51"));
	track[0].push(new TrackPoint(35.338220, 139.433296, 13.606, 12, 0, 0, "Fri Jun 5 2026 09:29:06"));
	track[0].push(new TrackPoint(35.337585, 139.432237, 13.725, 14, 0, 0, "Fri Jun 5 2026 09:30:05"));
	track[0].push(new TrackPoint(35.337413, 139.431848, 13.766, 15, 0, 0, "Fri Jun 5 2026 09:30:24"));
	track[0].push(new TrackPoint(35.337330, 139.431581, 13.792, 15, 0, 0, "Fri Jun 5 2026 09:30:36"));
	track[0].push(new TrackPoint(35.337305, 139.431433, 13.805, 15, 0, 0, "Fri Jun 5 2026 09:30:43"));
	track[0].push(new TrackPoint(35.337302, 139.431285, 13.819, 15, 0, 0, "Fri Jun 5 2026 09:30:49"));
	track[0].push(new TrackPoint(35.337178, 139.430380, 13.903, 12, 0, 0, "Fri Jun 5 2026 09:31:30"));
	track[0].push(new TrackPoint(35.337164, 139.430069, 13.931, 13, 0, 0, "Fri Jun 5 2026 09:31:44"));
	track[0].push(new TrackPoint(35.337088, 139.429759, 13.960, 13, 0, 0, "Fri Jun 5 2026 09:31:58"));
	track[0].push(new TrackPoint(35.337072, 139.429313, 14.001, 14, 0, 0, "Fri Jun 5 2026 09:32:18"));
	track[0].push(new TrackPoint(35.337110, 139.428834, 14.045, 14, 0, 0, "Fri Jun 5 2026 09:32:39"));
	track[0].push(new TrackPoint(35.337136, 139.428678, 14.059, 13, 0, 0, "Fri Jun 5 2026 09:32:46"));
	track[0].push(new TrackPoint(35.337143, 139.428306, 14.093, 13, 0, 0, "Fri Jun 5 2026 09:33:00"));
	track[0].push(new TrackPoint(35.337132, 139.428199, 14.103, 13, 0, 0, "Fri Jun 5 2026 09:33:06"));
	track[0].push(new TrackPoint(35.337179, 139.427681, 14.150, 13, 0, 0, "Fri Jun 5 2026 09:33:34"));
	track[0].push(new TrackPoint(35.337386, 139.426756, 14.238, 18, 0, 0, "Fri Jun 5 2026 09:34:18"));
	track[0].push(new TrackPoint(35.337422, 139.426341, 14.276, 16, 0, 0, "Fri Jun 5 2026 09:34:39"));
	track[0].push(new TrackPoint(35.337557, 139.425859, 14.323, 17, 0, 0, "Fri Jun 5 2026 09:35:01"));
	track[0].push(new TrackPoint(35.337819, 139.425052, 14.402, 14, 0, 0, "Fri Jun 5 2026 09:35:40"));
	track[0].push(new TrackPoint(35.337843, 139.424897, 14.416, 15, 0, 0, "Fri Jun 5 2026 09:35:47"));
	track[0].push(new TrackPoint(35.337841, 139.424319, 14.469, 19, 0, 0, "Fri Jun 5 2026 09:36:14"));
	track[0].push(new TrackPoint(35.337806, 139.424056, 14.494, 17, 0, 0, "Fri Jun 5 2026 09:36:27"));
	track[0].push(new TrackPoint(35.337816, 139.424006, 14.498, 17, 0, 0, "Fri Jun 5 2026 09:36:29"));
	track[0].push(new TrackPoint(35.337785, 139.423386, 14.555, 16, 0, 0, "Fri Jun 5 2026 09:36:56"));
	track[0].push(new TrackPoint(35.337752, 139.423257, 14.567, 16, 0, 0, "Fri Jun 5 2026 09:37:02"));
	track[0].push(new TrackPoint(35.337758, 139.423097, 14.582, 17, 0, 0, "Fri Jun 5 2026 09:37:09"));
	track[0].push(new TrackPoint(35.337722, 139.422785, 14.610, 16, 0, 0, "Fri Jun 5 2026 09:37:23"));
	track[0].push(new TrackPoint(35.337701, 139.422450, 14.644, 15, 0, 0, "Fri Jun 5 2026 09:38:33"));
	track[0].push(new TrackPoint(35.337676, 139.422330, 14.655, 13, 0, 0, "Fri Jun 5 2026 09:38:39"));
	track[0].push(new TrackPoint(35.337687, 139.422142, 14.672, 12, 0, 0, "Fri Jun 5 2026 09:38:47"));
	track[0].push(new TrackPoint(35.337679, 139.421743, 14.709, 11, 0, 0, "Fri Jun 5 2026 09:39:02"));
	track[0].push(new TrackPoint(35.337689, 139.421605, 14.722, 10, 0, 0, "Fri Jun 5 2026 09:39:08"));
	track[0].push(new TrackPoint(35.337619, 139.421081, 14.770, 12, 0, 0, "Fri Jun 5 2026 09:39:31"));
	track[0].push(new TrackPoint(35.337567, 139.420751, 14.801, 13, 0, 0, "Fri Jun 5 2026 09:39:45"));
	track[0].push(new TrackPoint(35.337510, 139.420592, 14.817, 13, 0, 0, "Fri Jun 5 2026 09:39:52"));
	track[0].push(new TrackPoint(35.337449, 139.420280, 14.846, 13, 0, 0, "Fri Jun 5 2026 09:40:06"));
	track[0].push(new TrackPoint(35.337411, 139.419980, 14.874, 13, 0, 0, "Fri Jun 5 2026 09:40:19"));
	track[0].push(new TrackPoint(35.337321, 139.419769, 14.895, 14, 0, 0, "Fri Jun 5 2026 09:40:30"));
	track[0].push(new TrackPoint(35.337312, 139.419679, 14.904, 15, 0, 0, "Fri Jun 5 2026 09:40:34"));
	track[0].push(new TrackPoint(35.337177, 139.419129, 14.956, 15, 0, 0, "Fri Jun 5 2026 09:40:59"));
	track[0].push(new TrackPoint(35.337083, 139.418871, 14.982, 15, 0, 0, "Fri Jun 5 2026 09:41:11"));
	track[0].push(new TrackPoint(35.337063, 139.418672, 15.000, 13, 0, 0, "Fri Jun 5 2026 09:41:21"));
	track[0].push(new TrackPoint(35.337020, 139.418516, 15.015, 12, 0, 0, "Fri Jun 5 2026 09:41:28"));
	track[0].push(new TrackPoint(35.336929, 139.418290, 15.038, 12, 0, 0, "Fri Jun 5 2026 09:41:58"));
	track[0].push(new TrackPoint(35.336821, 139.417901, 15.076, 14, 0, 0, "Fri Jun 5 2026 09:42:14"));
	track[0].push(new TrackPoint(35.336812, 139.417654, 15.098, 15, 0, 0, "Fri Jun 5 2026 09:42:25"));
	track[0].push(new TrackPoint(35.336675, 139.417019, 15.158, 14, 0, 0, "Fri Jun 5 2026 09:42:54"));
	track[0].push(new TrackPoint(35.336659, 139.416870, 15.172, 14, 0, 0, "Fri Jun 5 2026 09:43:01"));
	track[0].push(new TrackPoint(35.336613, 139.416703, 15.188, 14, 0, 0, "Fri Jun 5 2026 09:43:09"));
	track[0].push(new TrackPoint(35.336602, 139.416514, 15.205, 14, 0, 0, "Fri Jun 5 2026 09:43:17"));
	track[0].push(new TrackPoint(35.336444, 139.415419, 15.306, 15, 0, 0, "Fri Jun 5 2026 09:44:24"));
	track[0].push(new TrackPoint(35.336377, 139.414629, 15.379, 15, 0, 0, "Fri Jun 5 2026 09:45:00"));
	track[0].push(new TrackPoint(35.336416, 139.414475, 15.394, 15, 0, 0, "Fri Jun 5 2026 09:45:06"));
	track[0].push(new TrackPoint(35.336415, 139.414388, 15.402, 15, 0, 0, "Fri Jun 5 2026 09:45:09"));
	track[0].push(new TrackPoint(35.336312, 139.413918, 15.446, 14, 0, 0, "Fri Jun 5 2026 09:45:30"));
	track[0].push(new TrackPoint(35.336036, 139.413190, 15.519, 15, 0, 0, "Fri Jun 5 2026 09:46:05"));
	track[0].push(new TrackPoint(35.335859, 139.412894, 15.552, 15, 0, 0, "Fri Jun 5 2026 09:46:21"));
	track[0].push(new TrackPoint(35.335632, 139.412541, 15.593, 15, 0, 0, "Fri Jun 5 2026 09:46:41"));
	track[0].push(new TrackPoint(35.335507, 139.412281, 15.621, 16, 0, 0, "Fri Jun 5 2026 09:46:54"));
	track[0].push(new TrackPoint(35.335396, 139.411945, 15.653, 16, 0, 0, "Fri Jun 5 2026 09:47:12"));
	track[0].push(new TrackPoint(35.335331, 139.411827, 15.667, 16, 0, 0, "Fri Jun 5 2026 09:47:18"));
	track[0].push(new TrackPoint(35.335318, 139.411777, 15.671, 16, 0, 0, "Fri Jun 5 2026 09:47:20"));
	track[0].push(new TrackPoint(35.335280, 139.411713, 15.679, 16, 0, 0, "Fri Jun 5 2026 09:47:24"));
	track[0].push(new TrackPoint(35.335110, 139.411203, 15.729, 14, 0, 0, "Fri Jun 5 2026 09:47:48"));
	track[0].push(new TrackPoint(35.335083, 139.411079, 15.741, 14, 0, 0, "Fri Jun 5 2026 09:47:53"));
	track[0].push(new TrackPoint(35.334956, 139.410822, 15.768, 14, 0, 0, "Fri Jun 5 2026 09:48:06"));
	track[0].push(new TrackPoint(35.334451, 139.410093, 15.855, 15, 0, 0, "Fri Jun 5 2026 09:48:51"));
	track[0].push(new TrackPoint(35.334397, 139.409928, 15.871, 15, 0, 0, "Fri Jun 5 2026 09:48:59"));
	track[0].push(new TrackPoint(35.334370, 139.409743, 15.888, 16, 0, 0, "Fri Jun 5 2026 09:49:07"));
	track[0].push(new TrackPoint(35.334279, 139.409548, 15.909, 17, 0, 0, "Fri Jun 5 2026 09:49:16"));
	track[0].push(new TrackPoint(35.334113, 139.408915, 15.969, 16, 0, 0, "Fri Jun 5 2026 09:49:47"));
	track[0].push(new TrackPoint(35.334104, 139.408731, 15.986, 16, 0, 0, "Fri Jun 5 2026 09:49:55"));
	track[0].push(new TrackPoint(35.333997, 139.408090, 16.046, 12, 0, 0, "Fri Jun 5 2026 09:50:24"));
	track[0].push(new TrackPoint(35.333781, 139.407638, 16.094, 10, 0, 0, "Fri Jun 5 2026 09:50:46"));
	track[0].push(new TrackPoint(35.333551, 139.407042, 16.154, 11, 0, 0, "Fri Jun 5 2026 09:51:13"));
	track[0].push(new TrackPoint(35.333481, 139.406974, 16.164, 11, 0, 0, "Fri Jun 5 2026 09:51:34"));
	track[0].push(new TrackPoint(35.333360, 139.406951, 16.178, 10, 0, 0, "Fri Jun 5 2026 09:52:01"));
	track[0].push(new TrackPoint(35.333388, 139.407082, 16.191, 11, 0, 0, "Fri Jun 5 2026 09:52:35"));
	track[0].push(new TrackPoint(35.333351, 139.406916, 16.207, 10, 0, 0, "Fri Jun 5 2026 09:52:53"));
	track[0].push(new TrackPoint(35.333380, 139.406772, 16.221, 11, 0, 0, "Fri Jun 5 2026 09:53:07"));
	track[0].push(new TrackPoint(35.333355, 139.406650, 16.232, 12, 0, 0, "Fri Jun 5 2026 09:53:15"));
	track[0].push(new TrackPoint(35.333316, 139.406547, 16.243, 13, 0, 0, "Fri Jun 5 2026 09:54:02"));
	track[0].push(new TrackPoint(35.333325, 139.406428, 16.256, 15, 0, 0, "Fri Jun 5 2026 09:55:33"));
	track[0].push(new TrackPoint(35.333306, 139.406371, 16.262, 16, 0, 0, "Fri Jun 5 2026 09:55:58"));
	track[0].push(new TrackPoint(35.333302, 139.406216, 16.276, 18, 0, 0, "Fri Jun 5 2026 09:56:04"));
	track[0].push(new TrackPoint(35.333322, 139.406080, 16.289, 19, 0, 0, "Fri Jun 5 2026 09:56:10"));
	track[0].push(new TrackPoint(35.333308, 139.405932, 16.303, 19, 0, 0, "Fri Jun 5 2026 09:56:18"));
	track[0].push(new TrackPoint(35.333227, 139.405792, 16.319, 18, 0, 0, "Fri Jun 5 2026 09:56:31"));
	track[0].push(new TrackPoint(35.333070, 139.405809, 16.338, 15, 0, 0, "Fri Jun 5 2026 09:56:59"));
	track[0].push(new TrackPoint(35.333261, 139.405406, 16.380, 15, 0, 0, "Fri Jun 5 2026 09:57:28"));
	track[0].push(new TrackPoint(35.333071, 139.405033, 16.420, 16, 0, 0, "Fri Jun 5 2026 09:58:04"));
	track[0].push(new TrackPoint(35.332999, 139.404781, 16.444, 16, 0, 0, "Fri Jun 5 2026 09:58:21"));
	track[0].push(new TrackPoint(35.332936, 139.404667, 16.457, 15, 0, 0, "Fri Jun 5 2026 09:58:28"));
	track[0].push(new TrackPoint(35.332824, 139.404159, 16.507, 14, 0, 0, "Fri Jun 5 2026 09:59:11"));
	track[0].push(new TrackPoint(35.332650, 139.403743, 16.550, 14, 0, 0, "Fri Jun 5 2026 09:59:35"));
	track[0].push(new TrackPoint(35.332625, 139.403572, 16.566, 14, 0, 0, "Fri Jun 5 2026 09:59:42"));
	track[0].push(new TrackPoint(35.332631, 139.403520, 16.570, 14, 0, 0, "Fri Jun 5 2026 09:59:44"));
	track[0].push(new TrackPoint(35.332289, 139.402575, 16.665, 10, 0, 0, "Fri Jun 5 2026 10:00:27"));
	track[0].push(new TrackPoint(35.332224, 139.402463, 16.677, 10, 0, 0, "Fri Jun 5 2026 10:00:33"));
	track[0].push(new TrackPoint(35.332169, 139.402297, 16.693, 9, 0, 0, "Fri Jun 5 2026 10:00:41"));
	track[0].push(new TrackPoint(35.331828, 139.401736, 16.757, 10, 0, 0, "Fri Jun 5 2026 10:01:10"));
	track[0].push(new TrackPoint(35.331772, 139.401675, 16.765, 10, 0, 0, "Fri Jun 5 2026 10:01:14"));
	track[0].push(new TrackPoint(35.331700, 139.401509, 16.782, 9, 0, 0, "Fri Jun 5 2026 10:01:22"));
	track[0].push(new TrackPoint(35.331435, 139.401181, 16.824, 10, 0, 0, "Fri Jun 5 2026 10:01:44"));
	track[0].push(new TrackPoint(35.331386, 139.401144, 16.831, 11, 0, 0, "Fri Jun 5 2026 10:01:47"));
	track[0].push(new TrackPoint(35.331351, 139.401015, 16.843, 11, 0, 0, "Fri Jun 5 2026 10:01:52"));
	track[0].push(new TrackPoint(35.331168, 139.400643, 16.883, 9, 0, 0, "Fri Jun 5 2026 10:02:10"));
	track[0].push(new TrackPoint(35.330982, 139.400179, 16.930, 8, 0, 0, "Fri Jun 5 2026 10:02:34"));
	track[0].push(new TrackPoint(35.330692, 139.399615, 16.991, 10, 0, 0, "Fri Jun 5 2026 10:03:03"));
	track[0].push(new TrackPoint(35.330618, 139.399411, 17.011, 11, 0, 0, "Fri Jun 5 2026 10:03:13"));
	track[0].push(new TrackPoint(35.330544, 139.399260, 17.027, 11, 0, 0, "Fri Jun 5 2026 10:03:21"));
	track[0].push(new TrackPoint(35.330512, 139.399225, 17.032, 11, 0, 0, "Fri Jun 5 2026 10:03:23"));
	track[0].push(new TrackPoint(35.330152, 139.398213, 17.132, 7, 0, 0, "Fri Jun 5 2026 10:04:12"));
	track[0].push(new TrackPoint(35.330141, 139.398063, 17.146, 6, 0, 0, "Fri Jun 5 2026 10:04:18"));
	track[0].push(new TrackPoint(35.330063, 139.397816, 17.170, 7, 0, 0, "Fri Jun 5 2026 10:04:31"));
	track[0].push(new TrackPoint(35.330029, 139.397641, 17.187, 7, 0, 0, "Fri Jun 5 2026 10:04:39"));
	track[0].push(new TrackPoint(35.329784, 139.396947, 17.255, 10, 0, 0, "Fri Jun 5 2026 10:05:15"));
	track[0].push(new TrackPoint(35.329661, 139.396350, 17.312, 10, 0, 0, "Fri Jun 5 2026 10:05:42"));
	track[0].push(new TrackPoint(35.329565, 139.396017, 17.344, 9, 0, 0, "Fri Jun 5 2026 10:05:58"));
	track[0].push(new TrackPoint(35.329487, 139.395825, 17.363, 7, 0, 0, "Fri Jun 5 2026 10:06:08"));
	track[0].push(new TrackPoint(35.329366, 139.395325, 17.411, 8, 0, 0, "Fri Jun 5 2026 10:06:32"));
	track[0].push(new TrackPoint(35.329274, 139.395078, 17.436, 9, 0, 0, "Fri Jun 5 2026 10:06:45"));
	track[0].push(new TrackPoint(35.328941, 139.393817, 17.556, 8, 0, 0, "Fri Jun 5 2026 10:07:42"));
	track[0].push(new TrackPoint(35.328815, 139.393517, 17.587, 8, 0, 0, "Fri Jun 5 2026 10:07:56"));
	track[0].push(new TrackPoint(35.328733, 139.393209, 17.616, 8, 0, 0, "Fri Jun 5 2026 10:08:10"));
	track[0].push(new TrackPoint(35.328594, 139.392836, 17.654, 7, 0, 0, "Fri Jun 5 2026 10:08:29"));
	track[0].push(new TrackPoint(35.328578, 139.392619, 17.674, 7, 0, 0, "Fri Jun 5 2026 10:08:39"));
	track[0].push(new TrackPoint(35.328582, 139.392433, 17.691, 7, 0, 0, "Fri Jun 5 2026 10:08:47"));
	track[0].push(new TrackPoint(35.328663, 139.391924, 17.738, 6, 0, 0, "Fri Jun 5 2026 10:09:10"));
	track[0].push(new TrackPoint(35.328709, 139.391754, 17.754, 6, 0, 0, "Fri Jun 5 2026 10:09:18"));
	track[0].push(new TrackPoint(35.328775, 139.391620, 17.768, 6, 0, 0, "Fri Jun 5 2026 10:09:25"));
	track[0].push(new TrackPoint(35.328835, 139.391448, 17.785, 6, 0, 0, "Fri Jun 5 2026 10:09:33"));
	track[0].push(new TrackPoint(35.329195, 139.390662, 17.867, 5, 0, 0, "Fri Jun 5 2026 10:10:15"));
	track[0].push(new TrackPoint(35.329264, 139.390552, 17.880, 5, 0, 0, "Fri Jun 5 2026 10:10:22"));
	track[0].push(new TrackPoint(35.329603, 139.390276, 17.925, 2, 0, 0, "Fri Jun 5 2026 10:10:47"));
	track[0].push(new TrackPoint(35.330745, 139.389192, 18.086, 5, 0, 0, "Fri Jun 5 2026 10:12:09"));
	track[0].push(new TrackPoint(35.331717, 139.388288, 18.222, 6, 0, 0, "Fri Jun 5 2026 10:13:20"));
	track[0].push(new TrackPoint(35.332117, 139.387878, 18.280, 8, 0, 0, "Fri Jun 5 2026 10:13:51"));
	track[0].push(new TrackPoint(35.332361, 139.387566, 18.319, 7, 0, 0, "Fri Jun 5 2026 10:14:11"));
	track[0].push(new TrackPoint(35.332558, 139.387265, 18.354, 6, 0, 0, "Fri Jun 5 2026 10:14:29"));
	track[0].push(new TrackPoint(35.332621, 139.387143, 18.368, 6, 0, 0, "Fri Jun 5 2026 10:14:36"));
	track[0].push(new TrackPoint(35.332751, 139.386704, 18.410, 4, 0, 0, "Fri Jun 5 2026 10:14:58"));
	track[0].push(new TrackPoint(35.332775, 139.386391, 18.439, 3, 0, 0, "Fri Jun 5 2026 10:15:14"));
	track[0].push(new TrackPoint(35.332759, 139.386270, 18.450, 3, 0, 0, "Fri Jun 5 2026 10:15:19"));
	track[0].push(new TrackPoint(35.332784, 139.386110, 18.465, 3, 0, 0, "Fri Jun 5 2026 10:15:26"));
	track[0].push(new TrackPoint(35.332792, 139.385041, 18.563, 5, 0, 0, "Fri Jun 5 2026 10:16:14"));
	track[0].push(new TrackPoint(35.332834, 139.384969, 18.571, 5, 0, 0, "Fri Jun 5 2026 10:16:18"));
	track[0].push(new TrackPoint(35.332856, 139.384815, 18.585, 4, 0, 0, "Fri Jun 5 2026 10:16:26"));
	track[0].push(new TrackPoint(35.332860, 139.384505, 18.614, 2, 0, 0, "Fri Jun 5 2026 10:16:41"));
	track[0].push(new TrackPoint(35.332890, 139.384266, 18.636, 1, 0, 0, "Fri Jun 5 2026 10:16:52"));
	track[0].push(new TrackPoint(35.332891, 139.384061, 18.654, 2, 0, 0, "Fri Jun 5 2026 10:17:04"));
	track[0].push(new TrackPoint(35.332908, 139.384038, 18.657, 2, 0, 0, "Fri Jun 5 2026 10:17:10"));
	track[0].push(new TrackPoint(35.332972, 139.384174, 18.671, 1, 0, 0, "Fri Jun 5 2026 10:17:20"));
	track[0].push(new TrackPoint(35.333073, 139.384253, 18.685, 2, 0, 0, "Fri Jun 5 2026 10:17:31"));
	track[0].push(new TrackPoint(35.333038, 139.384250, 18.689, 2, 0, 0, "Fri Jun 5 2026 10:17:36"));
	track[0].push(new TrackPoint(35.333017, 139.384204, 18.694, 1, 0, 0, "Fri Jun 5 2026 10:17:39"));
	track[0].push(new TrackPoint(35.332911, 139.384143, 18.707, 1, 0, 0, "Fri Jun 5 2026 10:17:49"));
	track[0].push(new TrackPoint(35.332869, 139.384097, 18.714, 1, 0, 0, "Fri Jun 5 2026 10:17:58"));
	track[0].push(new TrackPoint(35.332942, 139.383901, 18.733, 2, 0, 0, "Fri Jun 5 2026 10:18:10"));
	track[0].push(new TrackPoint(35.333007, 139.383700, 18.753, 4, 0, 0, "Fri Jun 5 2026 10:18:25"));
	track[0].push(new TrackPoint(35.333194, 139.383770, 18.776, 7, 0, 0, "Fri Jun 5 2026 10:18:46"));
	track[0].push(new TrackPoint(35.333193, 139.383722, 18.781, 7, 0, 0, "Fri Jun 5 2026 10:18:50"));
	track[0].push(new TrackPoint(35.332947, 139.383555, 18.812, 5, 0, 0, "Fri Jun 5 2026 10:19:14"));
	track[0].push(new TrackPoint(35.332931, 139.383511, 18.817, 6, 0, 0, "Fri Jun 5 2026 10:19:18"));
	track[0].push(new TrackPoint(35.333146, 139.382416, 18.919, 4, 0, 0, "Fri Jun 5 2026 10:20:11"));
	track[0].push(new TrackPoint(35.333209, 139.382028, 18.955, 3, 0, 0, "Fri Jun 5 2026 10:20:28"));
	track[0].push(new TrackPoint(35.333245, 139.381886, 18.969, 3, 0, 0, "Fri Jun 5 2026 10:20:34"));
	track[0].push(new TrackPoint(35.333246, 139.381444, 19.009, 2, 0, 0, "Fri Jun 5 2026 10:20:54"));
	track[0].push(new TrackPoint(35.333217, 139.381099, 19.041, 3, 0, 0, "Fri Jun 5 2026 10:21:11"));
	track[0].push(new TrackPoint(35.333184, 139.380960, 19.054, 4, 0, 0, "Fri Jun 5 2026 10:21:18"));
	track[0].push(new TrackPoint(35.333144, 139.380490, 19.097, 5, 0, 0, "Fri Jun 5 2026 10:21:39"));
	track[0].push(new TrackPoint(35.332912, 139.379062, 19.229, 4, 0, 0, "Fri Jun 5 2026 10:22:44"));
	track[0].push(new TrackPoint(35.332875, 139.378671, 19.265, 3, 0, 0, "Fri Jun 5 2026 10:23:02"));
	track[0].push(new TrackPoint(35.332875, 139.378445, 19.286, 3, 0, 0, "Fri Jun 5 2026 10:23:11"));
	track[0].push(new TrackPoint(35.332904, 139.377614, 19.361, 3, 0, 0, "Fri Jun 5 2026 10:23:52"));
	track[0].push(new TrackPoint(35.333035, 139.377433, 19.383, 3, 0, 0, "Fri Jun 5 2026 10:24:11"));
	track[0].push(new TrackPoint(35.333035, 139.377283, 19.397, 4, 0, 0, "Fri Jun 5 2026 10:24:21"));
	track[0].push(new TrackPoint(35.332969, 139.377164, 19.410, 4, 0, 0, "Fri Jun 5 2026 10:24:28"));
	track[0].push(new TrackPoint(35.332978, 139.376572, 19.464, 5, 0, 0, "Fri Jun 5 2026 10:24:54"));
	track[0].push(new TrackPoint(35.332900, 139.375533, 19.559, 5, 0, 0, "Fri Jun 5 2026 10:25:43"));
	track[0].push(new TrackPoint(35.332625, 139.373764, 19.724, 7, 0, 0, "Fri Jun 5 2026 10:27:05"));
	track[0].push(new TrackPoint(35.332458, 139.372714, 19.821, 5, 0, 0, "Fri Jun 5 2026 10:27:54"));
	track[0].push(new TrackPoint(35.332358, 139.372326, 19.858, 5, 0, 0, "Fri Jun 5 2026 10:28:14"));
	track[0].push(new TrackPoint(35.332231, 139.371704, 19.917, 8, 0, 0, "Fri Jun 5 2026 10:28:58"));
	track[0].push(new TrackPoint(35.332121, 139.371380, 19.949, 5, 0, 0, "Fri Jun 5 2026 10:29:15"));
	track[0].push(new TrackPoint(35.332028, 139.370817, 20.001, 5, 0, 0, "Fri Jun 5 2026 10:29:43"));
	track[0].push(new TrackPoint(35.331756, 139.366157, 20.427, 0, 0, 0, "Fri Jun 5 2026 10:33:28"));
	track[0].push(new TrackPoint(35.331731, 139.365180, 20.517, 7, 0, 0, "Fri Jun 5 2026 10:34:13"));
	track[0].push(new TrackPoint(35.331739, 139.364841, 20.547, 6, 0, 0, "Fri Jun 5 2026 10:34:29"));
	track[0].push(new TrackPoint(35.331719, 139.364204, 20.605, 6, 0, 0, "Fri Jun 5 2026 10:34:58"));
	track[0].push(new TrackPoint(35.331705, 139.363229, 20.694, 11, 0, 0, "Fri Jun 5 2026 10:35:40"));
	track[0].push(new TrackPoint(35.331689, 139.363015, 20.714, 12, 0, 0, "Fri Jun 5 2026 10:35:49"));
	track[0].push(new TrackPoint(35.331733, 139.362833, 20.731, 11, 0, 0, "Fri Jun 5 2026 10:35:57"));
	track[0].push(new TrackPoint(35.331775, 139.362737, 20.741, 10, 0, 0, "Fri Jun 5 2026 10:36:02"));
	track[0].push(new TrackPoint(35.331737, 139.362408, 20.771, 9, 0, 0, "Fri Jun 5 2026 10:36:24"));
	track[0].push(new TrackPoint(35.331711, 139.362368, 20.776, 9, 0, 0, "Fri Jun 5 2026 10:36:28"));
	track[0].push(new TrackPoint(35.331591, 139.362307, 20.791, 10, 0, 0, "Fri Jun 5 2026 10:36:36"));
	track[0].push(new TrackPoint(35.331535, 139.362296, 20.797, 10, 0, 0, "Fri Jun 5 2026 10:36:43"));
	track[0].push(new TrackPoint(35.331601, 139.362052, 20.820, 10, 0, 0, "Fri Jun 5 2026 10:37:02"));
	track[0].push(new TrackPoint(35.331598, 139.362018, 20.824, 10, 0, 0, "Fri Jun 5 2026 10:37:05"));
	track[0].push(new TrackPoint(35.331544, 139.361945, 20.833, 10, 0, 0, "Fri Jun 5 2026 10:37:10"));
	track[0].push(new TrackPoint(35.331495, 139.361808, 20.846, 10, 0, 0, "Fri Jun 5 2026 10:37:19"));
	track[0].push(new TrackPoint(35.331460, 139.361529, 20.872, 8, 0, 0, "Fri Jun 5 2026 10:37:39"));
	track[0].push(new TrackPoint(35.331413, 139.361279, 20.895, 7, 0, 0, "Fri Jun 5 2026 10:37:57"));
	track[0].push(new TrackPoint(35.331378, 139.360519, 20.966, 8, 0, 0, "Fri Jun 5 2026 10:39:56"));
	track[0].push(new TrackPoint(35.331409, 139.360289, 20.987, 8, 0, 0, "Fri Jun 5 2026 10:40:09"));
	track[0].push(new TrackPoint(35.331383, 139.359853, 21.027, 6, 0, 0, "Fri Jun 5 2026 10:40:28"));
	track[0].push(new TrackPoint(35.331256, 139.359243, 21.086, 5, 0, 0, "Fri Jun 5 2026 10:41:55"));
	track[0].push(new TrackPoint(35.331177, 139.358480, 21.157, 10, 0, 0, "Fri Jun 5 2026 10:42:30"));
	track[0].push(new TrackPoint(35.331195, 139.358171, 21.185, 11, 0, 0, "Fri Jun 5 2026 10:42:44"));
	track[0].push(new TrackPoint(35.331182, 139.357996, 21.201, 11, 0, 0, "Fri Jun 5 2026 10:42:52"));
	track[0].push(new TrackPoint(35.331150, 139.357866, 21.213, 11, 0, 0, "Fri Jun 5 2026 10:43:00"));
	track[0].push(new TrackPoint(35.331178, 139.357701, 21.229, 11, 0, 0, "Fri Jun 5 2026 10:43:13"));
	track[0].push(new TrackPoint(35.331133, 139.357594, 21.240, 10, 0, 0, "Fri Jun 5 2026 10:43:35"));
	track[0].push(new TrackPoint(35.331090, 139.357268, 21.270, 9, 0, 0, "Fri Jun 5 2026 10:43:51"));
	track[0].push(new TrackPoint(35.330931, 139.356592, 21.334, 8, 0, 0, "Fri Jun 5 2026 10:44:27"));
	track[0].push(new TrackPoint(35.330941, 139.356494, 21.343, 9, 0, 0, "Fri Jun 5 2026 10:44:31"));
	track[0].push(new TrackPoint(35.330878, 139.356275, 21.365, 10, 0, 0, "Fri Jun 5 2026 10:44:40"));
	track[0].push(new TrackPoint(35.330857, 139.355910, 21.398, 10, 0, 0, "Fri Jun 5 2026 10:44:57"));
	track[0].push(new TrackPoint(35.330888, 139.355714, 21.416, 8, 0, 0, "Fri Jun 5 2026 10:45:06"));
	track[0].push(new TrackPoint(35.330851, 139.355478, 21.438, 8, 0, 0, "Fri Jun 5 2026 10:45:16"));
	track[0].push(new TrackPoint(35.330771, 139.355294, 21.457, 8, 0, 0, "Fri Jun 5 2026 10:45:24"));
	track[0].push(new TrackPoint(35.330760, 139.355185, 21.467, 8, 0, 0, "Fri Jun 5 2026 10:45:29"));
	track[0].push(new TrackPoint(35.330697, 139.355017, 21.484, 9, 0, 0, "Fri Jun 5 2026 10:45:36"));
	track[0].push(new TrackPoint(35.330597, 139.354601, 21.524, 11, 0, 0, "Fri Jun 5 2026 10:45:53"));
	track[0].push(new TrackPoint(35.330574, 139.354417, 21.541, 11, 0, 0, "Fri Jun 5 2026 10:46:02"));
	track[0].push(new TrackPoint(35.330573, 139.354272, 21.554, 10, 0, 0, "Fri Jun 5 2026 10:46:08"));
	track[0].push(new TrackPoint(35.330538, 139.354118, 21.568, 10, 0, 0, "Fri Jun 5 2026 10:46:14"));
	track[0].push(new TrackPoint(35.330526, 139.353725, 21.604, 11, 0, 0, "Fri Jun 5 2026 10:46:32"));
	track[0].push(new TrackPoint(35.330334, 139.353144, 21.661, 12, 0, 0, "Fri Jun 5 2026 10:46:57"));
	track[0].push(new TrackPoint(35.330227, 139.352320, 21.737, 10, 0, 0, "Fri Jun 5 2026 10:47:32"));
	track[0].push(new TrackPoint(35.330227, 139.352009, 21.765, 10, 0, 0, "Fri Jun 5 2026 10:47:45"));
	track[0].push(new TrackPoint(35.330179, 139.351779, 21.787, 10, 0, 0, "Fri Jun 5 2026 10:47:55"));
	track[0].push(new TrackPoint(35.330175, 139.351674, 21.796, 10, 0, 0, "Fri Jun 5 2026 10:48:00"));
	track[0].push(new TrackPoint(35.330081, 139.351293, 21.833, 11, 0, 0, "Fri Jun 5 2026 10:48:17"));
	track[0].push(new TrackPoint(35.330121, 139.351090, 21.852, 11, 0, 0, "Fri Jun 5 2026 10:48:26"));
	track[0].push(new TrackPoint(35.330097, 139.350910, 21.868, 11, 0, 0, "Fri Jun 5 2026 10:48:33"));
	track[0].push(new TrackPoint(35.330031, 139.350700, 21.889, 10, 0, 0, "Fri Jun 5 2026 10:48:42"));
	track[0].push(new TrackPoint(35.329980, 139.350571, 21.904, 9, 0, 0, "Fri Jun 5 2026 10:49:17"));
	track[0].push(new TrackPoint(35.329959, 139.350332, 21.926, 10, 0, 0, "Fri Jun 5 2026 10:49:28"));
	track[0].push(new TrackPoint(35.329931, 139.350224, 21.936, 10, 0, 0, "Fri Jun 5 2026 10:49:36"));
	track[0].push(new TrackPoint(35.329898, 139.350193, 21.942, 11, 0, 0, "Fri Jun 5 2026 10:50:43"));
	track[0].push(new TrackPoint(35.329851, 139.350213, 21.947, 11, 0, 0, "Fri Jun 5 2026 10:51:04"));
	track[0].push(new TrackPoint(35.329844, 139.350179, 21.950, 11, 0, 0, "Fri Jun 5 2026 10:51:33"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
	var count = 0;
	for (i=0; i<track.length; i++) {
		count += track[i].length;
	}

	if (count > 1 && !playing) {
		centerPointer.addTo(map);

		if (showMeterPanel) {
			infoPanel = new InfoPanel();
			map.addControl(infoPanel);
		}

		playing = true;
		goForward();
	}
}

function goForward() {
	var waittime;
	var pos = track[currTrack][currPoint].latlng;
	map.panTo(pos);
	centerPointer.setLatLng(pos);

	if (showMeterPanel) {
		displayInfoPanel(currTrack, currPoint);
	}

	if (currPoint < track[currTrack].length - 1) {
		if (realTimePlay) {
			waittime = track[currTrack][currPoint+1].time.getTime() - track[currTrack][currPoint].time.getTime();
			waittime /= parseFloat(document.getElementById("playSpeed").value);
		}
		else {
			waittime = 1000 / parseFloat(document.getElementById("playSpeed").value);
		}
		currPoint++;
	}
	else {
		if (currTrack < track.length - 1) {
			waittime = 1000;
			currTrack++;
			currPoint = 0;
		}
		else {
			window.clearTimeout(playTimer);
			playing = false;
			centerPointer.remove();

			if (showMeterPanel) {
				map.removeControl(infoPanel);
			}

			return;
		}
	}
	playTimer = window.setTimeout("goForward()", waittime);
}

function stopRoute() {
	if (playing) {
		window.clearTimeout(playTimer);
		playing = false;
		centerPointer.remove();

		if (showMeterPanel) {
			map.removeControl(infoPanel);
		}
	}
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
