// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([35.232331, 139.104587], [35.330063, 139.350408]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "0617_files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(35.329520, 139.347159, 13, "2026/06/17", "07:32:14", 0, "平塚駅前からスタート", "0617_files/IMG_20260617_073213.jpg", "", "商店街を走る", ""));
	waypoints.push(new MarkerInfo(35.328885, 139.343993, 12, "2026/06/17", "07:36:44", 0, "平塚宿の江戸見附", "0617_files/IMG_20260617_073641.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.317649, 139.321884, 10, "2026/06/17", "07:59:31", 0, "化粧坂の一里塚", "0617_files/IMG_20260617_075933.jpg", "", "住宅街の中", ""));
	waypoints.push(new MarkerInfo(35.309499, 139.315501, 13, "2026/06/17", "08:12:55", 0, "平塚宿 本陣跡", "0617_files/IMG_20260617_081255.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.304654, 139.281940, 17, "2026/06/17", "08:45:51", 0, "一里塚", "0617_files/IMG_20260617_084549.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.291878, 139.241457, 28, "2026/06/17", "09:26:01", 0, "一里塚跡", "0617_files/IMG_20260617_092600.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.286350, 139.230854, 20, "2026/06/17", "09:38:29", 0, "海が見えてきた！", "0617_files/IMG_20260617_093832.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.274976, 139.202347, 13, "2026/06/17", "10:08:28", 0, "小八幡の一里塚", "0617_files/IMG_20260617_100827_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.262507, 139.179467, 6, "2026/06/17", "10:43:40", 0, "渡しがあったところ", "0617_files/IMG_20260617_104341_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.254922, 139.168629, 11, "2026/06/17", "10:58:51", 0, "小田原宿", "0617_files/IMG_20260617_105852.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.254603, 139.168134, 11, "2026/06/17", "10:59:41", 0, "江戸口見附・一里塚", "0617_files/IMG_20260617_105941.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.248583, 139.160570, 16, "2026/06/17", "11:14:11", 0, "小田原宿 本陣跡", "0617_files/IMG_20260617_111415.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.246172, 139.127485, 42, "2026/06/17", "12:21:38", 0, "風祭の一里塚", "0617_files/IMG_20260617_122135_1.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(35.330063, 139.350406, 0.000, 10, 0, 0, "Wed Jun 17 2026 07:28:53"));
	track[0].push(new TrackPoint(35.330012, 139.350192, 0.021, 11, 0, 0, "Wed Jun 17 2026 07:29:16"));
	track[0].push(new TrackPoint(35.329949, 139.350076, 0.034, 11, 0, 0, "Wed Jun 17 2026 07:29:21"));
	track[0].push(new TrackPoint(35.329929, 139.349943, 0.046, 12, 0, 0, "Wed Jun 17 2026 07:29:27"));
	track[0].push(new TrackPoint(35.329836, 139.349683, 0.072, 15, 0, 0, "Wed Jun 17 2026 07:29:38"));
	track[0].push(new TrackPoint(35.329758, 139.349093, 0.127, 15, 0, 0, "Wed Jun 17 2026 07:30:00"));
	track[0].push(new TrackPoint(35.329821, 139.348672, 0.166, 13, 0, 0, "Wed Jun 17 2026 07:30:26"));
	track[0].push(new TrackPoint(35.329849, 139.348597, 0.174, 13, 0, 0, "Wed Jun 17 2026 07:30:31"));
	track[0].push(new TrackPoint(35.329668, 139.348319, 0.206, 13, 0, 0, "Wed Jun 17 2026 07:30:51"));
	track[0].push(new TrackPoint(35.329576, 139.348113, 0.228, 13, 0, 0, "Wed Jun 17 2026 07:31:05"));
	track[0].push(new TrackPoint(35.329561, 139.348002, 0.238, 12, 0, 0, "Wed Jun 17 2026 07:31:11"));
	track[0].push(new TrackPoint(35.329578, 139.347796, 0.257, 12, 0, 0, "Wed Jun 17 2026 07:31:23"));
	track[0].push(new TrackPoint(35.329604, 139.347723, 0.264, 12, 0, 0, "Wed Jun 17 2026 07:31:25"));
	track[0].push(new TrackPoint(35.329618, 139.347580, 0.278, 12, 0, 0, "Wed Jun 17 2026 07:31:38"));
	track[0].push(new TrackPoint(35.329556, 139.347480, 0.290, 13, 0, 0, "Wed Jun 17 2026 07:31:48"));
	track[0].push(new TrackPoint(35.329542, 139.347284, 0.308, 13, 0, 0, "Wed Jun 17 2026 07:32:05"));
	track[0].push(new TrackPoint(35.329514, 139.347133, 0.322, 13, 0, 0, "Wed Jun 17 2026 07:32:18"));
	track[0].push(new TrackPoint(35.329517, 139.347019, 0.332, 13, 0, 0, "Wed Jun 17 2026 07:32:26"));
	track[0].push(new TrackPoint(35.329475, 139.346923, 0.343, 13, 0, 0, "Wed Jun 17 2026 07:32:34"));
	track[0].push(new TrackPoint(35.329419, 139.346852, 0.352, 13, 0, 0, "Wed Jun 17 2026 07:32:44"));
	track[0].push(new TrackPoint(35.329326, 139.346497, 0.386, 11, 0, 0, "Wed Jun 17 2026 07:33:02"));
	track[0].push(new TrackPoint(35.329254, 139.346353, 0.402, 11, 0, 0, "Wed Jun 17 2026 07:33:07"));
	track[0].push(new TrackPoint(35.329214, 139.346116, 0.424, 9, 0, 0, "Wed Jun 17 2026 07:33:24"));
	track[0].push(new TrackPoint(35.329186, 139.346066, 0.430, 9, 0, 0, "Wed Jun 17 2026 07:33:28"));
	track[0].push(new TrackPoint(35.329214, 139.346019, 0.435, 9, 0, 0, "Wed Jun 17 2026 07:33:32"));
	track[0].push(new TrackPoint(35.329134, 139.345608, 0.474, 11, 0, 0, "Wed Jun 17 2026 07:33:55"));
	track[0].push(new TrackPoint(35.329127, 139.345422, 0.491, 12, 0, 0, "Wed Jun 17 2026 07:34:45"));
	track[0].push(new TrackPoint(35.329137, 139.345139, 0.517, 14, 0, 0, "Wed Jun 17 2026 07:35:10"));
	track[0].push(new TrackPoint(35.329025, 139.344694, 0.560, 15, 0, 0, "Wed Jun 17 2026 07:35:33"));
	track[0].push(new TrackPoint(35.328904, 139.344424, 0.588, 14, 0, 0, "Wed Jun 17 2026 07:35:49"));
	track[0].push(new TrackPoint(35.328911, 139.344267, 0.602, 13, 0, 0, "Wed Jun 17 2026 07:35:58"));
	track[0].push(new TrackPoint(35.328711, 139.342941, 0.727, 8, 0, 0, "Wed Jun 17 2026 07:37:48"));
	track[0].push(new TrackPoint(35.328655, 139.342658, 0.753, 8, 0, 0, "Wed Jun 17 2026 07:38:01"));
	track[0].push(new TrackPoint(35.328583, 139.342369, 0.781, 8, 0, 0, "Wed Jun 17 2026 07:38:14"));
	track[0].push(new TrackPoint(35.328576, 139.342250, 0.792, 9, 0, 0, "Wed Jun 17 2026 07:38:19"));
	track[0].push(new TrackPoint(35.328410, 139.341536, 0.860, 10, 0, 0, "Wed Jun 17 2026 07:38:52"));
	track[0].push(new TrackPoint(35.328244, 139.341134, 0.901, 11, 0, 0, "Wed Jun 17 2026 07:39:11"));
	track[0].push(new TrackPoint(35.328234, 139.340883, 0.924, 11, 0, 0, "Wed Jun 17 2026 07:39:21"));
	track[0].push(new TrackPoint(35.328060, 139.339891, 1.016, 9, 0, 0, "Wed Jun 17 2026 07:40:09"));
	track[0].push(new TrackPoint(35.327949, 139.339576, 1.048, 8, 0, 0, "Wed Jun 17 2026 07:40:35"));
	track[0].push(new TrackPoint(35.327910, 139.339332, 1.070, 8, 0, 0, "Wed Jun 17 2026 07:40:47"));
	track[0].push(new TrackPoint(35.327816, 139.338990, 1.104, 7, 0, 0, "Wed Jun 17 2026 07:41:05"));
	track[0].push(new TrackPoint(35.327705, 139.338481, 1.151, 6, 0, 0, "Wed Jun 17 2026 07:41:28"));
	track[0].push(new TrackPoint(35.327597, 139.338142, 1.185, 8, 0, 0, "Wed Jun 17 2026 07:41:45"));
	track[0].push(new TrackPoint(35.327550, 139.337909, 1.207, 9, 0, 0, "Wed Jun 17 2026 07:41:56"));
	track[0].push(new TrackPoint(35.327248, 139.336937, 1.305, 10, 0, 0, "Wed Jun 17 2026 07:43:15"));
	track[0].push(new TrackPoint(35.327170, 139.336810, 1.319, 10, 0, 0, "Wed Jun 17 2026 07:43:22"));
	track[0].push(new TrackPoint(35.327042, 139.336232, 1.374, 8, 0, 0, "Wed Jun 17 2026 07:43:47"));
	track[0].push(new TrackPoint(35.327024, 139.336095, 1.387, 7, 0, 0, "Wed Jun 17 2026 07:43:55"));
	track[0].push(new TrackPoint(35.326992, 139.335951, 1.400, 7, 0, 0, "Wed Jun 17 2026 07:44:07"));
	track[0].push(new TrackPoint(35.326924, 139.335529, 1.440, 7, 0, 0, "Wed Jun 17 2026 07:44:26"));
	track[0].push(new TrackPoint(35.326847, 139.335242, 1.467, 7, 0, 0, "Wed Jun 17 2026 07:44:39"));
	track[0].push(new TrackPoint(35.326772, 139.334843, 1.504, 7, 0, 0, "Wed Jun 17 2026 07:44:56"));
	track[0].push(new TrackPoint(35.326621, 139.334246, 1.561, 8, 0, 0, "Wed Jun 17 2026 07:45:23"));
	track[0].push(new TrackPoint(35.326517, 139.333646, 1.617, 7, 0, 0, "Wed Jun 17 2026 07:45:49"));
	track[0].push(new TrackPoint(35.326375, 139.332984, 1.679, 7, 0, 0, "Wed Jun 17 2026 07:46:19"));
	track[0].push(new TrackPoint(35.326258, 139.332632, 1.714, 7, 0, 0, "Wed Jun 17 2026 07:46:35"));
	track[0].push(new TrackPoint(35.326172, 139.332486, 1.730, 8, 0, 0, "Wed Jun 17 2026 07:46:43"));
	track[0].push(new TrackPoint(35.325853, 139.332308, 1.769, 8, 0, 0, "Wed Jun 17 2026 07:47:02"));
	track[0].push(new TrackPoint(35.325724, 139.332170, 1.788, 8, 0, 0, "Wed Jun 17 2026 07:47:11"));
	track[0].push(new TrackPoint(35.325791, 139.331970, 1.808, 7, 0, 0, "Wed Jun 17 2026 07:47:20"));
	track[0].push(new TrackPoint(35.325781, 139.331935, 1.811, 7, 0, 0, "Wed Jun 17 2026 07:47:22"));
	track[0].push(new TrackPoint(35.325355, 139.331646, 1.865, 5, 0, 0, "Wed Jun 17 2026 07:47:51"));
	track[0].push(new TrackPoint(35.325003, 139.331288, 1.916, 7, 0, 0, "Wed Jun 17 2026 07:48:18"));
	track[0].push(new TrackPoint(35.324846, 139.331066, 1.943, 7, 0, 0, "Wed Jun 17 2026 07:48:31"));
	track[0].push(new TrackPoint(35.324617, 139.330883, 1.973, 6, 0, 0, "Wed Jun 17 2026 07:48:46"));
	track[0].push(new TrackPoint(35.324138, 139.330172, 2.057, 7, 0, 0, "Wed Jun 17 2026 07:49:28"));
	track[0].push(new TrackPoint(35.323758, 139.329495, 2.132, 4, 0, 0, "Wed Jun 17 2026 07:50:07"));
	track[0].push(new TrackPoint(35.323593, 139.329304, 2.157, 2, 0, 0, "Wed Jun 17 2026 07:50:22"));
	track[0].push(new TrackPoint(35.323163, 139.328713, 2.229, 3, 0, 0, "Wed Jun 17 2026 07:51:01"));
	track[0].push(new TrackPoint(35.323073, 139.328566, 2.246, 6, 0, 0, "Wed Jun 17 2026 07:51:11"));
	track[0].push(new TrackPoint(35.323020, 139.328445, 2.259, 9, 0, 0, "Wed Jun 17 2026 07:51:56"));
	track[0].push(new TrackPoint(35.322691, 139.328060, 2.310, 11, 0, 0, "Wed Jun 17 2026 07:52:19"));
	track[0].push(new TrackPoint(35.322584, 139.327914, 2.328, 10, 0, 0, "Wed Jun 17 2026 07:52:27"));
	track[0].push(new TrackPoint(35.322032, 139.327323, 2.410, 9, 0, 0, "Wed Jun 17 2026 07:53:07"));
	track[0].push(new TrackPoint(35.320868, 139.325885, 2.594, 6, 0, 0, "Wed Jun 17 2026 07:54:34"));
	track[0].push(new TrackPoint(35.320256, 139.324846, 2.710, 7, 0, 0, "Wed Jun 17 2026 07:55:31"));
	track[0].push(new TrackPoint(35.320266, 139.324833, 2.713, 6, 0, 0, "Wed Jun 17 2026 07:55:51"));
	track[0].push(new TrackPoint(35.319966, 139.324279, 2.773, 8, 0, 0, "Wed Jun 17 2026 07:56:20"));
	track[0].push(new TrackPoint(35.319873, 139.324170, 2.788, 8, 0, 0, "Wed Jun 17 2026 07:56:27"));
	track[0].push(new TrackPoint(35.319678, 139.323822, 2.826, 8, 0, 0, "Wed Jun 17 2026 07:56:44"));
	track[0].push(new TrackPoint(35.319473, 139.323565, 2.859, 8, 0, 0, "Wed Jun 17 2026 07:56:59"));
	track[0].push(new TrackPoint(35.319338, 139.323447, 2.877, 8, 0, 0, "Wed Jun 17 2026 07:57:09"));
	track[0].push(new TrackPoint(35.319316, 139.323394, 2.883, 8, 0, 0, "Wed Jun 17 2026 07:57:12"));
	track[0].push(new TrackPoint(35.319090, 139.323127, 2.917, 7, 0, 0, "Wed Jun 17 2026 07:57:29"));
	track[0].push(new TrackPoint(35.318944, 139.323007, 2.937, 7, 0, 0, "Wed Jun 17 2026 07:57:38"));
	track[0].push(new TrackPoint(35.318832, 139.322867, 2.955, 8, 0, 0, "Wed Jun 17 2026 07:57:46"));
	track[0].push(new TrackPoint(35.318537, 139.322583, 2.997, 9, 0, 0, "Wed Jun 17 2026 07:58:06"));
	track[0].push(new TrackPoint(35.317693, 139.321873, 3.110, 10, 0, 0, "Wed Jun 17 2026 07:59:16"));
	track[0].push(new TrackPoint(35.317651, 139.321883, 3.116, 10, 0, 0, "Wed Jun 17 2026 07:59:49"));
	track[0].push(new TrackPoint(35.317678, 139.321823, 3.122, 10, 0, 0, "Wed Jun 17 2026 08:00:04"));
	track[0].push(new TrackPoint(35.317234, 139.321502, 3.180, 12, 0, 0, "Wed Jun 17 2026 08:00:36"));
	track[0].push(new TrackPoint(35.316682, 139.321045, 3.254, 11, 0, 0, "Wed Jun 17 2026 08:01:19"));
	track[0].push(new TrackPoint(35.316425, 139.320874, 3.286, 12, 0, 0, "Wed Jun 17 2026 08:01:34"));
	track[0].push(new TrackPoint(35.316295, 139.320759, 3.304, 12, 0, 0, "Wed Jun 17 2026 08:01:43"));
	track[0].push(new TrackPoint(35.315473, 139.319470, 3.453, 15, 0, 0, "Wed Jun 17 2026 08:02:56"));
	track[0].push(new TrackPoint(35.315381, 139.319353, 3.468, 15, 0, 0, "Wed Jun 17 2026 08:03:03"));
	track[0].push(new TrackPoint(35.315321, 139.319209, 3.485, 16, 0, 0, "Wed Jun 17 2026 08:03:17"));
	track[0].push(new TrackPoint(35.315384, 139.319378, 3.502, 15, 0, 0, "Wed Jun 17 2026 08:03:33"));
	track[0].push(new TrackPoint(35.315893, 139.320084, 3.587, 14, 0, 0, "Wed Jun 17 2026 08:04:12"));
	track[0].push(new TrackPoint(35.316336, 139.320759, 3.666, 12, 0, 0, "Wed Jun 17 2026 08:04:47"));
	track[0].push(new TrackPoint(35.316359, 139.320775, 3.669, 12, 0, 0, "Wed Jun 17 2026 08:04:51"));
	track[0].push(new TrackPoint(35.316240, 139.320557, 3.693, 14, 0, 0, "Wed Jun 17 2026 08:05:03"));
	track[0].push(new TrackPoint(35.315668, 139.320274, 3.762, 12, 0, 0, "Wed Jun 17 2026 08:05:36"));
	track[0].push(new TrackPoint(35.315612, 139.320290, 3.768, 12, 0, 0, "Wed Jun 17 2026 08:05:38"));
	track[0].push(new TrackPoint(35.315529, 139.320266, 3.777, 12, 0, 0, "Wed Jun 17 2026 08:05:43"));
	track[0].push(new TrackPoint(35.315087, 139.319956, 3.834, 11, 0, 0, "Wed Jun 17 2026 08:06:10"));
	track[0].push(new TrackPoint(35.314902, 139.319849, 3.857, 12, 0, 0, "Wed Jun 17 2026 08:06:23"));
	track[0].push(new TrackPoint(35.314767, 139.319734, 3.875, 13, 0, 0, "Wed Jun 17 2026 08:06:31"));
	track[0].push(new TrackPoint(35.314284, 139.319487, 3.933, 13, 0, 0, "Wed Jun 17 2026 08:07:03"));
	track[0].push(new TrackPoint(35.312632, 139.318273, 4.148, 10, 0, 0, "Wed Jun 17 2026 08:08:41"));
	track[0].push(new TrackPoint(35.312394, 139.318026, 4.182, 9, 0, 0, "Wed Jun 17 2026 08:08:57"));
	track[0].push(new TrackPoint(35.311986, 139.317430, 4.253, 10, 0, 0, "Wed Jun 17 2026 08:09:31"));
	track[0].push(new TrackPoint(35.311763, 139.317160, 4.288, 11, 0, 0, "Wed Jun 17 2026 08:09:48"));
	track[0].push(new TrackPoint(35.311668, 139.317022, 4.305, 12, 0, 0, "Wed Jun 17 2026 08:09:56"));
	track[0].push(new TrackPoint(35.311251, 139.316614, 4.365, 15, 0, 0, "Wed Jun 17 2026 08:10:37"));
	track[0].push(new TrackPoint(35.311177, 139.316602, 4.373, 15, 0, 0, "Wed Jun 17 2026 08:10:45"));
	track[0].push(new TrackPoint(35.311122, 139.316512, 4.383, 15, 0, 0, "Wed Jun 17 2026 08:11:02"));
	track[0].push(new TrackPoint(35.310792, 139.316243, 4.427, 14, 0, 0, "Wed Jun 17 2026 08:11:23"));
	track[0].push(new TrackPoint(35.310387, 139.315982, 4.478, 13, 0, 0, "Wed Jun 17 2026 08:11:48"));
	track[0].push(new TrackPoint(35.310207, 139.315898, 4.500, 13, 0, 0, "Wed Jun 17 2026 08:11:59"));
	track[0].push(new TrackPoint(35.310089, 139.315806, 4.515, 12, 0, 0, "Wed Jun 17 2026 08:12:07"));
	track[0].push(new TrackPoint(35.309125, 139.315313, 4.632, 17, 0, 0, "Wed Jun 17 2026 08:13:44"));
	track[0].push(new TrackPoint(35.308992, 139.315270, 4.647, 17, 0, 0, "Wed Jun 17 2026 08:13:51"));
	track[0].push(new TrackPoint(35.308993, 139.315226, 4.652, 17, 0, 0, "Wed Jun 17 2026 08:13:56"));
	track[0].push(new TrackPoint(35.308835, 139.315158, 4.671, 17, 0, 0, "Wed Jun 17 2026 08:14:29"));
	track[0].push(new TrackPoint(35.308610, 139.314983, 4.701, 14, 0, 0, "Wed Jun 17 2026 08:14:48"));
	track[0].push(new TrackPoint(35.308418, 139.314937, 4.723, 14, 0, 0, "Wed Jun 17 2026 08:14:57"));
	track[0].push(new TrackPoint(35.308257, 139.314800, 4.745, 13, 0, 0, "Wed Jun 17 2026 08:15:07"));
	track[0].push(new TrackPoint(35.308129, 139.314729, 4.760, 13, 0, 0, "Wed Jun 17 2026 08:15:15"));
	track[0].push(new TrackPoint(35.307851, 139.314429, 4.802, 14, 0, 0, "Wed Jun 17 2026 08:15:40"));
	track[0].push(new TrackPoint(35.307753, 139.314334, 4.817, 14, 0, 0, "Wed Jun 17 2026 08:16:52"));
	track[0].push(new TrackPoint(35.307632, 139.314403, 4.832, 13, 0, 0, "Wed Jun 17 2026 08:17:46"));
	track[0].push(new TrackPoint(35.307419, 139.314235, 4.860, 13, 0, 0, "Wed Jun 17 2026 08:18:03"));
	track[0].push(new TrackPoint(35.307310, 139.314199, 4.873, 13, 0, 0, "Wed Jun 17 2026 08:18:09"));
	track[0].push(new TrackPoint(35.307184, 139.314098, 4.890, 13, 0, 0, "Wed Jun 17 2026 08:18:16"));
	track[0].push(new TrackPoint(35.307156, 139.314011, 4.898, 13, 0, 0, "Wed Jun 17 2026 08:18:20"));
	track[0].push(new TrackPoint(35.307173, 139.313677, 4.928, 13, 0, 0, "Wed Jun 17 2026 08:18:34"));
	track[0].push(new TrackPoint(35.307313, 139.312754, 5.014, 15, 0, 0, "Wed Jun 17 2026 08:19:14"));
	track[0].push(new TrackPoint(35.307401, 139.312385, 5.049, 15, 0, 0, "Wed Jun 17 2026 08:19:30"));
	track[0].push(new TrackPoint(35.307514, 139.311984, 5.088, 15, 0, 0, "Wed Jun 17 2026 08:19:55"));
	track[0].push(new TrackPoint(35.307527, 139.311858, 5.100, 15, 0, 0, "Wed Jun 17 2026 08:20:05"));
	track[0].push(new TrackPoint(35.307678, 139.311001, 5.179, 17, 0, 0, "Wed Jun 17 2026 08:20:45"));
	track[0].push(new TrackPoint(35.307763, 139.310084, 5.264, 21, 0, 0, "Wed Jun 17 2026 08:21:32"));
	track[0].push(new TrackPoint(35.307790, 139.309917, 5.279, 22, 0, 0, "Wed Jun 17 2026 08:21:40"));
	track[0].push(new TrackPoint(35.307847, 139.309303, 5.336, 22, 0, 0, "Wed Jun 17 2026 08:22:10"));
	track[0].push(new TrackPoint(35.307896, 139.309059, 5.359, 23, 0, 0, "Wed Jun 17 2026 08:22:22"));
	track[0].push(new TrackPoint(35.307889, 139.308849, 5.378, 23, 0, 0, "Wed Jun 17 2026 08:22:37"));
	track[0].push(new TrackPoint(35.307916, 139.308796, 5.383, 23, 0, 0, "Wed Jun 17 2026 08:22:48"));
	track[0].push(new TrackPoint(35.307900, 139.308274, 5.431, 24, 0, 0, "Wed Jun 17 2026 08:23:13"));
	track[0].push(new TrackPoint(35.307854, 139.308004, 5.456, 26, 0, 0, "Wed Jun 17 2026 08:23:26"));
	track[0].push(new TrackPoint(35.307866, 139.307937, 5.463, 25, 0, 0, "Wed Jun 17 2026 08:23:29"));
	track[0].push(new TrackPoint(35.307818, 139.307848, 5.473, 26, 0, 0, "Wed Jun 17 2026 08:23:34"));
	track[0].push(new TrackPoint(35.307822, 139.307463, 5.508, 24, 0, 0, "Wed Jun 17 2026 08:23:50"));
	track[0].push(new TrackPoint(35.307759, 139.306891, 5.561, 24, 0, 0, "Wed Jun 17 2026 08:24:13"));
	track[0].push(new TrackPoint(35.307714, 139.306742, 5.575, 24, 0, 0, "Wed Jun 17 2026 08:24:20"));
	track[0].push(new TrackPoint(35.307620, 139.306251, 5.622, 23, 0, 0, "Wed Jun 17 2026 08:24:40"));
	track[0].push(new TrackPoint(35.307607, 139.306056, 5.639, 23, 0, 0, "Wed Jun 17 2026 08:24:48"));
	track[0].push(new TrackPoint(35.307505, 139.305751, 5.670, 27, 0, 0, "Wed Jun 17 2026 08:25:04"));
	track[0].push(new TrackPoint(35.307481, 139.305615, 5.683, 28, 0, 0, "Wed Jun 17 2026 08:25:12"));
	track[0].push(new TrackPoint(35.307432, 139.305624, 5.691, 29, 0, 0, "Wed Jun 17 2026 08:25:24"));
	track[0].push(new TrackPoint(35.307424, 139.305407, 5.711, 30, 0, 0, "Wed Jun 17 2026 08:25:35"));
	track[0].push(new TrackPoint(35.307356, 139.305002, 5.748, 27, 0, 0, "Wed Jun 17 2026 08:25:52"));
	track[0].push(new TrackPoint(35.307348, 139.304857, 5.762, 25, 0, 0, "Wed Jun 17 2026 08:25:59"));
	track[0].push(new TrackPoint(35.307300, 139.304499, 5.795, 24, 0, 0, "Wed Jun 17 2026 08:26:16"));
	track[0].push(new TrackPoint(35.307274, 139.304203, 5.822, 24, 0, 0, "Wed Jun 17 2026 08:26:30"));
	track[0].push(new TrackPoint(35.307213, 139.303874, 5.853, 24, 0, 0, "Wed Jun 17 2026 08:26:46"));
	track[0].push(new TrackPoint(35.307152, 139.303687, 5.871, 24, 0, 0, "Wed Jun 17 2026 08:26:54"));
	track[0].push(new TrackPoint(35.307075, 139.303311, 5.907, 23, 0, 0, "Wed Jun 17 2026 08:27:13"));
	track[0].push(new TrackPoint(35.306965, 139.302930, 5.943, 22, 0, 0, "Wed Jun 17 2026 08:27:31"));
	track[0].push(new TrackPoint(35.306923, 139.302702, 5.965, 22, 0, 0, "Wed Jun 17 2026 08:27:41"));
	track[0].push(new TrackPoint(35.306789, 139.302240, 6.009, 23, 0, 0, "Wed Jun 17 2026 08:28:03"));
	track[0].push(new TrackPoint(35.306750, 139.302042, 6.028, 23, 0, 0, "Wed Jun 17 2026 08:28:12"));
	track[0].push(new TrackPoint(35.306547, 139.301378, 6.092, 22, 0, 0, "Wed Jun 17 2026 08:28:42"));
	track[0].push(new TrackPoint(35.306192, 139.299804, 6.241, 23, 0, 0, "Wed Jun 17 2026 08:29:54"));
	track[0].push(new TrackPoint(35.306060, 139.299350, 6.285, 21, 0, 0, "Wed Jun 17 2026 08:30:16"));
	track[0].push(new TrackPoint(35.305808, 139.298306, 6.384, 23, 0, 0, "Wed Jun 17 2026 08:31:06"));
	track[0].push(new TrackPoint(35.305767, 139.298093, 6.404, 22, 0, 0, "Wed Jun 17 2026 08:31:16"));
	track[0].push(new TrackPoint(35.305704, 139.297873, 6.426, 21, 0, 0, "Wed Jun 17 2026 08:31:27"));
	track[0].push(new TrackPoint(35.305616, 139.297354, 6.474, 20, 0, 0, "Wed Jun 17 2026 08:31:52"));
	track[0].push(new TrackPoint(35.305382, 139.296515, 6.555, 21, 0, 0, "Wed Jun 17 2026 08:32:32"));
	track[0].push(new TrackPoint(35.305057, 139.295024, 6.695, 17, 0, 0, "Wed Jun 17 2026 08:33:40"));
	track[0].push(new TrackPoint(35.304857, 139.294300, 6.765, 18, 0, 0, "Wed Jun 17 2026 08:34:14"));
	track[0].push(new TrackPoint(35.304741, 139.293896, 6.804, 18, 0, 0, "Wed Jun 17 2026 08:34:34"));
	track[0].push(new TrackPoint(35.304669, 139.293708, 6.823, 18, 0, 0, "Wed Jun 17 2026 08:34:43"));
	track[0].push(new TrackPoint(35.304628, 139.293546, 6.838, 17, 0, 0, "Wed Jun 17 2026 08:34:51"));
	track[0].push(new TrackPoint(35.304461, 139.293115, 6.882, 17, 0, 0, "Wed Jun 17 2026 08:35:13"));
	track[0].push(new TrackPoint(35.304248, 139.292668, 6.929, 16, 0, 0, "Wed Jun 17 2026 08:35:36"));
	track[0].push(new TrackPoint(35.304216, 139.292526, 6.942, 15, 0, 0, "Wed Jun 17 2026 08:35:42"));
	track[0].push(new TrackPoint(35.304228, 139.292475, 6.947, 15, 0, 0, "Wed Jun 17 2026 08:35:44"));
	track[0].push(new TrackPoint(35.304221, 139.292359, 6.958, 16, 0, 0, "Wed Jun 17 2026 08:35:50"));
	track[0].push(new TrackPoint(35.304026, 139.291790, 7.014, 18, 0, 0, "Wed Jun 17 2026 08:36:15"));
	track[0].push(new TrackPoint(35.303980, 139.291621, 7.030, 19, 0, 0, "Wed Jun 17 2026 08:36:23"));
	track[0].push(new TrackPoint(35.303926, 139.291330, 7.058, 23, 0, 0, "Wed Jun 17 2026 08:36:38"));
	track[0].push(new TrackPoint(35.303891, 139.290932, 7.094, 26, 0, 0, "Wed Jun 17 2026 08:36:54"));
	track[0].push(new TrackPoint(35.303896, 139.290794, 7.107, 27, 0, 0, "Wed Jun 17 2026 08:37:01"));
	track[0].push(new TrackPoint(35.304151, 139.290234, 7.166, 18, 0, 0, "Wed Jun 17 2026 08:37:31"));
	track[0].push(new TrackPoint(35.304230, 139.290154, 7.178, 18, 0, 0, "Wed Jun 17 2026 08:37:38"));
	track[0].push(new TrackPoint(35.304431, 139.289737, 7.222, 15, 0, 0, "Wed Jun 17 2026 08:38:00"));
	track[0].push(new TrackPoint(35.304703, 139.289324, 7.270, 18, 0, 0, "Wed Jun 17 2026 08:38:28"));
	track[0].push(new TrackPoint(35.304693, 139.289259, 7.276, 17, 0, 0, "Wed Jun 17 2026 08:38:31"));
	track[0].push(new TrackPoint(35.304702, 139.289145, 7.287, 15, 0, 0, "Wed Jun 17 2026 08:38:38"));
	track[0].push(new TrackPoint(35.304826, 139.289015, 7.305, 14, 0, 0, "Wed Jun 17 2026 08:38:49"));
	track[0].push(new TrackPoint(35.305010, 139.288718, 7.339, 11, 0, 0, "Wed Jun 17 2026 08:39:07"));
	track[0].push(new TrackPoint(35.305231, 139.288313, 7.383, 10, 0, 0, "Wed Jun 17 2026 08:39:38"));
	track[0].push(new TrackPoint(35.305342, 139.288216, 7.399, 10, 0, 0, "Wed Jun 17 2026 08:39:45"));
	track[0].push(new TrackPoint(35.305431, 139.288067, 7.415, 11, 0, 0, "Wed Jun 17 2026 08:39:54"));
	track[0].push(new TrackPoint(35.305689, 139.287461, 7.478, 15, 0, 0, "Wed Jun 17 2026 08:40:30"));
	track[0].push(new TrackPoint(35.305709, 139.287065, 7.514, 17, 0, 0, "Wed Jun 17 2026 08:40:52"));
	track[0].push(new TrackPoint(35.305499, 139.285853, 7.627, 18, 0, 0, "Wed Jun 17 2026 08:41:54"));
	track[0].push(new TrackPoint(35.305390, 139.285521, 7.659, 18, 0, 0, "Wed Jun 17 2026 08:42:12"));
	track[0].push(new TrackPoint(35.305220, 139.285207, 7.694, 17, 0, 0, "Wed Jun 17 2026 08:42:31"));
	track[0].push(new TrackPoint(35.305101, 139.284830, 7.730, 17, 0, 0, "Wed Jun 17 2026 08:42:50"));
	track[0].push(new TrackPoint(35.304733, 139.282398, 7.956, 15, 0, 0, "Wed Jun 17 2026 08:44:47"));
	track[0].push(new TrackPoint(35.304697, 139.282004, 7.992, 17, 0, 0, "Wed Jun 17 2026 08:45:29"));
	track[0].push(new TrackPoint(35.304654, 139.281940, 8.000, 17, 0, 0, "Wed Jun 17 2026 08:45:51"));
	track[0].push(new TrackPoint(35.304667, 139.280856, 8.099, 19, 0, 0, "Wed Jun 17 2026 08:47:28"));
	track[0].push(new TrackPoint(35.304635, 139.280474, 8.134, 18, 0, 0, "Wed Jun 17 2026 08:47:47"));
	track[0].push(new TrackPoint(35.304558, 139.278913, 8.276, 20, 0, 0, "Wed Jun 17 2026 08:48:57"));
	track[0].push(new TrackPoint(35.304526, 139.278033, 8.356, 19, 0, 0, "Wed Jun 17 2026 08:49:37"));
	track[0].push(new TrackPoint(35.304468, 139.277623, 8.394, 19, 0, 0, "Wed Jun 17 2026 08:50:00"));
	track[0].push(new TrackPoint(35.304472, 139.277477, 8.408, 19, 0, 0, "Wed Jun 17 2026 08:50:14"));
	track[0].push(new TrackPoint(35.304391, 139.277210, 8.433, 19, 0, 0, "Wed Jun 17 2026 08:50:29"));
	track[0].push(new TrackPoint(35.304293, 139.276499, 8.499, 20, 0, 0, "Wed Jun 17 2026 08:51:04"));
	track[0].push(new TrackPoint(35.304107, 139.274551, 8.678, 22, 0, 0, "Wed Jun 17 2026 08:52:36"));
	track[0].push(new TrackPoint(35.303899, 139.272953, 8.825, 23, 0, 0, "Wed Jun 17 2026 08:53:51"));
	track[0].push(new TrackPoint(35.303862, 139.272783, 8.841, 23, 0, 0, "Wed Jun 17 2026 08:53:59"));
	track[0].push(new TrackPoint(35.302979, 139.270622, 9.061, 23, 0, 0, "Wed Jun 17 2026 08:55:53"));
	track[0].push(new TrackPoint(35.302519, 139.269596, 9.168, 22, 0, 0, "Wed Jun 17 2026 08:56:47"));
	track[0].push(new TrackPoint(35.302385, 139.269256, 9.202, 24, 0, 0, "Wed Jun 17 2026 08:57:05"));
	track[0].push(new TrackPoint(35.302135, 139.268769, 9.254, 26, 0, 0, "Wed Jun 17 2026 08:57:32"));
	track[0].push(new TrackPoint(35.301782, 139.267888, 9.344, 25, 0, 0, "Wed Jun 17 2026 08:58:16"));
	track[0].push(new TrackPoint(35.300856, 139.266052, 9.540, 23, 0, 0, "Wed Jun 17 2026 08:59:56"));
	track[0].push(new TrackPoint(35.300678, 139.265645, 9.582, 24, 0, 0, "Wed Jun 17 2026 09:00:15"));
	track[0].push(new TrackPoint(35.300143, 139.263951, 9.747, 22, 0, 0, "Wed Jun 17 2026 09:01:35"));
	track[0].push(new TrackPoint(35.299884, 139.263287, 9.814, 20, 0, 0, "Wed Jun 17 2026 09:02:08"));
	track[0].push(new TrackPoint(35.299796, 139.263112, 9.833, 19, 0, 0, "Wed Jun 17 2026 09:02:18"));
	track[0].push(new TrackPoint(35.299561, 139.262898, 9.866, 18, 0, 0, "Wed Jun 17 2026 09:02:34"));
	track[0].push(new TrackPoint(35.299467, 139.262778, 9.881, 18, 0, 0, "Wed Jun 17 2026 09:02:42"));
	track[0].push(new TrackPoint(35.299376, 139.262692, 9.894, 18, 0, 0, "Wed Jun 17 2026 09:02:48"));
	track[0].push(new TrackPoint(35.299200, 139.262362, 9.930, 19, 0, 0, "Wed Jun 17 2026 09:03:06"));
	track[0].push(new TrackPoint(35.299146, 139.262146, 9.951, 19, 0, 0, "Wed Jun 17 2026 09:03:25"));
	track[0].push(new TrackPoint(35.299160, 139.262104, 9.955, 19, 0, 0, "Wed Jun 17 2026 09:03:28"));
	track[0].push(new TrackPoint(35.299180, 139.262091, 9.957, 19, 0, 0, "Wed Jun 17 2026 09:03:31"));
	track[0].push(new TrackPoint(35.299190, 139.262124, 9.961, 19, 0, 0, "Wed Jun 17 2026 09:03:36"));
	track[0].push(new TrackPoint(35.299169, 139.262101, 9.964, 19, 0, 0, "Wed Jun 17 2026 09:03:42"));
	track[0].push(new TrackPoint(35.299197, 139.262101, 9.967, 19, 0, 0, "Wed Jun 17 2026 09:03:47"));
	track[0].push(new TrackPoint(35.299151, 139.262004, 9.977, 19, 0, 0, "Wed Jun 17 2026 09:04:02"));
	track[0].push(new TrackPoint(35.299118, 139.261889, 9.988, 19, 0, 0, "Wed Jun 17 2026 09:04:11"));
	track[0].push(new TrackPoint(35.299005, 139.261800, 10.003, 19, 0, 0, "Wed Jun 17 2026 09:04:31"));
	track[0].push(new TrackPoint(35.298388, 139.259767, 10.201, 26, 0, 0, "Wed Jun 17 2026 09:06:17"));
	track[0].push(new TrackPoint(35.298331, 139.259463, 10.229, 26, 0, 0, "Wed Jun 17 2026 09:06:32"));
	track[0].push(new TrackPoint(35.298277, 139.259306, 10.245, 26, 0, 0, "Wed Jun 17 2026 09:06:39"));
	track[0].push(new TrackPoint(35.298235, 139.259105, 10.264, 27, 0, 0, "Wed Jun 17 2026 09:06:48"));
	track[0].push(new TrackPoint(35.298121, 139.258712, 10.302, 26, 0, 0, "Wed Jun 17 2026 09:07:06"));
	track[0].push(new TrackPoint(35.297835, 139.257933, 10.380, 25, 0, 0, "Wed Jun 17 2026 09:07:45"));
	track[0].push(new TrackPoint(35.297740, 139.257606, 10.411, 25, 0, 0, "Wed Jun 17 2026 09:08:01"));
	track[0].push(new TrackPoint(35.297441, 139.256642, 10.505, 21, 0, 0, "Wed Jun 17 2026 09:08:47"));
	track[0].push(new TrackPoint(35.297407, 139.256465, 10.522, 22, 0, 0, "Wed Jun 17 2026 09:08:56"));
	track[0].push(new TrackPoint(35.297205, 139.255705, 10.595, 25, 0, 0, "Wed Jun 17 2026 09:09:32"));
	track[0].push(new TrackPoint(35.297093, 139.255204, 10.642, 23, 0, 0, "Wed Jun 17 2026 09:09:56"));
	track[0].push(new TrackPoint(35.296860, 139.254622, 10.701, 23, 0, 0, "Wed Jun 17 2026 09:10:27"));
	track[0].push(new TrackPoint(35.296807, 139.254443, 10.718, 24, 0, 0, "Wed Jun 17 2026 09:10:36"));
	track[0].push(new TrackPoint(35.296631, 139.254054, 10.759, 25, 0, 0, "Wed Jun 17 2026 09:10:57"));
	track[0].push(new TrackPoint(35.296318, 139.253028, 10.858, 24, 0, 0, "Wed Jun 17 2026 09:11:46"));
	track[0].push(new TrackPoint(35.296100, 139.252212, 10.937, 26, 0, 0, "Wed Jun 17 2026 09:12:26"));
	track[0].push(new TrackPoint(35.295387, 139.250254, 11.132, 24, 0, 0, "Wed Jun 17 2026 09:14:14"));
	track[0].push(new TrackPoint(35.295314, 139.249346, 11.215, 24, 0, 0, "Wed Jun 17 2026 09:15:44"));
	track[0].push(new TrackPoint(35.295337, 139.249239, 11.226, 24, 0, 0, "Wed Jun 17 2026 09:15:52"));
	track[0].push(new TrackPoint(35.295557, 139.248840, 11.270, 26, 0, 0, "Wed Jun 17 2026 09:16:27"));
	track[0].push(new TrackPoint(35.295554, 139.248743, 11.279, 25, 0, 0, "Wed Jun 17 2026 09:16:36"));
	track[0].push(new TrackPoint(35.295289, 139.248261, 11.332, 23, 0, 0, "Wed Jun 17 2026 09:17:19"));
	track[0].push(new TrackPoint(35.295028, 139.247611, 11.398, 27, 0, 0, "Wed Jun 17 2026 09:18:14"));
	track[0].push(new TrackPoint(35.294928, 139.247318, 11.427, 28, 0, 0, "Wed Jun 17 2026 09:18:39"));
	track[0].push(new TrackPoint(35.294753, 139.246969, 11.464, 27, 0, 0, "Wed Jun 17 2026 09:19:09"));
	track[0].push(new TrackPoint(35.294224, 139.246401, 11.543, 27, 0, 0, "Wed Jun 17 2026 09:20:12"));
	track[0].push(new TrackPoint(35.294034, 139.246216, 11.570, 27, 0, 0, "Wed Jun 17 2026 09:20:32"));
	track[0].push(new TrackPoint(35.293869, 139.245912, 11.604, 27, 0, 0, "Wed Jun 17 2026 09:21:11"));
	track[0].push(new TrackPoint(35.293799, 139.245960, 11.613, 26, 0, 0, "Wed Jun 17 2026 09:21:42"));
	track[0].push(new TrackPoint(35.293751, 139.245943, 11.619, 26, 0, 0, "Wed Jun 17 2026 09:21:46"));
	track[0].push(new TrackPoint(35.292661, 139.243639, 11.861, 28, 0, 0, "Wed Jun 17 2026 09:23:52"));
	track[0].push(new TrackPoint(35.292502, 139.243213, 11.904, 26, 0, 0, "Wed Jun 17 2026 09:24:14"));
	track[0].push(new TrackPoint(35.292439, 139.243091, 11.917, 26, 0, 0, "Wed Jun 17 2026 09:24:21"));
	track[0].push(new TrackPoint(35.292135, 139.242041, 12.018, 26, 0, 0, "Wed Jun 17 2026 09:25:13"));
	track[0].push(new TrackPoint(35.291877, 139.241456, 12.081, 28, 0, 0, "Wed Jun 17 2026 09:26:04"));
	track[0].push(new TrackPoint(35.291879, 139.241431, 12.083, 28, 0, 0, "Wed Jun 17 2026 09:26:28"));
	track[0].push(new TrackPoint(35.291316, 139.240487, 12.190, 26, 0, 0, "Wed Jun 17 2026 09:27:25"));
	track[0].push(new TrackPoint(35.291228, 139.240297, 12.209, 25, 0, 0, "Wed Jun 17 2026 09:27:35"));
	track[0].push(new TrackPoint(35.291159, 139.240102, 12.229, 25, 0, 0, "Wed Jun 17 2026 09:27:45"));
	track[0].push(new TrackPoint(35.291111, 139.239884, 12.249, 24, 0, 0, "Wed Jun 17 2026 09:27:55"));
	track[0].push(new TrackPoint(35.291094, 139.239703, 12.266, 24, 0, 0, "Wed Jun 17 2026 09:28:05"));
	track[0].push(new TrackPoint(35.291058, 139.239719, 12.271, 24, 0, 0, "Wed Jun 17 2026 09:28:18"));
	track[0].push(new TrackPoint(35.290866, 139.238661, 12.370, 23, 0, 0, "Wed Jun 17 2026 09:29:26"));
	track[0].push(new TrackPoint(35.290821, 139.238576, 12.379, 22, 0, 0, "Wed Jun 17 2026 09:29:34"));
	track[0].push(new TrackPoint(35.290798, 139.238497, 12.387, 22, 0, 0, "Wed Jun 17 2026 09:29:40"));
	track[0].push(new TrackPoint(35.290775, 139.238475, 12.390, 21, 0, 0, "Wed Jun 17 2026 09:29:42"));
	track[0].push(new TrackPoint(35.290754, 139.238416, 12.396, 21, 0, 0, "Wed Jun 17 2026 09:29:46"));
	track[0].push(new TrackPoint(35.290709, 139.238380, 12.402, 20, 0, 0, "Wed Jun 17 2026 09:29:50"));
	track[0].push(new TrackPoint(35.290703, 139.238339, 12.406, 19, 0, 0, "Wed Jun 17 2026 09:29:52"));
	track[0].push(new TrackPoint(35.290475, 139.238074, 12.441, 15, 0, 0, "Wed Jun 17 2026 09:30:11"));
	track[0].push(new TrackPoint(35.289803, 139.237501, 12.533, 9, 0, 0, "Wed Jun 17 2026 09:31:26"));
	track[0].push(new TrackPoint(35.289638, 139.237262, 12.562, 9, 0, 0, "Wed Jun 17 2026 09:31:53"));
	track[0].push(new TrackPoint(35.289577, 139.237133, 12.575, 9, 0, 0, "Wed Jun 17 2026 09:32:01"));
	track[0].push(new TrackPoint(35.289257, 139.236080, 12.677, 11, 0, 0, "Wed Jun 17 2026 09:32:53"));
	track[0].push(new TrackPoint(35.289037, 139.235626, 12.726, 12, 0, 0, "Wed Jun 17 2026 09:33:19"));
	track[0].push(new TrackPoint(35.288917, 139.235313, 12.757, 13, 0, 0, "Wed Jun 17 2026 09:33:37"));
	track[0].push(new TrackPoint(35.288650, 139.234809, 12.812, 15, 0, 0, "Wed Jun 17 2026 09:34:09"));
	track[0].push(new TrackPoint(35.288446, 139.234386, 12.856, 14, 0, 0, "Wed Jun 17 2026 09:34:34"));
	track[0].push(new TrackPoint(35.288295, 139.234156, 12.883, 13, 0, 0, "Wed Jun 17 2026 09:34:51"));
	track[0].push(new TrackPoint(35.288156, 139.233813, 12.918, 15, 0, 0, "Wed Jun 17 2026 09:35:12"));
	track[0].push(new TrackPoint(35.287990, 139.233420, 12.959, 18, 0, 0, "Wed Jun 17 2026 09:35:36"));
	track[0].push(new TrackPoint(35.287460, 139.232452, 13.065, 23, 0, 0, "Wed Jun 17 2026 09:36:32"));
	track[0].push(new TrackPoint(35.286525, 139.231143, 13.224, 22, 0, 0, "Wed Jun 17 2026 09:37:53"));
	track[0].push(new TrackPoint(35.286292, 139.230758, 13.267, 19, 0, 0, "Wed Jun 17 2026 09:38:54"));
	track[0].push(new TrackPoint(35.285881, 139.229681, 13.376, 19, 0, 0, "Wed Jun 17 2026 09:40:05"));
	track[0].push(new TrackPoint(35.285679, 139.229014, 13.441, 18, 0, 0, "Wed Jun 17 2026 09:40:41"));
	track[0].push(new TrackPoint(35.284311, 139.226044, 13.751, 12, 0, 0, "Wed Jun 17 2026 09:43:14"));
	track[0].push(new TrackPoint(35.283936, 139.224450, 13.902, 12, 0, 0, "Wed Jun 17 2026 09:44:33"));
	track[0].push(new TrackPoint(35.283920, 139.224291, 13.917, 13, 0, 0, "Wed Jun 17 2026 09:44:41"));
	track[0].push(new TrackPoint(35.283658, 139.223185, 14.022, 17, 0, 0, "Wed Jun 17 2026 09:45:38"));
	track[0].push(new TrackPoint(35.283496, 139.222714, 14.068, 17, 0, 0, "Wed Jun 17 2026 09:46:03"));
	track[0].push(new TrackPoint(35.282624, 139.221267, 14.232, 15, 0, 0, "Wed Jun 17 2026 09:47:26"));
	track[0].push(new TrackPoint(35.281822, 139.219825, 14.391, 15, 0, 0, "Wed Jun 17 2026 09:48:46"));
	track[0].push(new TrackPoint(35.281693, 139.219514, 14.422, 15, 0, 0, "Wed Jun 17 2026 09:49:03"));
	track[0].push(new TrackPoint(35.281537, 139.219013, 14.471, 12, 0, 0, "Wed Jun 17 2026 09:49:30"));
	track[0].push(new TrackPoint(35.281229, 139.218334, 14.542, 12, 0, 0, "Wed Jun 17 2026 09:50:07"));
	track[0].push(new TrackPoint(35.281199, 139.218194, 14.555, 13, 0, 0, "Wed Jun 17 2026 09:50:14"));
	track[0].push(new TrackPoint(35.281025, 139.217527, 14.619, 13, 0, 0, "Wed Jun 17 2026 09:50:44"));
	track[0].push(new TrackPoint(35.280814, 139.216000, 14.761, 17, 0, 0, "Wed Jun 17 2026 09:51:55"));
	track[0].push(new TrackPoint(35.280468, 139.214697, 14.885, 14, 0, 0, "Wed Jun 17 2026 09:53:02"));
	track[0].push(new TrackPoint(35.280469, 139.214640, 14.891, 15, 0, 0, "Wed Jun 17 2026 09:53:05"));
	track[0].push(new TrackPoint(35.280411, 139.214456, 14.909, 15, 0, 0, "Wed Jun 17 2026 09:53:13"));
	track[0].push(new TrackPoint(35.280361, 139.214127, 14.939, 17, 0, 0, "Wed Jun 17 2026 09:53:30"));
	track[0].push(new TrackPoint(35.280237, 139.213466, 15.001, 19, 0, 0, "Wed Jun 17 2026 09:54:05"));
	track[0].push(new TrackPoint(35.280235, 139.213256, 15.020, 20, 0, 0, "Wed Jun 17 2026 09:54:16"));
	track[0].push(new TrackPoint(35.279900, 139.211493, 15.190, 22, 0, 0, "Wed Jun 17 2026 09:56:15"));
	track[0].push(new TrackPoint(35.279918, 139.211436, 15.196, 21, 0, 0, "Wed Jun 17 2026 09:56:21"));
	track[0].push(new TrackPoint(35.279910, 139.211298, 15.209, 21, 0, 0, "Wed Jun 17 2026 09:56:30"));
	track[0].push(new TrackPoint(35.279788, 139.210656, 15.269, 18, 0, 0, "Wed Jun 17 2026 09:57:10"));
	track[0].push(new TrackPoint(35.279760, 139.210439, 15.289, 17, 0, 0, "Wed Jun 17 2026 09:57:25"));
	track[0].push(new TrackPoint(35.279771, 139.210332, 15.299, 17, 0, 0, "Wed Jun 17 2026 09:57:31"));
	track[0].push(new TrackPoint(35.279730, 139.210181, 15.313, 16, 0, 0, "Wed Jun 17 2026 09:57:39"));
	track[0].push(new TrackPoint(35.279715, 139.209930, 15.337, 17, 0, 0, "Wed Jun 17 2026 09:57:56"));
	track[0].push(new TrackPoint(35.279654, 139.209725, 15.356, 17, 0, 0, "Wed Jun 17 2026 09:58:10"));
	track[0].push(new TrackPoint(35.279669, 139.209618, 15.366, 17, 0, 0, "Wed Jun 17 2026 09:58:18"));
	track[0].push(new TrackPoint(35.279647, 139.209462, 15.381, 16, 0, 0, "Wed Jun 17 2026 09:58:31"));
	track[0].push(new TrackPoint(35.279625, 139.209418, 15.385, 16, 0, 0, "Wed Jun 17 2026 09:58:34"));
	track[0].push(new TrackPoint(35.279591, 139.209149, 15.410, 15, 0, 0, "Wed Jun 17 2026 09:58:49"));
	track[0].push(new TrackPoint(35.279529, 139.209010, 15.425, 14, 0, 0, "Wed Jun 17 2026 09:58:59"));
	track[0].push(new TrackPoint(35.279453, 139.208508, 15.472, 14, 0, 0, "Wed Jun 17 2026 09:59:30"));
	track[0].push(new TrackPoint(35.279426, 139.208438, 15.479, 14, 0, 0, "Wed Jun 17 2026 09:59:34"));
	track[0].push(new TrackPoint(35.279382, 139.208051, 15.514, 14, 0, 0, "Wed Jun 17 2026 10:00:00"));
	track[0].push(new TrackPoint(35.279156, 139.207245, 15.592, 11, 0, 0, "Wed Jun 17 2026 10:00:58"));
	track[0].push(new TrackPoint(35.279137, 139.207066, 15.609, 10, 0, 0, "Wed Jun 17 2026 10:01:12"));
	track[0].push(new TrackPoint(35.279091, 139.206891, 15.626, 9, 0, 0, "Wed Jun 17 2026 10:01:25"));
	track[0].push(new TrackPoint(35.278977, 139.206601, 15.655, 10, 0, 0, "Wed Jun 17 2026 10:01:40"));
	track[0].push(new TrackPoint(35.278960, 139.206494, 15.665, 10, 0, 0, "Wed Jun 17 2026 10:01:46"));
	track[0].push(new TrackPoint(35.278745, 139.205922, 15.722, 9, 0, 0, "Wed Jun 17 2026 10:02:14"));
	track[0].push(new TrackPoint(35.278718, 139.205800, 15.734, 9, 0, 0, "Wed Jun 17 2026 10:02:21"));
	track[0].push(new TrackPoint(35.278564, 139.205538, 15.763, 10, 0, 0, "Wed Jun 17 2026 10:02:34"));
	track[0].push(new TrackPoint(35.278394, 139.205138, 15.804, 8, 0, 0, "Wed Jun 17 2026 10:02:58"));
	track[0].push(new TrackPoint(35.278272, 139.205182, 15.819, 8, 0, 0, "Wed Jun 17 2026 10:03:15"));
	track[0].push(new TrackPoint(35.278345, 139.205084, 15.831, 8, 0, 0, "Wed Jun 17 2026 10:03:30"));
	track[0].push(new TrackPoint(35.278263, 139.204903, 15.850, 8, 0, 0, "Wed Jun 17 2026 10:03:48"));
	track[0].push(new TrackPoint(35.278190, 139.204968, 15.860, 8, 0, 0, "Wed Jun 17 2026 10:04:01"));
	track[0].push(new TrackPoint(35.278171, 139.204943, 15.863, 8, 0, 0, "Wed Jun 17 2026 10:04:04"));
	track[0].push(new TrackPoint(35.278263, 139.204848, 15.876, 8, 0, 0, "Wed Jun 17 2026 10:04:15"));
	track[0].push(new TrackPoint(35.278265, 139.204826, 15.878, 8, 0, 0, "Wed Jun 17 2026 10:04:17"));
	track[0].push(new TrackPoint(35.277988, 139.204407, 15.927, 10, 0, 0, "Wed Jun 17 2026 10:04:49"));
	track[0].push(new TrackPoint(35.277807, 139.204211, 15.954, 9, 0, 0, "Wed Jun 17 2026 10:05:02"));
	track[0].push(new TrackPoint(35.277540, 139.203999, 15.990, 9, 0, 0, "Wed Jun 17 2026 10:05:20"));
	track[0].push(new TrackPoint(35.277395, 139.203924, 16.007, 9, 0, 0, "Wed Jun 17 2026 10:05:29"));
	track[0].push(new TrackPoint(35.277324, 139.203852, 16.018, 10, 0, 0, "Wed Jun 17 2026 10:05:35"));
	track[0].push(new TrackPoint(35.276989, 139.203656, 16.059, 12, 0, 0, "Wed Jun 17 2026 10:05:57"));
	track[0].push(new TrackPoint(35.276258, 139.203144, 16.153, 9, 0, 0, "Wed Jun 17 2026 10:06:40"));
	track[0].push(new TrackPoint(35.276026, 139.203079, 16.179, 9, 0, 0, "Wed Jun 17 2026 10:06:55"));
	track[0].push(new TrackPoint(35.275778, 139.202949, 16.209, 10, 0, 0, "Wed Jun 17 2026 10:07:12"));
	track[0].push(new TrackPoint(35.274935, 139.202274, 16.325, 12, 0, 0, "Wed Jun 17 2026 10:11:27"));
	track[0].push(new TrackPoint(35.274861, 139.202239, 16.334, 12, 0, 0, "Wed Jun 17 2026 10:11:31"));
	track[0].push(new TrackPoint(35.274117, 139.201631, 16.434, 10, 0, 0, "Wed Jun 17 2026 10:12:39"));
	track[0].push(new TrackPoint(35.273853, 139.201352, 16.473, 10, 0, 0, "Wed Jun 17 2026 10:13:08"));
	track[0].push(new TrackPoint(35.273810, 139.201278, 16.481, 10, 0, 0, "Wed Jun 17 2026 10:13:14"));
	track[0].push(new TrackPoint(35.272795, 139.200134, 16.635, 12, 0, 0, "Wed Jun 17 2026 10:14:37"));
	track[0].push(new TrackPoint(35.272682, 139.199987, 16.653, 12, 0, 0, "Wed Jun 17 2026 10:14:47"));
	track[0].push(new TrackPoint(35.272625, 139.199882, 16.665, 12, 0, 0, "Wed Jun 17 2026 10:14:53"));
	track[0].push(new TrackPoint(35.271285, 139.198011, 16.891, 11, 0, 0, "Wed Jun 17 2026 10:16:47"));
	track[0].push(new TrackPoint(35.271116, 139.197742, 16.922, 12, 0, 0, "Wed Jun 17 2026 10:17:03"));
	track[0].push(new TrackPoint(35.270156, 139.196419, 17.083, 14, 0, 0, "Wed Jun 17 2026 10:18:28"));
	track[0].push(new TrackPoint(35.270022, 139.196198, 17.108, 13, 0, 0, "Wed Jun 17 2026 10:18:42"));
	track[0].push(new TrackPoint(35.269526, 139.195391, 17.200, 12, 0, 0, "Wed Jun 17 2026 10:19:31"));
	track[0].push(new TrackPoint(35.269409, 139.195226, 17.220, 11, 0, 0, "Wed Jun 17 2026 10:19:40"));
	track[0].push(new TrackPoint(35.269289, 139.194974, 17.246, 12, 0, 0, "Wed Jun 17 2026 10:19:55"));
	track[0].push(new TrackPoint(35.269115, 139.194717, 17.277, 12, 0, 0, "Wed Jun 17 2026 10:20:10"));
	track[0].push(new TrackPoint(35.268702, 139.193938, 17.361, 12, 0, 0, "Wed Jun 17 2026 10:20:52"));
	track[0].push(new TrackPoint(35.268299, 139.193266, 17.437, 12, 0, 0, "Wed Jun 17 2026 10:21:31"));
	track[0].push(new TrackPoint(35.268251, 139.193154, 17.449, 12, 0, 0, "Wed Jun 17 2026 10:21:37"));
	track[0].push(new TrackPoint(35.268309, 139.193052, 17.461, 12, 0, 0, "Wed Jun 17 2026 10:21:56"));
	track[0].push(new TrackPoint(35.268250, 139.192860, 17.479, 12, 0, 0, "Wed Jun 17 2026 10:22:09"));
	track[0].push(new TrackPoint(35.267895, 139.192186, 17.552, 12, 0, 0, "Wed Jun 17 2026 10:22:48"));
	track[0].push(new TrackPoint(35.267341, 139.190861, 17.688, 10, 0, 0, "Wed Jun 17 2026 10:23:57"));
	track[0].push(new TrackPoint(35.267046, 139.190008, 17.772, 11, 0, 0, "Wed Jun 17 2026 10:24:39"));
	track[0].push(new TrackPoint(35.266878, 139.189621, 17.814, 11, 0, 0, "Wed Jun 17 2026 10:26:19"));
	track[0].push(new TrackPoint(35.266806, 139.189321, 17.843, 10, 0, 0, "Wed Jun 17 2026 10:26:41"));
	track[0].push(new TrackPoint(35.266519, 139.188482, 17.926, 9, 0, 0, "Wed Jun 17 2026 10:27:34"));
	track[0].push(new TrackPoint(35.266409, 139.188250, 17.951, 7, 0, 0, "Wed Jun 17 2026 10:27:52"));
	track[0].push(new TrackPoint(35.265420, 139.185009, 18.266, 9, 0, 0, "Wed Jun 17 2026 10:30:40"));
	track[0].push(new TrackPoint(35.265408, 139.184900, 18.276, 10, 0, 0, "Wed Jun 17 2026 10:30:49"));
	track[0].push(new TrackPoint(35.265429, 139.184864, 18.280, 10, 0, 0, "Wed Jun 17 2026 10:31:00"));
	track[0].push(new TrackPoint(35.265330, 139.184643, 18.303, 11, 0, 0, "Wed Jun 17 2026 10:31:18"));
	track[0].push(new TrackPoint(35.265256, 139.184358, 18.330, 13, 0, 0, "Wed Jun 17 2026 10:31:34"));
	track[0].push(new TrackPoint(35.265252, 139.184274, 18.338, 14, 0, 0, "Wed Jun 17 2026 10:31:38"));
	track[0].push(new TrackPoint(35.265167, 139.184125, 18.355, 13, 0, 0, "Wed Jun 17 2026 10:31:47"));
	track[0].push(new TrackPoint(35.265120, 139.183921, 18.374, 12, 0, 0, "Wed Jun 17 2026 10:31:57"));
	track[0].push(new TrackPoint(35.264984, 139.183555, 18.411, 11, 0, 0, "Wed Jun 17 2026 10:32:19"));
	track[0].push(new TrackPoint(35.264908, 139.183319, 18.434, 12, 0, 0, "Wed Jun 17 2026 10:32:37"));
	track[0].push(new TrackPoint(35.264816, 139.183119, 18.455, 11, 0, 0, "Wed Jun 17 2026 10:32:54"));
	track[0].push(new TrackPoint(35.264766, 139.183058, 18.463, 11, 0, 0, "Wed Jun 17 2026 10:32:59"));
	track[0].push(new TrackPoint(35.264614, 139.182769, 18.494, 9, 0, 0, "Wed Jun 17 2026 10:33:30"));
	track[0].push(new TrackPoint(35.264394, 139.182438, 18.534, 4, 0, 0, "Wed Jun 17 2026 10:34:15"));
	track[0].push(new TrackPoint(35.263275, 139.181194, 18.703, 1, 0, 0, "Wed Jun 17 2026 10:36:42"));
	track[0].push(new TrackPoint(35.263090, 139.180969, 18.732, 0, 0, 0, "Wed Jun 17 2026 10:37:21"));
	track[0].push(new TrackPoint(35.263038, 139.180939, 18.739, 0, 0, 0, "Wed Jun 17 2026 10:37:30"));
	track[0].push(new TrackPoint(35.262380, 139.180247, 18.835, 4, 0, 0, "Wed Jun 17 2026 10:38:45"));
	track[0].push(new TrackPoint(35.261364, 139.179256, 18.980, 8, 0, 0, "Wed Jun 17 2026 10:40:28"));
	track[0].push(new TrackPoint(35.261271, 139.179148, 18.995, 8, 0, 0, "Wed Jun 17 2026 10:40:38"));
	track[0].push(new TrackPoint(35.261180, 139.179067, 19.007, 9, 0, 0, "Wed Jun 17 2026 10:40:49"));
	track[0].push(new TrackPoint(35.261446, 139.178779, 19.048, 8, 0, 0, "Wed Jun 17 2026 10:41:21"));
	track[0].push(new TrackPoint(35.261489, 139.178687, 19.057, 8, 0, 0, "Wed Jun 17 2026 10:41:28"));
	track[0].push(new TrackPoint(35.261492, 139.178599, 19.065, 8, 0, 0, "Wed Jun 17 2026 10:41:33"));
	track[0].push(new TrackPoint(35.261543, 139.178549, 19.073, 9, 0, 0, "Wed Jun 17 2026 10:41:39"));
	track[0].push(new TrackPoint(35.261616, 139.178552, 19.081, 9, 0, 0, "Wed Jun 17 2026 10:41:43"));
	track[0].push(new TrackPoint(35.261647, 139.178528, 19.086, 9, 0, 0, "Wed Jun 17 2026 10:41:46"));
	track[0].push(new TrackPoint(35.261655, 139.178494, 19.089, 9, 0, 0, "Wed Jun 17 2026 10:41:49"));
	track[0].push(new TrackPoint(35.261770, 139.178585, 19.104, 8, 0, 0, "Wed Jun 17 2026 10:42:01"));
	track[0].push(new TrackPoint(35.262311, 139.179161, 19.184, 6, 0, 0, "Wed Jun 17 2026 10:42:55"));
	track[0].push(new TrackPoint(35.262421, 139.179308, 19.202, 7, 0, 0, "Wed Jun 17 2026 10:43:08"));
	track[0].push(new TrackPoint(35.262455, 139.179395, 19.211, 7, 0, 0, "Wed Jun 17 2026 10:43:14"));
	track[0].push(new TrackPoint(35.262493, 139.179443, 19.223, 6, 0, 0, "Wed Jun 17 2026 10:44:18"));
	track[0].push(new TrackPoint(35.262425, 139.179328, 19.236, 7, 0, 0, "Wed Jun 17 2026 10:44:26"));
	track[0].push(new TrackPoint(35.262004, 139.178877, 19.298, 6, 0, 0, "Wed Jun 17 2026 10:45:11"));
	track[0].push(new TrackPoint(35.261925, 139.178809, 19.309, 6, 0, 0, "Wed Jun 17 2026 10:45:18"));
	track[0].push(new TrackPoint(35.261512, 139.178352, 19.372, 10, 0, 0, "Wed Jun 17 2026 10:46:04"));
	track[0].push(new TrackPoint(35.261456, 139.178270, 19.381, 10, 0, 0, "Wed Jun 17 2026 10:46:11"));
	track[0].push(new TrackPoint(35.261345, 139.178187, 19.396, 10, 0, 0, "Wed Jun 17 2026 10:46:24"));
	track[0].push(new TrackPoint(35.261268, 139.178243, 19.406, 10, 0, 0, "Wed Jun 17 2026 10:46:32"));
	track[0].push(new TrackPoint(35.261072, 139.178301, 19.428, 10, 0, 0, "Wed Jun 17 2026 10:46:48"));
	track[0].push(new TrackPoint(35.260942, 139.178292, 19.443, 11, 0, 0, "Wed Jun 17 2026 10:46:59"));
	track[0].push(new TrackPoint(35.260752, 139.178233, 19.464, 11, 0, 0, "Wed Jun 17 2026 10:47:14"));
	track[0].push(new TrackPoint(35.260653, 139.178247, 19.476, 11, 0, 0, "Wed Jun 17 2026 10:47:23"));
	track[0].push(new TrackPoint(35.260568, 139.178333, 19.488, 12, 0, 0, "Wed Jun 17 2026 10:47:34"));
	track[0].push(new TrackPoint(35.260340, 139.178167, 19.518, 10, 0, 0, "Wed Jun 17 2026 10:47:56"));
	track[0].push(new TrackPoint(35.260271, 139.178094, 19.528, 10, 0, 0, "Wed Jun 17 2026 10:48:35"));
	track[0].push(new TrackPoint(35.260241, 139.178149, 19.534, 10, 0, 0, "Wed Jun 17 2026 10:48:43"));
	track[0].push(new TrackPoint(35.260132, 139.178242, 19.549, 10, 0, 0, "Wed Jun 17 2026 10:48:52"));
	track[0].push(new TrackPoint(35.259817, 139.178348, 19.586, 8, 0, 0, "Wed Jun 17 2026 10:49:20"));
	track[0].push(new TrackPoint(35.259709, 139.178339, 19.598, 8, 0, 0, "Wed Jun 17 2026 10:49:29"));
	track[0].push(new TrackPoint(35.259605, 139.178072, 19.625, 9, 0, 0, "Wed Jun 17 2026 10:49:49"));
	track[0].push(new TrackPoint(35.259515, 139.177766, 19.655, 10, 0, 0, "Wed Jun 17 2026 10:50:10"));
	track[0].push(new TrackPoint(35.259467, 139.177652, 19.666, 10, 0, 0, "Wed Jun 17 2026 10:50:18"));
	track[0].push(new TrackPoint(35.259247, 139.177206, 19.714, 8, 0, 0, "Wed Jun 17 2026 10:50:44"));
	track[0].push(new TrackPoint(35.259162, 139.176973, 19.737, 8, 0, 0, "Wed Jun 17 2026 10:50:57"));
	track[0].push(new TrackPoint(35.259000, 139.176736, 19.765, 8, 0, 0, "Wed Jun 17 2026 10:51:11"));
	track[0].push(new TrackPoint(35.258789, 139.176474, 19.799, 9, 0, 0, "Wed Jun 17 2026 10:51:27"));
	track[0].push(new TrackPoint(35.258450, 139.175974, 19.858, 10, 0, 0, "Wed Jun 17 2026 10:51:58"));
	track[0].push(new TrackPoint(35.258395, 139.175841, 19.871, 11, 0, 0, "Wed Jun 17 2026 10:52:05"));
	track[0].push(new TrackPoint(35.257881, 139.175150, 19.957, 8, 0, 0, "Wed Jun 17 2026 10:52:51"));
	track[0].push(new TrackPoint(35.257703, 139.174863, 19.989, 7, 0, 0, "Wed Jun 17 2026 10:53:08"));
	track[0].push(new TrackPoint(35.257347, 139.174160, 20.065, 7, 0, 0, "Wed Jun 17 2026 10:53:46"));
	track[0].push(new TrackPoint(35.257322, 139.174076, 20.073, 8, 0, 0, "Wed Jun 17 2026 10:53:51"));
	track[0].push(new TrackPoint(35.257204, 139.173879, 20.095, 8, 0, 0, "Wed Jun 17 2026 10:54:02"));
	track[0].push(new TrackPoint(35.257193, 139.173815, 20.101, 8, 0, 0, "Wed Jun 17 2026 10:54:05"));
	track[0].push(new TrackPoint(35.256804, 139.173079, 20.181, 8, 0, 0, "Wed Jun 17 2026 10:54:43"));
	track[0].push(new TrackPoint(35.256720, 139.172959, 20.195, 8, 0, 0, "Wed Jun 17 2026 10:54:49"));
	track[0].push(new TrackPoint(35.256523, 139.172529, 20.240, 8, 0, 0, "Wed Jun 17 2026 10:55:12"));
	track[0].push(new TrackPoint(35.256313, 139.171935, 20.299, 10, 0, 0, "Wed Jun 17 2026 10:55:44"));
	track[0].push(new TrackPoint(35.256298, 139.171791, 20.312, 10, 0, 0, "Wed Jun 17 2026 10:55:52"));
	track[0].push(new TrackPoint(35.256234, 139.171516, 20.338, 10, 0, 0, "Wed Jun 17 2026 10:56:06"));
	track[0].push(new TrackPoint(35.256119, 139.171170, 20.372, 10, 0, 0, "Wed Jun 17 2026 10:56:22"));
	track[0].push(new TrackPoint(35.256015, 139.170752, 20.412, 9, 0, 0, "Wed Jun 17 2026 10:56:41"));
	track[0].push(new TrackPoint(35.255836, 139.170415, 20.449, 8, 0, 0, "Wed Jun 17 2026 10:56:58"));
	track[0].push(new TrackPoint(35.255318, 139.169373, 20.560, 8, 0, 0, "Wed Jun 17 2026 10:57:58"));
	track[0].push(new TrackPoint(35.255316, 139.169333, 20.564, 8, 0, 0, "Wed Jun 17 2026 10:58:01"));
	track[0].push(new TrackPoint(35.254976, 139.168803, 20.625, 10, 0, 0, "Wed Jun 17 2026 10:58:32"));
	track[0].push(new TrackPoint(35.254920, 139.168622, 20.643, 11, 0, 0, "Wed Jun 17 2026 10:58:54"));
	track[0].push(new TrackPoint(35.254878, 139.168602, 20.648, 11, 0, 0, "Wed Jun 17 2026 10:59:02"));
	track[0].push(new TrackPoint(35.254576, 139.168087, 20.706, 10, 0, 0, "Wed Jun 17 2026 11:00:20"));
	track[0].push(new TrackPoint(35.254505, 139.167897, 20.725, 10, 0, 0, "Wed Jun 17 2026 11:00:28"));
	track[0].push(new TrackPoint(35.254104, 139.167275, 20.799, 9, 0, 0, "Wed Jun 17 2026 11:01:17"));
	track[0].push(new TrackPoint(35.253966, 139.167117, 20.820, 10, 0, 0, "Wed Jun 17 2026 11:01:34"));
	track[0].push(new TrackPoint(35.253943, 139.167034, 20.828, 10, 0, 0, "Wed Jun 17 2026 11:01:42"));
	track[0].push(new TrackPoint(35.253780, 139.166838, 20.854, 10, 0, 0, "Wed Jun 17 2026 11:02:02"));
	track[0].push(new TrackPoint(35.253708, 139.166651, 20.872, 11, 0, 0, "Wed Jun 17 2026 11:02:13"));
	track[0].push(new TrackPoint(35.253493, 139.166432, 20.904, 11, 0, 0, "Wed Jun 17 2026 11:02:35"));
	track[0].push(new TrackPoint(35.252771, 139.165260, 21.038, 10, 0, 0, "Wed Jun 17 2026 11:04:13"));
	track[0].push(new TrackPoint(35.252670, 139.165197, 21.050, 10, 0, 0, "Wed Jun 17 2026 11:04:20"));
	track[0].push(new TrackPoint(35.252550, 139.165295, 21.067, 11, 0, 0, "Wed Jun 17 2026 11:04:32"));
	track[0].push(new TrackPoint(35.252479, 139.165411, 21.080, 11, 0, 0, "Wed Jun 17 2026 11:04:41"));
	track[0].push(new TrackPoint(35.252381, 139.165521, 21.095, 11, 0, 0, "Wed Jun 17 2026 11:04:51"));
	track[0].push(new TrackPoint(35.252295, 139.165538, 21.105, 11, 0, 0, "Wed Jun 17 2026 11:04:58"));
	track[0].push(new TrackPoint(35.252203, 139.165654, 21.119, 10, 0, 0, "Wed Jun 17 2026 11:05:12"));
	track[0].push(new TrackPoint(35.252123, 139.165853, 21.140, 11, 0, 0, "Wed Jun 17 2026 11:05:27"));
	track[0].push(new TrackPoint(35.252080, 139.165885, 21.145, 11, 0, 0, "Wed Jun 17 2026 11:05:31"));
	track[0].push(new TrackPoint(35.252005, 139.165872, 21.154, 12, 0, 0, "Wed Jun 17 2026 11:05:34"));
	track[0].push(new TrackPoint(35.251824, 139.165717, 21.178, 12, 0, 0, "Wed Jun 17 2026 11:05:49"));
	track[0].push(new TrackPoint(35.251535, 139.165356, 21.225, 13, 0, 0, "Wed Jun 17 2026 11:06:43"));
	track[0].push(new TrackPoint(35.251340, 139.165065, 21.259, 13, 0, 0, "Wed Jun 17 2026 11:07:03"));
	track[0].push(new TrackPoint(35.250284, 139.163730, 21.428, 12, 0, 0, "Wed Jun 17 2026 11:09:02"));
	track[0].push(new TrackPoint(35.250036, 139.163446, 21.466, 12, 0, 0, "Wed Jun 17 2026 11:09:30"));
	track[0].push(new TrackPoint(35.249416, 139.162532, 21.574, 12, 0, 0, "Wed Jun 17 2026 11:10:47"));
	track[0].push(new TrackPoint(35.249195, 139.162133, 21.618, 14, 0, 0, "Wed Jun 17 2026 11:11:20"));
	track[0].push(new TrackPoint(35.249148, 139.161989, 21.633, 16, 0, 0, "Wed Jun 17 2026 11:11:29"));
	track[0].push(new TrackPoint(35.249142, 139.161894, 21.642, 18, 0, 0, "Wed Jun 17 2026 11:11:35"));
	track[0].push(new TrackPoint(35.249097, 139.161850, 21.648, 18, 0, 0, "Wed Jun 17 2026 11:11:48"));
	track[0].push(new TrackPoint(35.249047, 139.161863, 21.655, 17, 0, 0, "Wed Jun 17 2026 11:12:14"));
	track[0].push(new TrackPoint(35.248995, 139.161695, 21.671, 18, 0, 0, "Wed Jun 17 2026 11:12:38"));
	track[0].push(new TrackPoint(35.249033, 139.161594, 21.681, 18, 0, 0, "Wed Jun 17 2026 11:12:47"));
	track[0].push(new TrackPoint(35.249030, 139.161566, 21.684, 18, 0, 0, "Wed Jun 17 2026 11:12:49"));
	track[0].push(new TrackPoint(35.248967, 139.161526, 21.692, 18, 0, 0, "Wed Jun 17 2026 11:13:00"));
	track[0].push(new TrackPoint(35.248884, 139.161344, 21.711, 17, 0, 0, "Wed Jun 17 2026 11:13:14"));
	track[0].push(new TrackPoint(35.248797, 139.161214, 21.726, 16, 0, 0, "Wed Jun 17 2026 11:13:20"));
	track[0].push(new TrackPoint(35.248730, 139.161053, 21.743, 15, 0, 0, "Wed Jun 17 2026 11:13:32"));
	track[0].push(new TrackPoint(35.248703, 139.160823, 21.764, 15, 0, 0, "Wed Jun 17 2026 11:13:44"));
	track[0].push(new TrackPoint(35.248674, 139.160704, 21.776, 16, 0, 0, "Wed Jun 17 2026 11:13:51"));
	track[0].push(new TrackPoint(35.248583, 139.160570, 21.793, 16, 0, 0, "Wed Jun 17 2026 11:14:23"));
	track[0].push(new TrackPoint(35.248548, 139.160417, 21.807, 16, 0, 0, "Wed Jun 17 2026 11:15:01"));
	track[0].push(new TrackPoint(35.248421, 139.160131, 21.837, 16, 0, 0, "Wed Jun 17 2026 11:15:20"));
	track[0].push(new TrackPoint(35.248421, 139.160087, 21.841, 16, 0, 0, "Wed Jun 17 2026 11:15:22"));
	track[0].push(new TrackPoint(35.248292, 139.159788, 21.872, 16, 0, 0, "Wed Jun 17 2026 11:15:42"));
	track[0].push(new TrackPoint(35.248292, 139.159691, 21.881, 16, 0, 0, "Wed Jun 17 2026 11:15:50"));
	track[0].push(new TrackPoint(35.248270, 139.159653, 21.885, 16, 0, 0, "Wed Jun 17 2026 11:15:53"));
	track[0].push(new TrackPoint(35.248241, 139.159644, 21.889, 16, 0, 0, "Wed Jun 17 2026 11:15:58"));
	track[0].push(new TrackPoint(35.248222, 139.159538, 21.899, 16, 0, 0, "Wed Jun 17 2026 11:16:04"));
	track[0].push(new TrackPoint(35.248192, 139.159517, 21.903, 17, 0, 0, "Wed Jun 17 2026 11:16:08"));
	track[0].push(new TrackPoint(35.248204, 139.159443, 21.910, 16, 0, 0, "Wed Jun 17 2026 11:16:13"));
	track[0].push(new TrackPoint(35.248126, 139.159274, 21.928, 17, 0, 0, "Wed Jun 17 2026 11:16:22"));
	track[0].push(new TrackPoint(35.248083, 139.159220, 21.939, 18, 0, 0, "Wed Jun 17 2026 11:16:46"));
	track[0].push(new TrackPoint(35.248080, 139.159134, 21.948, 18, 0, 0, "Wed Jun 17 2026 11:16:55"));
	track[0].push(new TrackPoint(35.248279, 139.158799, 21.985, 14, 0, 0, "Wed Jun 17 2026 11:44:26"));
	track[0].push(new TrackPoint(35.248030, 139.159027, 22.046, 18, 0, 0, "Wed Jun 17 2026 11:44:36"));
	track[0].push(new TrackPoint(35.247974, 139.158975, 22.054, 18, 0, 0, "Wed Jun 17 2026 11:44:44"));
	track[0].push(new TrackPoint(35.247990, 139.158844, 22.066, 17, 0, 0, "Wed Jun 17 2026 11:44:55"));
	track[0].push(new TrackPoint(35.247982, 139.158788, 22.071, 17, 0, 0, "Wed Jun 17 2026 11:45:01"));
	track[0].push(new TrackPoint(35.247921, 139.158712, 22.081, 17, 0, 0, "Wed Jun 17 2026 11:45:09"));
	track[0].push(new TrackPoint(35.247905, 139.158543, 22.105, 16, 0, 0, "Wed Jun 17 2026 11:46:03"));
	track[0].push(new TrackPoint(35.247848, 139.158354, 22.124, 15, 0, 0, "Wed Jun 17 2026 11:46:19"));
	track[0].push(new TrackPoint(35.247782, 139.158267, 22.135, 15, 0, 0, "Wed Jun 17 2026 11:46:29"));
	track[0].push(new TrackPoint(35.247647, 139.157885, 22.173, 14, 0, 0, "Wed Jun 17 2026 11:46:58"));
	track[0].push(new TrackPoint(35.247640, 139.157834, 22.178, 14, 0, 0, "Wed Jun 17 2026 11:47:04"));
	track[0].push(new TrackPoint(35.247548, 139.157707, 22.193, 14, 0, 0, "Wed Jun 17 2026 11:47:16"));
	track[0].push(new TrackPoint(35.247541, 139.157655, 22.198, 14, 0, 0, "Wed Jun 17 2026 11:47:21"));
	track[0].push(new TrackPoint(35.247565, 139.157610, 22.203, 14, 0, 0, "Wed Jun 17 2026 11:47:29"));
	track[0].push(new TrackPoint(35.247659, 139.157549, 22.215, 14, 0, 0, "Wed Jun 17 2026 11:47:39"));
	track[0].push(new TrackPoint(35.247504, 139.157064, 22.262, 15, 0, 0, "Wed Jun 17 2026 11:48:17"));
	track[0].push(new TrackPoint(35.247391, 139.156421, 22.323, 16, 0, 0, "Wed Jun 17 2026 11:49:03"));
	track[0].push(new TrackPoint(35.247334, 139.154828, 22.469, 14, 0, 0, "Wed Jun 17 2026 11:50:52"));
	track[0].push(new TrackPoint(35.247338, 139.154657, 22.484, 14, 0, 0, "Wed Jun 17 2026 11:51:08"));
	track[0].push(new TrackPoint(35.247326, 139.154540, 22.495, 14, 0, 0, "Wed Jun 17 2026 11:51:16"));
	track[0].push(new TrackPoint(35.247329, 139.154226, 22.524, 14, 0, 0, "Wed Jun 17 2026 11:51:33"));
	track[0].push(new TrackPoint(35.247272, 139.153478, 22.592, 15, 0, 0, "Wed Jun 17 2026 11:52:10"));
	track[0].push(new TrackPoint(35.247169, 139.152863, 22.650, 15, 0, 0, "Wed Jun 17 2026 11:52:41"));
	track[0].push(new TrackPoint(35.247141, 139.152579, 22.676, 15, 0, 0, "Wed Jun 17 2026 11:52:56"));
	track[0].push(new TrackPoint(35.247056, 139.152126, 22.718, 16, 0, 0, "Wed Jun 17 2026 11:53:19"));
	track[0].push(new TrackPoint(35.247043, 139.151889, 22.740, 18, 0, 0, "Wed Jun 17 2026 11:53:31"));
	track[0].push(new TrackPoint(35.246947, 139.151162, 22.807, 18, 0, 0, "Wed Jun 17 2026 11:54:09"));
	track[0].push(new TrackPoint(35.246730, 139.149918, 22.923, 18, 0, 0, "Wed Jun 17 2026 11:55:21"));
	track[0].push(new TrackPoint(35.246725, 139.149817, 22.932, 18, 0, 0, "Wed Jun 17 2026 11:55:29"));
	track[0].push(new TrackPoint(35.246742, 139.149763, 22.939, 17, 0, 0, "Wed Jun 17 2026 11:56:05"));
	track[0].push(new TrackPoint(35.246621, 139.149405, 22.974, 18, 0, 0, "Wed Jun 17 2026 11:56:29"));
	track[0].push(new TrackPoint(35.246418, 139.148431, 23.066, 19, 0, 0, "Wed Jun 17 2026 11:57:14"));
	track[0].push(new TrackPoint(35.246363, 139.148240, 23.084, 19, 0, 0, "Wed Jun 17 2026 11:57:23"));
	track[0].push(new TrackPoint(35.246265, 139.147751, 23.130, 19, 0, 0, "Wed Jun 17 2026 11:57:47"));
	track[0].push(new TrackPoint(35.246258, 139.147648, 23.140, 19, 0, 0, "Wed Jun 17 2026 11:57:52"));
	track[0].push(new TrackPoint(35.246495, 139.147430, 23.173, 21, 0, 0, "Wed Jun 17 2026 11:58:11"));
	track[0].push(new TrackPoint(35.246609, 139.147110, 23.205, 20, 0, 0, "Wed Jun 17 2026 11:58:30"));
	track[0].push(new TrackPoint(35.246638, 139.146939, 23.221, 19, 0, 0, "Wed Jun 17 2026 11:58:39"));
	track[0].push(new TrackPoint(35.246940, 139.145871, 23.324, 16, 0, 0, "Wed Jun 17 2026 11:59:38"));
	track[0].push(new TrackPoint(35.246952, 139.145711, 23.338, 17, 0, 0, "Wed Jun 17 2026 11:59:46"));
	track[0].push(new TrackPoint(35.247034, 139.145249, 23.382, 18, 0, 0, "Wed Jun 17 2026 12:00:11"));
	track[0].push(new TrackPoint(35.247076, 139.145105, 23.396, 18, 0, 0, "Wed Jun 17 2026 12:00:19"));
	track[0].push(new TrackPoint(35.247369, 139.143385, 23.556, 20, 0, 0, "Wed Jun 17 2026 12:02:02"));
	track[0].push(new TrackPoint(35.247414, 139.143195, 23.574, 20, 0, 0, "Wed Jun 17 2026 12:02:12"));
	track[0].push(new TrackPoint(35.247517, 139.142664, 23.624, 19, 0, 0, "Wed Jun 17 2026 12:02:49"));
	track[0].push(new TrackPoint(35.247556, 139.142260, 23.661, 20, 0, 0, "Wed Jun 17 2026 12:03:18"));
	track[0].push(new TrackPoint(35.247601, 139.141866, 23.698, 22, 0, 0, "Wed Jun 17 2026 12:03:45"));
	track[0].push(new TrackPoint(35.247557, 139.141709, 23.713, 22, 0, 0, "Wed Jun 17 2026 12:03:56"));
	track[0].push(new TrackPoint(35.247336, 139.141311, 23.757, 22, 0, 0, "Wed Jun 17 2026 12:04:31"));
	track[0].push(new TrackPoint(35.247231, 139.141078, 23.781, 25, 0, 0, "Wed Jun 17 2026 12:04:50"));
	track[0].push(new TrackPoint(35.247074, 139.140844, 23.809, 27, 0, 0, "Wed Jun 17 2026 12:05:13"));
	track[0].push(new TrackPoint(35.247041, 139.140771, 23.816, 27, 0, 0, "Wed Jun 17 2026 12:05:18"));
	track[0].push(new TrackPoint(35.246983, 139.140483, 23.844, 29, 0, 0, "Wed Jun 17 2026 12:05:38"));
	track[0].push(new TrackPoint(35.246979, 139.140346, 23.856, 30, 0, 0, "Wed Jun 17 2026 12:05:47"));
	track[0].push(new TrackPoint(35.246914, 139.140180, 23.873, 28, 0, 0, "Wed Jun 17 2026 12:05:57"));
	track[0].push(new TrackPoint(35.246895, 139.140008, 23.889, 28, 0, 0, "Wed Jun 17 2026 12:06:10"));
	track[0].push(new TrackPoint(35.246913, 139.139595, 23.927, 33, 0, 0, "Wed Jun 17 2026 12:06:38"));
	track[0].push(new TrackPoint(35.246679, 139.137466, 24.125, 49, 0, 0, "Wed Jun 17 2026 12:08:51"));
	track[0].push(new TrackPoint(35.246657, 139.136214, 24.240, 54, 0, 0, "Wed Jun 17 2026 12:10:09"));
	track[0].push(new TrackPoint(35.246628, 139.135889, 24.270, 53, 0, 0, "Wed Jun 17 2026 12:10:31"));
	track[0].push(new TrackPoint(35.246566, 139.135340, 24.320, 52, 0, 0, "Wed Jun 17 2026 12:11:05"));
	track[0].push(new TrackPoint(35.246572, 139.135064, 24.346, 54, 0, 0, "Wed Jun 17 2026 12:11:22"));
	track[0].push(new TrackPoint(35.246986, 139.132980, 24.543, 45, 0, 0, "Wed Jun 17 2026 12:13:39"));
	track[0].push(new TrackPoint(35.247019, 139.132789, 24.564, 44, 0, 0, "Wed Jun 17 2026 12:15:02"));
	track[0].push(new TrackPoint(35.247081, 139.132696, 24.575, 45, 0, 0, "Wed Jun 17 2026 12:15:07"));
	track[0].push(new TrackPoint(35.247213, 139.132335, 24.612, 42, 0, 0, "Wed Jun 17 2026 12:15:34"));
	track[0].push(new TrackPoint(35.247349, 139.132015, 24.645, 39, 0, 0, "Wed Jun 17 2026 12:15:57"));
	track[0].push(new TrackPoint(35.247347, 139.131964, 24.650, 40, 0, 0, "Wed Jun 17 2026 12:16:00"));
	track[0].push(new TrackPoint(35.247047, 139.131162, 24.730, 41, 0, 0, "Wed Jun 17 2026 12:16:57"));
	track[0].push(new TrackPoint(35.247017, 139.131048, 24.741, 41, 0, 0, "Wed Jun 17 2026 12:17:05"));
	track[0].push(new TrackPoint(35.246779, 139.130323, 24.813, 43, 0, 0, "Wed Jun 17 2026 12:17:56"));
	track[0].push(new TrackPoint(35.246747, 139.130052, 24.838, 44, 0, 0, "Wed Jun 17 2026 12:18:17"));
	track[0].push(new TrackPoint(35.246783, 139.129779, 24.863, 45, 0, 0, "Wed Jun 17 2026 12:18:35"));
	track[0].push(new TrackPoint(35.246764, 139.129593, 24.880, 47, 0, 0, "Wed Jun 17 2026 12:18:45"));
	track[0].push(new TrackPoint(35.246665, 139.129348, 24.905, 46, 0, 0, "Wed Jun 17 2026 12:19:03"));
	track[0].push(new TrackPoint(35.246632, 139.128893, 24.947, 44, 0, 0, "Wed Jun 17 2026 12:19:31"));
	track[0].push(new TrackPoint(35.246640, 139.128655, 24.969, 44, 0, 0, "Wed Jun 17 2026 12:19:49"));
	track[0].push(new TrackPoint(35.246586, 139.128508, 24.984, 43, 0, 0, "Wed Jun 17 2026 12:19:59"));
	track[0].push(new TrackPoint(35.246436, 139.128260, 25.012, 42, 0, 0, "Wed Jun 17 2026 12:20:18"));
	track[0].push(new TrackPoint(35.246128, 139.127558, 25.085, 42, 0, 0, "Wed Jun 17 2026 12:21:10"));
	track[0].push(new TrackPoint(35.246173, 139.127485, 25.093, 42, 0, 0, "Wed Jun 17 2026 12:21:57"));
	track[0].push(new TrackPoint(35.246069, 139.127509, 25.105, 42, 0, 0, "Wed Jun 17 2026 12:22:18"));
	track[0].push(new TrackPoint(35.245841, 139.127374, 25.133, 41, 0, 0, "Wed Jun 17 2026 12:22:39"));
	track[0].push(new TrackPoint(35.245712, 139.127258, 25.151, 41, 0, 0, "Wed Jun 17 2026 12:22:53"));
	track[0].push(new TrackPoint(35.245620, 139.127219, 25.162, 42, 0, 0, "Wed Jun 17 2026 12:23:03"));
	track[0].push(new TrackPoint(35.245580, 139.127231, 25.166, 42, 0, 0, "Wed Jun 17 2026 12:23:06"));
	track[0].push(new TrackPoint(35.245519, 139.127219, 25.173, 42, 0, 0, "Wed Jun 17 2026 12:23:11"));
	track[0].push(new TrackPoint(35.245451, 139.127152, 25.183, 42, 0, 0, "Wed Jun 17 2026 12:23:20"));
	track[0].push(new TrackPoint(35.245394, 139.127127, 25.190, 42, 0, 0, "Wed Jun 17 2026 12:23:25"));
	track[0].push(new TrackPoint(35.245199, 139.126897, 25.220, 45, 0, 0, "Wed Jun 17 2026 12:23:45"));
	track[0].push(new TrackPoint(35.245016, 139.126589, 25.255, 47, 0, 0, "Wed Jun 17 2026 12:24:13"));
	track[0].push(new TrackPoint(35.244955, 139.126513, 25.265, 47, 0, 0, "Wed Jun 17 2026 12:24:21"));
	track[0].push(new TrackPoint(35.244788, 139.126174, 25.301, 49, 0, 0, "Wed Jun 17 2026 12:24:44"));
	track[0].push(new TrackPoint(35.244423, 139.125601, 25.369, 60, 0, 0, "Wed Jun 17 2026 12:25:31"));
	track[0].push(new TrackPoint(35.244406, 139.125512, 25.378, 62, 0, 0, "Wed Jun 17 2026 12:25:38"));
	track[0].push(new TrackPoint(35.244361, 139.125415, 25.388, 64, 0, 0, "Wed Jun 17 2026 12:25:46"));
	track[0].push(new TrackPoint(35.244191, 139.125205, 25.416, 60, 0, 0, "Wed Jun 17 2026 12:26:07"));
	track[0].push(new TrackPoint(35.244124, 139.125146, 25.425, 57, 0, 0, "Wed Jun 17 2026 12:26:14"));
	track[0].push(new TrackPoint(35.243887, 139.124816, 25.465, 53, 0, 0, "Wed Jun 17 2026 12:26:43"));
	track[0].push(new TrackPoint(35.243761, 139.124594, 25.490, 54, 0, 0, "Wed Jun 17 2026 12:26:59"));
	track[0].push(new TrackPoint(35.243726, 139.124453, 25.504, 54, 0, 0, "Wed Jun 17 2026 12:27:07"));
	track[0].push(new TrackPoint(35.243667, 139.124304, 25.519, 55, 0, 0, "Wed Jun 17 2026 12:27:18"));
	track[0].push(new TrackPoint(35.243548, 139.124114, 25.541, 56, 0, 0, "Wed Jun 17 2026 12:27:36"));
	track[0].push(new TrackPoint(35.243495, 139.123861, 25.564, 58, 0, 0, "Wed Jun 17 2026 12:27:53"));
	track[0].push(new TrackPoint(35.243387, 139.123661, 25.586, 58, 0, 0, "Wed Jun 17 2026 12:28:09"));
	track[0].push(new TrackPoint(35.243335, 139.123605, 25.594, 57, 0, 0, "Wed Jun 17 2026 12:28:14"));
	track[0].push(new TrackPoint(35.243252, 139.123461, 25.610, 57, 0, 0, "Wed Jun 17 2026 12:28:26"));
	track[0].push(new TrackPoint(35.243210, 139.123294, 25.626, 59, 0, 0, "Wed Jun 17 2026 12:28:36"));
	track[0].push(new TrackPoint(35.243118, 139.123143, 25.643, 59, 0, 0, "Wed Jun 17 2026 12:28:48"));
	track[0].push(new TrackPoint(35.242970, 139.122805, 25.679, 61, 0, 0, "Wed Jun 17 2026 12:29:12"));
	track[0].push(new TrackPoint(35.242908, 139.122522, 25.705, 63, 0, 0, "Wed Jun 17 2026 12:29:28"));
	track[0].push(new TrackPoint(35.242863, 139.122433, 25.715, 63, 0, 0, "Wed Jun 17 2026 12:29:36"));
	track[0].push(new TrackPoint(35.242800, 139.122390, 25.723, 62, 0, 0, "Wed Jun 17 2026 12:29:43"));
	track[0].push(new TrackPoint(35.242544, 139.122121, 25.761, 60, 0, 0, "Wed Jun 17 2026 12:30:12"));
	track[0].push(new TrackPoint(35.242295, 139.121922, 25.796, 58, 0, 0, "Wed Jun 17 2026 12:31:42"));
	track[0].push(new TrackPoint(35.242062, 139.121783, 25.825, 57, 0, 0, "Wed Jun 17 2026 12:32:09"));
	track[0].push(new TrackPoint(35.241956, 139.121630, 25.843, 56, 0, 0, "Wed Jun 17 2026 12:32:27"));
	track[0].push(new TrackPoint(35.241632, 139.121247, 25.894, 57, 0, 0, "Wed Jun 17 2026 12:33:04"));
	track[0].push(new TrackPoint(35.241600, 139.121169, 25.901, 57, 0, 0, "Wed Jun 17 2026 12:33:09"));
	track[0].push(new TrackPoint(35.241184, 139.120777, 25.960, 61, 0, 0, "Wed Jun 17 2026 12:33:51"));
	track[0].push(new TrackPoint(35.241181, 139.120752, 25.963, 61, 0, 0, "Wed Jun 17 2026 12:33:53"));
	track[0].push(new TrackPoint(35.241030, 139.120658, 25.982, 62, 0, 0, "Wed Jun 17 2026 12:34:06"));
	track[0].push(new TrackPoint(35.240823, 139.120398, 26.015, 60, 0, 0, "Wed Jun 17 2026 12:34:30"));
	track[0].push(new TrackPoint(35.240594, 139.120226, 26.045, 57, 0, 0, "Wed Jun 17 2026 12:34:51"));
	track[0].push(new TrackPoint(35.240490, 139.120196, 26.057, 56, 0, 0, "Wed Jun 17 2026 12:35:00"));
	track[0].push(new TrackPoint(35.240368, 139.120190, 26.071, 56, 0, 0, "Wed Jun 17 2026 12:35:07"));
	track[0].push(new TrackPoint(35.240213, 139.120085, 26.091, 58, 0, 0, "Wed Jun 17 2026 12:35:17"));
	track[0].push(new TrackPoint(35.240080, 139.119904, 26.113, 61, 0, 0, "Wed Jun 17 2026 12:35:35"));
	track[0].push(new TrackPoint(35.240019, 139.119864, 26.121, 62, 0, 0, "Wed Jun 17 2026 12:35:42"));
	track[0].push(new TrackPoint(35.239780, 139.119546, 26.161, 64, 0, 0, "Wed Jun 17 2026 12:36:12"));
	track[0].push(new TrackPoint(35.239592, 139.119113, 26.206, 66, 0, 0, "Wed Jun 17 2026 12:36:49"));
	track[0].push(new TrackPoint(35.239477, 139.118928, 26.227, 67, 0, 0, "Wed Jun 17 2026 12:37:15"));
	track[0].push(new TrackPoint(35.239064, 139.118572, 26.284, 69, 0, 0, "Wed Jun 17 2026 12:38:09"));
	track[0].push(new TrackPoint(35.238883, 139.118326, 26.315, 74, 0, 0, "Wed Jun 17 2026 12:38:35"));
	track[0].push(new TrackPoint(35.238835, 139.118152, 26.332, 78, 0, 0, "Wed Jun 17 2026 12:39:00"));
	track[0].push(new TrackPoint(35.238743, 139.118069, 26.345, 78, 0, 0, "Wed Jun 17 2026 12:39:13"));
	track[0].push(new TrackPoint(35.238666, 139.118045, 26.354, 76, 0, 0, "Wed Jun 17 2026 12:39:20"));
	track[0].push(new TrackPoint(35.238461, 139.117873, 26.382, 73, 0, 0, "Wed Jun 17 2026 12:39:45"));
	track[0].push(new TrackPoint(35.238183, 139.117451, 26.431, 74, 0, 0, "Wed Jun 17 2026 12:40:30"));
	track[0].push(new TrackPoint(35.238035, 139.117048, 26.472, 79, 0, 0, "Wed Jun 17 2026 12:41:00"));
	track[0].push(new TrackPoint(35.238033, 139.117004, 26.476, 80, 0, 0, "Wed Jun 17 2026 12:41:07"));
	track[0].push(new TrackPoint(35.237803, 139.116613, 26.521, 76, 0, 0, "Wed Jun 17 2026 12:41:41"));
	track[0].push(new TrackPoint(35.237567, 139.116375, 26.556, 72, 0, 0, "Wed Jun 17 2026 12:42:06"));
	track[0].push(new TrackPoint(35.237506, 139.116286, 26.566, 71, 0, 0, "Wed Jun 17 2026 12:42:14"));
	track[0].push(new TrackPoint(35.237438, 139.116219, 26.576, 70, 0, 0, "Wed Jun 17 2026 12:42:21"));
	track[0].push(new TrackPoint(35.237152, 139.115731, 26.631, 73, 0, 0, "Wed Jun 17 2026 12:43:06"));
	track[0].push(new TrackPoint(35.237116, 139.115630, 26.642, 76, 0, 0, "Wed Jun 17 2026 12:43:15"));
	track[0].push(new TrackPoint(35.236988, 139.115460, 26.663, 79, 0, 0, "Wed Jun 17 2026 12:43:32"));
	track[0].push(new TrackPoint(35.236923, 139.115416, 26.671, 79, 0, 0, "Wed Jun 17 2026 12:43:39"));
	track[0].push(new TrackPoint(35.236856, 139.115307, 26.684, 80, 0, 0, "Wed Jun 17 2026 12:43:48"));
	track[0].push(new TrackPoint(35.236674, 139.115190, 26.707, 78, 0, 0, "Wed Jun 17 2026 12:44:06"));
	track[0].push(new TrackPoint(35.236621, 139.115122, 26.716, 79, 0, 0, "Wed Jun 17 2026 12:44:12"));
	track[0].push(new TrackPoint(35.236078, 139.114722, 26.786, 76, 0, 0, "Wed Jun 17 2026 12:45:07"));
	track[0].push(new TrackPoint(35.235952, 139.114556, 26.807, 77, 0, 0, "Wed Jun 17 2026 12:45:23"));
	track[0].push(new TrackPoint(35.235742, 139.114268, 26.842, 80, 0, 0, "Wed Jun 17 2026 12:45:53"));
	track[0].push(new TrackPoint(35.235429, 139.113996, 26.886, 83, 0, 0, "Wed Jun 17 2026 12:46:34"));
	track[0].push(new TrackPoint(35.235203, 139.113908, 26.912, 84, 0, 0, "Wed Jun 17 2026 12:46:58"));
	track[0].push(new TrackPoint(35.234974, 139.113737, 26.942, 85, 0, 0, "Wed Jun 17 2026 12:47:53"));
	track[0].push(new TrackPoint(35.234880, 139.113598, 26.959, 88, 0, 0, "Wed Jun 17 2026 12:48:03"));
	track[0].push(new TrackPoint(35.234830, 139.113476, 26.972, 90, 0, 0, "Wed Jun 17 2026 12:48:11"));
	track[0].push(new TrackPoint(35.234661, 139.113199, 27.003, 93, 0, 0, "Wed Jun 17 2026 12:48:32"));
	track[0].push(new TrackPoint(35.234579, 139.113126, 27.014, 92, 0, 0, "Wed Jun 17 2026 12:48:40"));
	track[0].push(new TrackPoint(35.234531, 139.113034, 27.024, 92, 0, 0, "Wed Jun 17 2026 12:48:48"));
	track[0].push(new TrackPoint(35.234463, 139.112952, 27.035, 91, 0, 0, "Wed Jun 17 2026 12:48:56"));
	track[0].push(new TrackPoint(35.234353, 139.112756, 27.057, 92, 0, 0, "Wed Jun 17 2026 12:49:14"));
	track[0].push(new TrackPoint(35.234164, 139.112309, 27.103, 92, 0, 0, "Wed Jun 17 2026 12:49:50"));
	track[0].push(new TrackPoint(35.234141, 139.112187, 27.114, 93, 0, 0, "Wed Jun 17 2026 12:49:58"));
	track[0].push(new TrackPoint(35.234106, 139.112133, 27.120, 92, 0, 0, "Wed Jun 17 2026 12:50:04"));
	track[0].push(new TrackPoint(35.233763, 139.110576, 27.268, 98, 0, 0, "Wed Jun 17 2026 12:51:58"));
	track[0].push(new TrackPoint(35.233694, 139.110103, 27.312, 98, 0, 0, "Wed Jun 17 2026 12:52:35"));
	track[0].push(new TrackPoint(35.233710, 139.109825, 27.337, 98, 0, 0, "Wed Jun 17 2026 12:52:54"));
	track[0].push(new TrackPoint(35.233688, 139.109558, 27.362, 96, 0, 0, "Wed Jun 17 2026 12:53:14"));
	track[0].push(new TrackPoint(35.233784, 139.109026, 27.412, 96, 0, 0, "Wed Jun 17 2026 12:53:47"));
	track[0].push(new TrackPoint(35.233856, 139.108789, 27.435, 95, 0, 0, "Wed Jun 17 2026 12:53:58"));
	track[0].push(new TrackPoint(35.233801, 139.108727, 27.444, 93, 0, 0, "Wed Jun 17 2026 12:54:05"));
	track[0].push(new TrackPoint(35.233569, 139.108697, 27.470, 89, 0, 0, "Wed Jun 17 2026 12:54:27"));
	track[0].push(new TrackPoint(35.233053, 139.108525, 27.530, 87, 0, 0, "Wed Jun 17 2026 12:55:18"));
	track[0].push(new TrackPoint(35.232940, 139.108547, 27.543, 87, 0, 0, "Wed Jun 17 2026 12:55:29"));
	track[0].push(new TrackPoint(35.232619, 139.108692, 27.581, 88, 0, 0, "Wed Jun 17 2026 12:56:03"));
	track[0].push(new TrackPoint(35.232545, 139.108692, 27.589, 88, 0, 0, "Wed Jun 17 2026 12:56:09"));
	track[0].push(new TrackPoint(35.232446, 139.108660, 27.600, 88, 0, 0, "Wed Jun 17 2026 12:56:17"));
	track[0].push(new TrackPoint(35.232331, 139.108587, 27.617, 89, 0, 0, "Wed Jun 17 2026 12:57:32"));
	track[0].push(new TrackPoint(35.232465, 139.108370, 27.642, 90, 0, 0, "Wed Jun 17 2026 12:58:46"));
	track[0].push(new TrackPoint(35.232509, 139.108326, 27.649, 91, 0, 0, "Wed Jun 17 2026 12:58:51"));
	track[0].push(new TrackPoint(35.232618, 139.108148, 27.669, 92, 0, 0, "Wed Jun 17 2026 12:59:06"));
	track[0].push(new TrackPoint(35.232642, 139.108079, 27.676, 92, 0, 0, "Wed Jun 17 2026 12:59:13"));
	track[0].push(new TrackPoint(35.232651, 139.107977, 27.685, 93, 0, 0, "Wed Jun 17 2026 12:59:21"));
	track[0].push(new TrackPoint(35.232734, 139.107739, 27.709, 93, 0, 0, "Wed Jun 17 2026 12:59:40"));
	track[0].push(new TrackPoint(35.232731, 139.107664, 27.716, 94, 0, 0, "Wed Jun 17 2026 12:59:45"));
	track[0].push(new TrackPoint(35.232684, 139.107508, 27.732, 95, 0, 0, "Wed Jun 17 2026 12:59:57"));
	track[0].push(new TrackPoint(35.232713, 139.107429, 27.740, 95, 0, 0, "Wed Jun 17 2026 13:00:03"));
	track[0].push(new TrackPoint(35.232754, 139.107207, 27.761, 95, 0, 0, "Wed Jun 17 2026 13:00:20"));
	track[0].push(new TrackPoint(35.232696, 139.106716, 27.806, 99, 0, 0, "Wed Jun 17 2026 13:00:58"));
	track[0].push(new TrackPoint(35.232705, 139.106641, 27.813, 99, 0, 0, "Wed Jun 17 2026 13:01:04"));
	track[0].push(new TrackPoint(35.232676, 139.106294, 27.846, 102, 0, 0, "Wed Jun 17 2026 13:01:31"));
	track[0].push(new TrackPoint(35.232696, 139.106103, 27.864, 102, 0, 0, "Wed Jun 17 2026 13:01:45"));
	track[0].push(new TrackPoint(35.232720, 139.105690, 27.904, 100, 0, 0, "Wed Jun 17 2026 13:02:17"));
	track[0].push(new TrackPoint(35.232804, 139.105519, 27.922, 98, 0, 0, "Wed Jun 17 2026 13:02:33"));
	track[0].push(new TrackPoint(35.233577, 139.105038, 28.020, 97, 0, 0, "Wed Jun 17 2026 13:03:48"));
	track[0].push(new TrackPoint(35.233606, 139.104976, 28.027, 99, 0, 0, "Wed Jun 17 2026 13:03:54"));
	track[0].push(new TrackPoint(35.233469, 139.104605, 28.064, 98, 0, 0, "Wed Jun 17 2026 13:04:26"));
	track[0].push(new TrackPoint(35.233431, 139.104587, 28.069, 98, 0, 0, "Wed Jun 17 2026 13:05:32"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
	var count = 0;
	for (i=0; i<track.length; i++) {
		count += track[i].length;
	}

	if (count > 1 && !playing) {
		centerPointer.addTo(map);

		if (showMeterPanel) {
			infoPanel = new InfoPanel();
			map.addControl(infoPanel);
		}

		playing = true;
		goForward();
	}
}

function goForward() {
	var waittime;
	var pos = track[currTrack][currPoint].latlng;
	map.panTo(pos);
	centerPointer.setLatLng(pos);

	if (showMeterPanel) {
		displayInfoPanel(currTrack, currPoint);
	}

	if (currPoint < track[currTrack].length - 1) {
		if (realTimePlay) {
			waittime = track[currTrack][currPoint+1].time.getTime() - track[currTrack][currPoint].time.getTime();
			waittime /= parseFloat(document.getElementById("playSpeed").value);
		}
		else {
			waittime = 1000 / parseFloat(document.getElementById("playSpeed").value);
		}
		currPoint++;
	}
	else {
		if (currTrack < track.length - 1) {
			waittime = 1000;
			currTrack++;
			currPoint = 0;
		}
		else {
			window.clearTimeout(playTimer);
			playing = false;
			centerPointer.remove();

			if (showMeterPanel) {
				map.removeControl(infoPanel);
			}

			return;
		}
	}
	playTimer = window.setTimeout("goForward()", waittime);
}

function stopRoute() {
	if (playing) {
		window.clearTimeout(playTimer);
		playing = false;
		centerPointer.remove();

		if (showMeterPanel) {
			map.removeControl(infoPanel);
		}
	}
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
