// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([35.528194, 139.700287], [35.684410, 139.775763]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "0517_files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(35.684410, 139.774414, 40, "2026/05/17", "07:25:56", 0, "五街道の起点「日本国道路元標」", "0517_files/IMG_20260517_072556.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.679012, 139.771439, 130, "2026/05/17", "07:39:32", 0, "銀座の不思議なオブジェ", "0517_files/IMG_20260517_073932_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.623932, 139.739120, 45, "2026/05/17", "08:51:47", 0, "品川宿", "0517_files/IMG_20260517_085147.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.535953, 139.708420, 38, "2026/05/17", "10:49:42", 0, "武州六郷船渡図", "0517_files/IMG_20260517_104942_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.535923, 139.708450, 37, "2026/05/17", "10:49:49", 0, "六郷の渡し跡", "0517_files/IMG_20260517_104949_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.535683, 139.707748, 44, "2026/05/17", "10:52:24", 0, "六郷の渡しと旅籠街の案内", "0517_files/IMG_20260517_105224_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.528194, 139.700287, 68, "2026/05/17", "11:12:17", 0, "川崎宿", "0517_files/IMG_20260517_111217_1.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(35.684158, 139.775746, 0.000, 16, 0, 0, "Sun May 17 2026 07:32:37"));
	track[0].push(new TrackPoint(35.684091, 139.775763, 0.008, 16, 0, 0, "Sun May 17 2026 07:32:44"));
	track[0].push(new TrackPoint(35.684121, 139.775425, 0.039, 15, 0, 0, "Sun May 17 2026 07:33:10"));
	track[0].push(new TrackPoint(35.683953, 139.775236, 0.065, 14, 0, 0, "Sun May 17 2026 07:33:37"));
	track[0].push(new TrackPoint(35.683960, 139.775220, 0.067, 14, 0, 0, "Sun May 17 2026 07:33:46"));
	track[0].push(new TrackPoint(35.683751, 139.774934, 0.102, 15, 0, 0, "Sun May 17 2026 07:34:01"));
	track[0].push(new TrackPoint(35.683643, 139.774716, 0.125, 16, 0, 0, "Sun May 17 2026 07:34:13"));
	track[0].push(new TrackPoint(35.683592, 139.774355, 0.158, 18, 0, 0, "Sun May 17 2026 07:34:21"));
	track[0].push(new TrackPoint(35.683572, 139.774288, 0.164, 19, 0, 0, "Sun May 17 2026 07:34:41"));
	track[0].push(new TrackPoint(35.683588, 139.774252, 0.168, 19, 0, 0, "Sun May 17 2026 07:34:56"));
	track[0].push(new TrackPoint(35.683384, 139.774136, 0.193, 20, 0, 0, "Sun May 17 2026 07:35:14"));
	track[0].push(new TrackPoint(35.683055, 139.774043, 0.231, 25, 0, 0, "Sun May 17 2026 07:35:31"));
	track[0].push(new TrackPoint(35.682708, 139.773829, 0.276, 32, 0, 0, "Sun May 17 2026 07:35:52"));
	track[0].push(new TrackPoint(35.682704, 139.773765, 0.282, 33, 0, 0, "Sun May 17 2026 07:35:54"));
	track[0].push(new TrackPoint(35.682648, 139.773713, 0.290, 33, 0, 0, "Sun May 17 2026 07:35:57"));
	track[0].push(new TrackPoint(35.682504, 139.773626, 0.307, 34, 0, 0, "Sun May 17 2026 07:36:05"));
	track[0].push(new TrackPoint(35.682347, 139.773609, 0.325, 31, 0, 0, "Sun May 17 2026 07:36:13"));
	track[0].push(new TrackPoint(35.682169, 139.773413, 0.352, 30, 0, 0, "Sun May 17 2026 07:36:25"));
	track[0].push(new TrackPoint(35.682037, 139.773350, 0.368, 28, 0, 0, "Sun May 17 2026 07:36:32"));
	track[0].push(new TrackPoint(35.681962, 139.773356, 0.376, 28, 0, 0, "Sun May 17 2026 07:36:36"));
	track[0].push(new TrackPoint(35.681883, 139.773304, 0.386, 28, 0, 0, "Sun May 17 2026 07:36:41"));
	track[0].push(new TrackPoint(35.681776, 139.773308, 0.398, 28, 0, 0, "Sun May 17 2026 07:36:46"));
	track[0].push(new TrackPoint(35.681630, 139.773174, 0.419, 29, 0, 0, "Sun May 17 2026 07:36:56"));
	track[0].push(new TrackPoint(35.681611, 139.773119, 0.424, 29, 0, 0, "Sun May 17 2026 07:36:58"));
	track[0].push(new TrackPoint(35.681442, 139.772974, 0.447, 30, 0, 0, "Sun May 17 2026 07:37:09"));
	track[0].push(new TrackPoint(35.681381, 139.772957, 0.454, 30, 0, 0, "Sun May 17 2026 07:37:12"));
	track[0].push(new TrackPoint(35.681211, 139.772827, 0.476, 29, 0, 0, "Sun May 17 2026 07:37:22"));
	track[0].push(new TrackPoint(35.681015, 139.772708, 0.501, 27, 0, 0, "Sun May 17 2026 07:37:35"));
	track[0].push(new TrackPoint(35.680898, 139.772549, 0.520, 27, 0, 0, "Sun May 17 2026 07:37:44"));
	track[0].push(new TrackPoint(35.680731, 139.772457, 0.541, 25, 0, 0, "Sun May 17 2026 07:37:54"));
	track[0].push(new TrackPoint(35.680663, 139.772440, 0.549, 24, 0, 0, "Sun May 17 2026 07:37:58"));
	track[0].push(new TrackPoint(35.680628, 139.772406, 0.554, 24, 0, 0, "Sun May 17 2026 07:38:00"));
	track[0].push(new TrackPoint(35.680545, 139.772366, 0.564, 24, 0, 0, "Sun May 17 2026 07:38:05"));
	track[0].push(new TrackPoint(35.680334, 139.772340, 0.587, 26, 0, 0, "Sun May 17 2026 07:38:17"));
	track[0].push(new TrackPoint(35.680159, 139.772225, 0.610, 25, 0, 0, "Sun May 17 2026 07:38:28"));
	track[0].push(new TrackPoint(35.680041, 139.772171, 0.624, 24, 0, 0, "Sun May 17 2026 07:38:36"));
	track[0].push(new TrackPoint(35.679791, 139.771985, 0.656, 21, 0, 0, "Sun May 17 2026 07:38:53"));
	track[0].push(new TrackPoint(35.679703, 139.771956, 0.666, 22, 0, 0, "Sun May 17 2026 07:38:59"));
	track[0].push(new TrackPoint(35.679460, 139.771699, 0.702, 20, 0, 0, "Sun May 17 2026 07:39:25"));
	track[0].push(new TrackPoint(35.679460, 139.771669, 0.705, 20, 0, 0, "Sun May 17 2026 07:39:59"));
	track[0].push(new TrackPoint(35.679404, 139.771605, 0.714, 21, 0, 0, "Sun May 17 2026 07:40:10"));
	track[0].push(new TrackPoint(35.679114, 139.771566, 0.746, 22, 0, 0, "Sun May 17 2026 07:40:27"));
	track[0].push(new TrackPoint(35.678659, 139.771395, 0.799, 22, 0, 0, "Sun May 17 2026 07:40:50"));
	track[0].push(new TrackPoint(35.678257, 139.771060, 0.854, 20, 0, 0, "Sun May 17 2026 07:41:16"));
	track[0].push(new TrackPoint(35.677935, 139.770780, 0.899, 21, 0, 0, "Sun May 17 2026 07:41:44"));
	track[0].push(new TrackPoint(35.677814, 139.770741, 0.913, 24, 0, 0, "Sun May 17 2026 07:42:13"));
	track[0].push(new TrackPoint(35.677709, 139.770639, 0.928, 23, 0, 0, "Sun May 17 2026 07:42:21"));
	track[0].push(new TrackPoint(35.677367, 139.770472, 0.969, 23, 0, 0, "Sun May 17 2026 07:42:41"));
	track[0].push(new TrackPoint(35.677220, 139.770338, 0.990, 22, 0, 0, "Sun May 17 2026 07:42:50"));
	track[0].push(new TrackPoint(35.677063, 139.770259, 1.009, 21, 0, 0, "Sun May 17 2026 07:42:59"));
	track[0].push(new TrackPoint(35.676672, 139.770068, 1.056, 20, 0, 0, "Sun May 17 2026 07:43:24"));
	track[0].push(new TrackPoint(35.676562, 139.770039, 1.070, 19, 0, 0, "Sun May 17 2026 07:43:34"));
	track[0].push(new TrackPoint(35.676457, 139.769872, 1.089, 20, 0, 0, "Sun May 17 2026 07:43:46"));
	track[0].push(new TrackPoint(35.676374, 139.769797, 1.100, 20, 0, 0, "Sun May 17 2026 07:43:59"));
	track[0].push(new TrackPoint(35.676363, 139.769753, 1.106, 21, 0, 0, "Sun May 17 2026 07:44:16"));
	track[0].push(new TrackPoint(35.676188, 139.769604, 1.130, 20, 0, 0, "Sun May 17 2026 07:44:39"));
	track[0].push(new TrackPoint(35.675991, 139.769535, 1.152, 20, 0, 0, "Sun May 17 2026 07:44:50"));
	track[0].push(new TrackPoint(35.675927, 139.769492, 1.161, 20, 0, 0, "Sun May 17 2026 07:44:54"));
	track[0].push(new TrackPoint(35.675847, 139.769489, 1.170, 20, 0, 0, "Sun May 17 2026 07:44:58"));
	track[0].push(new TrackPoint(35.675448, 139.769319, 1.216, 19, 0, 0, "Sun May 17 2026 07:45:20"));
	track[0].push(new TrackPoint(35.675214, 139.769114, 1.248, 19, 0, 0, "Sun May 17 2026 07:45:36"));
	track[0].push(new TrackPoint(35.675083, 139.769109, 1.263, 19, 0, 0, "Sun May 17 2026 07:45:44"));
	track[0].push(new TrackPoint(35.675017, 139.769128, 1.270, 19, 0, 0, "Sun May 17 2026 07:45:49"));
	track[0].push(new TrackPoint(35.674912, 139.769057, 1.284, 21, 0, 0, "Sun May 17 2026 07:45:58"));
	track[0].push(new TrackPoint(35.674855, 139.768931, 1.297, 22, 0, 0, "Sun May 17 2026 07:46:05"));
	track[0].push(new TrackPoint(35.674688, 139.768676, 1.327, 25, 0, 0, "Sun May 17 2026 07:46:20"));
	track[0].push(new TrackPoint(35.674601, 139.768602, 1.339, 26, 0, 0, "Sun May 17 2026 07:46:26"));
	track[0].push(new TrackPoint(35.674428, 139.768418, 1.364, 26, 0, 0, "Sun May 17 2026 07:46:39"));
	track[0].push(new TrackPoint(35.674088, 139.768106, 1.412, 25, 0, 0, "Sun May 17 2026 07:47:02"));
	track[0].push(new TrackPoint(35.674031, 139.768071, 1.419, 26, 0, 0, "Sun May 17 2026 07:47:05"));
	track[0].push(new TrackPoint(35.673814, 139.767817, 1.452, 25, 0, 0, "Sun May 17 2026 07:47:19"));
	track[0].push(new TrackPoint(35.673396, 139.767296, 1.518, 26, 0, 0, "Sun May 17 2026 07:47:54"));
	track[0].push(new TrackPoint(35.672941, 139.766972, 1.578, 25, 0, 0, "Sun May 17 2026 07:49:07"));
	track[0].push(new TrackPoint(35.672738, 139.766696, 1.612, 27, 0, 0, "Sun May 17 2026 07:49:26"));
	track[0].push(new TrackPoint(35.672643, 139.766530, 1.630, 26, 0, 0, "Sun May 17 2026 07:49:34"));
	track[0].push(new TrackPoint(35.672460, 139.766366, 1.656, 26, 0, 0, "Sun May 17 2026 07:49:46"));
	track[0].push(new TrackPoint(35.671952, 139.765860, 1.728, 28, 0, 0, "Sun May 17 2026 07:50:21"));
	track[0].push(new TrackPoint(35.671685, 139.765530, 1.771, 29, 0, 0, "Sun May 17 2026 07:50:43"));
	track[0].push(new TrackPoint(35.671615, 139.765472, 1.780, 28, 0, 0, "Sun May 17 2026 07:50:50"));
	track[0].push(new TrackPoint(35.671483, 139.765319, 1.801, 27, 0, 0, "Sun May 17 2026 07:51:05"));
	track[0].push(new TrackPoint(35.671426, 139.765276, 1.808, 26, 0, 0, "Sun May 17 2026 07:51:12"));
	track[0].push(new TrackPoint(35.671343, 139.765130, 1.825, 25, 0, 0, "Sun May 17 2026 07:51:20"));
	track[0].push(new TrackPoint(35.671243, 139.764995, 1.841, 24, 0, 0, "Sun May 17 2026 07:51:28"));
	track[0].push(new TrackPoint(35.671117, 139.764878, 1.859, 24, 0, 0, "Sun May 17 2026 07:51:37"));
	track[0].push(new TrackPoint(35.671047, 139.764912, 1.867, 24, 0, 0, "Sun May 17 2026 07:51:43"));
	track[0].push(new TrackPoint(35.671011, 139.764787, 1.880, 25, 0, 0, "Sun May 17 2026 07:51:49"));
	track[0].push(new TrackPoint(35.670899, 139.764725, 1.893, 25, 0, 0, "Sun May 17 2026 07:51:56"));
	track[0].push(new TrackPoint(35.670754, 139.764593, 1.913, 24, 0, 0, "Sun May 17 2026 07:52:04"));
	track[0].push(new TrackPoint(35.670651, 139.764449, 1.931, 24, 0, 0, "Sun May 17 2026 07:52:11"));
	track[0].push(new TrackPoint(35.670500, 139.764382, 1.949, 24, 0, 0, "Sun May 17 2026 07:52:19"));
	track[0].push(new TrackPoint(35.670388, 139.764295, 1.963, 24, 0, 0, "Sun May 17 2026 07:52:26"));
	track[0].push(new TrackPoint(35.670195, 139.764051, 1.994, 23, 0, 0, "Sun May 17 2026 07:52:40"));
	track[0].push(new TrackPoint(35.669894, 139.763826, 2.034, 20, 0, 0, "Sun May 17 2026 07:53:00"));
	track[0].push(new TrackPoint(35.669663, 139.763504, 2.073, 19, 0, 0, "Sun May 17 2026 07:53:18"));
	track[0].push(new TrackPoint(35.669419, 139.763269, 2.107, 21, 0, 0, "Sun May 17 2026 07:53:35"));
	track[0].push(new TrackPoint(35.669242, 139.762971, 2.141, 24, 0, 0, "Sun May 17 2026 07:53:51"));
	track[0].push(new TrackPoint(35.669023, 139.762742, 2.173, 26, 0, 0, "Sun May 17 2026 07:54:07"));
	track[0].push(new TrackPoint(35.668819, 139.762635, 2.197, 25, 0, 0, "Sun May 17 2026 07:54:21"));
	track[0].push(new TrackPoint(35.668783, 139.762636, 2.201, 25, 0, 0, "Sun May 17 2026 07:54:23"));
	track[0].push(new TrackPoint(35.668743, 139.762547, 2.211, 24, 0, 0, "Sun May 17 2026 07:54:28"));
	track[0].push(new TrackPoint(35.668424, 139.762176, 2.260, 22, 0, 0, "Sun May 17 2026 07:54:53"));
	track[0].push(new TrackPoint(35.668272, 139.762068, 2.279, 24, 0, 0, "Sun May 17 2026 07:55:04"));
	track[0].push(new TrackPoint(35.668168, 139.761895, 2.299, 27, 0, 0, "Sun May 17 2026 07:55:13"));
	track[0].push(new TrackPoint(35.667776, 139.761533, 2.354, 31, 0, 0, "Sun May 17 2026 07:55:42"));
	track[0].push(new TrackPoint(35.667714, 139.761448, 2.364, 32, 0, 0, "Sun May 17 2026 07:55:49"));
	track[0].push(new TrackPoint(35.667672, 139.761457, 2.369, 31, 0, 0, "Sun May 17 2026 07:55:53"));
	track[0].push(new TrackPoint(35.667578, 139.761363, 2.383, 31, 0, 0, "Sun May 17 2026 07:56:10"));
	track[0].push(new TrackPoint(35.667597, 139.761357, 2.385, 31, 0, 0, "Sun May 17 2026 07:56:27"));
	track[0].push(new TrackPoint(35.667524, 139.761216, 2.405, 31, 0, 0, "Sun May 17 2026 07:56:46"));
	track[0].push(new TrackPoint(35.667413, 139.761165, 2.418, 29, 0, 0, "Sun May 17 2026 07:56:52"));
	track[0].push(new TrackPoint(35.667200, 139.760969, 2.448, 26, 0, 0, "Sun May 17 2026 07:57:06"));
	track[0].push(new TrackPoint(35.666935, 139.760850, 2.480, 24, 0, 0, "Sun May 17 2026 07:57:18"));
	track[0].push(new TrackPoint(35.666842, 139.760527, 2.511, 22, 0, 0, "Sun May 17 2026 07:57:32"));
	track[0].push(new TrackPoint(35.666827, 139.760522, 2.512, 22, 0, 0, "Sun May 17 2026 07:57:35"));
	track[0].push(new TrackPoint(35.666814, 139.760479, 2.517, 22, 0, 0, "Sun May 17 2026 07:57:37"));
	track[0].push(new TrackPoint(35.666740, 139.760376, 2.529, 22, 0, 0, "Sun May 17 2026 07:57:42"));
	track[0].push(new TrackPoint(35.666622, 139.760279, 2.545, 23, 0, 0, "Sun May 17 2026 07:57:49"));
	track[0].push(new TrackPoint(35.666579, 139.760267, 2.550, 24, 0, 0, "Sun May 17 2026 07:57:51"));
	track[0].push(new TrackPoint(35.666526, 139.760180, 2.560, 25, 0, 0, "Sun May 17 2026 07:57:55"));
	track[0].push(new TrackPoint(35.666400, 139.760123, 2.575, 27, 0, 0, "Sun May 17 2026 07:58:01"));
	track[0].push(new TrackPoint(35.666307, 139.760057, 2.587, 28, 0, 0, "Sun May 17 2026 07:58:07"));
	track[0].push(new TrackPoint(35.666184, 139.759897, 2.607, 28, 0, 0, "Sun May 17 2026 07:58:15"));
	track[0].push(new TrackPoint(35.665756, 139.759567, 2.663, 24, 0, 0, "Sun May 17 2026 07:58:46"));
	track[0].push(new TrackPoint(35.665737, 139.759568, 2.665, 24, 0, 0, "Sun May 17 2026 07:58:49"));
	track[0].push(new TrackPoint(35.665693, 139.759647, 2.675, 24, 0, 0, "Sun May 17 2026 07:59:29"));
	track[0].push(new TrackPoint(35.665629, 139.759645, 2.685, 24, 0, 0, "Sun May 17 2026 08:00:03"));
	track[0].push(new TrackPoint(35.665396, 139.759472, 2.716, 24, 0, 0, "Sun May 17 2026 08:00:17"));
	track[0].push(new TrackPoint(35.665269, 139.759255, 2.740, 20, 0, 0, "Sun May 17 2026 08:00:26"));
	track[0].push(new TrackPoint(35.665064, 139.759200, 2.764, 18, 0, 0, "Sun May 17 2026 08:00:37"));
	track[0].push(new TrackPoint(35.664894, 139.759067, 2.787, 15, 0, 0, "Sun May 17 2026 08:00:45"));
	track[0].push(new TrackPoint(35.664840, 139.758908, 2.802, 13, 0, 0, "Sun May 17 2026 08:00:50"));
	track[0].push(new TrackPoint(35.664653, 139.758772, 2.826, 13, 0, 0, "Sun May 17 2026 08:01:02"));
	track[0].push(new TrackPoint(35.664501, 139.758747, 2.843, 12, 0, 0, "Sun May 17 2026 08:01:11"));
	track[0].push(new TrackPoint(35.664455, 139.758757, 2.849, 12, 0, 0, "Sun May 17 2026 08:01:18"));
	track[0].push(new TrackPoint(35.664476, 139.758713, 2.854, 12, 0, 0, "Sun May 17 2026 08:01:23"));
	track[0].push(new TrackPoint(35.664361, 139.758666, 2.867, 12, 0, 0, "Sun May 17 2026 08:01:32"));
	track[0].push(new TrackPoint(35.664221, 139.758548, 2.886, 12, 0, 0, "Sun May 17 2026 08:01:39"));
	track[0].push(new TrackPoint(35.664099, 139.758395, 2.905, 13, 0, 0, "Sun May 17 2026 08:01:45"));
	track[0].push(new TrackPoint(35.664013, 139.758266, 2.921, 14, 0, 0, "Sun May 17 2026 08:01:50"));
	track[0].push(new TrackPoint(35.663955, 139.758117, 2.936, 14, 0, 0, "Sun May 17 2026 08:01:55"));
	track[0].push(new TrackPoint(35.663921, 139.758101, 2.940, 14, 0, 0, "Sun May 17 2026 08:01:57"));
	track[0].push(new TrackPoint(35.663869, 139.758032, 2.949, 14, 0, 0, "Sun May 17 2026 08:02:01"));
	track[0].push(new TrackPoint(35.663852, 139.757815, 2.968, 14, 0, 0, "Sun May 17 2026 08:02:06"));
	track[0].push(new TrackPoint(35.663806, 139.757762, 2.976, 14, 0, 0, "Sun May 17 2026 08:02:34"));
	track[0].push(new TrackPoint(35.663506, 139.757603, 3.012, 13, 0, 0, "Sun May 17 2026 08:02:49"));
	track[0].push(new TrackPoint(35.663388, 139.757560, 3.026, 13, 0, 0, "Sun May 17 2026 08:02:56"));
	track[0].push(new TrackPoint(35.663222, 139.757450, 3.047, 15, 0, 0, "Sun May 17 2026 08:03:06"));
	track[0].push(new TrackPoint(35.663011, 139.757367, 3.072, 18, 0, 0, "Sun May 17 2026 08:03:18"));
	track[0].push(new TrackPoint(35.662733, 139.757121, 3.110, 21, 0, 0, "Sun May 17 2026 08:03:37"));
	track[0].push(new TrackPoint(35.662565, 139.756925, 3.136, 22, 0, 0, "Sun May 17 2026 08:03:49"));
	track[0].push(new TrackPoint(35.662365, 139.756823, 3.160, 20, 0, 0, "Sun May 17 2026 08:04:01"));
	track[0].push(new TrackPoint(35.662221, 139.756720, 3.178, 19, 0, 0, "Sun May 17 2026 08:04:10"));
	track[0].push(new TrackPoint(35.662096, 139.756685, 3.193, 19, 0, 0, "Sun May 17 2026 08:04:17"));
	track[0].push(new TrackPoint(35.661995, 139.756568, 3.208, 19, 0, 0, "Sun May 17 2026 08:04:24"));
	track[0].push(new TrackPoint(35.661881, 139.756484, 3.223, 19, 0, 0, "Sun May 17 2026 08:04:31"));
	track[0].push(new TrackPoint(35.661642, 139.756235, 3.258, 21, 0, 0, "Sun May 17 2026 08:04:51"));
	track[0].push(new TrackPoint(35.661381, 139.756081, 3.290, 24, 0, 0, "Sun May 17 2026 08:05:08"));
	track[0].push(new TrackPoint(35.661338, 139.756075, 3.295, 24, 0, 0, "Sun May 17 2026 08:05:10"));
	track[0].push(new TrackPoint(35.661271, 139.755993, 3.306, 23, 0, 0, "Sun May 17 2026 08:05:15"));
	track[0].push(new TrackPoint(35.661001, 139.755756, 3.343, 22, 0, 0, "Sun May 17 2026 08:05:32"));
	track[0].push(new TrackPoint(35.660626, 139.755453, 3.394, 26, 0, 0, "Sun May 17 2026 08:05:57"));
	track[0].push(new TrackPoint(35.660546, 139.755340, 3.407, 26, 0, 0, "Sun May 17 2026 08:06:03"));
	track[0].push(new TrackPoint(35.660360, 139.755198, 3.432, 24, 0, 0, "Sun May 17 2026 08:06:21"));
	track[0].push(new TrackPoint(35.660294, 139.755068, 3.448, 22, 0, 0, "Sun May 17 2026 08:07:15"));
	track[0].push(new TrackPoint(35.660193, 139.755048, 3.459, 22, 0, 0, "Sun May 17 2026 08:07:22"));
	track[0].push(new TrackPoint(35.660132, 139.755056, 3.466, 23, 0, 0, "Sun May 17 2026 08:07:25"));
	track[0].push(new TrackPoint(35.660005, 139.755122, 3.482, 24, 0, 0, "Sun May 17 2026 08:07:32"));
	track[0].push(new TrackPoint(35.659774, 139.755147, 3.508, 24, 0, 0, "Sun May 17 2026 08:07:44"));
	track[0].push(new TrackPoint(35.659513, 139.755255, 3.538, 25, 0, 0, "Sun May 17 2026 08:07:56"));
	track[0].push(new TrackPoint(35.659190, 139.755242, 3.574, 24, 0, 0, "Sun May 17 2026 08:08:13"));
	track[0].push(new TrackPoint(35.658848, 139.755223, 3.613, 24, 0, 0, "Sun May 17 2026 08:08:33"));
	track[0].push(new TrackPoint(35.658422, 139.755121, 3.662, 26, 0, 0, "Sun May 17 2026 08:09:25"));
	track[0].push(new TrackPoint(35.657766, 139.755106, 3.735, 19, 0, 0, "Sun May 17 2026 08:09:58"));
	track[0].push(new TrackPoint(35.657693, 139.755089, 3.743, 17, 0, 0, "Sun May 17 2026 08:10:02"));
	track[0].push(new TrackPoint(35.657611, 139.755012, 3.755, 16, 0, 0, "Sun May 17 2026 08:10:07"));
	track[0].push(new TrackPoint(35.657387, 139.754904, 3.782, 13, 0, 0, "Sun May 17 2026 08:10:21"));
	track[0].push(new TrackPoint(35.657162, 139.754959, 3.808, 11, 0, 0, "Sun May 17 2026 08:10:34"));
	track[0].push(new TrackPoint(35.656991, 139.754922, 3.827, 12, 0, 0, "Sun May 17 2026 08:10:43"));
	track[0].push(new TrackPoint(35.656738, 139.754751, 3.860, 17, 0, 0, "Sun May 17 2026 08:10:57"));
	track[0].push(new TrackPoint(35.656457, 139.754670, 3.892, 18, 0, 0, "Sun May 17 2026 08:11:13"));
	track[0].push(new TrackPoint(35.655885, 139.754697, 3.956, 20, 0, 0, "Sun May 17 2026 08:11:44"));
	track[0].push(new TrackPoint(35.655849, 139.754686, 3.960, 20, 0, 0, "Sun May 17 2026 08:11:46"));
	track[0].push(new TrackPoint(35.655567, 139.754728, 3.992, 23, 0, 0, "Sun May 17 2026 08:12:01"));
	track[0].push(new TrackPoint(35.655326, 139.754693, 4.019, 24, 0, 0, "Sun May 17 2026 08:12:15"));
	track[0].push(new TrackPoint(35.654878, 139.754645, 4.069, 29, 0, 0, "Sun May 17 2026 08:12:39"));
	track[0].push(new TrackPoint(35.654681, 139.754504, 4.094, 30, 0, 0, "Sun May 17 2026 08:12:51"));
	track[0].push(new TrackPoint(35.654574, 139.754471, 4.107, 29, 0, 0, "Sun May 17 2026 08:12:58"));
	track[0].push(new TrackPoint(35.654483, 139.754487, 4.117, 29, 0, 0, "Sun May 17 2026 08:13:03"));
	track[0].push(new TrackPoint(35.654188, 139.754443, 4.150, 28, 0, 0, "Sun May 17 2026 08:13:20"));
	track[0].push(new TrackPoint(35.653888, 139.754490, 4.183, 27, 0, 0, "Sun May 17 2026 08:13:36"));
	track[0].push(new TrackPoint(35.653578, 139.754432, 4.218, 25, 0, 0, "Sun May 17 2026 08:13:53"));
	track[0].push(new TrackPoint(35.653496, 139.754390, 4.228, 23, 0, 0, "Sun May 17 2026 08:14:01"));
	track[0].push(new TrackPoint(35.653426, 139.754287, 4.241, 23, 0, 0, "Sun May 17 2026 08:14:10"));
	track[0].push(new TrackPoint(35.653314, 139.754241, 4.254, 21, 0, 0, "Sun May 17 2026 08:14:17"));
	track[0].push(new TrackPoint(35.653213, 139.754125, 4.269, 21, 0, 0, "Sun May 17 2026 08:14:25"));
	track[0].push(new TrackPoint(35.653047, 139.754069, 4.289, 21, 0, 0, "Sun May 17 2026 08:14:38"));
	track[0].push(new TrackPoint(35.652817, 139.754038, 4.315, 23, 0, 0, "Sun May 17 2026 08:14:50"));
	track[0].push(new TrackPoint(35.652664, 139.754054, 4.332, 25, 0, 0, "Sun May 17 2026 08:14:56"));
	track[0].push(new TrackPoint(35.652638, 139.754077, 4.335, 25, 0, 0, "Sun May 17 2026 08:14:57"));
	track[0].push(new TrackPoint(35.652357, 139.754130, 4.367, 28, 0, 0, "Sun May 17 2026 08:15:09"));
	track[0].push(new TrackPoint(35.652202, 139.754129, 4.384, 29, 0, 0, "Sun May 17 2026 08:15:17"));
	track[0].push(new TrackPoint(35.651986, 139.754160, 4.409, 28, 0, 0, "Sun May 17 2026 08:15:29"));
	track[0].push(new TrackPoint(35.651623, 139.754166, 4.450, 20, 0, 0, "Sun May 17 2026 08:15:47"));
	track[0].push(new TrackPoint(35.651360, 139.754151, 4.479, 22, 0, 0, "Sun May 17 2026 08:16:02"));
	track[0].push(new TrackPoint(35.651126, 139.754061, 4.507, 28, 0, 0, "Sun May 17 2026 08:16:15"));
	track[0].push(new TrackPoint(35.651059, 139.754021, 4.515, 30, 0, 0, "Sun May 17 2026 08:16:19"));
	track[0].push(new TrackPoint(35.650995, 139.753936, 4.526, 32, 0, 0, "Sun May 17 2026 08:16:24"));
	track[0].push(new TrackPoint(35.650619, 139.753902, 4.568, 34, 0, 0, "Sun May 17 2026 08:16:46"));
	track[0].push(new TrackPoint(35.650561, 139.753928, 4.575, 34, 0, 0, "Sun May 17 2026 08:16:50"));
	track[0].push(new TrackPoint(35.650184, 139.753808, 4.619, 31, 0, 0, "Sun May 17 2026 08:17:09"));
	track[0].push(new TrackPoint(35.650092, 139.753716, 4.632, 29, 0, 0, "Sun May 17 2026 08:17:15"));
	track[0].push(new TrackPoint(35.649766, 139.753526, 4.672, 29, 0, 0, "Sun May 17 2026 08:17:35"));
	track[0].push(new TrackPoint(35.649519, 139.753450, 4.700, 26, 0, 0, "Sun May 17 2026 08:17:49"));
	track[0].push(new TrackPoint(35.649378, 139.753448, 4.716, 24, 0, 0, "Sun May 17 2026 08:17:56"));
	track[0].push(new TrackPoint(35.649267, 139.753387, 4.730, 23, 0, 0, "Sun May 17 2026 08:18:03"));
	track[0].push(new TrackPoint(35.649191, 139.753015, 4.765, 23, 0, 0, "Sun May 17 2026 08:18:52"));
	track[0].push(new TrackPoint(35.649202, 139.753010, 4.768, 24, 0, 0, "Sun May 17 2026 08:19:15"));
	track[0].push(new TrackPoint(35.649139, 139.752920, 4.779, 23, 0, 0, "Sun May 17 2026 08:19:30"));
	track[0].push(new TrackPoint(35.648987, 139.752834, 4.798, 21, 0, 0, "Sun May 17 2026 08:19:38"));
	track[0].push(new TrackPoint(35.648963, 139.752681, 4.812, 20, 0, 0, "Sun May 17 2026 08:19:44"));
	track[0].push(new TrackPoint(35.648881, 139.752495, 4.831, 20, 0, 0, "Sun May 17 2026 08:19:53"));
	track[0].push(new TrackPoint(35.648821, 139.752266, 4.853, 22, 0, 0, "Sun May 17 2026 08:20:02"));
	track[0].push(new TrackPoint(35.648760, 139.752105, 4.869, 24, 0, 0, "Sun May 17 2026 08:20:10"));
	track[0].push(new TrackPoint(35.648687, 139.751980, 4.883, 25, 0, 0, "Sun May 17 2026 08:20:17"));
	track[0].push(new TrackPoint(35.648647, 139.751793, 4.901, 24, 0, 0, "Sun May 17 2026 08:20:24"));
	track[0].push(new TrackPoint(35.648587, 139.751615, 4.918, 22, 0, 0, "Sun May 17 2026 08:20:32"));
	track[0].push(new TrackPoint(35.648491, 139.751440, 4.937, 22, 0, 0, "Sun May 17 2026 08:20:40"));
	track[0].push(new TrackPoint(35.648463, 139.751309, 4.950, 20, 0, 0, "Sun May 17 2026 08:20:46"));
	track[0].push(new TrackPoint(35.648409, 139.751181, 4.963, 20, 0, 0, "Sun May 17 2026 08:20:53"));
	track[0].push(new TrackPoint(35.648404, 139.750957, 4.983, 18, 0, 0, "Sun May 17 2026 08:21:01"));
	track[0].push(new TrackPoint(35.648340, 139.750772, 5.001, 18, 0, 0, "Sun May 17 2026 08:21:08"));
	track[0].push(new TrackPoint(35.648273, 139.750646, 5.015, 17, 0, 0, "Sun May 17 2026 08:21:15"));
	track[0].push(new TrackPoint(35.648220, 139.750420, 5.037, 16, 0, 0, "Sun May 17 2026 08:21:27"));
	track[0].push(new TrackPoint(35.648213, 139.750256, 5.052, 16, 0, 0, "Sun May 17 2026 08:21:34"));
	track[0].push(new TrackPoint(35.648171, 139.750065, 5.069, 16, 0, 0, "Sun May 17 2026 08:21:42"));
	track[0].push(new TrackPoint(35.648094, 139.750007, 5.080, 17, 0, 0, "Sun May 17 2026 08:21:49"));
	track[0].push(new TrackPoint(35.647979, 139.749677, 5.112, 17, 0, 0, "Sun May 17 2026 08:22:05"));
	track[0].push(new TrackPoint(35.647919, 139.749546, 5.126, 18, 0, 0, "Sun May 17 2026 08:22:12"));
	track[0].push(new TrackPoint(35.647850, 139.749492, 5.135, 18, 0, 0, "Sun May 17 2026 08:22:17"));
	track[0].push(new TrackPoint(35.647809, 139.749373, 5.147, 18, 0, 0, "Sun May 17 2026 08:22:23"));
	track[0].push(new TrackPoint(35.647678, 139.749237, 5.166, 16, 0, 0, "Sun May 17 2026 08:22:31"));
	track[0].push(new TrackPoint(35.647605, 139.748965, 5.192, 15, 0, 0, "Sun May 17 2026 08:22:43"));
	track[0].push(new TrackPoint(35.647593, 139.748805, 5.206, 14, 0, 0, "Sun May 17 2026 08:22:49"));
	track[0].push(new TrackPoint(35.647517, 139.748726, 5.217, 14, 0, 0, "Sun May 17 2026 08:22:55"));
	track[0].push(new TrackPoint(35.647548, 139.748571, 5.232, 13, 0, 0, "Sun May 17 2026 08:23:00"));
	track[0].push(new TrackPoint(35.647466, 139.748494, 5.244, 14, 0, 0, "Sun May 17 2026 08:23:07"));
	track[0].push(new TrackPoint(35.647384, 139.748341, 5.260, 16, 0, 0, "Sun May 17 2026 08:23:15"));
	track[0].push(new TrackPoint(35.647313, 139.748156, 5.279, 16, 0, 0, "Sun May 17 2026 08:23:23"));
	track[0].push(new TrackPoint(35.647247, 139.748030, 5.292, 16, 0, 0, "Sun May 17 2026 08:23:29"));
	track[0].push(new TrackPoint(35.647142, 139.747655, 5.328, 15, 0, 0, "Sun May 17 2026 08:23:47"));
	track[0].push(new TrackPoint(35.647099, 139.747557, 5.338, 15, 0, 0, "Sun May 17 2026 08:23:54"));
	track[0].push(new TrackPoint(35.646974, 139.747344, 5.362, 15, 0, 0, "Sun May 17 2026 08:24:05"));
	track[0].push(new TrackPoint(35.646935, 139.747187, 5.377, 15, 0, 0, "Sun May 17 2026 08:24:12"));
	track[0].push(new TrackPoint(35.646763, 139.746904, 5.409, 15, 0, 0, "Sun May 17 2026 08:24:29"));
	track[0].push(new TrackPoint(35.646547, 139.746715, 5.439, 16, 0, 0, "Sun May 17 2026 08:24:47"));
	track[0].push(new TrackPoint(35.646512, 139.746616, 5.449, 17, 0, 0, "Sun May 17 2026 08:24:54"));
	track[0].push(new TrackPoint(35.646503, 139.746534, 5.456, 17, 0, 0, "Sun May 17 2026 08:24:59"));
	track[0].push(new TrackPoint(35.646237, 139.746261, 5.496, 21, 0, 0, "Sun May 17 2026 08:25:15"));
	track[0].push(new TrackPoint(35.646188, 139.746236, 5.501, 21, 0, 0, "Sun May 17 2026 08:25:17"));
	track[0].push(new TrackPoint(35.646034, 139.745985, 5.530, 22, 0, 0, "Sun May 17 2026 08:25:31"));
	track[0].push(new TrackPoint(35.646013, 139.745774, 5.549, 23, 0, 0, "Sun May 17 2026 08:25:39"));
	track[0].push(new TrackPoint(35.645941, 139.745644, 5.563, 22, 0, 0, "Sun May 17 2026 08:25:48"));
	track[0].push(new TrackPoint(35.645823, 139.745514, 5.582, 23, 0, 0, "Sun May 17 2026 08:26:00"));
	track[0].push(new TrackPoint(35.645490, 139.744836, 5.654, 25, 0, 0, "Sun May 17 2026 08:26:31"));
	track[0].push(new TrackPoint(35.645430, 139.744810, 5.661, 23, 0, 0, "Sun May 17 2026 08:26:36"));
	track[0].push(new TrackPoint(35.645459, 139.744729, 5.672, 25, 0, 0, "Sun May 17 2026 08:27:55"));
	track[0].push(new TrackPoint(35.645384, 139.744701, 5.682, 22, 0, 0, "Sun May 17 2026 08:28:03"));
	track[0].push(new TrackPoint(35.645334, 139.744529, 5.698, 21, 0, 0, "Sun May 17 2026 08:28:15"));
	track[0].push(new TrackPoint(35.645144, 139.744250, 5.731, 22, 0, 0, "Sun May 17 2026 08:28:30"));
	track[0].push(new TrackPoint(35.645116, 139.744120, 5.744, 23, 0, 0, "Sun May 17 2026 08:28:35"));
	track[0].push(new TrackPoint(35.644877, 139.743842, 5.780, 25, 0, 0, "Sun May 17 2026 08:28:53"));
	track[0].push(new TrackPoint(35.644797, 139.743667, 5.799, 25, 0, 0, "Sun May 17 2026 08:29:01"));
	track[0].push(new TrackPoint(35.644609, 139.743515, 5.824, 24, 0, 0, "Sun May 17 2026 08:29:13"));
	track[0].push(new TrackPoint(35.644322, 139.743156, 5.869, 19, 0, 0, "Sun May 17 2026 08:29:36"));
	track[0].push(new TrackPoint(35.644208, 139.743046, 5.886, 17, 0, 0, "Sun May 17 2026 08:29:44"));
	track[0].push(new TrackPoint(35.643732, 139.742902, 5.941, 19, 0, 0, "Sun May 17 2026 08:30:11"));
	track[0].push(new TrackPoint(35.643607, 139.742809, 5.958, 23, 0, 0, "Sun May 17 2026 08:30:19"));
	track[0].push(new TrackPoint(35.643364, 139.742723, 5.987, 30, 0, 0, "Sun May 17 2026 08:30:33"));
	track[0].push(new TrackPoint(35.643088, 139.742496, 6.023, 29, 0, 0, "Sun May 17 2026 08:30:51"));
	track[0].push(new TrackPoint(35.643026, 139.742425, 6.033, 28, 0, 0, "Sun May 17 2026 08:30:57"));
	track[0].push(new TrackPoint(35.642629, 139.742215, 6.082, 21, 0, 0, "Sun May 17 2026 08:31:22"));
	track[0].push(new TrackPoint(35.642570, 139.742168, 6.090, 20, 0, 0, "Sun May 17 2026 08:31:26"));
	track[0].push(new TrackPoint(35.642387, 139.742115, 6.111, 17, 0, 0, "Sun May 17 2026 08:31:38"));
	track[0].push(new TrackPoint(35.642312, 139.742053, 6.121, 16, 0, 0, "Sun May 17 2026 08:31:43"));
	track[0].push(new TrackPoint(35.642252, 139.741951, 6.132, 16, 0, 0, "Sun May 17 2026 08:31:48"));
	track[0].push(new TrackPoint(35.642113, 139.741866, 6.150, 16, 0, 0, "Sun May 17 2026 08:31:56"));
	track[0].push(new TrackPoint(35.641983, 139.741711, 6.170, 16, 0, 0, "Sun May 17 2026 08:32:06"));
	track[0].push(new TrackPoint(35.641814, 139.741609, 6.191, 17, 0, 0, "Sun May 17 2026 08:32:16"));
	track[0].push(new TrackPoint(35.641753, 139.741548, 6.200, 17, 0, 0, "Sun May 17 2026 08:32:20"));
	track[0].push(new TrackPoint(35.641453, 139.741442, 6.234, 20, 0, 0, "Sun May 17 2026 08:32:37"));
	track[0].push(new TrackPoint(35.641302, 139.741428, 6.251, 20, 0, 0, "Sun May 17 2026 08:32:45"));
	track[0].push(new TrackPoint(35.641198, 139.741384, 6.263, 20, 0, 0, "Sun May 17 2026 08:32:51"));
	track[0].push(new TrackPoint(35.641098, 139.741407, 6.275, 19, 0, 0, "Sun May 17 2026 08:32:56"));
	track[0].push(new TrackPoint(35.640855, 139.741343, 6.302, 20, 0, 0, "Sun May 17 2026 08:33:11"));
	track[0].push(new TrackPoint(35.640692, 139.741346, 6.321, 22, 0, 0, "Sun May 17 2026 08:33:20"));
	track[0].push(new TrackPoint(35.640570, 139.741302, 6.335, 22, 0, 0, "Sun May 17 2026 08:33:27"));
	track[0].push(new TrackPoint(35.640402, 139.741196, 6.356, 20, 0, 0, "Sun May 17 2026 08:33:37"));
	track[0].push(new TrackPoint(35.640121, 139.741210, 6.387, 18, 0, 0, "Sun May 17 2026 08:33:51"));
	track[0].push(new TrackPoint(35.639996, 139.741090, 6.405, 19, 0, 0, "Sun May 17 2026 08:33:59"));
	track[0].push(new TrackPoint(35.639612, 139.740829, 6.454, 24, 0, 0, "Sun May 17 2026 08:34:24"));
	track[0].push(new TrackPoint(35.639511, 139.740653, 6.473, 25, 0, 0, "Sun May 17 2026 08:34:32"));
	track[0].push(new TrackPoint(35.639363, 139.740508, 6.495, 23, 0, 0, "Sun May 17 2026 08:34:42"));
	track[0].push(new TrackPoint(35.639346, 139.740449, 6.500, 21, 0, 0, "Sun May 17 2026 08:34:44"));
	track[0].push(new TrackPoint(35.639228, 139.740352, 6.516, 19, 0, 0, "Sun May 17 2026 08:34:53"));
	track[0].push(new TrackPoint(35.638920, 139.740226, 6.552, 20, 0, 0, "Sun May 17 2026 08:35:12"));
	track[0].push(new TrackPoint(35.638720, 139.740034, 6.581, 17, 0, 0, "Sun May 17 2026 08:35:27"));
	track[0].push(new TrackPoint(35.638479, 139.739853, 6.612, 17, 0, 0, "Sun May 17 2026 08:35:43"));
	track[0].push(new TrackPoint(35.638225, 139.739831, 6.641, 20, 0, 0, "Sun May 17 2026 08:35:54"));
	track[0].push(new TrackPoint(35.638040, 139.739679, 6.666, 23, 0, 0, "Sun May 17 2026 08:36:08"));
	track[0].push(new TrackPoint(35.637949, 139.739548, 6.681, 23, 0, 0, "Sun May 17 2026 08:36:14"));
	track[0].push(new TrackPoint(35.637825, 139.739469, 6.697, 24, 0, 0, "Sun May 17 2026 08:36:22"));
	track[0].push(new TrackPoint(35.637740, 139.739439, 6.707, 24, 0, 0, "Sun May 17 2026 08:36:29"));
	track[0].push(new TrackPoint(35.637713, 139.739511, 6.714, 23, 0, 0, "Sun May 17 2026 08:36:40"));
	track[0].push(new TrackPoint(35.637529, 139.739497, 6.737, 20, 0, 0, "Sun May 17 2026 08:37:34"));
	track[0].push(new TrackPoint(35.637368, 139.739507, 6.755, 19, 0, 0, "Sun May 17 2026 08:37:41"));
	track[0].push(new TrackPoint(35.637181, 139.739390, 6.778, 17, 0, 0, "Sun May 17 2026 08:37:50"));
	track[0].push(new TrackPoint(35.637036, 139.739395, 6.795, 14, 0, 0, "Sun May 17 2026 08:37:58"));
	track[0].push(new TrackPoint(35.636768, 139.739422, 6.825, 11, 0, 0, "Sun May 17 2026 08:38:13"));
	track[0].push(new TrackPoint(35.636644, 139.739393, 6.839, 12, 0, 0, "Sun May 17 2026 08:38:21"));
	track[0].push(new TrackPoint(35.636500, 139.739330, 6.857, 15, 0, 0, "Sun May 17 2026 08:38:28"));
	track[0].push(new TrackPoint(35.636140, 139.739139, 6.901, 22, 0, 0, "Sun May 17 2026 08:38:48"));
	track[0].push(new TrackPoint(35.636075, 139.739144, 6.909, 23, 0, 0, "Sun May 17 2026 08:38:53"));
	track[0].push(new TrackPoint(35.635804, 139.739053, 6.940, 25, 0, 0, "Sun May 17 2026 08:39:11"));
	track[0].push(new TrackPoint(35.635724, 139.739054, 6.949, 25, 0, 0, "Sun May 17 2026 08:39:14"));
	track[0].push(new TrackPoint(35.635582, 139.739008, 6.966, 24, 0, 0, "Sun May 17 2026 08:39:22"));
	track[0].push(new TrackPoint(35.635452, 139.739045, 6.981, 21, 0, 0, "Sun May 17 2026 08:39:30"));
	track[0].push(new TrackPoint(35.635172, 139.738877, 7.017, 16, 0, 0, "Sun May 17 2026 08:39:50"));
	track[0].push(new TrackPoint(35.634829, 139.738612, 7.062, 14, 0, 0, "Sun May 17 2026 08:40:09"));
	track[0].push(new TrackPoint(35.634657, 139.738561, 7.081, 14, 0, 0, "Sun May 17 2026 08:40:18"));
	track[0].push(new TrackPoint(35.634457, 139.738457, 7.106, 13, 0, 0, "Sun May 17 2026 08:40:31"));
	track[0].push(new TrackPoint(35.634167, 139.738420, 7.138, 14, 0, 0, "Sun May 17 2026 08:40:44"));
	track[0].push(new TrackPoint(35.634020, 139.738462, 7.155, 13, 0, 0, "Sun May 17 2026 08:40:51"));
	track[0].push(new TrackPoint(35.633918, 139.738465, 7.166, 13, 0, 0, "Sun May 17 2026 08:40:56"));
	track[0].push(new TrackPoint(35.633815, 139.738405, 7.179, 13, 0, 0, "Sun May 17 2026 08:41:03"));
	track[0].push(new TrackPoint(35.633703, 139.738289, 7.195, 15, 0, 0, "Sun May 17 2026 08:41:11"));
	track[0].push(new TrackPoint(35.633537, 139.738271, 7.214, 15, 0, 0, "Sun May 17 2026 08:41:21"));
	track[0].push(new TrackPoint(35.633412, 139.738343, 7.229, 14, 0, 0, "Sun May 17 2026 08:41:27"));
	track[0].push(new TrackPoint(35.633321, 139.738316, 7.239, 14, 0, 0, "Sun May 17 2026 08:41:32"));
	track[0].push(new TrackPoint(35.633060, 139.738178, 7.271, 16, 0, 0, "Sun May 17 2026 08:41:48"));
	track[0].push(new TrackPoint(35.632958, 139.738145, 7.283, 17, 0, 0, "Sun May 17 2026 08:41:54"));
	track[0].push(new TrackPoint(35.632869, 139.738037, 7.297, 17, 0, 0, "Sun May 17 2026 08:42:01"));
	track[0].push(new TrackPoint(35.632673, 139.738006, 7.319, 18, 0, 0, "Sun May 17 2026 08:42:12"));
	track[0].push(new TrackPoint(35.632577, 139.738030, 7.330, 19, 0, 0, "Sun May 17 2026 08:42:18"));
	track[0].push(new TrackPoint(35.632409, 139.737960, 7.350, 21, 0, 0, "Sun May 17 2026 08:42:26"));
	track[0].push(new TrackPoint(35.632182, 139.737931, 7.376, 25, 0, 0, "Sun May 17 2026 08:42:38"));
	track[0].push(new TrackPoint(35.631950, 139.737863, 7.403, 28, 0, 0, "Sun May 17 2026 08:42:51"));
	track[0].push(new TrackPoint(35.631798, 139.737849, 7.420, 29, 0, 0, "Sun May 17 2026 08:43:03"));
	track[0].push(new TrackPoint(35.631707, 139.737823, 7.430, 30, 0, 0, "Sun May 17 2026 08:43:08"));
	track[0].push(new TrackPoint(35.631640, 139.737887, 7.440, 30, 0, 0, "Sun May 17 2026 08:43:15"));
	track[0].push(new TrackPoint(35.631441, 139.737880, 7.462, 29, 0, 0, "Sun May 17 2026 08:43:28"));
	track[0].push(new TrackPoint(35.631319, 139.737846, 7.476, 29, 0, 0, "Sun May 17 2026 08:43:34"));
	track[0].push(new TrackPoint(35.631262, 139.737795, 7.484, 28, 0, 0, "Sun May 17 2026 08:43:37"));
	track[0].push(new TrackPoint(35.631190, 139.737765, 7.492, 28, 0, 0, "Sun May 17 2026 08:43:40"));
	track[0].push(new TrackPoint(35.631110, 139.737841, 7.503, 28, 0, 0, "Sun May 17 2026 08:43:49"));
	track[0].push(new TrackPoint(35.630795, 139.737778, 7.539, 31, 0, 0, "Sun May 17 2026 08:44:09"));
	track[0].push(new TrackPoint(35.630714, 139.737748, 7.549, 32, 0, 0, "Sun May 17 2026 08:44:12"));
	track[0].push(new TrackPoint(35.630586, 139.737762, 7.563, 32, 0, 0, "Sun May 17 2026 08:44:18"));
	track[0].push(new TrackPoint(35.630561, 139.737787, 7.567, 31, 0, 0, "Sun May 17 2026 08:44:20"));
	track[0].push(new TrackPoint(35.630439, 139.737792, 7.580, 31, 0, 0, "Sun May 17 2026 08:44:28"));
	track[0].push(new TrackPoint(35.630333, 139.737744, 7.593, 32, 0, 0, "Sun May 17 2026 08:44:34"));
	track[0].push(new TrackPoint(35.630045, 139.737708, 7.625, 28, 0, 0, "Sun May 17 2026 08:44:48"));
	track[0].push(new TrackPoint(35.629887, 139.737729, 7.643, 26, 0, 0, "Sun May 17 2026 08:44:59"));
	track[0].push(new TrackPoint(35.629647, 139.737713, 7.670, 26, 0, 0, "Sun May 17 2026 08:45:10"));
	track[0].push(new TrackPoint(35.629529, 139.737680, 7.684, 26, 0, 0, "Sun May 17 2026 08:45:16"));
	track[0].push(new TrackPoint(35.628866, 139.737686, 7.757, 29, 0, 0, "Sun May 17 2026 08:45:52"));
	track[0].push(new TrackPoint(35.628616, 139.737718, 7.786, 26, 0, 0, "Sun May 17 2026 08:46:05"));
	track[0].push(new TrackPoint(35.628574, 139.737703, 7.791, 25, 0, 0, "Sun May 17 2026 08:46:08"));
	track[0].push(new TrackPoint(35.627894, 139.737717, 7.868, 16, 0, 0, "Sun May 17 2026 08:46:44"));
	track[0].push(new TrackPoint(35.627864, 139.737746, 7.872, 16, 0, 0, "Sun May 17 2026 08:46:47"));
	track[0].push(new TrackPoint(35.627570, 139.737769, 7.905, 15, 0, 0, "Sun May 17 2026 08:47:03"));
	track[0].push(new TrackPoint(35.627502, 139.737730, 7.913, 16, 0, 0, "Sun May 17 2026 08:47:08"));
	track[0].push(new TrackPoint(35.627370, 139.737729, 7.928, 16, 0, 0, "Sun May 17 2026 08:47:15"));
	track[0].push(new TrackPoint(35.627207, 139.737777, 7.947, 14, 0, 0, "Sun May 17 2026 08:47:24"));
	track[0].push(new TrackPoint(35.627068, 139.737778, 7.962, 13, 0, 0, "Sun May 17 2026 08:47:31"));
	track[0].push(new TrackPoint(35.626796, 139.737845, 7.993, 11, 0, 0, "Sun May 17 2026 08:47:44"));
	track[0].push(new TrackPoint(35.626667, 139.737858, 8.008, 12, 0, 0, "Sun May 17 2026 08:47:51"));
	track[0].push(new TrackPoint(35.626568, 139.737889, 8.019, 11, 0, 0, "Sun May 17 2026 08:47:57"));
	track[0].push(new TrackPoint(35.626397, 139.737998, 8.041, 13, 0, 0, "Sun May 17 2026 08:48:04"));
	track[0].push(new TrackPoint(35.626307, 139.737973, 8.051, 15, 0, 0, "Sun May 17 2026 08:48:11"));
	track[0].push(new TrackPoint(35.626204, 139.738055, 8.065, 17, 0, 0, "Sun May 17 2026 08:48:16"));
	track[0].push(new TrackPoint(35.626072, 139.738091, 8.080, 19, 0, 0, "Sun May 17 2026 08:48:24"));
	track[0].push(new TrackPoint(35.625930, 139.738162, 8.097, 21, 0, 0, "Sun May 17 2026 08:48:31"));
	track[0].push(new TrackPoint(35.625803, 139.738148, 8.112, 23, 0, 0, "Sun May 17 2026 08:48:41"));
	track[0].push(new TrackPoint(35.625564, 139.738234, 8.139, 22, 0, 0, "Sun May 17 2026 08:48:56"));
	track[0].push(new TrackPoint(35.625472, 139.738219, 8.150, 23, 0, 0, "Sun May 17 2026 08:49:04"));
	track[0].push(new TrackPoint(35.625290, 139.738273, 8.171, 22, 0, 0, "Sun May 17 2026 08:49:23"));
	track[0].push(new TrackPoint(35.624807, 139.738496, 8.230, 14, 0, 0, "Sun May 17 2026 08:50:40"));
	track[0].push(new TrackPoint(35.624681, 139.738496, 8.244, 14, 0, 0, "Sun May 17 2026 08:50:46"));
	track[0].push(new TrackPoint(35.624566, 139.738590, 8.260, 14, 0, 0, "Sun May 17 2026 08:50:54"));
	track[0].push(new TrackPoint(35.624463, 139.738747, 8.278, 14, 0, 0, "Sun May 17 2026 08:51:03"));
	track[0].push(new TrackPoint(35.624323, 139.738883, 8.298, 12, 0, 0, "Sun May 17 2026 08:51:13"));
	track[0].push(new TrackPoint(35.624154, 139.738970, 8.318, 11, 0, 0, "Sun May 17 2026 08:51:20"));
	track[0].push(new TrackPoint(35.624027, 139.738952, 8.333, 8, 0, 0, "Sun May 17 2026 08:51:27"));
	track[0].push(new TrackPoint(35.623980, 139.738981, 8.339, 7, 0, 0, "Sun May 17 2026 08:51:31"));
	track[0].push(new TrackPoint(35.623928, 139.739161, 8.358, 10, 0, 0, "Sun May 17 2026 08:52:44"));
	track[0].push(new TrackPoint(35.623724, 139.739129, 8.381, 10, 0, 0, "Sun May 17 2026 08:53:00"));
	track[0].push(new TrackPoint(35.623566, 139.739156, 8.399, 12, 0, 0, "Sun May 17 2026 08:53:16"));
	track[0].push(new TrackPoint(35.623058, 139.739421, 8.462, 16, 0, 0, "Sun May 17 2026 08:54:04"));
	track[0].push(new TrackPoint(35.622929, 139.739513, 8.478, 15, 0, 0, "Sun May 17 2026 08:54:12"));
	track[0].push(new TrackPoint(35.622768, 139.739607, 8.498, 14, 0, 0, "Sun May 17 2026 08:54:22"));
	track[0].push(new TrackPoint(35.622519, 139.739711, 8.528, 11, 0, 0, "Sun May 17 2026 08:54:36"));
	track[0].push(new TrackPoint(35.622186, 139.739896, 8.569, 10, 0, 0, "Sun May 17 2026 08:55:01"));
	track[0].push(new TrackPoint(35.622124, 139.739977, 8.579, 10, 0, 0, "Sun May 17 2026 08:55:06"));
	track[0].push(new TrackPoint(35.621814, 139.740200, 8.619, 11, 0, 0, "Sun May 17 2026 08:55:28"));
	track[0].push(new TrackPoint(35.621332, 139.740675, 8.688, 9, 0, 0, "Sun May 17 2026 08:56:03"));
	track[0].push(new TrackPoint(35.621263, 139.740724, 8.697, 10, 0, 0, "Sun May 17 2026 08:56:07"));
	track[0].push(new TrackPoint(35.621195, 139.740818, 8.709, 12, 0, 0, "Sun May 17 2026 08:56:13"));
	track[0].push(new TrackPoint(35.621100, 139.740889, 8.721, 13, 0, 0, "Sun May 17 2026 08:56:20"));
	track[0].push(new TrackPoint(35.620939, 139.741080, 8.746, 16, 0, 0, "Sun May 17 2026 08:56:32"));
	track[0].push(new TrackPoint(35.620891, 139.741113, 8.752, 16, 0, 0, "Sun May 17 2026 08:56:35"));
	track[0].push(new TrackPoint(35.620829, 139.741127, 8.759, 16, 0, 0, "Sun May 17 2026 08:56:41"));
	track[0].push(new TrackPoint(35.620473, 139.741447, 8.809, 13, 0, 0, "Sun May 17 2026 08:57:06"));
	track[0].push(new TrackPoint(35.620381, 139.741577, 8.825, 11, 0, 0, "Sun May 17 2026 08:57:13"));
	track[0].push(new TrackPoint(35.620282, 139.741649, 8.837, 11, 0, 0, "Sun May 17 2026 08:57:21"));
	track[0].push(new TrackPoint(35.620207, 139.741783, 8.852, 10, 0, 0, "Sun May 17 2026 08:57:28"));
	track[0].push(new TrackPoint(35.619846, 139.742271, 8.912, 9, 0, 0, "Sun May 17 2026 08:58:03"));
	track[0].push(new TrackPoint(35.619536, 139.742577, 8.957, 7, 0, 0, "Sun May 17 2026 08:58:28"));
	track[0].push(new TrackPoint(35.619313, 139.742888, 8.994, 8, 0, 0, "Sun May 17 2026 08:58:49"));
	track[0].push(new TrackPoint(35.618928, 139.743300, 9.051, 11, 0, 0, "Sun May 17 2026 08:59:19"));
	track[0].push(new TrackPoint(35.618704, 139.743495, 9.082, 11, 0, 0, "Sun May 17 2026 08:59:35"));
	track[0].push(new TrackPoint(35.618663, 139.743548, 9.088, 11, 0, 0, "Sun May 17 2026 08:59:39"));
	track[0].push(new TrackPoint(35.618644, 139.743552, 9.091, 11, 0, 0, "Sun May 17 2026 08:59:41"));
	track[0].push(new TrackPoint(35.618331, 139.743821, 9.134, 11, 0, 0, "Sun May 17 2026 09:00:08"));
	track[0].push(new TrackPoint(35.618293, 139.743799, 9.138, 12, 0, 0, "Sun May 17 2026 09:00:14"));
	track[0].push(new TrackPoint(35.618083, 139.743925, 9.166, 9, 0, 0, "Sun May 17 2026 09:00:58"));
	track[0].push(new TrackPoint(35.617899, 139.744071, 9.190, 8, 0, 0, "Sun May 17 2026 09:01:09"));
	track[0].push(new TrackPoint(35.617344, 139.744403, 9.259, 9, 0, 0, "Sun May 17 2026 09:01:42"));
	track[0].push(new TrackPoint(35.617333, 139.744387, 9.261, 9, 0, 0, "Sun May 17 2026 09:01:44"));
	track[0].push(new TrackPoint(35.617222, 139.744467, 9.282, 9, 0, 0, "Sun May 17 2026 09:02:27"));
	track[0].push(new TrackPoint(35.616939, 139.744472, 9.314, 9, 0, 0, "Sun May 17 2026 09:02:50"));
	track[0].push(new TrackPoint(35.616901, 139.744449, 9.318, 9, 0, 0, "Sun May 17 2026 09:03:10"));
	track[0].push(new TrackPoint(35.615868, 139.744379, 9.433, 8, 0, 0, "Sun May 17 2026 09:04:21"));
	track[0].push(new TrackPoint(35.615385, 139.744222, 9.489, 9, 0, 0, "Sun May 17 2026 09:04:52"));
	track[0].push(new TrackPoint(35.615316, 139.744224, 9.497, 9, 0, 0, "Sun May 17 2026 09:04:56"));
	track[0].push(new TrackPoint(35.615200, 139.744175, 9.510, 9, 0, 0, "Sun May 17 2026 09:05:03"));
	track[0].push(new TrackPoint(35.614756, 139.744136, 9.560, 10, 0, 0, "Sun May 17 2026 09:05:41"));
	track[0].push(new TrackPoint(35.614705, 139.744105, 9.566, 10, 0, 0, "Sun May 17 2026 09:05:47"));
	track[0].push(new TrackPoint(35.614417, 139.744110, 9.598, 9, 0, 0, "Sun May 17 2026 09:06:04"));
	track[0].push(new TrackPoint(35.614046, 139.744093, 9.639, 9, 0, 0, "Sun May 17 2026 09:06:26"));
	track[0].push(new TrackPoint(35.613969, 139.744073, 9.648, 9, 0, 0, "Sun May 17 2026 09:06:33"));
	track[0].push(new TrackPoint(35.614036, 139.744052, 9.656, 9, 0, 0, "Sun May 17 2026 09:06:56"));
	track[0].push(new TrackPoint(35.613823, 139.744043, 9.680, 8, 0, 0, "Sun May 17 2026 09:07:15"));
	track[0].push(new TrackPoint(35.613589, 139.744083, 9.706, 5, 0, 0, "Sun May 17 2026 09:07:30"));
	track[0].push(new TrackPoint(35.613301, 139.744068, 9.738, 4, 0, 0, "Sun May 17 2026 09:07:46"));
	track[0].push(new TrackPoint(35.612775, 139.744088, 9.797, 8, 0, 0, "Sun May 17 2026 09:08:15"));
	track[0].push(new TrackPoint(35.612670, 139.744109, 9.809, 8, 0, 0, "Sun May 17 2026 09:08:21"));
	track[0].push(new TrackPoint(35.612537, 139.744165, 9.825, 9, 0, 0, "Sun May 17 2026 09:08:29"));
	track[0].push(new TrackPoint(35.612284, 139.744184, 9.853, 9, 0, 0, "Sun May 17 2026 09:08:45"));
	track[0].push(new TrackPoint(35.611905, 139.744147, 9.896, 6, 0, 0, "Sun May 17 2026 09:09:08"));
	track[0].push(new TrackPoint(35.611662, 139.744176, 9.923, 6, 0, 0, "Sun May 17 2026 09:09:23"));
	track[0].push(new TrackPoint(35.611437, 139.744142, 9.948, 8, 0, 0, "Sun May 17 2026 09:09:38"));
	track[0].push(new TrackPoint(35.611275, 139.744156, 9.966, 8, 0, 0, "Sun May 17 2026 09:09:47"));
	track[0].push(new TrackPoint(35.610825, 139.744119, 10.016, 9, 0, 0, "Sun May 17 2026 09:10:16"));
	track[0].push(new TrackPoint(35.610706, 139.744153, 10.030, 10, 0, 0, "Sun May 17 2026 09:10:28"));
	track[0].push(new TrackPoint(35.610612, 139.744144, 10.041, 11, 0, 0, "Sun May 17 2026 09:11:01"));
	track[0].push(new TrackPoint(35.610123, 139.744261, 10.096, 12, 0, 0, "Sun May 17 2026 09:11:31"));
	track[0].push(new TrackPoint(35.609850, 139.744262, 10.127, 10, 0, 0, "Sun May 17 2026 09:11:48"));
	track[0].push(new TrackPoint(35.609756, 139.744293, 10.138, 9, 0, 0, "Sun May 17 2026 09:11:54"));
	track[0].push(new TrackPoint(35.609208, 139.744283, 10.200, 9, 0, 0, "Sun May 17 2026 09:12:41"));
	track[0].push(new TrackPoint(35.608431, 139.744183, 10.287, 8, 0, 0, "Sun May 17 2026 09:13:28"));
	track[0].push(new TrackPoint(35.608184, 139.744175, 10.314, 8, 0, 0, "Sun May 17 2026 09:13:42"));
	track[0].push(new TrackPoint(35.607963, 139.744208, 10.339, 8, 0, 0, "Sun May 17 2026 09:13:54"));
	track[0].push(new TrackPoint(35.607825, 139.744200, 10.354, 8, 0, 0, "Sun May 17 2026 09:14:02"));
	track[0].push(new TrackPoint(35.607569, 139.744124, 10.383, 8, 0, 0, "Sun May 17 2026 09:14:17"));
	track[0].push(new TrackPoint(35.607162, 139.744123, 10.429, 10, 0, 0, "Sun May 17 2026 09:14:39"));
	track[0].push(new TrackPoint(35.606923, 139.744067, 10.456, 10, 0, 0, "Sun May 17 2026 09:14:55"));
	track[0].push(new TrackPoint(35.606702, 139.744094, 10.481, 9, 0, 0, "Sun May 17 2026 09:15:10"));
	track[0].push(new TrackPoint(35.606512, 139.744074, 10.502, 9, 0, 0, "Sun May 17 2026 09:15:21"));
	track[0].push(new TrackPoint(35.606247, 139.743983, 10.533, 11, 0, 0, "Sun May 17 2026 09:15:36"));
	track[0].push(new TrackPoint(35.605920, 139.743818, 10.572, 12, 0, 0, "Sun May 17 2026 09:15:55"));
	track[0].push(new TrackPoint(35.605786, 139.743689, 10.591, 11, 0, 0, "Sun May 17 2026 09:16:05"));
	track[0].push(new TrackPoint(35.605520, 139.743493, 10.626, 8, 0, 0, "Sun May 17 2026 09:16:23"));
	track[0].push(new TrackPoint(35.605106, 139.743320, 10.674, 6, 0, 0, "Sun May 17 2026 09:16:48"));
	track[0].push(new TrackPoint(35.604979, 139.743240, 10.690, 7, 0, 0, "Sun May 17 2026 09:16:57"));
	track[0].push(new TrackPoint(35.604322, 139.742920, 10.769, 8, 0, 0, "Sun May 17 2026 09:17:39"));
	track[0].push(new TrackPoint(35.604190, 139.742840, 10.785, 7, 0, 0, "Sun May 17 2026 09:17:48"));
	track[0].push(new TrackPoint(35.603750, 139.742656, 10.837, 4, 0, 0, "Sun May 17 2026 09:18:15"));
	track[0].push(new TrackPoint(35.603362, 139.742445, 10.884, 4, 0, 0, "Sun May 17 2026 09:18:41"));
	track[0].push(new TrackPoint(35.603168, 139.742372, 10.907, 5, 0, 0, "Sun May 17 2026 09:18:52"));
	track[0].push(new TrackPoint(35.602580, 139.742048, 10.978, 4, 0, 0, "Sun May 17 2026 09:19:30"));
	track[0].push(new TrackPoint(35.602438, 139.742002, 10.995, 4, 0, 0, "Sun May 17 2026 09:19:39"));
	track[0].push(new TrackPoint(35.601588, 139.741526, 11.098, 5, 0, 0, "Sun May 17 2026 09:20:35"));
	track[0].push(new TrackPoint(35.601361, 139.741414, 11.126, 6, 0, 0, "Sun May 17 2026 09:20:49"));
	track[0].push(new TrackPoint(35.601214, 139.741364, 11.143, 6, 0, 0, "Sun May 17 2026 09:20:58"));
	track[0].push(new TrackPoint(35.601095, 139.741288, 11.158, 6, 0, 0, "Sun May 17 2026 09:21:06"));
	track[0].push(new TrackPoint(35.600966, 139.741269, 11.172, 8, 0, 0, "Sun May 17 2026 09:21:14"));
	track[0].push(new TrackPoint(35.600722, 139.741277, 11.199, 10, 0, 0, "Sun May 17 2026 09:21:29"));
	track[0].push(new TrackPoint(35.600469, 139.741211, 11.228, 12, 0, 0, "Sun May 17 2026 09:21:45"));
	track[0].push(new TrackPoint(35.600364, 139.741160, 11.241, 12, 0, 0, "Sun May 17 2026 09:21:53"));
	track[0].push(new TrackPoint(35.599770, 139.740944, 11.310, 12, 0, 0, "Sun May 17 2026 09:22:30"));
	track[0].push(new TrackPoint(35.599350, 139.740842, 11.357, 8, 0, 0, "Sun May 17 2026 09:22:55"));
	track[0].push(new TrackPoint(35.598261, 139.740351, 11.487, 12, 0, 0, "Sun May 17 2026 09:24:02"));
	track[0].push(new TrackPoint(35.597503, 139.739836, 11.583, 6, 0, 0, "Sun May 17 2026 09:24:51"));
	track[0].push(new TrackPoint(35.597108, 139.739568, 11.633, 6, 0, 0, "Sun May 17 2026 09:25:19"));
	track[0].push(new TrackPoint(35.596983, 139.739547, 11.647, 6, 0, 0, "Sun May 17 2026 09:25:27"));
	track[0].push(new TrackPoint(35.596667, 139.739428, 11.684, 6, 0, 0, "Sun May 17 2026 09:25:49"));
	track[0].push(new TrackPoint(35.596138, 139.739282, 11.745, 4, 0, 0, "Sun May 17 2026 09:27:07"));
	track[0].push(new TrackPoint(35.595969, 139.739278, 11.764, 5, 0, 0, "Sun May 17 2026 09:27:20"));
	track[0].push(new TrackPoint(35.595782, 139.739206, 11.786, 5, 0, 0, "Sun May 17 2026 09:27:32"));
	track[0].push(new TrackPoint(35.595551, 139.739046, 11.815, 6, 0, 0, "Sun May 17 2026 09:27:45"));
	track[0].push(new TrackPoint(35.595383, 139.738969, 11.835, 6, 0, 0, "Sun May 17 2026 09:27:55"));
	track[0].push(new TrackPoint(35.594842, 139.738661, 11.902, 7, 0, 0, "Sun May 17 2026 09:28:29"));
	track[0].push(new TrackPoint(35.594574, 139.738456, 11.937, 8, 0, 0, "Sun May 17 2026 09:28:47"));
	track[0].push(new TrackPoint(35.594286, 139.738294, 11.972, 8, 0, 0, "Sun May 17 2026 09:29:05"));
	track[0].push(new TrackPoint(35.594175, 139.738204, 11.987, 8, 0, 0, "Sun May 17 2026 09:29:13"));
	track[0].push(new TrackPoint(35.594018, 139.738111, 12.006, 8, 0, 0, "Sun May 17 2026 09:29:24"));
	track[0].push(new TrackPoint(35.593909, 139.738023, 12.021, 8, 0, 0, "Sun May 17 2026 09:29:31"));
	track[0].push(new TrackPoint(35.593668, 139.737866, 12.051, 6, 0, 0, "Sun May 17 2026 09:29:47"));
	track[0].push(new TrackPoint(35.593134, 139.737399, 12.124, 4, 0, 0, "Sun May 17 2026 09:30:25"));
	track[0].push(new TrackPoint(35.592963, 139.737286, 12.146, 8, 0, 0, "Sun May 17 2026 09:30:36"));
	track[0].push(new TrackPoint(35.592672, 139.737151, 12.181, 12, 0, 0, "Sun May 17 2026 09:30:54"));
	track[0].push(new TrackPoint(35.592470, 139.736998, 12.208, 12, 0, 0, "Sun May 17 2026 09:31:09"));
	track[0].push(new TrackPoint(35.592341, 139.736945, 12.223, 11, 0, 0, "Sun May 17 2026 09:31:17"));
	track[0].push(new TrackPoint(35.591890, 139.736619, 12.281, 8, 0, 0, "Sun May 17 2026 09:31:50"));
	track[0].push(new TrackPoint(35.591877, 139.736592, 12.284, 8, 0, 0, "Sun May 17 2026 09:31:52"));
	track[0].push(new TrackPoint(35.591853, 139.736582, 12.287, 7, 0, 0, "Sun May 17 2026 09:31:54"));
	track[0].push(new TrackPoint(35.591824, 139.736598, 12.291, 7, 0, 0, "Sun May 17 2026 09:31:59"));
	track[0].push(new TrackPoint(35.591519, 139.736518, 12.327, 9, 0, 0, "Sun May 17 2026 09:33:32"));
	track[0].push(new TrackPoint(35.591513, 139.736503, 12.332, 9, 0, 0, "Sun May 17 2026 09:33:49"));
	track[0].push(new TrackPoint(35.591505, 139.736514, 12.334, 10, 0, 0, "Sun May 17 2026 09:33:55"));
	track[0].push(new TrackPoint(35.591548, 139.736543, 12.339, 9, 0, 0, "Sun May 17 2026 09:34:06"));
	track[0].push(new TrackPoint(35.591534, 139.736568, 12.346, 9, 0, 0, "Sun May 17 2026 09:35:10"));
	track[0].push(new TrackPoint(35.591300, 139.736446, 12.375, 12, 0, 0, "Sun May 17 2026 09:35:37"));
	track[0].push(new TrackPoint(35.591216, 139.736436, 12.385, 13, 0, 0, "Sun May 17 2026 09:35:41"));
	track[0].push(new TrackPoint(35.591046, 139.736372, 12.405, 13, 0, 0, "Sun May 17 2026 09:35:49"));
	track[0].push(new TrackPoint(35.590856, 139.736264, 12.428, 9, 0, 0, "Sun May 17 2026 09:35:57"));
	track[0].push(new TrackPoint(35.590672, 139.736241, 12.449, 8, 0, 0, "Sun May 17 2026 09:36:06"));
	track[0].push(new TrackPoint(35.590577, 139.736253, 12.459, 7, 0, 0, "Sun May 17 2026 09:36:11"));
	track[0].push(new TrackPoint(35.590240, 139.736180, 12.497, 9, 0, 0, "Sun May 17 2026 09:36:31"));
	track[0].push(new TrackPoint(35.590099, 139.736110, 12.515, 12, 0, 0, "Sun May 17 2026 09:36:40"));
	track[0].push(new TrackPoint(35.589899, 139.736079, 12.538, 16, 0, 0, "Sun May 17 2026 09:36:53"));
	track[0].push(new TrackPoint(35.589767, 139.736036, 12.553, 18, 0, 0, "Sun May 17 2026 09:37:00"));
	track[0].push(new TrackPoint(35.589681, 139.736061, 12.563, 19, 0, 0, "Sun May 17 2026 09:37:05"));
	track[0].push(new TrackPoint(35.589564, 139.736022, 12.576, 20, 0, 0, "Sun May 17 2026 09:37:12"));
	track[0].push(new TrackPoint(35.589401, 139.736066, 12.595, 19, 0, 0, "Sun May 17 2026 09:37:22"));
	track[0].push(new TrackPoint(35.589315, 139.736058, 12.605, 18, 0, 0, "Sun May 17 2026 09:37:27"));
	track[0].push(new TrackPoint(35.589170, 139.736023, 12.621, 16, 0, 0, "Sun May 17 2026 09:37:34"));
	track[0].push(new TrackPoint(35.588881, 139.735947, 12.655, 15, 0, 0, "Sun May 17 2026 09:37:48"));
	track[0].push(new TrackPoint(35.588786, 139.735997, 12.666, 16, 0, 0, "Sun May 17 2026 09:37:56"));
	track[0].push(new TrackPoint(35.588557, 139.735944, 12.692, 16, 0, 0, "Sun May 17 2026 09:38:10"));
	track[0].push(new TrackPoint(35.588373, 139.735970, 12.713, 16, 0, 0, "Sun May 17 2026 09:38:22"));
	track[0].push(new TrackPoint(35.587969, 139.735908, 12.758, 13, 0, 0, "Sun May 17 2026 09:38:41"));
	track[0].push(new TrackPoint(35.587696, 139.735903, 12.789, 11, 0, 0, "Sun May 17 2026 09:38:59"));
	track[0].push(new TrackPoint(35.587630, 139.735875, 12.797, 11, 0, 0, "Sun May 17 2026 09:39:04"));
	track[0].push(new TrackPoint(35.587556, 139.735920, 12.806, 10, 0, 0, "Sun May 17 2026 09:39:08"));
	track[0].push(new TrackPoint(35.587433, 139.735893, 12.820, 11, 0, 0, "Sun May 17 2026 09:39:16"));
	track[0].push(new TrackPoint(35.587371, 139.735902, 12.828, 12, 0, 0, "Sun May 17 2026 09:39:21"));
	track[0].push(new TrackPoint(35.587031, 139.736029, 12.867, 14, 0, 0, "Sun May 17 2026 09:39:40"));
	track[0].push(new TrackPoint(35.586917, 139.736090, 12.881, 14, 0, 0, "Sun May 17 2026 09:39:46"));
	track[0].push(new TrackPoint(35.586889, 139.736126, 12.886, 13, 0, 0, "Sun May 17 2026 09:39:48"));
	track[0].push(new TrackPoint(35.586796, 139.736130, 12.897, 11, 0, 0, "Sun May 17 2026 09:39:55"));
	track[0].push(new TrackPoint(35.586656, 139.736141, 12.913, 9, 0, 0, "Sun May 17 2026 09:40:04"));
	track[0].push(new TrackPoint(35.586549, 139.736202, 12.926, 9, 0, 0, "Sun May 17 2026 09:40:12"));
	track[0].push(new TrackPoint(35.586405, 139.736183, 12.942, 9, 0, 0, "Sun May 17 2026 09:40:21"));
	track[0].push(new TrackPoint(35.586368, 139.736216, 12.947, 10, 0, 0, "Sun May 17 2026 09:40:24"));
	track[0].push(new TrackPoint(35.586127, 139.736247, 12.975, 13, 0, 0, "Sun May 17 2026 09:40:37"));
	track[0].push(new TrackPoint(35.585986, 139.736215, 12.991, 18, 0, 0, "Sun May 17 2026 09:40:43"));
	track[0].push(new TrackPoint(35.585859, 139.736265, 13.007, 21, 0, 0, "Sun May 17 2026 09:40:50"));
	track[0].push(new TrackPoint(35.585668, 139.736282, 13.028, 20, 0, 0, "Sun May 17 2026 09:41:00"));
	track[0].push(new TrackPoint(35.585506, 139.736252, 13.047, 18, 0, 0, "Sun May 17 2026 09:41:07"));
	track[0].push(new TrackPoint(35.585169, 139.736365, 13.087, 7, 0, 0, "Sun May 17 2026 09:41:26"));
	track[0].push(new TrackPoint(35.584994, 139.736395, 13.107, 3, 0, 0, "Sun May 17 2026 09:41:35"));
	track[0].push(new TrackPoint(35.584822, 139.736487, 13.128, -1, 0, 0, "Sun May 17 2026 09:41:45"));
	track[0].push(new TrackPoint(35.583972, 139.736672, 13.226, 2, 0, 0, "Sun May 17 2026 09:42:36"));
	track[0].push(new TrackPoint(35.583532, 139.736663, 13.276, 11, 0, 0, "Sun May 17 2026 09:43:03"));
	track[0].push(new TrackPoint(35.583408, 139.736622, 13.290, 12, 0, 0, "Sun May 17 2026 09:43:09"));
	track[0].push(new TrackPoint(35.583343, 139.736627, 13.297, 12, 0, 0, "Sun May 17 2026 09:43:14"));
	track[0].push(new TrackPoint(35.583336, 139.736641, 13.299, 12, 0, 0, "Sun May 17 2026 09:43:15"));
	track[0].push(new TrackPoint(35.583234, 139.736662, 13.310, 12, 0, 0, "Sun May 17 2026 09:43:23"));
	track[0].push(new TrackPoint(35.583203, 139.736736, 13.318, 11, 0, 0, "Sun May 17 2026 09:43:28"));
	track[0].push(new TrackPoint(35.583053, 139.736799, 13.337, 11, 0, 0, "Sun May 17 2026 09:44:50"));
	track[0].push(new TrackPoint(35.582590, 139.736849, 13.389, 9, 0, 0, "Sun May 17 2026 09:45:16"));
	track[0].push(new TrackPoint(35.582487, 139.736785, 13.402, 9, 0, 0, "Sun May 17 2026 09:45:21"));
	track[0].push(new TrackPoint(35.582298, 139.736753, 13.423, 9, 0, 0, "Sun May 17 2026 09:45:31"));
	track[0].push(new TrackPoint(35.582182, 139.736709, 13.437, 9, 0, 0, "Sun May 17 2026 09:45:37"));
	track[0].push(new TrackPoint(35.582003, 139.736737, 13.457, 11, 0, 0, "Sun May 17 2026 09:45:48"));
	track[0].push(new TrackPoint(35.581795, 139.736697, 13.480, 11, 0, 0, "Sun May 17 2026 09:45:59"));
	track[0].push(new TrackPoint(35.581660, 139.736724, 13.496, 11, 0, 0, "Sun May 17 2026 09:46:07"));
	track[0].push(new TrackPoint(35.581537, 139.736771, 13.510, 11, 0, 0, "Sun May 17 2026 09:46:14"));
	track[0].push(new TrackPoint(35.581237, 139.736785, 13.543, 11, 0, 0, "Sun May 17 2026 09:46:31"));
	track[0].push(new TrackPoint(35.581107, 139.736760, 13.558, 11, 0, 0, "Sun May 17 2026 09:46:39"));
	track[0].push(new TrackPoint(35.580864, 139.736768, 13.585, 12, 0, 0, "Sun May 17 2026 09:46:53"));
	track[0].push(new TrackPoint(35.580589, 139.736806, 13.616, 11, 0, 0, "Sun May 17 2026 09:47:10"));
	track[0].push(new TrackPoint(35.580246, 139.736753, 13.654, 8, 0, 0, "Sun May 17 2026 09:47:31"));
	track[0].push(new TrackPoint(35.579510, 139.736713, 13.736, 10, 0, 0, "Sun May 17 2026 09:48:16"));
	track[0].push(new TrackPoint(35.579223, 139.736677, 13.768, 10, 0, 0, "Sun May 17 2026 09:48:33"));
	track[0].push(new TrackPoint(35.579084, 139.736632, 13.784, 9, 0, 0, "Sun May 17 2026 09:48:41"));
	track[0].push(new TrackPoint(35.578421, 139.736497, 13.859, 7, 0, 0, "Sun May 17 2026 09:49:20"));
	track[0].push(new TrackPoint(35.577678, 139.736247, 13.945, 2, 0, 0, "Sun May 17 2026 09:50:14"));
	track[0].push(new TrackPoint(35.577636, 139.736186, 13.953, 3, 0, 0, "Sun May 17 2026 09:50:59"));
	track[0].push(new TrackPoint(35.577621, 139.736207, 13.956, 3, 0, 0, "Sun May 17 2026 09:51:29"));
	track[0].push(new TrackPoint(35.577563, 139.736220, 13.962, 3, 0, 0, "Sun May 17 2026 09:51:54"));
	track[0].push(new TrackPoint(35.577181, 139.736072, 14.007, 7, 0, 0, "Sun May 17 2026 09:52:16"));
	track[0].push(new TrackPoint(35.576730, 139.735864, 14.061, 7, 0, 0, "Sun May 17 2026 09:52:44"));
	track[0].push(new TrackPoint(35.576462, 139.735773, 14.092, 7, 0, 0, "Sun May 17 2026 09:53:00"));
	track[0].push(new TrackPoint(35.576299, 139.735687, 14.112, 7, 0, 0, "Sun May 17 2026 09:53:14"));
	track[0].push(new TrackPoint(35.576299, 139.735635, 14.119, 6, 0, 0, "Sun May 17 2026 09:53:37"));
	track[0].push(new TrackPoint(35.575987, 139.735566, 14.154, 8, 0, 0, "Sun May 17 2026 09:54:09"));
	track[0].push(new TrackPoint(35.575522, 139.735371, 14.209, 9, 0, 0, "Sun May 17 2026 09:54:38"));
	track[0].push(new TrackPoint(35.574288, 139.734680, 14.360, 5, 0, 0, "Sun May 17 2026 09:55:55"));
	track[0].push(new TrackPoint(35.574011, 139.734390, 14.400, 7, 0, 0, "Sun May 17 2026 09:56:16"));
	track[0].push(new TrackPoint(35.573804, 139.734201, 14.429, 8, 0, 0, "Sun May 17 2026 09:56:32"));
	track[0].push(new TrackPoint(35.573558, 139.734143, 14.457, 8, 0, 0, "Sun May 17 2026 09:56:51"));
	track[0].push(new TrackPoint(35.573524, 139.734175, 14.462, 8, 0, 0, "Sun May 17 2026 09:56:56"));
	track[0].push(new TrackPoint(35.573482, 139.734182, 14.467, 8, 0, 0, "Sun May 17 2026 09:57:00"));
	track[0].push(new TrackPoint(35.573375, 139.734143, 14.479, 8, 0, 0, "Sun May 17 2026 09:57:35"));
	track[0].push(new TrackPoint(35.573394, 139.734055, 14.491, 9, 0, 0, "Sun May 17 2026 09:58:16"));
	track[0].push(new TrackPoint(35.573333, 139.733943, 14.503, 9, 0, 0, "Sun May 17 2026 09:58:22"));
	track[0].push(new TrackPoint(35.573255, 139.733922, 14.512, 8, 0, 0, "Sun May 17 2026 09:58:26"));
	track[0].push(new TrackPoint(35.572290, 139.733061, 14.645, 8, 0, 0, "Sun May 17 2026 09:59:37"));
	track[0].push(new TrackPoint(35.572150, 139.733010, 14.661, 9, 0, 0, "Sun May 17 2026 09:59:46"));
	track[0].push(new TrackPoint(35.571913, 139.732847, 14.692, 9, 0, 0, "Sun May 17 2026 10:00:02"));
	track[0].push(new TrackPoint(35.571759, 139.732685, 14.714, 7, 0, 0, "Sun May 17 2026 10:00:18"));
	track[0].push(new TrackPoint(35.571743, 139.732642, 14.721, 7, 0, 0, "Sun May 17 2026 10:01:02"));
	track[0].push(new TrackPoint(35.571494, 139.732490, 14.753, 7, 0, 0, "Sun May 17 2026 10:01:24"));
	track[0].push(new TrackPoint(35.571432, 139.732482, 14.760, 7, 0, 0, "Sun May 17 2026 10:01:29"));
	track[0].push(new TrackPoint(35.571381, 139.732450, 14.767, 7, 0, 0, "Sun May 17 2026 10:01:32"));
	track[0].push(new TrackPoint(35.571316, 139.732378, 14.776, 8, 0, 0, "Sun May 17 2026 10:01:36"));
	track[0].push(new TrackPoint(35.571008, 139.732145, 14.817, 10, 0, 0, "Sun May 17 2026 10:01:56"));
	track[0].push(new TrackPoint(35.570637, 139.731796, 14.869, 9, 0, 0, "Sun May 17 2026 10:02:21"));
	track[0].push(new TrackPoint(35.570502, 139.731700, 14.886, 10, 0, 0, "Sun May 17 2026 10:02:29"));
	track[0].push(new TrackPoint(35.570106, 139.731327, 14.942, 10, 0, 0, "Sun May 17 2026 10:02:58"));
	track[0].push(new TrackPoint(35.569758, 139.731154, 14.984, 8, 0, 0, "Sun May 17 2026 10:03:22"));
	track[0].push(new TrackPoint(35.569486, 139.730961, 15.019, 7, 0, 0, "Sun May 17 2026 10:03:39"));
	track[0].push(new TrackPoint(35.569358, 139.730885, 15.034, 7, 0, 0, "Sun May 17 2026 10:03:49"));
	track[0].push(new TrackPoint(35.569297, 139.730796, 15.045, 7, 0, 0, "Sun May 17 2026 10:03:55"));
	track[0].push(new TrackPoint(35.568196, 139.730023, 15.186, 3, 0, 0, "Sun May 17 2026 10:05:04"));
	track[0].push(new TrackPoint(35.567919, 139.729841, 15.221, 5, 0, 0, "Sun May 17 2026 10:05:22"));
	track[0].push(new TrackPoint(35.567575, 139.729508, 15.270, 9, 0, 0, "Sun May 17 2026 10:05:48"));
	track[0].push(new TrackPoint(35.567311, 139.729355, 15.303, 9, 0, 0, "Sun May 17 2026 10:06:04"));
	track[0].push(new TrackPoint(35.566946, 139.729050, 15.352, 8, 0, 0, "Sun May 17 2026 10:06:29"));
	track[0].push(new TrackPoint(35.566560, 139.728796, 15.401, 7, 0, 0, "Sun May 17 2026 10:06:52"));
	track[0].push(new TrackPoint(35.566189, 139.728575, 15.447, 5, 0, 0, "Sun May 17 2026 10:07:18"));
	track[0].push(new TrackPoint(35.565790, 139.728265, 15.499, 6, 0, 0, "Sun May 17 2026 10:07:44"));
	track[0].push(new TrackPoint(35.565467, 139.728090, 15.538, 7, 0, 0, "Sun May 17 2026 10:08:05"));
	track[0].push(new TrackPoint(35.565370, 139.728010, 15.551, 7, 0, 0, "Sun May 17 2026 10:08:11"));
	track[0].push(new TrackPoint(35.565310, 139.727914, 15.562, 6, 0, 0, "Sun May 17 2026 10:08:18"));
	track[0].push(new TrackPoint(35.564786, 139.727500, 15.632, 3, 0, 0, "Sun May 17 2026 10:08:50"));
	track[0].push(new TrackPoint(35.564676, 139.727438, 15.645, 3, 0, 0, "Sun May 17 2026 10:08:57"));
	track[0].push(new TrackPoint(35.564392, 139.727216, 15.683, 4, 0, 0, "Sun May 17 2026 10:09:16"));
	track[0].push(new TrackPoint(35.563750, 139.726769, 15.765, 5, 0, 0, "Sun May 17 2026 10:09:58"));
	track[0].push(new TrackPoint(35.563608, 139.726691, 15.782, 5, 0, 0, "Sun May 17 2026 10:10:07"));
	track[0].push(new TrackPoint(35.562206, 139.725623, 15.966, 8, 0, 0, "Sun May 17 2026 10:11:42"));
	track[0].push(new TrackPoint(35.561953, 139.725340, 16.004, 8, 0, 0, "Sun May 17 2026 10:12:02"));
	track[0].push(new TrackPoint(35.561922, 139.725336, 16.007, 8, 0, 0, "Sun May 17 2026 10:12:06"));
	track[0].push(new TrackPoint(35.561585, 139.725022, 16.054, 7, 0, 0, "Sun May 17 2026 10:12:28"));
	track[0].push(new TrackPoint(35.561381, 139.724894, 16.080, 6, 0, 0, "Sun May 17 2026 10:12:40"));
	track[0].push(new TrackPoint(35.561205, 139.724812, 16.101, 5, 0, 0, "Sun May 17 2026 10:12:50"));
	track[0].push(new TrackPoint(35.560990, 139.724661, 16.128, 4, 0, 0, "Sun May 17 2026 10:13:05"));
	track[0].push(new TrackPoint(35.560513, 139.724211, 16.195, 3, 0, 0, "Sun May 17 2026 10:13:42"));
	track[0].push(new TrackPoint(35.560165, 139.724068, 16.236, 3, 0, 0, "Sun May 17 2026 10:14:02"));
	track[0].push(new TrackPoint(35.560025, 139.723920, 16.257, 3, 0, 0, "Sun May 17 2026 10:14:16"));
	track[0].push(new TrackPoint(35.559479, 139.723557, 16.326, 5, 0, 0, "Sun May 17 2026 10:14:48"));
	track[0].push(new TrackPoint(35.559227, 139.723349, 16.360, 5, 0, 0, "Sun May 17 2026 10:15:05"));
	track[0].push(new TrackPoint(35.559031, 139.723119, 16.390, 4, 0, 0, "Sun May 17 2026 10:15:22"));
	track[0].push(new TrackPoint(35.558774, 139.722940, 16.423, 6, 0, 0, "Sun May 17 2026 10:15:39"));
	track[0].push(new TrackPoint(35.558286, 139.722668, 16.483, 6, 0, 0, "Sun May 17 2026 10:16:08"));
	track[0].push(new TrackPoint(35.558315, 139.722580, 16.494, 6, 0, 0, "Sun May 17 2026 10:17:28"));
	track[0].push(new TrackPoint(35.558159, 139.722508, 16.512, 6, 0, 0, "Sun May 17 2026 10:17:37"));
	track[0].push(new TrackPoint(35.558068, 139.722517, 16.522, 6, 0, 0, "Sun May 17 2026 10:17:44"));
	track[0].push(new TrackPoint(35.557992, 139.722483, 16.531, 6, 0, 0, "Sun May 17 2026 10:17:49"));
	track[0].push(new TrackPoint(35.557890, 139.722405, 16.545, 6, 0, 0, "Sun May 17 2026 10:17:58"));
	track[0].push(new TrackPoint(35.557733, 139.722215, 16.569, 5, 0, 0, "Sun May 17 2026 10:18:12"));
	track[0].push(new TrackPoint(35.557405, 139.722025, 16.610, 7, 0, 0, "Sun May 17 2026 10:18:33"));
	track[0].push(new TrackPoint(35.556903, 139.721618, 16.677, 9, 0, 0, "Sun May 17 2026 10:19:09"));
	track[0].push(new TrackPoint(35.555761, 139.720775, 16.825, 7, 0, 0, "Sun May 17 2026 10:20:22"));
	track[0].push(new TrackPoint(35.555620, 139.720648, 16.845, 8, 0, 0, "Sun May 17 2026 10:20:32"));
	track[0].push(new TrackPoint(35.554313, 139.719624, 17.017, 5, 0, 0, "Sun May 17 2026 10:22:03"));
	track[0].push(new TrackPoint(35.554235, 139.719533, 17.029, 4, 0, 0, "Sun May 17 2026 10:22:10"));
	track[0].push(new TrackPoint(35.554122, 139.719497, 17.042, 4, 0, 0, "Sun May 17 2026 10:22:17"));
	track[0].push(new TrackPoint(35.553909, 139.719289, 17.072, 5, 0, 0, "Sun May 17 2026 10:22:32"));
	track[0].push(new TrackPoint(35.553605, 139.719087, 17.111, 8, 0, 0, "Sun May 17 2026 10:22:51"));
	track[0].push(new TrackPoint(35.553265, 139.718831, 17.155, 8, 0, 0, "Sun May 17 2026 10:23:15"));
	track[0].push(new TrackPoint(35.552909, 139.718602, 17.200, 8, 0, 0, "Sun May 17 2026 10:23:38"));
	track[0].push(new TrackPoint(35.552456, 139.718201, 17.262, 6, 0, 0, "Sun May 17 2026 10:24:06"));
	track[0].push(new TrackPoint(35.552426, 139.718137, 17.269, 5, 0, 0, "Sun May 17 2026 10:24:11"));
	track[0].push(new TrackPoint(35.552374, 139.718079, 17.277, 5, 0, 0, "Sun May 17 2026 10:24:15"));
	track[0].push(new TrackPoint(35.551257, 139.717271, 17.421, 11, 0, 0, "Sun May 17 2026 10:25:25"));
	track[0].push(new TrackPoint(35.550341, 139.716557, 17.543, 5, 0, 0, "Sun May 17 2026 10:26:29"));
	track[0].push(new TrackPoint(35.550016, 139.716354, 17.583, 6, 0, 0, "Sun May 17 2026 10:26:48"));
	track[0].push(new TrackPoint(35.549883, 139.716164, 17.606, 9, 0, 0, "Sun May 17 2026 10:27:01"));
	track[0].push(new TrackPoint(35.549627, 139.715977, 17.640, 8, 0, 0, "Sun May 17 2026 10:27:50"));
	track[0].push(new TrackPoint(35.549479, 139.715895, 17.658, 7, 0, 0, "Sun May 17 2026 10:27:58"));
	track[0].push(new TrackPoint(35.549183, 139.715662, 17.697, 7, 0, 0, "Sun May 17 2026 10:28:17"));
	track[0].push(new TrackPoint(35.548804, 139.715411, 17.745, 10, 0, 0, "Sun May 17 2026 10:28:40"));
	track[0].push(new TrackPoint(35.548198, 139.714941, 17.825, 6, 0, 0, "Sun May 17 2026 10:29:21"));
	track[0].push(new TrackPoint(35.547982, 139.714822, 17.851, 5, 0, 0, "Sun May 17 2026 10:29:35"));
	track[0].push(new TrackPoint(35.547544, 139.714490, 17.908, 4, 0, 0, "Sun May 17 2026 10:30:05"));
	track[0].push(new TrackPoint(35.547415, 139.714420, 17.924, 4, 0, 0, "Sun May 17 2026 10:30:13"));
	track[0].push(new TrackPoint(35.547278, 139.714306, 17.942, 3, 0, 0, "Sun May 17 2026 10:30:23"));
	track[0].push(new TrackPoint(35.547054, 139.714181, 17.970, 4, 0, 0, "Sun May 17 2026 10:30:37"));
	track[0].push(new TrackPoint(35.546917, 139.714027, 17.990, 5, 0, 0, "Sun May 17 2026 10:30:47"));
	track[0].push(new TrackPoint(35.546802, 139.713948, 18.005, 6, 0, 0, "Sun May 17 2026 10:30:55"));
	track[0].push(new TrackPoint(35.546743, 139.713933, 18.012, 6, 0, 0, "Sun May 17 2026 10:30:59"));
	track[0].push(new TrackPoint(35.546197, 139.713439, 18.088, 6, 0, 0, "Sun May 17 2026 10:31:56"));
	track[0].push(new TrackPoint(35.545699, 139.713071, 18.164, 6, 0, 0, "Sun May 17 2026 10:34:48"));
	track[0].push(new TrackPoint(35.545453, 139.712842, 18.199, 8, 0, 0, "Sun May 17 2026 10:35:17"));
	track[0].push(new TrackPoint(35.545174, 139.712667, 18.234, 8, 0, 0, "Sun May 17 2026 10:35:42"));
	track[0].push(new TrackPoint(35.545109, 139.712597, 18.244, 7, 0, 0, "Sun May 17 2026 10:35:50"));
	track[0].push(new TrackPoint(35.544724, 139.712309, 18.294, 5, 0, 0, "Sun May 17 2026 10:36:17"));
	track[0].push(new TrackPoint(35.544109, 139.711855, 18.374, 4, 0, 0, "Sun May 17 2026 10:37:01"));
	track[0].push(new TrackPoint(35.543573, 139.711520, 18.442, 6, 0, 0, "Sun May 17 2026 10:37:36"));
	track[0].push(new TrackPoint(35.542357, 139.710665, 18.598, 5, 0, 0, "Sun May 17 2026 10:39:01"));
	track[0].push(new TrackPoint(35.542208, 139.710545, 18.617, 4, 0, 0, "Sun May 17 2026 10:39:10"));
	track[0].push(new TrackPoint(35.542001, 139.710426, 18.643, 3, 0, 0, "Sun May 17 2026 10:39:24"));
	track[0].push(new TrackPoint(35.541784, 139.710246, 18.672, 3, 0, 0, "Sun May 17 2026 10:39:41"));
	track[0].push(new TrackPoint(35.540648, 139.709494, 18.816, 6, 0, 0, "Sun May 17 2026 10:41:09"));
	track[0].push(new TrackPoint(35.540468, 139.709384, 18.839, 5, 0, 0, "Sun May 17 2026 10:41:51"));
	track[0].push(new TrackPoint(35.540261, 139.709312, 18.863, 5, 0, 0, "Sun May 17 2026 10:42:02"));
	track[0].push(new TrackPoint(35.540115, 139.709292, 18.880, 6, 0, 0, "Sun May 17 2026 10:42:32"));
	track[0].push(new TrackPoint(35.539968, 139.709195, 18.899, 7, 0, 0, "Sun May 17 2026 10:42:51"));
	track[0].push(new TrackPoint(35.539925, 139.709130, 18.906, 7, 0, 0, "Sun May 17 2026 10:42:59"));
	track[0].push(new TrackPoint(35.539774, 139.709108, 18.924, 9, 0, 0, "Sun May 17 2026 10:43:39"));
	track[0].push(new TrackPoint(35.538529, 139.708861, 19.065, 4, 0, 0, "Sun May 17 2026 10:45:25"));
	track[0].push(new TrackPoint(35.536977, 139.708578, 19.241, 7, 0, 0, "Sun May 17 2026 10:47:26"));
	track[0].push(new TrackPoint(35.536138, 139.708482, 19.336, 3, 0, 0, "Sun May 17 2026 10:49:07"));
	track[0].push(new TrackPoint(35.536048, 139.708454, 19.347, 5, 0, 0, "Sun May 17 2026 10:49:16"));
	track[0].push(new TrackPoint(35.535968, 139.708488, 19.358, 6, 0, 0, "Sun May 17 2026 10:50:16"));
	track[0].push(new TrackPoint(35.535589, 139.708410, 19.401, 9, 0, 0, "Sun May 17 2026 10:50:41"));
	track[0].push(new TrackPoint(35.535518, 139.708347, 19.410, 9, 0, 0, "Sun May 17 2026 10:50:49"));
	track[0].push(new TrackPoint(35.535396, 139.708311, 19.424, 9, 0, 0, "Sun May 17 2026 10:51:03"));
	track[0].push(new TrackPoint(35.535379, 139.708327, 19.427, 9, 0, 0, "Sun May 17 2026 10:51:23"));
	track[0].push(new TrackPoint(35.535416, 139.708238, 19.436, 10, 0, 0, "Sun May 17 2026 10:51:44"));
	track[0].push(new TrackPoint(35.535378, 139.708194, 19.443, 10, 0, 0, "Sun May 17 2026 10:51:53"));
	track[0].push(new TrackPoint(35.535388, 139.708124, 19.449, 10, 0, 0, "Sun May 17 2026 10:51:59"));
	track[0].push(new TrackPoint(35.535451, 139.708077, 19.458, 11, 0, 0, "Sun May 17 2026 10:52:04"));
	track[0].push(new TrackPoint(35.535498, 139.707893, 19.476, 10, 0, 0, "Sun May 17 2026 10:52:37"));
	track[0].push(new TrackPoint(35.535446, 139.707665, 19.498, 9, 0, 0, "Sun May 17 2026 10:53:01"));
	track[0].push(new TrackPoint(35.535402, 139.707620, 19.504, 9, 0, 0, "Sun May 17 2026 10:53:07"));
	track[0].push(new TrackPoint(35.535305, 139.707475, 19.522, 9, 0, 0, "Sun May 17 2026 10:53:28"));
	track[0].push(new TrackPoint(35.535240, 139.707311, 19.538, 8, 0, 0, "Sun May 17 2026 10:53:41"));
	track[0].push(new TrackPoint(35.535199, 139.707304, 19.543, 8, 0, 0, "Sun May 17 2026 10:53:44"));
	track[0].push(new TrackPoint(35.535093, 139.707106, 19.564, 8, 0, 0, "Sun May 17 2026 10:53:59"));
	track[0].push(new TrackPoint(35.535020, 139.707072, 19.574, 8, 0, 0, "Sun May 17 2026 10:54:06"));
	track[0].push(new TrackPoint(35.534843, 139.706723, 19.611, 6, 0, 0, "Sun May 17 2026 10:54:32"));
	track[0].push(new TrackPoint(35.534758, 139.706465, 19.637, 7, 0, 0, "Sun May 17 2026 10:54:52"));
	track[0].push(new TrackPoint(35.534658, 139.706311, 19.655, 9, 0, 0, "Sun May 17 2026 10:55:09"));
	track[0].push(new TrackPoint(35.534636, 139.706305, 19.659, 9, 0, 0, "Sun May 17 2026 10:56:11"));
	track[0].push(new TrackPoint(35.534552, 139.706089, 19.681, 13, 0, 0, "Sun May 17 2026 10:56:32"));
	track[0].push(new TrackPoint(35.534462, 139.706011, 19.693, 14, 0, 0, "Sun May 17 2026 10:56:41"));
	track[0].push(new TrackPoint(35.534430, 139.705947, 19.700, 15, 0, 0, "Sun May 17 2026 10:56:46"));
	track[0].push(new TrackPoint(35.534345, 139.705916, 19.710, 14, 0, 0, "Sun May 17 2026 10:56:52"));
	track[0].push(new TrackPoint(35.534260, 139.705832, 19.722, 14, 0, 0, "Sun May 17 2026 10:57:00"));
	track[0].push(new TrackPoint(35.534230, 139.705646, 19.740, 13, 0, 0, "Sun May 17 2026 10:57:10"));
	track[0].push(new TrackPoint(35.534145, 139.705525, 19.755, 12, 0, 0, "Sun May 17 2026 10:57:20"));
	track[0].push(new TrackPoint(35.534110, 139.705525, 19.759, 11, 0, 0, "Sun May 17 2026 10:57:22"));
	track[0].push(new TrackPoint(35.534005, 139.705415, 19.775, 8, 0, 0, "Sun May 17 2026 10:57:33"));
	track[0].push(new TrackPoint(35.533958, 139.705316, 19.785, 7, 0, 0, "Sun May 17 2026 10:57:41"));
	track[0].push(new TrackPoint(35.533920, 139.705149, 19.801, 6, 0, 0, "Sun May 17 2026 10:57:52"));
	track[0].push(new TrackPoint(35.533907, 139.704982, 19.817, 6, 0, 0, "Sun May 17 2026 10:58:02"));
	track[0].push(new TrackPoint(35.533835, 139.704821, 19.834, 6, 0, 0, "Sun May 17 2026 10:58:33"));
	track[0].push(new TrackPoint(35.533743, 139.704642, 19.856, 7, 0, 0, "Sun May 17 2026 11:00:06"));
	track[0].push(new TrackPoint(35.533683, 139.704564, 19.866, 7, 0, 0, "Sun May 17 2026 11:00:14"));
	track[0].push(new TrackPoint(35.533583, 139.704478, 19.880, 7, 0, 0, "Sun May 17 2026 11:00:24"));
	track[0].push(new TrackPoint(35.533555, 139.704430, 19.886, 8, 0, 0, "Sun May 17 2026 11:00:28"));
	track[0].push(new TrackPoint(35.533534, 139.704329, 19.895, 8, 0, 0, "Sun May 17 2026 11:00:34"));
	track[0].push(new TrackPoint(35.533418, 139.704126, 19.918, 9, 0, 0, "Sun May 17 2026 11:00:51"));
	track[0].push(new TrackPoint(35.533361, 139.704103, 19.925, 9, 0, 0, "Sun May 17 2026 11:00:57"));
	track[0].push(new TrackPoint(35.533331, 139.703987, 19.936, 9, 0, 0, "Sun May 17 2026 11:01:05"));
	track[0].push(new TrackPoint(35.533261, 139.703901, 19.947, 9, 0, 0, "Sun May 17 2026 11:01:12"));
	track[0].push(new TrackPoint(35.533225, 139.703900, 19.951, 10, 0, 0, "Sun May 17 2026 11:01:14"));
	track[0].push(new TrackPoint(35.533065, 139.703677, 19.979, 11, 0, 0, "Sun May 17 2026 11:01:36"));
	track[0].push(new TrackPoint(35.532986, 139.703472, 19.999, 11, 0, 0, "Sun May 17 2026 11:01:49"));
	track[0].push(new TrackPoint(35.532977, 139.703401, 20.006, 11, 0, 0, "Sun May 17 2026 11:01:55"));
	track[0].push(new TrackPoint(35.532968, 139.703409, 20.007, 11, 0, 0, "Sun May 17 2026 11:02:03"));
	track[0].push(new TrackPoint(35.532833, 139.703215, 20.030, 10, 0, 0, "Sun May 17 2026 11:02:27"));
	track[0].push(new TrackPoint(35.532767, 139.703096, 20.044, 10, 0, 0, "Sun May 17 2026 11:02:35"));
	track[0].push(new TrackPoint(35.532648, 139.702983, 20.060, 10, 0, 0, "Sun May 17 2026 11:02:48"));
	track[0].push(new TrackPoint(35.532554, 139.702845, 20.077, 11, 0, 0, "Sun May 17 2026 11:03:01"));
	track[0].push(new TrackPoint(35.532538, 139.702844, 20.079, 11, 0, 0, "Sun May 17 2026 11:03:02"));
	track[0].push(new TrackPoint(35.532536, 139.702773, 20.085, 11, 0, 0, "Sun May 17 2026 11:03:07"));
	track[0].push(new TrackPoint(35.532508, 139.702712, 20.091, 11, 0, 0, "Sun May 17 2026 11:03:12"));
	track[0].push(new TrackPoint(35.532425, 139.702673, 20.102, 10, 0, 0, "Sun May 17 2026 11:03:20"));
	track[0].push(new TrackPoint(35.532401, 139.702582, 20.110, 10, 0, 0, "Sun May 17 2026 11:03:24"));
	track[0].push(new TrackPoint(35.532283, 139.702376, 20.133, 7, 0, 0, "Sun May 17 2026 11:03:52"));
	track[0].push(new TrackPoint(35.532217, 139.702307, 20.143, 5, 0, 0, "Sun May 17 2026 11:03:59"));
	track[0].push(new TrackPoint(35.532191, 139.702233, 20.151, 6, 0, 0, "Sun May 17 2026 11:04:12"));
	track[0].push(new TrackPoint(35.532152, 139.702202, 20.156, 7, 0, 0, "Sun May 17 2026 11:04:20"));
	track[0].push(new TrackPoint(35.532076, 139.702184, 20.165, 7, 0, 0, "Sun May 17 2026 11:04:25"));
	track[0].push(new TrackPoint(35.531954, 139.702048, 20.184, 10, 0, 0, "Sun May 17 2026 11:04:42"));
	track[0].push(new TrackPoint(35.531905, 139.701937, 20.195, 12, 0, 0, "Sun May 17 2026 11:04:49"));
	track[0].push(new TrackPoint(35.531728, 139.701748, 20.222, 15, 0, 0, "Sun May 17 2026 11:05:08"));
	track[0].push(new TrackPoint(35.531694, 139.701678, 20.229, 16, 0, 0, "Sun May 17 2026 11:05:14"));
	track[0].push(new TrackPoint(35.531558, 139.701620, 20.245, 15, 0, 0, "Sun May 17 2026 11:05:26"));
	track[0].push(new TrackPoint(35.531534, 139.701576, 20.250, 15, 0, 0, "Sun May 17 2026 11:05:33"));
	track[0].push(new TrackPoint(35.531490, 139.701587, 20.255, 15, 0, 0, "Sun May 17 2026 11:05:38"));
	track[0].push(new TrackPoint(35.531324, 139.701520, 20.276, 14, 0, 0, "Sun May 17 2026 11:06:24"));
	track[0].push(new TrackPoint(35.531087, 139.701490, 20.302, 14, 0, 0, "Sun May 17 2026 11:06:41"));
	track[0].push(new TrackPoint(35.530988, 139.701420, 20.315, 15, 0, 0, "Sun May 17 2026 11:06:50"));
	track[0].push(new TrackPoint(35.530900, 139.701395, 20.325, 16, 0, 0, "Sun May 17 2026 11:06:57"));
	track[0].push(new TrackPoint(35.530712, 139.701190, 20.354, 20, 0, 0, "Sun May 17 2026 11:07:17"));
	track[0].push(new TrackPoint(35.530706, 139.701141, 20.358, 20, 0, 0, "Sun May 17 2026 11:07:21"));
	track[0].push(new TrackPoint(35.530718, 139.701115, 20.361, 20, 0, 0, "Sun May 17 2026 11:07:25"));
	track[0].push(new TrackPoint(35.530712, 139.701085, 20.364, 20, 0, 0, "Sun May 17 2026 11:07:31"));
	track[0].push(new TrackPoint(35.530279, 139.701052, 20.413, 26, 0, 0, "Sun May 17 2026 11:08:04"));
	track[0].push(new TrackPoint(35.530037, 139.701025, 20.440, 24, 0, 0, "Sun May 17 2026 11:08:23"));
	track[0].push(new TrackPoint(35.529951, 139.701033, 20.450, 23, 0, 0, "Sun May 17 2026 11:08:27"));
	track[0].push(new TrackPoint(35.529865, 139.700960, 20.462, 21, 0, 0, "Sun May 17 2026 11:08:46"));
	track[0].push(new TrackPoint(35.529837, 139.700957, 20.465, 21, 0, 0, "Sun May 17 2026 11:08:52"));
	track[0].push(new TrackPoint(35.529755, 139.700995, 20.475, 21, 0, 0, "Sun May 17 2026 11:09:00"));
	track[0].push(new TrackPoint(35.529640, 139.700984, 20.487, 20, 0, 0, "Sun May 17 2026 11:09:11"));
	track[0].push(new TrackPoint(35.529541, 139.700925, 20.500, 18, 0, 0, "Sun May 17 2026 11:09:21"));
	track[0].push(new TrackPoint(35.529527, 139.700858, 20.506, 17, 0, 0, "Sun May 17 2026 11:09:26"));
	track[0].push(new TrackPoint(35.529425, 139.700837, 20.518, 16, 0, 0, "Sun May 17 2026 11:09:33"));
	track[0].push(new TrackPoint(35.529332, 139.700749, 20.532, 15, 0, 0, "Sun May 17 2026 11:09:47"));
	track[0].push(new TrackPoint(35.529202, 139.700739, 20.547, 14, 0, 0, "Sun May 17 2026 11:09:56"));
	track[0].push(new TrackPoint(35.529013, 139.700704, 20.568, 15, 0, 0, "Sun May 17 2026 11:10:08"));
	track[0].push(new TrackPoint(35.528970, 139.700669, 20.574, 15, 0, 0, "Sun May 17 2026 11:10:14"));
	track[0].push(new TrackPoint(35.528942, 139.700694, 20.578, 15, 0, 0, "Sun May 17 2026 11:10:21"));
	track[0].push(new TrackPoint(35.528877, 139.700686, 20.586, 15, 0, 0, "Sun May 17 2026 11:10:33"));
	track[0].push(new TrackPoint(35.528810, 139.700645, 20.594, 16, 0, 0, "Sun May 17 2026 11:10:39"));
	track[0].push(new TrackPoint(35.528741, 139.700640, 20.602, 16, 0, 0, "Sun May 17 2026 11:10:45"));
	track[0].push(new TrackPoint(35.528707, 139.700603, 20.607, 16, 0, 0, "Sun May 17 2026 11:10:49"));
	track[0].push(new TrackPoint(35.528567, 139.700588, 20.623, 16, 0, 0, "Sun May 17 2026 11:11:03"));
	track[0].push(new TrackPoint(35.528387, 139.700614, 20.643, 16, 0, 0, "Sun May 17 2026 11:11:16"));
	track[0].push(new TrackPoint(35.528317, 139.700575, 20.651, 16, 0, 0, "Sun May 17 2026 11:11:22"));
	track[0].push(new TrackPoint(35.528298, 139.700511, 20.658, 15, 0, 0, "Sun May 17 2026 11:11:29"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
    var count = 0;

    for (i = 0; i < track.length; i++) {
        count += track[i].length;
    }

    if (count > 1 && !playing) {
        centerPointer.addTo(map);

        // 情報パネルは、まだ作られていない場合だけ作成
        if (showMeterPanel) {
            if (!infoPanel) {
                infoPanel = new InfoPanel();
                map.addControl(infoPanel);
            }
        }

        playing = true;
        goForward();
    }
}


function goForward() {
    var waittime;
    var pos = track[currTrack][currPoint].latlng;
    map.panTo(pos);
    centerPointer.setLatLng(pos);

    if (showMeterPanel) {
        displayInfoPanel(currTrack, currPoint);
    }

    if (currPoint < track[currTrack].length - 1) {
        if (realTimePlay) {
            waittime =
                track[currTrack][currPoint + 1].time.getTime() -
                track[currTrack][currPoint].time.getTime();

            waittime /=
                parseFloat(document.getElementById("playSpeed").value);
        }
        else {
            waittime =
                1000 /
                parseFloat(document.getElementById("playSpeed").value);
        }

        currPoint++;
    }
    else {
        if (currTrack < track.length - 1) {
            waittime = 1000;
            currTrack++;
            currPoint = 0;
        }
        else {
            window.clearTimeout(playTimer);
            playing = false;

            centerPointer.remove();

            // 情報パネルは終了後も残す
            return;
        }
    }

    playTimer = window.setTimeout("goForward()", waittime);
}


function stopRoute() {
    if (playing) {
        window.clearTimeout(playTimer);
        playing = false;

        // 情報パネルは停止後も残す
    }
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
