// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([36.742547, 136.807497], [37.529053, 137.359122]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(36.814819, 137.041473, 45, "2026/07/26", "09:39:53", 0, "雨晴海岸・氷見線", "files/IMG_20260726_093953.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.389042, 136.906281, 43, "2026/07/26", "12:09:53", 0, "輪島駅跡", "files/IMG_20260726_120953.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.424454, 136.998199, 99, "2026/07/26", "13:41:34", 0, "千枚田", "files/IMG_20260726_134134_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.441700, 137.270401, 51, "2026/07/26", "15:48:43", 0, "珠洲駅跡", "files/IMG_20260726_154843.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.529053, 137.325974, 90, "2026/07/26", "17:12:10", 0, "禄剛崎灯台モニュメント", "files/IMG_20260726_171211.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.528854, 137.325943, 94, "2026/07/26", "17:15:45", 0, "禄剛崎灯台", "files/IMG_20260726_171545.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.367561, 137.244354, 64, "2026/07/26", "19:00:12", 0, "ラブロ恋路の夕食", "files/IMG_20260726_190012.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(36.742547, 137.018156, 0.000, 0, 0, 0, "Sun Jul 26 2026 08:30:00"));
	track[0].push(new TrackPoint(36.747063, 137.014732, 0.587, 0, 0, 0, "Sun Jul 26 2026 08:33:00"));
	track[0].push(new TrackPoint(36.761754, 137.029987, 2.712, 0, 0, 0, "Sun Jul 26 2026 08:38:00"));
	track[0].push(new TrackPoint(36.763400, 137.032102, 2.974, 0, 0, 0, "Sun Jul 26 2026 08:39:00"));
	track[0].push(new TrackPoint(36.763423, 137.032057, 2.979, 0, 0, 0, "Sun Jul 26 2026 08:45:00"));
	track[0].push(new TrackPoint(36.767742, 137.037022, 3.632, 0, 0, 0, "Sun Jul 26 2026 08:46:00"));
	track[0].push(new TrackPoint(36.787495, 137.048470, 6.051, 0, 0, 0, "Sun Jul 26 2026 08:51:00"));
	track[0].push(new TrackPoint(36.790294, 137.048815, 6.363, 0, 0, 0, "Sun Jul 26 2026 08:52:00"));
	track[0].push(new TrackPoint(36.802185, 137.050850, 7.695, 0, 0, 0, "Sun Jul 26 2026 08:55:00"));
	track[0].push(new TrackPoint(36.814356, 137.042411, 9.241, 0, 0, 0, "Sun Jul 26 2026 08:57:00"));
	track[0].push(new TrackPoint(36.815102, 137.041183, 9.378, 0, 0, 0, "Sun Jul 26 2026 08:59:00"));
	track[0].push(new TrackPoint(36.815081, 137.041326, 9.391, 0, 0, 0, "Sun Jul 26 2026 09:56:00"));
	track[0].push(new TrackPoint(36.816647, 137.029055, 10.500, 0, 0, 0, "Sun Jul 26 2026 09:58:00"));
	track[0].push(new TrackPoint(36.834870, 136.992583, 14.331, 0, 0, 0, "Sun Jul 26 2026 10:03:00"));
	track[0].push(new TrackPoint(36.844313, 136.987300, 15.480, 0, 0, 0, "Sun Jul 26 2026 10:06:00"));
	track[0].push(new TrackPoint(36.859188, 136.986988, 17.131, 0, 0, 0, "Sun Jul 26 2026 10:09:00"));
	track[0].push(new TrackPoint(36.858045, 136.978757, 17.876, 0, 0, 0, "Sun Jul 26 2026 10:11:00"));
	track[0].push(new TrackPoint(36.856430, 136.969848, 18.690, 0, 0, 0, "Sun Jul 26 2026 10:14:00"));
	track[0].push(new TrackPoint(36.860415, 136.959515, 19.713, 0, 0, 0, "Sun Jul 26 2026 10:15:00"));
	track[0].push(new TrackPoint(36.857645, 136.957882, 20.053, 0, 0, 0, "Sun Jul 26 2026 10:16:00"));
	track[0].push(new TrackPoint(36.856113, 136.954605, 20.391, 0, 0, 0, "Sun Jul 26 2026 10:16:00"));
	track[0].push(new TrackPoint(36.865507, 136.958618, 21.493, 0, 0, 0, "Sun Jul 26 2026 10:17:00"));
	track[0].push(new TrackPoint(36.947583, 137.033088, 32.763, 0, 0, 0, "Sun Jul 26 2026 10:27:00"));
	track[0].push(new TrackPoint(36.948795, 137.030320, 33.044, 0, 0, 0, "Sun Jul 26 2026 10:27:00"));
	track[0].push(new TrackPoint(36.962358, 137.047522, 35.191, 0, 0, 0, "Sun Jul 26 2026 10:29:00"));
	track[0].push(new TrackPoint(36.966675, 137.048847, 35.685, 0, 0, 0, "Sun Jul 26 2026 10:30:00"));
	track[0].push(new TrackPoint(36.998807, 137.043338, 39.284, 0, 0, 0, "Sun Jul 26 2026 10:33:00"));
	track[0].push(new TrackPoint(37.010197, 137.032173, 40.892, 0, 0, 0, "Sun Jul 26 2026 10:35:00"));
	track[0].push(new TrackPoint(37.014940, 137.019108, 42.169, 0, 0, 0, "Sun Jul 26 2026 10:36:00"));
	track[0].push(new TrackPoint(37.016556, 136.962294, 47.228, 0, 0, 0, "Sun Jul 26 2026 10:41:00"));
	track[0].push(new TrackPoint(37.028074, 136.962628, 48.506, 0, 0, 0, "Sun Jul 26 2026 10:44:00"));
	track[0].push(new TrackPoint(37.029375, 136.966198, 48.855, 0, 0, 0, "Sun Jul 26 2026 10:44:00"));
	track[0].push(new TrackPoint(37.037285, 136.969036, 49.769, 0, 0, 0, "Sun Jul 26 2026 10:47:00"));
	track[0].push(new TrackPoint(37.042022, 136.969566, 50.297, 0, 0, 0, "Sun Jul 26 2026 10:48:00"));
	track[0].push(new TrackPoint(37.043768, 136.964169, 50.814, 0, 0, 0, "Sun Jul 26 2026 10:49:00"));
	track[0].push(new TrackPoint(37.046155, 136.958843, 51.357, 0, 0, 0, "Sun Jul 26 2026 10:52:00"));
	track[0].push(new TrackPoint(37.044252, 136.956288, 51.667, 0, 0, 0, "Sun Jul 26 2026 10:53:00"));
	track[0].push(new TrackPoint(37.046570, 136.948115, 52.439, 0, 0, 0, "Sun Jul 26 2026 10:55:00"));
	track[0].push(new TrackPoint(37.052152, 136.925387, 54.553, 0, 0, 0, "Sun Jul 26 2026 10:57:00"));
	track[0].push(new TrackPoint(37.062692, 136.916550, 55.962, 0, 0, 0, "Sun Jul 26 2026 10:59:00"));
	track[0].push(new TrackPoint(37.055935, 136.898282, 57.752, 0, 0, 0, "Sun Jul 26 2026 11:01:00"));
	track[0].push(new TrackPoint(37.054815, 136.883342, 59.087, 0, 0, 0, "Sun Jul 26 2026 11:02:00"));
	track[0].push(new TrackPoint(37.061645, 136.867665, 60.674, 0, 0, 0, "Sun Jul 26 2026 11:03:00"));
	track[0].push(new TrackPoint(37.058637, 136.847855, 62.467, 0, 0, 0, "Sun Jul 26 2026 11:05:00"));
	track[0].push(new TrackPoint(37.063772, 136.832377, 63.957, 0, 0, 0, "Sun Jul 26 2026 11:06:00"));
	track[0].push(new TrackPoint(37.079728, 136.820353, 66.025, 0, 0, 0, "Sun Jul 26 2026 11:08:00"));
	track[0].push(new TrackPoint(37.081250, 136.811943, 66.792, 0, 0, 0, "Sun Jul 26 2026 11:09:00"));
	track[0].push(new TrackPoint(37.086847, 136.807497, 67.528, 0, 0, 0, "Sun Jul 26 2026 11:10:00"));
	track[0].push(new TrackPoint(37.116338, 136.815872, 70.885, 0, 0, 0, "Sun Jul 26 2026 11:13:00"));
	track[0].push(new TrackPoint(37.141309, 136.848056, 74.867, 0, 0, 0, "Sun Jul 26 2026 11:21:00"));
	track[0].push(new TrackPoint(37.178969, 136.855391, 79.097, 0, 0, 0, "Sun Jul 26 2026 11:26:00"));
	track[0].push(new TrackPoint(37.178688, 136.855497, 79.130, 0, 0, 0, "Sun Jul 26 2026 11:33:00"));
	track[0].push(new TrackPoint(37.211899, 136.880906, 83.451, 0, 0, 0, "Sun Jul 26 2026 11:39:00"));
	track[0].push(new TrackPoint(37.269873, 136.918794, 90.711, 0, 0, 0, "Sun Jul 26 2026 11:45:00"));
	track[0].push(new TrackPoint(37.283125, 136.927087, 92.355, 0, 0, 0, "Sun Jul 26 2026 11:48:00"));
	track[0].push(new TrackPoint(37.306942, 136.906375, 95.573, 0, 0, 0, "Sun Jul 26 2026 11:53:00"));
	track[0].push(new TrackPoint(37.319753, 136.910148, 97.034, 0, 0, 0, "Sun Jul 26 2026 11:54:00"));
	track[0].push(new TrackPoint(37.323038, 136.909308, 97.406, 0, 0, 0, "Sun Jul 26 2026 11:55:00"));
	track[0].push(new TrackPoint(37.325890, 136.902423, 98.094, 0, 0, 0, "Sun Jul 26 2026 11:56:00"));
	track[0].push(new TrackPoint(37.341503, 136.897189, 99.888, 0, 0, 0, "Sun Jul 26 2026 11:59:00"));
	track[0].push(new TrackPoint(37.381240, 136.909009, 104.420, 0, 0, 0, "Sun Jul 26 2026 12:05:00"));
	track[0].push(new TrackPoint(37.389225, 136.906199, 105.341, 0, 0, 0, "Sun Jul 26 2026 12:07:00"));
	track[0].push(new TrackPoint(37.386478, 136.905872, 105.647, 0, 0, 0, "Sun Jul 26 2026 12:09:00"));
	track[0].push(new TrackPoint(37.388948, 136.906334, 105.924, 0, 0, 0, "Sun Jul 26 2026 12:13:00"));
	track[0].push(new TrackPoint(37.389168, 136.906377, 105.949, 0, 0, 0, "Sun Jul 26 2026 12:24:00"));
	track[0].push(new TrackPoint(37.393374, 136.904705, 106.439, 0, 0, 0, "Sun Jul 26 2026 12:28:00"));
	track[0].push(new TrackPoint(37.395650, 136.905499, 106.701, 0, 0, 0, "Sun Jul 26 2026 12:29:00"));
	track[0].push(new TrackPoint(37.394652, 136.920580, 108.041, 0, 0, 0, "Sun Jul 26 2026 12:34:00"));
	track[0].push(new TrackPoint(37.401313, 136.943633, 110.212, 0, 0, 0, "Sun Jul 26 2026 12:38:00"));
	track[0].push(new TrackPoint(37.402202, 136.949832, 110.769, 0, 0, 0, "Sun Jul 26 2026 12:40:00"));
	track[0].push(new TrackPoint(37.410711, 136.969695, 112.766, 0, 0, 0, "Sun Jul 26 2026 12:46:00"));
	track[0].push(new TrackPoint(37.409933, 136.973277, 113.094, 0, 0, 0, "Sun Jul 26 2026 12:47:00"));
	track[0].push(new TrackPoint(37.410710, 136.973838, 113.194, 0, 0, 0, "Sun Jul 26 2026 13:35:00"));
	track[0].push(new TrackPoint(37.424240, 136.997813, 115.794, 0, 0, 0, "Sun Jul 26 2026 13:40:00"));
	track[0].push(new TrackPoint(37.424239, 136.997808, 115.794, 0, 0, 0, "Sun Jul 26 2026 14:10:00"));
	track[0].push(new TrackPoint(37.425620, 137.000161, 116.053, 0, 0, 0, "Sun Jul 26 2026 14:11:00"));
	track[0].push(new TrackPoint(37.432334, 137.021560, 118.088, 0, 0, 0, "Sun Jul 26 2026 14:16:00"));
	track[0].push(new TrackPoint(37.432231, 137.027817, 118.642, 0, 0, 0, "Sun Jul 26 2026 14:17:00"));
	track[0].push(new TrackPoint(37.433691, 137.031172, 118.980, 0, 0, 0, "Sun Jul 26 2026 14:18:00"));
	track[0].push(new TrackPoint(37.442628, 137.043212, 120.436, 0, 0, 0, "Sun Jul 26 2026 14:22:00"));
	track[0].push(new TrackPoint(37.449575, 137.065298, 122.537, 0, 0, 0, "Sun Jul 26 2026 14:25:00"));
	track[0].push(new TrackPoint(37.449217, 137.070313, 122.982, 0, 0, 0, "Sun Jul 26 2026 14:26:00"));
	track[0].push(new TrackPoint(37.462144, 137.081134, 124.707, 0, 0, 0, "Sun Jul 26 2026 14:29:00"));
	track[0].push(new TrackPoint(37.472400, 137.092720, 126.239, 0, 0, 0, "Sun Jul 26 2026 14:33:00"));
	track[0].push(new TrackPoint(37.471147, 137.090345, 126.491, 0, 0, 0, "Sun Jul 26 2026 14:38:00"));
	track[0].push(new TrackPoint(37.473200, 137.093705, 126.865, 0, 0, 0, "Sun Jul 26 2026 14:40:00"));
	track[0].push(new TrackPoint(37.474060, 137.096443, 127.126, 0, 0, 0, "Sun Jul 26 2026 14:42:00"));
	track[0].push(new TrackPoint(37.471527, 137.093248, 127.524, 0, 0, 0, "Sun Jul 26 2026 14:45:00"));
	track[0].push(new TrackPoint(37.471150, 137.090195, 127.798, 0, 0, 0, "Sun Jul 26 2026 14:46:00"));
	track[0].push(new TrackPoint(37.466335, 137.086620, 128.419, 0, 0, 0, "Sun Jul 26 2026 14:47:00"));
	track[0].push(new TrackPoint(37.459745, 137.077483, 129.509, 0, 0, 0, "Sun Jul 26 2026 14:52:00"));
	track[0].push(new TrackPoint(37.428129, 137.087119, 133.120, 0, 0, 0, "Sun Jul 26 2026 14:59:00"));
	track[0].push(new TrackPoint(37.387301, 137.112701, 138.186, 0, 0, 0, "Sun Jul 26 2026 15:07:00"));
	track[0].push(new TrackPoint(37.381069, 137.114874, 138.904, 0, 0, 0, "Sun Jul 26 2026 15:09:00"));
	track[0].push(new TrackPoint(37.368589, 137.099152, 140.868, 0, 0, 0, "Sun Jul 26 2026 15:12:00"));
	track[0].push(new TrackPoint(37.354039, 137.100510, 142.487, 0, 0, 0, "Sun Jul 26 2026 15:15:00"));
	track[0].push(new TrackPoint(37.350382, 137.128235, 144.977, 0, 0, 0, "Sun Jul 26 2026 15:19:00"));
	track[0].push(new TrackPoint(37.365628, 137.188700, 150.594, 0, 0, 0, "Sun Jul 26 2026 15:25:00"));
	track[0].push(new TrackPoint(37.397504, 137.236191, 156.090, 0, 0, 0, "Sun Jul 26 2026 15:31:00"));
	track[0].push(new TrackPoint(37.412224, 137.235286, 157.726, 0, 0, 0, "Sun Jul 26 2026 15:34:00"));
	track[0].push(new TrackPoint(37.427867, 137.248296, 159.809, 0, 0, 0, "Sun Jul 26 2026 15:36:00"));
	track[0].push(new TrackPoint(37.441237, 137.270377, 162.263, 0, 0, 0, "Sun Jul 26 2026 15:40:00"));
	track[0].push(new TrackPoint(37.441467, 137.269975, 162.307, 0, 0, 0, "Sun Jul 26 2026 16:23:00"));
	track[0].push(new TrackPoint(37.441254, 137.273021, 162.578, 0, 0, 0, "Sun Jul 26 2026 16:27:00"));
	track[0].push(new TrackPoint(37.445096, 137.291791, 164.292, 0, 0, 0, "Sun Jul 26 2026 16:31:00"));
	track[0].push(new TrackPoint(37.466412, 137.322148, 167.872, 0, 0, 0, "Sun Jul 26 2026 16:39:00"));
	track[0].push(new TrackPoint(37.472881, 137.306805, 169.407, 0, 0, 0, "Sun Jul 26 2026 16:41:00"));
	track[0].push(new TrackPoint(37.475717, 137.306526, 169.723, 0, 0, 0, "Sun Jul 26 2026 16:41:00"));
	track[0].push(new TrackPoint(37.478050, 137.308322, 170.027, 0, 0, 0, "Sun Jul 26 2026 16:42:00"));
	track[0].push(new TrackPoint(37.480188, 137.311375, 170.386, 0, 0, 0, "Sun Jul 26 2026 16:43:00"));
	track[0].push(new TrackPoint(37.486130, 137.314985, 171.119, 0, 0, 0, "Sun Jul 26 2026 16:44:00"));
	track[0].push(new TrackPoint(37.488150, 137.315627, 171.350, 0, 0, 0, "Sun Jul 26 2026 16:46:00"));
	track[0].push(new TrackPoint(37.490800, 137.316667, 171.658, 0, 0, 0, "Sun Jul 26 2026 16:46:00"));
	track[0].push(new TrackPoint(37.493402, 137.314885, 171.987, 0, 0, 0, "Sun Jul 26 2026 16:47:00"));
	track[0].push(new TrackPoint(37.502955, 137.311138, 173.098, 0, 0, 0, "Sun Jul 26 2026 16:50:00"));
	track[0].push(new TrackPoint(37.505247, 137.308775, 173.427, 0, 0, 0, "Sun Jul 26 2026 16:50:00"));
	track[0].push(new TrackPoint(37.505748, 137.306237, 173.659, 0, 0, 0, "Sun Jul 26 2026 16:51:00"));
	track[0].push(new TrackPoint(37.507988, 137.306677, 173.910, 0, 0, 0, "Sun Jul 26 2026 16:52:00"));
	track[0].push(new TrackPoint(37.510247, 137.305318, 174.188, 0, 0, 0, "Sun Jul 26 2026 16:53:00"));
	track[0].push(new TrackPoint(37.514237, 137.299018, 174.900, 0, 0, 0, "Sun Jul 26 2026 16:54:00"));
	track[0].push(new TrackPoint(37.516815, 137.297118, 175.231, 0, 0, 0, "Sun Jul 26 2026 16:55:00"));
	track[0].push(new TrackPoint(37.520055, 137.298383, 175.608, 0, 0, 0, "Sun Jul 26 2026 16:55:00"));
	track[0].push(new TrackPoint(37.522827, 137.302363, 176.075, 0, 0, 0, "Sun Jul 26 2026 16:56:00"));
	track[0].push(new TrackPoint(37.526067, 137.325252, 178.130, 0, 0, 0, "Sun Jul 26 2026 16:59:00"));
	track[0].push(new TrackPoint(37.529050, 137.325977, 178.468, 0, 0, 0, "Sun Jul 26 2026 17:12:00"));
	track[0].push(new TrackPoint(37.528857, 137.325970, 178.489, 0, 0, 0, "Sun Jul 26 2026 17:21:00"));
	track[0].push(new TrackPoint(37.524729, 137.325861, 178.947, 0, 0, 0, "Sun Jul 26 2026 17:29:00"));
	track[0].push(new TrackPoint(37.500836, 137.348204, 182.254, 0, 0, 0, "Sun Jul 26 2026 17:38:00"));
	track[0].push(new TrackPoint(37.497923, 137.347522, 182.583, 0, 0, 0, "Sun Jul 26 2026 17:42:00"));
	track[0].push(new TrackPoint(37.498820, 137.346078, 182.745, 0, 0, 0, "Sun Jul 26 2026 17:43:00"));
	track[0].push(new TrackPoint(37.496723, 137.346757, 182.985, 0, 0, 0, "Sun Jul 26 2026 17:46:00"));
	track[0].push(new TrackPoint(37.498066, 137.346194, 183.142, 0, 0, 0, "Sun Jul 26 2026 17:49:00"));
	track[0].push(new TrackPoint(37.467010, 137.349453, 186.601, 0, 0, 0, "Sun Jul 26 2026 18:03:00"));
	track[0].push(new TrackPoint(37.455317, 137.359122, 188.155, 0, 0, 0, "Sun Jul 26 2026 18:06:00"));
	track[0].push(new TrackPoint(37.450487, 137.356568, 188.737, 0, 0, 0, "Sun Jul 26 2026 18:08:00"));
	track[0].push(new TrackPoint(37.443230, 137.343192, 190.169, 0, 0, 0, "Sun Jul 26 2026 18:11:00"));
	track[0].push(new TrackPoint(37.441035, 137.316405, 192.552, 0, 0, 0, "Sun Jul 26 2026 18:16:00"));
	track[0].push(new TrackPoint(37.444732, 137.294848, 194.503, 0, 0, 0, "Sun Jul 26 2026 18:19:00"));
	track[0].push(new TrackPoint(37.445783, 137.292720, 194.725, 0, 0, 0, "Sun Jul 26 2026 18:20:00"));
	track[0].push(new TrackPoint(37.444727, 137.288928, 195.080, 0, 0, 0, "Sun Jul 26 2026 18:21:00"));
	track[0].push(new TrackPoint(37.441237, 137.275495, 196.330, 0, 0, 0, "Sun Jul 26 2026 18:24:00"));
	track[0].push(new TrackPoint(37.432602, 137.257536, 198.186, 0, 0, 0, "Sun Jul 26 2026 18:27:00"));
	track[0].push(new TrackPoint(37.426743, 137.251378, 199.035, 0, 0, 0, "Sun Jul 26 2026 18:29:00"));
	track[0].push(new TrackPoint(37.411615, 137.245147, 200.802, 0, 0, 0, "Sun Jul 26 2026 18:31:00"));
	track[0].push(new TrackPoint(37.409437, 137.242670, 201.128, 0, 0, 0, "Sun Jul 26 2026 18:32:00"));
	track[0].push(new TrackPoint(37.402697, 137.240780, 201.895, 0, 0, 0, "Sun Jul 26 2026 18:33:00"));
	track[0].push(new TrackPoint(37.401638, 137.233813, 202.523, 0, 0, 0, "Sun Jul 26 2026 18:35:00"));
	track[0].push(new TrackPoint(37.397747, 137.235402, 202.977, 0, 0, 0, "Sun Jul 26 2026 18:36:00"));
	track[0].push(new TrackPoint(37.393000, 137.234225, 203.514, 0, 0, 0, "Sun Jul 26 2026 18:37:00"));
	track[0].push(new TrackPoint(37.391962, 137.237118, 203.795, 0, 0, 0, "Sun Jul 26 2026 18:38:00"));
	track[0].push(new TrackPoint(37.374690, 137.237288, 205.712, 0, 0, 0, "Sun Jul 26 2026 18:40:00"));
	track[0].push(new TrackPoint(37.370940, 137.239713, 206.180, 0, 0, 0, "Sun Jul 26 2026 18:41:00"));
	track[0].push(new TrackPoint(37.369668, 137.243523, 206.546, 0, 0, 0, "Sun Jul 26 2026 18:42:00"));
	track[0].push(new TrackPoint(37.367590, 137.244823, 206.804, 0, 0, 0, "Sun Jul 26 2026 18:43:00"));
	track[0].push(new TrackPoint(37.367862, 137.244364, 206.855, 0, 0, 0, "Sun Jul 26 2026 18:48:00"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
	var count = 0;
	for (i=0; i<track.length; i++) {
		count += track[i].length;
	}

	if (count > 1 && !playing) {
		centerPointer.addTo(map);

		if (showMeterPanel) {
			infoPanel = new InfoPanel();
			map.addControl(infoPanel);
		}

		playing = true;
		goForward();
	}
}

function goForward() {
	var waittime;
	var pos = track[currTrack][currPoint].latlng;
	map.panTo(pos);
	centerPointer.setLatLng(pos);

	if (showMeterPanel) {
		displayInfoPanel(currTrack, currPoint);
	}

	if (currPoint < track[currTrack].length - 1) {
		if (realTimePlay) {
			waittime = track[currTrack][currPoint+1].time.getTime() - track[currTrack][currPoint].time.getTime();
			waittime /= parseFloat(document.getElementById("playSpeed").value);
		}
		else {
			waittime = 1000 / parseFloat(document.getElementById("playSpeed").value);
		}
		currPoint++;
	}
	else {
		if (currTrack < track.length - 1) {
			waittime = 1000;
			currTrack++;
			currPoint = 0;
		}
		else {
			window.clearTimeout(playTimer);
			playing = false;
			centerPointer.remove();

			if (showMeterPanel) {
				map.removeControl(infoPanel);
			}

			return;
		}
	}
	playTimer = window.setTimeout("goForward()", waittime);
}

function stopRoute() {
	if (playing) {
		window.clearTimeout(playTimer);
		playing = false;
		centerPointer.remove();

		if (showMeterPanel) {
			map.removeControl(infoPanel);
		}
	}
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
