// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([36.577601, 136.627925], [37.397941, 137.263887]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(37.397732, 137.243602, 0, "2026/07/27", "08:58:00", 0, "見附島の鐘", "files/IMG_20260727_090409_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.397743, 137.243707, 0, "2026/07/27", "09:14:00", 0, "見附島", "files/IMG_20260727_091141_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.312388, 137.229975, 0, "2026/07/27", "09:40:00", 0, "イカキング", "files/IMG_20260727_094320_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.312172, 137.230011, 38, "2026/07/27", "09:45:29", 0, "イカキングに食われる友子", "files/IMG_20260727_094529.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.312183, 137.229996, 41, "2026/07/27", "09:47:01", 0, "イカキングに食われる美穂", "files/IMG_20260727_094701_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.233237, 136.951732, 0, "2026/07/27", "11:35:00", 0, "ボラ待ちやぐら", "files/IMG_20260727_113505_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.165396, 136.886817, 0, "2026/07/27", "12:16:00", 0, "なぎさガーデン・刺身定食", "files/IMG_20260727_121710.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(37.165396, 136.886817, 0, "2026/07/27", "12:16:00", 0, "なぎさガーデン・生ガキ", "files/IMG_20260727_121719.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(36.847693, 136.752522, 0, "2026/07/27", "14:08:00", 0, "千里浜", "files/IMG_20260727_140855_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(36.847848, 136.752513, 0, "2026/07/27", "14:13:00", 0, "千里浜", "files/IMG_20260727_141233_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(36.886082, 136.768358, 0, "2026/07/27", "14:33:00", 0, "千里浜の砂で作られた像", "files/IMG_20260727_143333.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(36.886082, 136.768358, 0, "2026/07/27", "14:33:00", 0, "千里浜近くの道の駅", "files/IMG_20260727_144425_1.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(37.367830, 137.244324, 0.110, 0, 0, 0, "Mon Jul 27 2026 08:48:00"));
	track[0].push(new TrackPoint(37.366713, 137.242367, 0.323, 0, 0, 0, "Mon Jul 27 2026 08:50:00"));
	track[0].push(new TrackPoint(37.369595, 137.243392, 0.655, 0, 0, 0, "Mon Jul 27 2026 08:51:00"));
	track[0].push(new TrackPoint(37.370195, 137.240178, 0.947, 0, 0, 0, "Mon Jul 27 2026 08:51:00"));
	track[0].push(new TrackPoint(37.382182, 137.235912, 2.330, 0, 0, 0, "Mon Jul 27 2026 08:54:00"));
	track[0].push(new TrackPoint(37.397941, 137.242801, 4.183, 0, 0, 0, "Mon Jul 27 2026 08:57:00"));
	track[0].push(new TrackPoint(37.397732, 137.243602, 4.258, 0, 0, 0, "Mon Jul 27 2026 08:58:00"));
	track[0].push(new TrackPoint(37.397743, 137.243707, 4.267, 0, 0, 0, "Mon Jul 27 2026 09:14:00"));
	track[0].push(new TrackPoint(37.397837, 137.235673, 4.978, 0, 0, 0, "Mon Jul 27 2026 09:17:00"));
	track[0].push(new TrackPoint(37.359399, 137.241884, 9.280, 0, 0, 0, "Mon Jul 27 2026 09:24:00"));
	track[0].push(new TrackPoint(37.355273, 137.242807, 9.745, 0, 0, 0, "Mon Jul 27 2026 09:25:00"));
	track[0].push(new TrackPoint(37.349305, 137.250152, 10.673, 0, 0, 0, "Mon Jul 27 2026 09:26:00"));
	track[0].push(new TrackPoint(37.344830, 137.251260, 11.180, 0, 0, 0, "Mon Jul 27 2026 09:27:00"));
	track[0].push(new TrackPoint(37.339885, 137.246723, 11.860, 0, 0, 0, "Mon Jul 27 2026 09:28:00"));
	track[0].push(new TrackPoint(37.341960, 137.248629, 12.145, 0, 0, 0, "Mon Jul 27 2026 09:29:00"));
	track[0].push(new TrackPoint(37.333813, 137.251855, 13.094, 0, 0, 0, "Mon Jul 27 2026 09:30:00"));
	track[0].push(new TrackPoint(37.326387, 137.263887, 14.441, 0, 0, 0, "Mon Jul 27 2026 09:32:00"));
	track[0].push(new TrackPoint(37.325128, 137.260518, 14.771, 0, 0, 0, "Mon Jul 27 2026 09:33:00"));
	track[0].push(new TrackPoint(37.321385, 137.258808, 15.213, 0, 0, 0, "Mon Jul 27 2026 09:33:00"));
	track[0].push(new TrackPoint(37.317163, 137.250572, 16.081, 0, 0, 0, "Mon Jul 27 2026 09:34:00"));
	track[0].push(new TrackPoint(37.307867, 137.246815, 17.165, 0, 0, 0, "Mon Jul 27 2026 09:37:00"));
	track[0].push(new TrackPoint(37.307283, 137.242512, 17.552, 0, 0, 0, "Mon Jul 27 2026 09:37:00"));
	track[0].push(new TrackPoint(37.308283, 137.240220, 17.783, 0, 0, 0, "Mon Jul 27 2026 09:38:00"));
	track[0].push(new TrackPoint(37.312348, 137.236820, 18.326, 0, 0, 0, "Mon Jul 27 2026 09:39:00"));
	track[0].push(new TrackPoint(37.314005, 137.231963, 18.794, 0, 0, 0, "Mon Jul 27 2026 09:39:00"));
	track[0].push(new TrackPoint(37.312388, 137.229975, 19.046, 0, 0, 0, "Mon Jul 27 2026 09:40:00"));
	track[0].push(new TrackPoint(37.312084, 137.229741, 19.085, 0, 0, 0, "Mon Jul 27 2026 10:22:00"));
	track[0].push(new TrackPoint(37.308113, 137.225898, 19.642, 0, 0, 0, "Mon Jul 27 2026 10:24:00"));
	track[0].push(new TrackPoint(37.306068, 137.225832, 19.869, 0, 0, 0, "Mon Jul 27 2026 10:25:00"));
	track[0].push(new TrackPoint(37.300859, 137.228329, 20.488, 0, 0, 0, "Mon Jul 27 2026 10:26:00"));
	track[0].push(new TrackPoint(37.298157, 137.232250, 20.947, 0, 0, 0, "Mon Jul 27 2026 10:28:00"));
	track[0].push(new TrackPoint(37.297292, 137.230210, 21.152, 0, 0, 0, "Mon Jul 27 2026 10:29:00"));
	track[0].push(new TrackPoint(37.296802, 137.227828, 21.370, 0, 0, 0, "Mon Jul 27 2026 10:30:00"));
	track[0].push(new TrackPoint(37.295247, 137.225393, 21.647, 0, 0, 0, "Mon Jul 27 2026 10:31:00"));
	track[0].push(new TrackPoint(37.297203, 137.229720, 22.087, 0, 0, 0, "Mon Jul 27 2026 10:33:00"));
	track[0].push(new TrackPoint(37.297698, 137.232587, 22.347, 0, 0, 0, "Mon Jul 27 2026 10:33:00"));
	track[0].push(new TrackPoint(37.299719, 137.228533, 22.771, 0, 0, 0, "Mon Jul 27 2026 10:35:00"));
	track[0].push(new TrackPoint(37.303582, 137.212597, 24.248, 0, 0, 0, "Mon Jul 27 2026 10:37:00"));
	track[0].push(new TrackPoint(37.300323, 137.199982, 25.423, 0, 0, 0, "Mon Jul 27 2026 10:39:00"));
	track[0].push(new TrackPoint(37.298487, 137.196970, 25.759, 0, 0, 0, "Mon Jul 27 2026 10:40:00"));
	track[0].push(new TrackPoint(37.299040, 137.192620, 26.150, 0, 0, 0, "Mon Jul 27 2026 10:41:00"));
	track[0].push(new TrackPoint(37.301155, 137.189722, 26.498, 0, 0, 0, "Mon Jul 27 2026 10:42:00"));
	track[0].push(new TrackPoint(37.300798, 137.186377, 26.797, 0, 0, 0, "Mon Jul 27 2026 10:42:00"));
	track[0].push(new TrackPoint(37.299040, 137.184673, 27.044, 0, 0, 0, "Mon Jul 27 2026 10:43:00"));
	track[0].push(new TrackPoint(37.300880, 137.175432, 27.888, 0, 0, 0, "Mon Jul 27 2026 10:44:00"));
	track[0].push(new TrackPoint(37.299720, 137.171012, 28.300, 0, 0, 0, "Mon Jul 27 2026 10:45:00"));
	track[0].push(new TrackPoint(37.302823, 137.168852, 28.695, 0, 0, 0, "Mon Jul 27 2026 10:46:00"));
	track[0].push(new TrackPoint(37.304930, 137.163710, 29.207, 0, 0, 0, "Mon Jul 27 2026 10:47:00"));
	track[0].push(new TrackPoint(37.304713, 137.158625, 29.658, 0, 0, 0, "Mon Jul 27 2026 10:48:00"));
	track[0].push(new TrackPoint(37.306373, 137.155612, 29.983, 0, 0, 0, "Mon Jul 27 2026 10:49:00"));
	track[0].push(new TrackPoint(37.306972, 137.150600, 30.432, 0, 0, 0, "Mon Jul 27 2026 10:50:00"));
	track[0].push(new TrackPoint(37.310018, 137.146238, 30.946, 0, 0, 0, "Mon Jul 27 2026 10:52:00"));
	track[0].push(new TrackPoint(37.299873, 137.143357, 32.100, 0, 0, 0, "Mon Jul 27 2026 10:55:00"));
	track[0].push(new TrackPoint(37.298045, 137.142508, 32.317, 0, 0, 0, "Mon Jul 27 2026 10:56:00"));
	track[0].push(new TrackPoint(37.288100, 137.115792, 34.930, 0, 0, 0, "Mon Jul 27 2026 11:00:00"));
	track[0].push(new TrackPoint(37.280433, 137.106370, 36.123, 0, 0, 0, "Mon Jul 27 2026 11:01:00"));
	track[0].push(new TrackPoint(37.279635, 137.100558, 36.646, 0, 0, 0, "Mon Jul 27 2026 11:02:00"));
	track[0].push(new TrackPoint(37.275802, 137.096738, 37.189, 0, 0, 0, "Mon Jul 27 2026 11:03:00"));
	track[0].push(new TrackPoint(37.267118, 137.093600, 38.192, 0, 0, 0, "Mon Jul 27 2026 11:04:00"));
	track[0].push(new TrackPoint(37.263137, 137.089625, 38.758, 0, 0, 0, "Mon Jul 27 2026 11:05:00"));
	track[0].push(new TrackPoint(37.258287, 137.089337, 39.297, 0, 0, 0, "Mon Jul 27 2026 11:05:00"));
	track[0].push(new TrackPoint(37.255903, 137.081580, 40.034, 0, 0, 0, "Mon Jul 27 2026 11:07:00"));
	track[0].push(new TrackPoint(37.264877, 137.065487, 41.774, 0, 0, 0, "Mon Jul 27 2026 11:09:00"));
	track[0].push(new TrackPoint(37.266140, 137.059198, 42.350, 0, 0, 0, "Mon Jul 27 2026 11:10:00"));
	track[0].push(new TrackPoint(37.271434, 137.056456, 42.985, 0, 0, 0, "Mon Jul 27 2026 11:11:00"));
	track[0].push(new TrackPoint(37.276108, 137.053422, 43.570, 0, 0, 0, "Mon Jul 27 2026 11:13:00"));
	track[0].push(new TrackPoint(37.280982, 137.043315, 44.617, 0, 0, 0, "Mon Jul 27 2026 11:14:00"));
	track[0].push(new TrackPoint(37.281632, 137.032693, 45.562, 0, 0, 0, "Mon Jul 27 2026 11:15:00"));
	track[0].push(new TrackPoint(37.275225, 137.024352, 46.588, 0, 0, 0, "Mon Jul 27 2026 11:17:00"));
	track[0].push(new TrackPoint(37.267817, 137.007390, 48.302, 0, 0, 0, "Mon Jul 27 2026 11:22:00"));
	track[0].push(new TrackPoint(37.255065, 137.004620, 49.738, 0, 0, 0, "Mon Jul 27 2026 11:25:00"));
	track[0].push(new TrackPoint(37.241767, 136.987662, 51.846, 0, 0, 0, "Mon Jul 27 2026 11:28:00"));
	track[0].push(new TrackPoint(37.241728, 136.980690, 52.465, 0, 0, 0, "Mon Jul 27 2026 11:29:00"));
	track[0].push(new TrackPoint(37.237710, 136.979567, 52.922, 0, 0, 0, "Mon Jul 27 2026 11:29:00"));
	track[0].push(new TrackPoint(37.234370, 136.970143, 53.836, 0, 0, 0, "Mon Jul 27 2026 11:31:00"));
	track[0].push(new TrackPoint(37.236323, 136.959523, 54.803, 0, 0, 0, "Mon Jul 27 2026 11:32:00"));
	track[0].push(new TrackPoint(37.235437, 136.955207, 55.199, 0, 0, 0, "Mon Jul 27 2026 11:33:00"));
	track[0].push(new TrackPoint(37.233432, 136.951860, 55.570, 0, 0, 0, "Mon Jul 27 2026 11:34:00"));
	track[0].push(new TrackPoint(37.233237, 136.951732, 55.594, 0, 0, 0, "Mon Jul 27 2026 11:35:00"));
	track[0].push(new TrackPoint(37.235579, 136.966065, 56.892, 0, 0, 0, "Mon Jul 27 2026 11:40:00"));
	track[0].push(new TrackPoint(37.232818, 136.947255, 58.589, 0, 0, 0, "Mon Jul 27 2026 11:41:00"));
	track[0].push(new TrackPoint(37.230015, 136.948782, 58.929, 0, 0, 0, "Mon Jul 27 2026 11:41:00"));
	track[0].push(new TrackPoint(37.238523, 136.937077, 60.333, 0, 0, 0, "Mon Jul 27 2026 11:45:00"));
	track[0].push(new TrackPoint(37.235922, 136.923265, 61.592, 0, 0, 0, "Mon Jul 27 2026 11:47:00"));
	track[0].push(new TrackPoint(37.235979, 136.906485, 63.081, 0, 0, 0, "Mon Jul 27 2026 11:49:00"));
	track[0].push(new TrackPoint(37.230195, 136.910238, 63.804, 0, 0, 0, "Mon Jul 27 2026 11:51:00"));
	track[0].push(new TrackPoint(37.226653, 136.909620, 64.201, 0, 0, 0, "Mon Jul 27 2026 11:52:00"));
	track[0].push(new TrackPoint(37.225085, 136.907910, 64.432, 0, 0, 0, "Mon Jul 27 2026 11:52:00"));
	track[0].push(new TrackPoint(37.220232, 136.906112, 64.994, 0, 0, 0, "Mon Jul 27 2026 11:53:00"));
	track[0].push(new TrackPoint(37.205438, 136.907612, 66.641, 0, 0, 0, "Mon Jul 27 2026 11:56:00"));
	track[0].push(new TrackPoint(37.203279, 136.905819, 66.928, 0, 0, 0, "Mon Jul 27 2026 11:57:00"));
	track[0].push(new TrackPoint(37.191980, 136.907029, 68.187, 0, 0, 0, "Mon Jul 27 2026 11:59:00"));
	track[0].push(new TrackPoint(37.187517, 136.905040, 68.713, 0, 0, 0, "Mon Jul 27 2026 12:00:00"));
	track[0].push(new TrackPoint(37.184572, 136.901137, 69.189, 0, 0, 0, "Mon Jul 27 2026 12:01:00"));
	track[0].push(new TrackPoint(37.171210, 136.890653, 70.940, 0, 0, 0, "Mon Jul 27 2026 12:03:00"));
	track[0].push(new TrackPoint(37.165396, 136.886817, 71.670, 0, 0, 0, "Mon Jul 27 2026 12:09:00"));
	track[0].push(new TrackPoint(37.170757, 136.890412, 72.345, 0, 0, 0, "Mon Jul 27 2026 12:10:00"));
	track[0].push(new TrackPoint(37.165396, 136.886817, 73.020, 0, 0, 0, "Mon Jul 27 2026 12:16:00"));
	track[0].push(new TrackPoint(37.170776, 136.890414, 73.698, 0, 0, 0, "Mon Jul 27 2026 12:21:00"));
	track[0].push(new TrackPoint(37.170902, 136.890587, 73.718, 0, 0, 0, "Mon Jul 27 2026 12:49:00"));
	track[0].push(new TrackPoint(37.148776, 136.876563, 76.472, 0, 0, 0, "Mon Jul 27 2026 12:53:00"));
	track[0].push(new TrackPoint(37.104934, 136.850772, 81.850, 0, 0, 0, "Mon Jul 27 2026 13:03:00"));
	track[0].push(new TrackPoint(37.070252, 136.859083, 85.769, 0, 0, 0, "Mon Jul 27 2026 13:07:00"));
	track[0].push(new TrackPoint(37.068572, 136.856350, 86.076, 0, 0, 0, "Mon Jul 27 2026 13:07:00"));
	track[0].push(new TrackPoint(37.068253, 136.850020, 86.640, 0, 0, 0, "Mon Jul 27 2026 13:08:00"));
	track[0].push(new TrackPoint(37.062627, 136.837180, 87.941, 0, 0, 0, "Mon Jul 27 2026 13:10:00"));
	track[0].push(new TrackPoint(37.061957, 136.832447, 88.369, 0, 0, 0, "Mon Jul 27 2026 13:10:00"));
	track[0].push(new TrackPoint(37.057343, 136.842788, 89.422, 0, 0, 0, "Mon Jul 27 2026 13:12:00"));
	track[0].push(new TrackPoint(37.051097, 136.840673, 90.140, 0, 0, 0, "Mon Jul 27 2026 13:13:00"));
	track[0].push(new TrackPoint(37.018346, 136.812523, 94.554, 0, 0, 0, "Mon Jul 27 2026 13:19:00"));
	track[0].push(new TrackPoint(36.955505, 136.814342, 101.530, 0, 0, 0, "Mon Jul 27 2026 13:25:00"));
	track[0].push(new TrackPoint(36.921775, 136.773963, 106.721, 0, 0, 0, "Mon Jul 27 2026 13:29:00"));
	track[0].push(new TrackPoint(36.915813, 136.774913, 107.388, 0, 0, 0, "Mon Jul 27 2026 13:30:00"));
	track[0].push(new TrackPoint(36.919332, 136.775892, 107.788, 0, 0, 0, "Mon Jul 27 2026 13:31:00"));
	track[0].push(new TrackPoint(36.923770, 136.767797, 108.661, 0, 0, 0, "Mon Jul 27 2026 13:33:00"));
	track[0].push(new TrackPoint(36.925114, 136.766912, 108.830, 0, 0, 0, "Mon Jul 27 2026 13:45:00"));
	track[0].push(new TrackPoint(36.923318, 136.767535, 109.037, 0, 0, 0, "Mon Jul 27 2026 13:47:00"));
	track[0].push(new TrackPoint(36.921700, 136.772225, 109.492, 0, 0, 0, "Mon Jul 27 2026 13:47:00"));
	track[0].push(new TrackPoint(36.918265, 136.776558, 110.034, 0, 0, 0, "Mon Jul 27 2026 13:48:00"));
	track[0].push(new TrackPoint(36.910475, 136.778075, 110.909, 0, 0, 0, "Mon Jul 27 2026 13:50:00"));
	track[0].push(new TrackPoint(36.897152, 136.776068, 112.399, 0, 0, 0, "Mon Jul 27 2026 13:53:00"));
	track[0].push(new TrackPoint(36.894148, 136.777265, 112.749, 0, 0, 0, "Mon Jul 27 2026 13:54:00"));
	track[0].push(new TrackPoint(36.892863, 136.774585, 113.027, 0, 0, 0, "Mon Jul 27 2026 13:55:00"));
	track[0].push(new TrackPoint(36.796852, 136.743885, 124.028, 0, 0, 0, "Mon Jul 27 2026 14:02:00"));
	track[0].push(new TrackPoint(36.847693, 136.752522, 129.722, 0, 0, 0, "Mon Jul 27 2026 14:08:00"));
	track[0].push(new TrackPoint(36.847848, 136.752513, 129.740, 0, 0, 0, "Mon Jul 27 2026 14:13:00"));
	track[0].push(new TrackPoint(36.837390, 136.753664, 130.905, 0, 0, 0, "Mon Jul 27 2026 14:19:00"));
	track[0].push(new TrackPoint(36.918463, 136.774178, 140.086, 0, 0, 0, "Mon Jul 27 2026 14:28:00"));
	track[0].push(new TrackPoint(36.886082, 136.768358, 143.717, 0, 0, 0, "Mon Jul 27 2026 14:33:00"));
	track[0].push(new TrackPoint(36.885602, 136.768612, 143.775, 0, 0, 0, "Mon Jul 27 2026 15:39:00"));
	track[0].push(new TrackPoint(36.885847, 136.766365, 143.977, 0, 0, 0, "Mon Jul 27 2026 15:40:00"));
	track[0].push(new TrackPoint(36.796852, 136.743885, 154.054, 0, 0, 0, "Mon Jul 27 2026 15:47:00"));
	track[0].push(new TrackPoint(36.840855, 136.750035, 158.968, 0, 0, 0, "Mon Jul 27 2026 15:49:00"));
	track[0].push(new TrackPoint(36.833340, 136.751602, 159.814, 0, 0, 0, "Mon Jul 27 2026 15:51:00"));
	track[0].push(new TrackPoint(36.836386, 136.754674, 160.249, 0, 0, 0, "Mon Jul 27 2026 15:53:00"));
	track[0].push(new TrackPoint(36.838393, 136.753568, 160.493, 0, 0, 0, "Mon Jul 27 2026 15:54:00"));
	track[0].push(new TrackPoint(36.787292, 136.722079, 166.822, 0, 0, 0, "Mon Jul 27 2026 16:00:00"));
	track[0].push(new TrackPoint(36.679790, 136.675093, 179.468, 0, 0, 0, "Mon Jul 27 2026 16:10:00"));
	track[0].push(new TrackPoint(36.642868, 136.627925, 185.348, 0, 0, 0, "Mon Jul 27 2026 16:16:00"));
	track[0].push(new TrackPoint(36.624397, 136.636386, 187.533, 0, 0, 0, "Mon Jul 27 2026 16:22:00"));
	track[0].push(new TrackPoint(36.614007, 136.631401, 188.769, 0, 0, 0, "Mon Jul 27 2026 16:25:00"));
	track[0].push(new TrackPoint(36.591925, 136.642491, 191.413, 0, 0, 0, "Mon Jul 27 2026 16:33:00"));
	track[0].push(new TrackPoint(36.589308, 136.646721, 191.890, 0, 0, 0, "Mon Jul 27 2026 16:39:00"));
	track[0].push(new TrackPoint(36.579783, 136.646625, 192.947, 0, 0, 0, "Mon Jul 27 2026 16:45:00"));
	track[0].push(new TrackPoint(36.577601, 136.644682, 193.245, 0, 0, 0, "Mon Jul 27 2026 16:47:00"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
    var count = 0;
    for (i=0; i<track.length; i++) {
        count += track[i].length;
    }

    if (count > 1 && !playing) {
        centerPointer.addTo(map);

        if (showMeterPanel) {
            // 情報パネルがまだ作られていない場合だけ作る
            if (!infoPanel) {
                infoPanel = new InfoPanel();
                map.addControl(infoPanel);
            }
        }

        playing = true;
        goForward();
    }
}

function goForward() {
	var waittime;
	var pos = track[currTrack][currPoint].latlng;
	map.panTo(pos);
	centerPointer.setLatLng(pos);

	if (showMeterPanel) {
		displayInfoPanel(currTrack, currPoint);
	}

	if (currPoint < track[currTrack].length - 1) {
		if (realTimePlay) {
			waittime = track[currTrack][currPoint+1].time.getTime() - track[currTrack][currPoint].time.getTime();
			waittime /= parseFloat(document.getElementById("playSpeed").value);
		}
		else {
			waittime = 1000 / parseFloat(document.getElementById("playSpeed").value);
		}
		currPoint++;
	}
	else {
		if (currTrack < track.length - 1) {
			waittime = 1000;
			currTrack++;
			currPoint = 0;
		}
		else {
		    window.clearTimeout(playTimer);
		    playing = false;
		    centerPointer.remove();

		    // 情報パネルは残す
		    // if (showMeterPanel) {
		    //     map.removeControl(infoPanel);
		    // }

		    return;
		}
	}
	playTimer = window.setTimeout("goForward()", waittime);
}

function stopRoute() {
	if (playing) {
		window.clearTimeout(playTimer);
		playing = false;
		// centerPointer.remove();

		// if (showMeterPanel) {
		// 	map.removeControl(infoPanel);
		// }
	}
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
