// JavaScript generated by Wadachi Version 4.28

var track = new Array();
var route = new Array();
var waypoints = new Array();
var markerIcon = new Array();
var markers = new Array();
var markers = new Array();
var map;
var currPoint = 0;
var currTrack = 0;
var playTimer;
var playing = false;
var centerPointer;
var infoPanel;
var showMeterPanel = true;
var realTimePlay = false;

function displayMap() {
	var osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var osmjp = L.tileLayer("https://tile.openstreetmap.jp/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 19,
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'
	});

	var cjm = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var pale = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'
	});

	var air = L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg", {
		minZoom: 2,
		maxZoom: 18,
		attribution: '&copy; <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a> | データソース: Landsat8画像(GSI,TSIC,GEO Grid/AIST,courtesy of USGS), 海底地形(GEBCO), <a href="https://lpdaac.usgs.gov/data_access" target="_blank">世界衛星モザイク画像</a>(LP DAAC, USGS/EROS Center)'
	});

	map = L.map("map", {layers: [osm]});
	var baseMaps = {"OpenStreetMap本家": osm, "OpenStreetMap日本": osmjp, "地理院地図（標準）": cjm, "地理院地図（淡色）": pale, "空中写真": air};
	L.control.layers(baseMaps).addTo(map);
	L.control.scale({imperial: false}).addTo(map);
	map.addControl(L.control.fullscreen());
	map.fitBounds(L.latLngBounds([35.401763, 139.533245], [35.528311, 139.700266]))
	/*<SetView>*/

	var pointerIcon = L.icon({
		iconUrl: "0524_files/center_pointer.png",
		iconSize: [32, 32],
		iconAnchor: [15, 15]
	});
	centerPointer = L.marker([0, 0], {icon: pointerIcon, zIndexOffset: 9999});

	setIcon();

	setWaypoints();
	setRoutes();
	drawWaypoints(true, true, true, true);
	setTracks();
}

function setWaypoints() {
	waypoints.push(new MarkerInfo(35.523418, 139.691345, 51, "2026/05/24", "07:24:39", 0, "川崎宿", "0524_files/IMG_20260524_072439_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.517609, 139.684113, 41, "2026/05/24", "07:32:57", 0, "市場村一里塚", "0524_files/IMG_20260524_073257.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.495815, 139.674011, 45, "2026/05/24", "07:59:30", 0, "蚊も蚊も発祥の地？", "0524_files/IMG_20260524_075930_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.491577, 139.662872, 0, "2026/05/24", "08:10:09", 0, "生麦事件碑", "0524_files/IMG_20260524_081009.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.470619, 139.625183, 46, "2026/05/24", "08:56:39", 0, "一里塚", "0524_files/IMG_20260524_085639.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.470528, 139.624359, 25, "2026/05/24", "08:58:10", 0, "神奈川宿 袖ヶ浦", "0524_files/IMG_20260524_085811.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.470489, 139.623901, 27, "2026/05/24", "08:59:25", 0, "坂本龍馬の妻おりょうが働いていた田中家", "0524_files/IMG_20260524_085925.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.465828, 139.611832, 45, "2026/05/24", "09:15:48", 0, "歩道橋からランドマークタワーを望む", "0524_files/IMG_20260524_091549.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.459553, 139.606445, 43, "2026/05/24", "09:24:27", 0, "八王子道との追分", "0524_files/IMG_20260524_092427.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.453552, 139.603027, 33, "2026/05/24", "09:36:35", 0, "旧帷子橋跡", "0524_files/IMG_20260524_093635.jpg", "", "初代広重の「東海道五十三次之内　保土ヶ谷」にも描かれている", ""));
	waypoints.push(new MarkerInfo(35.445061, 139.589905, 23, "2026/05/24", "10:01:51", 0, "一里塚・上方見附跡", "0524_files/IMG_20260524_100151_1.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.445072, 139.589889, 24, "2026/05/24", "10:01:59", 0, "一里塚の木", "0524_files/IMG_20260524_100159_1.jpg", "", "保存会の方が、一里塚や見附について説明してくれた上に、冷たい清涼飲料水までくださった。", ""));
	waypoints.push(new MarkerInfo(35.443626, 139.575623, 88, "2026/05/24", "10:22:28", 0, "きつくて有名な権太坂", "0524_files/IMG_20260524_102228.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.436810, 139.567245, 106, "2026/05/24", "10:35:39", 0, "境木立場跡", "0524_files/IMG_20260524_103539.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.432579, 139.564438, 94, "2026/05/24", "10:45:30", 0, "品濃一里塚", "0524_files/IMG_20260524_104530.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.406502, 139.537704, 54, "2026/05/24", "11:28:51", 0, "吉田一里塚跡", "0524_files/IMG_20260524_112851.jpg", "", "", ""));
	waypoints.push(new MarkerInfo(35.402115, 139.533936, 70, "2026/05/24", "11:42:11", 0, "ゴールの戸塚駅", "0524_files/IMG_20260524_114211_1.jpg", "", "", ""));
}

function setRoutes() {
/*<RouteList>*/
}

function setTracks() {

	track[0] = new Array();
	track[0].push(new TrackPoint(35.528310, 139.700265, 0.000, 14, 0, 0, "Sun May 24 2026 07:12:33"));
	track[0].push(new TrackPoint(35.528227, 139.700233, 0.010, 13, 0, 0, "Sun May 24 2026 07:12:43"));
	track[0].push(new TrackPoint(35.528115, 139.700107, 0.028, 12, 0, 0, "Sun May 24 2026 07:13:00"));
	track[0].push(new TrackPoint(35.528140, 139.700067, 0.034, 12, 0, 0, "Sun May 24 2026 07:13:41"));
	track[0].push(new TrackPoint(35.527954, 139.700023, 0.060, 13, 0, 0, "Sun May 24 2026 07:14:05"));
	track[0].push(new TrackPoint(35.527906, 139.699929, 0.070, 14, 0, 0, "Sun May 24 2026 07:14:10"));
	track[0].push(new TrackPoint(35.527899, 139.699858, 0.076, 14, 0, 0, "Sun May 24 2026 07:14:13"));
	track[0].push(new TrackPoint(35.527738, 139.699787, 0.096, 15, 0, 0, "Sun May 24 2026 07:14:29"));
	track[0].push(new TrackPoint(35.527565, 139.699437, 0.135, 13, 0, 0, "Sun May 24 2026 07:14:52"));
	track[0].push(new TrackPoint(35.527496, 139.699208, 0.157, 12, 0, 0, "Sun May 24 2026 07:15:04"));
	track[0].push(new TrackPoint(35.527470, 139.699167, 0.161, 12, 0, 0, "Sun May 24 2026 07:15:09"));
	track[0].push(new TrackPoint(35.527400, 139.699107, 0.172, 11, 0, 0, "Sun May 24 2026 07:15:18"));
	track[0].push(new TrackPoint(35.527288, 139.698909, 0.194, 9, 0, 0, "Sun May 24 2026 07:15:35"));
	track[0].push(new TrackPoint(35.527226, 139.698911, 0.201, 9, 0, 0, "Sun May 24 2026 07:15:40"));
	track[0].push(new TrackPoint(35.527192, 139.698887, 0.205, 9, 0, 0, "Sun May 24 2026 07:15:44"));
	track[0].push(new TrackPoint(35.527139, 139.698565, 0.235, 7, 0, 0, "Sun May 24 2026 07:15:57"));
	track[0].push(new TrackPoint(35.527074, 139.698360, 0.255, 6, 0, 0, "Sun May 24 2026 07:16:05"));
	track[0].push(new TrackPoint(35.526950, 139.698140, 0.279, 7, 0, 0, "Sun May 24 2026 07:16:16"));
	track[0].push(new TrackPoint(35.526873, 139.697963, 0.298, 9, 0, 0, "Sun May 24 2026 07:16:25"));
	track[0].push(new TrackPoint(35.526697, 139.697722, 0.327, 11, 0, 0, "Sun May 24 2026 07:16:40"));
	track[0].push(new TrackPoint(35.526611, 139.697545, 0.346, 12, 0, 0, "Sun May 24 2026 07:16:48"));
	track[0].push(new TrackPoint(35.526574, 139.697394, 0.360, 11, 0, 0, "Sun May 24 2026 07:16:53"));
	track[0].push(new TrackPoint(35.526176, 139.696721, 0.436, 8, 0, 0, "Sun May 24 2026 07:17:28"));
	track[0].push(new TrackPoint(35.526060, 139.696453, 0.463, 8, 0, 0, "Sun May 24 2026 07:17:39"));
	track[0].push(new TrackPoint(35.526024, 139.696439, 0.468, 8, 0, 0, "Sun May 24 2026 07:17:41"));
	track[0].push(new TrackPoint(35.525801, 139.696040, 0.512, 5, 0, 0, "Sun May 24 2026 07:18:14"));
	track[0].push(new TrackPoint(35.525775, 139.695882, 0.528, 4, 0, 0, "Sun May 24 2026 07:19:28"));
	track[0].push(new TrackPoint(35.525721, 139.695784, 0.539, 3, 0, 0, "Sun May 24 2026 07:19:48"));
	track[0].push(new TrackPoint(35.525558, 139.695650, 0.561, 2, 0, 0, "Sun May 24 2026 07:19:59"));
	track[0].push(new TrackPoint(35.525422, 139.695316, 0.595, 6, 0, 0, "Sun May 24 2026 07:20:13"));
	track[0].push(new TrackPoint(35.525373, 139.695179, 0.609, 7, 0, 0, "Sun May 24 2026 07:20:19"));
	track[0].push(new TrackPoint(35.525283, 139.695115, 0.621, 8, 0, 0, "Sun May 24 2026 07:20:25"));
	track[0].push(new TrackPoint(35.525195, 139.694843, 0.648, 8, 0, 0, "Sun May 24 2026 07:20:36"));
	track[0].push(new TrackPoint(35.524663, 139.694071, 0.740, 7, 0, 0, "Sun May 24 2026 07:21:20"));
	track[0].push(new TrackPoint(35.524592, 139.693884, 0.758, 8, 0, 0, "Sun May 24 2026 07:21:27"));
	track[0].push(new TrackPoint(35.524441, 139.693590, 0.790, 8, 0, 0, "Sun May 24 2026 07:21:41"));
	track[0].push(new TrackPoint(35.524390, 139.693449, 0.804, 7, 0, 0, "Sun May 24 2026 07:21:47"));
	track[0].push(new TrackPoint(35.524242, 139.693263, 0.828, 6, 0, 0, "Sun May 24 2026 07:22:01"));
	track[0].push(new TrackPoint(35.524103, 139.692986, 0.858, 4, 0, 0, "Sun May 24 2026 07:22:23"));
	track[0].push(new TrackPoint(35.524078, 139.692993, 0.861, 4, 0, 0, "Sun May 24 2026 07:22:27"));
	track[0].push(new TrackPoint(35.524045, 139.692942, 0.867, 3, 0, 0, "Sun May 24 2026 07:22:32"));
	track[0].push(new TrackPoint(35.523974, 139.692754, 0.886, 2, 0, 0, "Sun May 24 2026 07:22:46"));
	track[0].push(new TrackPoint(35.523949, 139.692742, 0.890, 2, 0, 0, "Sun May 24 2026 07:22:49"));
	track[0].push(new TrackPoint(35.523930, 139.692519, 0.910, 0, 0, 0, "Sun May 24 2026 07:23:02"));
	track[0].push(new TrackPoint(35.523958, 139.692516, 0.913, 0, 0, 0, "Sun May 24 2026 07:23:06"));
	track[0].push(new TrackPoint(35.523901, 139.692400, 0.926, 1, 0, 0, "Sun May 24 2026 07:23:21"));
	track[0].push(new TrackPoint(35.523703, 139.692226, 0.953, 0, 0, 0, "Sun May 24 2026 07:23:35"));
	track[0].push(new TrackPoint(35.523528, 139.692192, 0.973, 0, 0, 0, "Sun May 24 2026 07:23:45"));
	track[0].push(new TrackPoint(35.523473, 139.692084, 0.984, 1, 0, 0, "Sun May 24 2026 07:23:51"));
	track[0].push(new TrackPoint(35.523512, 139.691911, 1.001, 1, 0, 0, "Sun May 24 2026 07:23:59"));
	track[0].push(new TrackPoint(35.523521, 139.691758, 1.014, 1, 0, 0, "Sun May 24 2026 07:24:06"));
	track[0].push(new TrackPoint(35.523302, 139.691358, 1.059, -0, 0, 0, "Sun May 24 2026 07:24:52"));
	track[0].push(new TrackPoint(35.523102, 139.691203, 1.085, -1, 0, 0, "Sun May 24 2026 07:25:04"));
	track[0].push(new TrackPoint(35.522943, 139.690997, 1.111, -0, 0, 0, "Sun May 24 2026 07:25:17"));
	track[0].push(new TrackPoint(35.522868, 139.690804, 1.130, 0, 0, 0, "Sun May 24 2026 07:25:25"));
	track[0].push(new TrackPoint(35.522580, 139.690523, 1.172, 4, 0, 0, "Sun May 24 2026 07:25:44"));
	track[0].push(new TrackPoint(35.522501, 139.690340, 1.191, 5, 0, 0, "Sun May 24 2026 07:25:52"));
	track[0].push(new TrackPoint(35.522468, 139.690304, 1.195, 5, 0, 0, "Sun May 24 2026 07:25:54"));
	track[0].push(new TrackPoint(35.522403, 139.690133, 1.213, 5, 0, 0, "Sun May 24 2026 07:26:02"));
	track[0].push(new TrackPoint(35.522293, 139.689936, 1.234, 5, 0, 0, "Sun May 24 2026 07:26:12"));
	track[0].push(new TrackPoint(35.522121, 139.689687, 1.264, 5, 0, 0, "Sun May 24 2026 07:26:26"));
	track[0].push(new TrackPoint(35.521950, 139.689507, 1.289, 4, 0, 0, "Sun May 24 2026 07:26:39"));
	track[0].push(new TrackPoint(35.521885, 139.689352, 1.305, 3, 0, 0, "Sun May 24 2026 07:26:46"));
	track[0].push(new TrackPoint(35.521837, 139.689325, 1.311, 3, 0, 0, "Sun May 24 2026 07:26:49"));
	track[0].push(new TrackPoint(35.521794, 139.689253, 1.319, 3, 0, 0, "Sun May 24 2026 07:26:53"));
	track[0].push(new TrackPoint(35.521697, 139.689154, 1.333, 2, 0, 0, "Sun May 24 2026 07:27:00"));
	track[0].push(new TrackPoint(35.521542, 139.688911, 1.361, 1, 0, 0, "Sun May 24 2026 07:27:21"));
	track[0].push(new TrackPoint(35.521521, 139.688800, 1.372, 0, 0, 0, "Sun May 24 2026 07:27:28"));
	track[0].push(new TrackPoint(35.521468, 139.688740, 1.380, 0, 0, 0, "Sun May 24 2026 07:27:33"));
	track[0].push(new TrackPoint(35.521369, 139.688720, 1.391, 0, 0, 0, "Sun May 24 2026 07:27:38"));
	track[0].push(new TrackPoint(35.521156, 139.688361, 1.431, 0, 0, 0, "Sun May 24 2026 07:27:57"));
	track[0].push(new TrackPoint(35.520859, 139.688010, 1.477, 2, 0, 0, "Sun May 24 2026 07:28:20"));
	track[0].push(new TrackPoint(35.520652, 139.687727, 1.512, 4, 0, 0, "Sun May 24 2026 07:28:38"));
	track[0].push(new TrackPoint(35.520266, 139.687263, 1.572, 1, 0, 0, "Sun May 24 2026 07:29:10"));
	track[0].push(new TrackPoint(35.519748, 139.686752, 1.646, 5, 0, 0, "Sun May 24 2026 07:29:46"));
	track[0].push(new TrackPoint(35.519670, 139.686690, 1.657, 5, 0, 0, "Sun May 24 2026 07:29:51"));
	track[0].push(new TrackPoint(35.519575, 139.686573, 1.672, 4, 0, 0, "Sun May 24 2026 07:29:58"));
	track[0].push(new TrackPoint(35.519444, 139.686338, 1.698, 2, 0, 0, "Sun May 24 2026 07:30:10"));
	track[0].push(new TrackPoint(35.518953, 139.685789, 1.772, 1, 0, 0, "Sun May 24 2026 07:30:47"));
	track[0].push(new TrackPoint(35.518840, 139.685620, 1.792, 2, 0, 0, "Sun May 24 2026 07:30:56"));
	track[0].push(new TrackPoint(35.518745, 139.685532, 1.805, 3, 0, 0, "Sun May 24 2026 07:31:03"));
	track[0].push(new TrackPoint(35.518636, 139.685376, 1.824, 3, 0, 0, "Sun May 24 2026 07:31:12"));
	track[0].push(new TrackPoint(35.518347, 139.685119, 1.864, 4, 0, 0, "Sun May 24 2026 07:31:34"));
	track[0].push(new TrackPoint(35.518074, 139.684734, 1.910, 4, 0, 0, "Sun May 24 2026 07:31:58"));
	track[0].push(new TrackPoint(35.517953, 139.684636, 1.926, 4, 0, 0, "Sun May 24 2026 07:32:06"));
	track[0].push(new TrackPoint(35.517863, 139.684530, 1.940, 4, 0, 0, "Sun May 24 2026 07:32:13"));
	track[0].push(new TrackPoint(35.517790, 139.684412, 1.953, 4, 0, 0, "Sun May 24 2026 07:32:20"));
	track[0].push(new TrackPoint(35.517697, 139.684324, 1.966, 4, 0, 0, "Sun May 24 2026 07:32:27"));
	track[0].push(new TrackPoint(35.517597, 139.684258, 1.979, 4, 0, 0, "Sun May 24 2026 07:32:34"));
	track[0].push(new TrackPoint(35.517211, 139.683784, 2.050, 2, 0, 0, "Sun May 24 2026 07:33:51"));
	track[0].push(new TrackPoint(35.517107, 139.683703, 2.063, 2, 0, 0, "Sun May 24 2026 07:34:03"));
	track[0].push(new TrackPoint(35.516639, 139.683244, 2.130, 0, 0, 0, "Sun May 24 2026 07:34:38"));
	track[0].push(new TrackPoint(35.516227, 139.682806, 2.191, 0, 0, 0, "Sun May 24 2026 07:35:09"));
	track[0].push(new TrackPoint(35.516117, 139.682650, 2.209, 1, 0, 0, "Sun May 24 2026 07:35:18"));
	track[0].push(new TrackPoint(35.515977, 139.682516, 2.229, 1, 0, 0, "Sun May 24 2026 07:35:28"));
	track[0].push(new TrackPoint(35.515810, 139.682268, 2.258, 1, 0, 0, "Sun May 24 2026 07:35:41"));
	track[0].push(new TrackPoint(35.515743, 139.682221, 2.267, 1, 0, 0, "Sun May 24 2026 07:35:45"));
	track[0].push(new TrackPoint(35.515675, 139.682142, 2.277, 0, 0, 0, "Sun May 24 2026 07:35:50"));
	track[0].push(new TrackPoint(35.515591, 139.682001, 2.293, -1, 0, 0, "Sun May 24 2026 07:35:57"));
	track[0].push(new TrackPoint(35.515112, 139.681554, 2.360, -2, 0, 0, "Sun May 24 2026 07:36:33"));
	track[0].push(new TrackPoint(35.514895, 139.681338, 2.392, -5, 0, 0, "Sun May 24 2026 07:36:50"));
	track[0].push(new TrackPoint(35.514586, 139.681130, 2.431, -6, 0, 0, "Sun May 24 2026 07:37:12"));
	track[0].push(new TrackPoint(35.514417, 139.681042, 2.451, -4, 0, 0, "Sun May 24 2026 07:37:22"));
	track[0].push(new TrackPoint(35.514111, 139.680796, 2.492, -1, 0, 0, "Sun May 24 2026 07:37:43"));
	track[0].push(new TrackPoint(35.513659, 139.680490, 2.550, -1, 0, 0, "Sun May 24 2026 07:38:12"));
	track[0].push(new TrackPoint(35.513524, 139.680416, 2.566, -0, 0, 0, "Sun May 24 2026 07:38:19"));
	track[0].push(new TrackPoint(35.513260, 139.680219, 2.601, 1, 0, 0, "Sun May 24 2026 07:38:36"));
	track[0].push(new TrackPoint(35.513080, 139.680157, 2.622, 2, 0, 0, "Sun May 24 2026 07:38:57"));
	track[0].push(new TrackPoint(35.513077, 139.680129, 2.625, 2, 0, 0, "Sun May 24 2026 07:39:00"));
	track[0].push(new TrackPoint(35.512832, 139.680026, 2.654, 3, 0, 0, "Sun May 24 2026 07:39:19"));
	track[0].push(new TrackPoint(35.512795, 139.679989, 2.659, 3, 0, 0, "Sun May 24 2026 07:39:22"));
	track[0].push(new TrackPoint(35.512734, 139.679870, 2.672, 4, 0, 0, "Sun May 24 2026 07:39:27"));
	track[0].push(new TrackPoint(35.512677, 139.679796, 2.681, 4, 0, 0, "Sun May 24 2026 07:39:34"));
	track[0].push(new TrackPoint(35.512559, 139.679726, 2.696, 4, 0, 0, "Sun May 24 2026 07:39:43"));
	track[0].push(new TrackPoint(35.512461, 139.679634, 2.709, 4, 0, 0, "Sun May 24 2026 07:39:49"));
	track[0].push(new TrackPoint(35.511927, 139.679184, 2.782, 6, 0, 0, "Sun May 24 2026 07:41:12"));
	track[0].push(new TrackPoint(35.511695, 139.679119, 2.809, 5, 0, 0, "Sun May 24 2026 07:41:24"));
	track[0].push(new TrackPoint(35.511301, 139.678878, 2.858, 3, 0, 0, "Sun May 24 2026 07:41:51"));
	track[0].push(new TrackPoint(35.510932, 139.678604, 2.906, 7, 0, 0, "Sun May 24 2026 07:42:19"));
	track[0].push(new TrackPoint(35.510873, 139.678544, 2.915, 8, 0, 0, "Sun May 24 2026 07:42:24"));
	track[0].push(new TrackPoint(35.510825, 139.678467, 2.924, 9, 0, 0, "Sun May 24 2026 07:42:30"));
	track[0].push(new TrackPoint(35.510732, 139.678377, 2.937, 11, 0, 0, "Sun May 24 2026 07:42:37"));
	track[0].push(new TrackPoint(35.510451, 139.678180, 2.974, 14, 0, 0, "Sun May 24 2026 07:42:56"));
	track[0].push(new TrackPoint(35.510208, 139.678051, 3.003, 14, 0, 0, "Sun May 24 2026 07:43:10"));
	track[0].push(new TrackPoint(35.510019, 139.677892, 3.029, 12, 0, 0, "Sun May 24 2026 07:43:24"));
	track[0].push(new TrackPoint(35.509923, 139.677867, 3.040, 11, 0, 0, "Sun May 24 2026 07:43:29"));
	track[0].push(new TrackPoint(35.509841, 139.677885, 3.049, 11, 0, 0, "Sun May 24 2026 07:43:34"));
	track[0].push(new TrackPoint(35.509721, 139.677872, 3.062, 11, 0, 0, "Sun May 24 2026 07:43:40"));
	track[0].push(new TrackPoint(35.509284, 139.677986, 3.112, 15, 0, 0, "Sun May 24 2026 07:44:08"));
	track[0].push(new TrackPoint(35.509197, 139.678033, 3.123, 15, 0, 0, "Sun May 24 2026 07:44:14"));
	track[0].push(new TrackPoint(35.509064, 139.678022, 3.138, 15, 0, 0, "Sun May 24 2026 07:44:23"));
	track[0].push(new TrackPoint(35.508940, 139.678146, 3.156, 13, 0, 0, "Sun May 24 2026 07:44:31"));
	track[0].push(new TrackPoint(35.508793, 139.678201, 3.173, 12, 0, 0, "Sun May 24 2026 07:44:38"));
	track[0].push(new TrackPoint(35.508722, 139.678256, 3.183, 11, 0, 0, "Sun May 24 2026 07:44:41"));
	track[0].push(new TrackPoint(35.508622, 139.678244, 3.194, 11, 0, 0, "Sun May 24 2026 07:44:46"));
	track[0].push(new TrackPoint(35.508394, 139.678374, 3.222, 10, 0, 0, "Sun May 24 2026 07:44:58"));
	track[0].push(new TrackPoint(35.508269, 139.678407, 3.236, 10, 0, 0, "Sun May 24 2026 07:45:05"));
	track[0].push(new TrackPoint(35.508216, 139.678467, 3.244, 10, 0, 0, "Sun May 24 2026 07:45:11"));
	track[0].push(new TrackPoint(35.508083, 139.678466, 3.259, 9, 0, 0, "Sun May 24 2026 07:45:21"));
	track[0].push(new TrackPoint(35.507963, 139.678421, 3.273, 9, 0, 0, "Sun May 24 2026 07:45:32"));
	track[0].push(new TrackPoint(35.507927, 139.678374, 3.279, 9, 0, 0, "Sun May 24 2026 07:45:46"));
	track[0].push(new TrackPoint(35.507947, 139.678385, 3.282, 9, 0, 0, "Sun May 24 2026 07:45:50"));
	track[0].push(new TrackPoint(35.507938, 139.678408, 3.284, 9, 0, 0, "Sun May 24 2026 07:45:53"));
	track[0].push(new TrackPoint(35.507916, 139.678380, 3.295, 9, 0, 0, "Sun May 24 2026 07:46:43"));
	track[0].push(new TrackPoint(35.507992, 139.678403, 3.304, 9, 0, 0, "Sun May 24 2026 07:46:50"));
	track[0].push(new TrackPoint(35.507903, 139.678422, 3.314, 9, 0, 0, "Sun May 24 2026 07:47:02"));
	track[0].push(new TrackPoint(35.507898, 139.678394, 3.317, 9, 0, 0, "Sun May 24 2026 07:47:08"));
	track[0].push(new TrackPoint(35.507521, 139.678411, 3.359, 12, 0, 0, "Sun May 24 2026 07:47:20"));
	track[0].push(new TrackPoint(35.506829, 139.678271, 3.437, 13, 0, 0, "Sun May 24 2026 07:47:57"));
	track[0].push(new TrackPoint(35.506304, 139.678043, 3.500, 10, 0, 0, "Sun May 24 2026 07:48:25"));
	track[0].push(new TrackPoint(35.506205, 139.677934, 3.515, 11, 0, 0, "Sun May 24 2026 07:48:32"));
	track[0].push(new TrackPoint(35.506002, 139.677862, 3.538, 12, 0, 0, "Sun May 24 2026 07:48:42"));
	track[0].push(new TrackPoint(35.505876, 139.677787, 3.554, 13, 0, 0, "Sun May 24 2026 07:48:49"));
	track[0].push(new TrackPoint(35.505643, 139.677712, 3.581, 11, 0, 0, "Sun May 24 2026 07:49:01"));
	track[0].push(new TrackPoint(35.505390, 139.677570, 3.612, 9, 0, 0, "Sun May 24 2026 07:49:17"));
	track[0].push(new TrackPoint(35.505264, 139.677518, 3.626, 8, 0, 0, "Sun May 24 2026 07:49:24"));
	track[0].push(new TrackPoint(35.505164, 139.677454, 3.639, 8, 0, 0, "Sun May 24 2026 07:49:30"));
	track[0].push(new TrackPoint(35.504553, 139.677221, 3.710, 6, 0, 0, "Sun May 24 2026 07:50:04"));
	track[0].push(new TrackPoint(35.504379, 139.677134, 3.731, 6, 0, 0, "Sun May 24 2026 07:50:14"));
	track[0].push(new TrackPoint(35.504354, 139.677141, 3.734, 6, 0, 0, "Sun May 24 2026 07:50:15"));
	track[0].push(new TrackPoint(35.503352, 139.676658, 3.854, 5, 0, 0, "Sun May 24 2026 07:51:14"));
	track[0].push(new TrackPoint(35.503085, 139.676530, 3.886, 3, 0, 0, "Sun May 24 2026 07:51:28"));
	track[0].push(new TrackPoint(35.502994, 139.676521, 3.896, 3, 0, 0, "Sun May 24 2026 07:51:32"));
	track[0].push(new TrackPoint(35.502944, 139.676471, 3.903, 2, 0, 0, "Sun May 24 2026 07:51:35"));
	track[0].push(new TrackPoint(35.502682, 139.676368, 3.934, 2, 0, 0, "Sun May 24 2026 07:51:53"));
	track[0].push(new TrackPoint(35.502516, 139.676338, 3.953, 2, 0, 0, "Sun May 24 2026 07:52:11"));
	track[0].push(new TrackPoint(35.502472, 139.676346, 3.958, 3, 0, 0, "Sun May 24 2026 07:52:15"));
	track[0].push(new TrackPoint(35.502390, 139.676313, 3.967, 3, 0, 0, "Sun May 24 2026 07:52:22"));
	track[0].push(new TrackPoint(35.502342, 139.676324, 3.973, 3, 0, 0, "Sun May 24 2026 07:52:26"));
	track[0].push(new TrackPoint(35.502253, 139.676258, 3.984, 3, 0, 0, "Sun May 24 2026 07:52:35"));
	track[0].push(new TrackPoint(35.502196, 139.676201, 3.993, 3, 0, 0, "Sun May 24 2026 07:52:56"));
	track[0].push(new TrackPoint(35.502069, 139.676335, 4.012, 3, 0, 0, "Sun May 24 2026 07:53:05"));
	track[0].push(new TrackPoint(35.501706, 139.676436, 4.054, 4, 0, 0, "Sun May 24 2026 07:53:25"));
	track[0].push(new TrackPoint(35.501417, 139.676383, 4.086, 5, 0, 0, "Sun May 24 2026 07:53:41"));
	track[0].push(new TrackPoint(35.500642, 139.676050, 4.177, 4, 0, 0, "Sun May 24 2026 07:54:27"));
	track[0].push(new TrackPoint(35.500551, 139.676058, 4.187, 3, 0, 0, "Sun May 24 2026 07:54:32"));
	track[0].push(new TrackPoint(35.500509, 139.676041, 4.192, 3, 0, 0, "Sun May 24 2026 07:54:35"));
	track[0].push(new TrackPoint(35.500436, 139.675935, 4.205, 3, 0, 0, "Sun May 24 2026 07:54:40"));
	track[0].push(new TrackPoint(35.499946, 139.675782, 4.261, 2, 0, 0, "Sun May 24 2026 07:55:10"));
	track[0].push(new TrackPoint(35.499440, 139.675538, 4.322, 3, 0, 0, "Sun May 24 2026 07:55:41"));
	track[0].push(new TrackPoint(35.499195, 139.675479, 4.349, 2, 0, 0, "Sun May 24 2026 07:55:54"));
	track[0].push(new TrackPoint(35.498774, 139.675305, 4.399, 2, 0, 0, "Sun May 24 2026 07:56:19"));
	track[0].push(new TrackPoint(35.498695, 139.675293, 4.408, 3, 0, 0, "Sun May 24 2026 07:56:23"));
	track[0].push(new TrackPoint(35.498541, 139.675235, 4.425, 3, 0, 0, "Sun May 24 2026 07:56:32"));
	track[0].push(new TrackPoint(35.498252, 139.675196, 4.458, 3, 0, 0, "Sun May 24 2026 07:56:47"));
	track[0].push(new TrackPoint(35.497707, 139.674993, 4.521, 0, 0, 0, "Sun May 24 2026 07:57:19"));
	track[0].push(new TrackPoint(35.497542, 139.674901, 4.541, -0, 0, 0, "Sun May 24 2026 07:57:29"));
	track[0].push(new TrackPoint(35.496459, 139.674464, 4.668, 3, 0, 0, "Sun May 24 2026 07:58:33"));
	track[0].push(new TrackPoint(35.495924, 139.674170, 4.733, 3, 0, 0, "Sun May 24 2026 07:59:07"));
	track[0].push(new TrackPoint(35.495800, 139.674082, 4.749, 2, 0, 0, "Sun May 24 2026 07:59:16"));
	track[0].push(new TrackPoint(35.495788, 139.674040, 4.753, 2, 0, 0, "Sun May 24 2026 07:59:56"));
	track[0].push(new TrackPoint(35.495601, 139.673908, 4.778, 1, 0, 0, "Sun May 24 2026 08:00:10"));
	track[0].push(new TrackPoint(35.495208, 139.673257, 4.851, 2, 0, 0, "Sun May 24 2026 08:00:48"));
	track[0].push(new TrackPoint(35.495044, 139.672897, 4.889, 1, 0, 0, "Sun May 24 2026 08:01:07"));
	track[0].push(new TrackPoint(35.494956, 139.672768, 4.904, 0, 0, 0, "Sun May 24 2026 08:01:14"));
	track[0].push(new TrackPoint(35.494857, 139.672537, 4.928, 0, 0, 0, "Sun May 24 2026 08:01:25"));
	track[0].push(new TrackPoint(35.494397, 139.671716, 5.018, 1, 0, 0, "Sun May 24 2026 08:02:11"));
	track[0].push(new TrackPoint(35.493938, 139.670831, 5.113, 3, 0, 0, "Sun May 24 2026 08:02:56"));
	track[0].push(new TrackPoint(35.493606, 139.670032, 5.195, 2, 0, 0, "Sun May 24 2026 08:03:41"));
	track[0].push(new TrackPoint(35.493601, 139.669958, 5.202, 2, 0, 0, "Sun May 24 2026 08:03:46"));
	track[0].push(new TrackPoint(35.493550, 139.669801, 5.217, 3, 0, 0, "Sun May 24 2026 08:04:00"));
	track[0].push(new TrackPoint(35.493560, 139.669742, 5.223, 3, 0, 0, "Sun May 24 2026 08:04:48"));
	track[0].push(new TrackPoint(35.493313, 139.669173, 5.282, 1, 0, 0, "Sun May 24 2026 08:05:21"));
	track[0].push(new TrackPoint(35.492994, 139.668292, 5.369, 3, 0, 0, "Sun May 24 2026 08:06:04"));
	track[0].push(new TrackPoint(35.492749, 139.667612, 5.437, 6, 0, 0, "Sun May 24 2026 08:06:36"));
	track[0].push(new TrackPoint(35.492655, 139.667392, 5.460, 6, 0, 0, "Sun May 24 2026 08:06:46"));
	track[0].push(new TrackPoint(35.492604, 139.667222, 5.476, 6, 0, 0, "Sun May 24 2026 08:06:55"));
	track[0].push(new TrackPoint(35.492318, 139.666556, 5.545, 1, 0, 0, "Sun May 24 2026 08:07:31"));
	track[0].push(new TrackPoint(35.492297, 139.666383, 5.561, 0, 0, 0, "Sun May 24 2026 08:07:39"));
	track[0].push(new TrackPoint(35.492246, 139.666276, 5.572, 1, 0, 0, "Sun May 24 2026 08:07:45"));
	track[0].push(new TrackPoint(35.492221, 139.666062, 5.592, 2, 0, 0, "Sun May 24 2026 08:07:54"));
	track[0].push(new TrackPoint(35.492119, 139.665711, 5.626, 2, 0, 0, "Sun May 24 2026 08:08:10"));
	track[0].push(new TrackPoint(35.491989, 139.665383, 5.659, 2, 0, 0, "Sun May 24 2026 08:08:26"));
	track[0].push(new TrackPoint(35.491888, 139.664941, 5.701, 2, 0, 0, "Sun May 24 2026 08:08:48"));
	track[0].push(new TrackPoint(35.491797, 139.664630, 5.731, 3, 0, 0, "Sun May 24 2026 08:09:02"));
	track[0].push(new TrackPoint(35.491737, 139.664211, 5.770, 5, 0, 0, "Sun May 24 2026 08:09:19"));
	track[0].push(new TrackPoint(35.491725, 139.664013, 5.788, 5, 0, 0, "Sun May 24 2026 08:09:27"));
	track[0].push(new TrackPoint(35.491664, 139.663861, 5.803, 4, 0, 0, "Sun May 24 2026 08:09:37"));
	track[0].push(new TrackPoint(35.491512, 139.663685, 5.827, 4, 0, 0, "Sun May 24 2026 08:09:50"));
	track[0].push(new TrackPoint(35.491421, 139.663729, 5.838, 4, 0, 0, "Sun May 24 2026 08:09:58"));
	track[0].push(new TrackPoint(35.491275, 139.663859, 5.859, 4, 0, 0, "Sun May 24 2026 08:10:19"));
	track[0].push(new TrackPoint(35.491259, 139.663845, 5.863, 4, 0, 0, "Sun May 24 2026 08:10:31"));
	track[0].push(new TrackPoint(35.491231, 139.663846, 5.874, 4, 0, 0, "Sun May 24 2026 08:11:11"));
	track[0].push(new TrackPoint(35.491326, 139.663739, 5.889, 4, 0, 0, "Sun May 24 2026 08:11:19"));
	track[0].push(new TrackPoint(35.491322, 139.663628, 5.899, 4, 0, 0, "Sun May 24 2026 08:11:24"));
	track[0].push(new TrackPoint(35.491280, 139.663445, 5.916, 4, 0, 0, "Sun May 24 2026 08:11:32"));
	track[0].push(new TrackPoint(35.491255, 139.663450, 5.919, 4, 0, 0, "Sun May 24 2026 08:11:42"));
	track[0].push(new TrackPoint(35.491101, 139.663231, 5.945, 5, 0, 0, "Sun May 24 2026 08:12:05"));
	track[0].push(new TrackPoint(35.491071, 139.663146, 5.954, 5, 0, 0, "Sun May 24 2026 08:12:10"));
	track[0].push(new TrackPoint(35.490855, 139.662841, 5.991, 3, 0, 0, "Sun May 24 2026 08:12:27"));
	track[0].push(new TrackPoint(35.490494, 139.662219, 6.060, 5, 0, 0, "Sun May 24 2026 08:12:51"));
	track[0].push(new TrackPoint(35.490180, 139.661843, 6.109, 2, 0, 0, "Sun May 24 2026 08:13:15"));
	track[0].push(new TrackPoint(35.490094, 139.661707, 6.125, 1, 0, 0, "Sun May 24 2026 08:13:23"));
	track[0].push(new TrackPoint(35.489735, 139.661293, 6.180, 0, 0, 0, "Sun May 24 2026 08:13:58"));
	track[0].push(new TrackPoint(35.489466, 139.660952, 6.224, 4, 0, 0, "Sun May 24 2026 08:14:36"));
	track[0].push(new TrackPoint(35.489268, 139.660582, 6.264, 7, 0, 0, "Sun May 24 2026 08:15:08"));
	track[0].push(new TrackPoint(35.489158, 139.660430, 6.282, 9, 0, 0, "Sun May 24 2026 08:15:20"));
	track[0].push(new TrackPoint(35.489105, 139.660297, 6.296, 10, 0, 0, "Sun May 24 2026 08:15:29"));
	track[0].push(new TrackPoint(35.489021, 139.660188, 6.310, 10, 0, 0, "Sun May 24 2026 08:15:39"));
	track[0].push(new TrackPoint(35.488943, 139.660125, 6.320, 11, 0, 0, "Sun May 24 2026 08:15:47"));
	track[0].push(new TrackPoint(35.488791, 139.659874, 6.349, 8, 0, 0, "Sun May 24 2026 08:16:09"));
	track[0].push(new TrackPoint(35.488819, 139.659798, 6.356, 8, 0, 0, "Sun May 24 2026 08:16:13"));
	track[0].push(new TrackPoint(35.488918, 139.659699, 6.371, 9, 0, 0, "Sun May 24 2026 08:16:20"));
	track[0].push(new TrackPoint(35.488906, 139.659611, 6.379, 8, 0, 0, "Sun May 24 2026 08:16:25"));
	track[0].push(new TrackPoint(35.488766, 139.659312, 6.411, 7, 0, 0, "Sun May 24 2026 08:16:39"));
	track[0].push(new TrackPoint(35.488726, 139.659180, 6.423, 7, 0, 0, "Sun May 24 2026 08:16:46"));
	track[0].push(new TrackPoint(35.488547, 139.658898, 6.456, 5, 0, 0, "Sun May 24 2026 08:17:02"));
	track[0].push(new TrackPoint(35.488294, 139.658424, 6.508, 2, 0, 0, "Sun May 24 2026 08:17:28"));
	track[0].push(new TrackPoint(35.488195, 139.658290, 6.524, 2, 0, 0, "Sun May 24 2026 08:17:36"));
	track[0].push(new TrackPoint(35.488115, 139.658146, 6.540, 1, 0, 0, "Sun May 24 2026 08:17:43"));
	track[0].push(new TrackPoint(35.487586, 139.657507, 6.623, 1, 0, 0, "Sun May 24 2026 08:18:23"));
	track[0].push(new TrackPoint(35.487436, 139.657380, 6.643, 2, 0, 0, "Sun May 24 2026 08:18:32"));
	track[0].push(new TrackPoint(35.487311, 139.657230, 6.662, 2, 0, 0, "Sun May 24 2026 08:18:43"));
	track[0].push(new TrackPoint(35.487094, 139.657025, 6.693, 1, 0, 0, "Sun May 24 2026 08:18:58"));
	track[0].push(new TrackPoint(35.486931, 139.656783, 6.721, 2, 0, 0, "Sun May 24 2026 08:19:12"));
	track[0].push(new TrackPoint(35.486595, 139.656156, 6.790, 6, 0, 0, "Sun May 24 2026 08:19:45"));
	track[0].push(new TrackPoint(35.486535, 139.656012, 6.804, 6, 0, 0, "Sun May 24 2026 08:19:52"));
	track[0].push(new TrackPoint(35.486450, 139.655905, 6.818, 7, 0, 0, "Sun May 24 2026 08:19:58"));
	track[0].push(new TrackPoint(35.486400, 139.655675, 6.840, 6, 0, 0, "Sun May 24 2026 08:20:12"));
	track[0].push(new TrackPoint(35.486483, 139.655561, 6.854, 6, 0, 0, "Sun May 24 2026 08:20:18"));
	track[0].push(new TrackPoint(35.486525, 139.655459, 6.866, 7, 0, 0, "Sun May 24 2026 08:20:25"));
	track[0].push(new TrackPoint(35.486414, 139.655496, 6.879, 6, 0, 0, "Sun May 24 2026 08:20:31"));
	track[0].push(new TrackPoint(35.486367, 139.655470, 6.885, 6, 0, 0, "Sun May 24 2026 08:20:34"));
	track[0].push(new TrackPoint(35.486314, 139.655218, 6.909, 6, 0, 0, "Sun May 24 2026 08:20:45"));
	track[0].push(new TrackPoint(35.486263, 139.655128, 6.919, 6, 0, 0, "Sun May 24 2026 08:20:52"));
	track[0].push(new TrackPoint(35.486162, 139.655052, 6.932, 5, 0, 0, "Sun May 24 2026 08:20:57"));
	track[0].push(new TrackPoint(35.486123, 139.654998, 6.938, 5, 0, 0, "Sun May 24 2026 08:21:00"));
	track[0].push(new TrackPoint(35.486050, 139.654840, 6.955, 5, 0, 0, "Sun May 24 2026 08:21:09"));
	track[0].push(new TrackPoint(35.485998, 139.654352, 6.999, 5, 0, 0, "Sun May 24 2026 08:21:27"));
	track[0].push(new TrackPoint(35.485807, 139.653564, 7.074, 8, 0, 0, "Sun May 24 2026 08:22:03"));
	track[0].push(new TrackPoint(35.485694, 139.653220, 7.108, 6, 0, 0, "Sun May 24 2026 08:22:19"));
	track[0].push(new TrackPoint(35.485415, 139.651911, 7.231, 6, 0, 0, "Sun May 24 2026 08:23:19"));
	track[0].push(new TrackPoint(35.485328, 139.651143, 7.302, 3, 0, 0, "Sun May 24 2026 08:23:53"));
	track[0].push(new TrackPoint(35.485294, 139.651003, 7.315, 4, 0, 0, "Sun May 24 2026 08:24:00"));
	track[0].push(new TrackPoint(35.485278, 139.650781, 7.335, 5, 0, 0, "Sun May 24 2026 08:24:10"));
	track[0].push(new TrackPoint(35.485194, 139.650245, 7.385, 6, 0, 0, "Sun May 24 2026 08:24:34"));
	track[0].push(new TrackPoint(35.485103, 139.649525, 7.451, 5, 0, 0, "Sun May 24 2026 08:25:07"));
	track[0].push(new TrackPoint(35.485018, 139.649252, 7.478, 5, 0, 0, "Sun May 24 2026 08:25:30"));
	track[0].push(new TrackPoint(35.484930, 139.648538, 7.544, 9, 0, 0, "Sun May 24 2026 08:26:24"));
	track[0].push(new TrackPoint(35.484787, 139.647756, 7.617, 10, 0, 0, "Sun May 24 2026 08:27:00"));
	track[0].push(new TrackPoint(35.484724, 139.647222, 7.666, 6, 0, 0, "Sun May 24 2026 08:27:25"));
	track[0].push(new TrackPoint(35.484536, 139.646425, 7.742, 9, 0, 0, "Sun May 24 2026 08:28:01"));
	track[0].push(new TrackPoint(35.484455, 139.646199, 7.764, 10, 0, 0, "Sun May 24 2026 08:28:11"));
	track[0].push(new TrackPoint(35.484424, 139.645865, 7.795, 10, 0, 0, "Sun May 24 2026 08:28:27"));
	track[0].push(new TrackPoint(35.484285, 139.645599, 7.823, 10, 0, 0, "Sun May 24 2026 08:28:41"));
	track[0].push(new TrackPoint(35.484193, 139.645465, 7.839, 9, 0, 0, "Sun May 24 2026 08:28:49"));
	track[0].push(new TrackPoint(35.483981, 139.645050, 7.884, 9, 0, 0, "Sun May 24 2026 08:29:11"));
	track[0].push(new TrackPoint(35.483764, 139.644685, 7.925, 8, 0, 0, "Sun May 24 2026 08:29:31"));
	track[0].push(new TrackPoint(35.483687, 139.644523, 7.942, 8, 0, 0, "Sun May 24 2026 08:29:39"));
	track[0].push(new TrackPoint(35.483340, 139.643933, 8.008, 10, 0, 0, "Sun May 24 2026 08:30:12"));
	track[0].push(new TrackPoint(35.483226, 139.643774, 8.027, 11, 0, 0, "Sun May 24 2026 08:30:21"));
	track[0].push(new TrackPoint(35.483124, 139.643591, 8.047, 12, 0, 0, "Sun May 24 2026 08:30:31"));
	track[0].push(new TrackPoint(35.482996, 139.643427, 8.068, 12, 0, 0, "Sun May 24 2026 08:30:41"));
	track[0].push(new TrackPoint(35.482875, 139.643230, 8.090, 13, 0, 0, "Sun May 24 2026 08:30:52"));
	track[0].push(new TrackPoint(35.482783, 139.643135, 8.104, 13, 0, 0, "Sun May 24 2026 08:30:58"));
	track[0].push(new TrackPoint(35.482013, 139.641895, 8.245, 14, 0, 0, "Sun May 24 2026 08:32:04"));
	track[0].push(new TrackPoint(35.481787, 139.641585, 8.283, 12, 0, 0, "Sun May 24 2026 08:32:21"));
	track[0].push(new TrackPoint(35.481529, 139.641171, 8.330, 12, 0, 0, "Sun May 24 2026 08:32:42"));
	track[0].push(new TrackPoint(35.481440, 139.641058, 8.344, 13, 0, 0, "Sun May 24 2026 08:32:49"));
	track[0].push(new TrackPoint(35.481341, 139.640969, 8.358, 13, 0, 0, "Sun May 24 2026 08:32:55"));
	track[0].push(new TrackPoint(35.481227, 139.640811, 8.377, 13, 0, 0, "Sun May 24 2026 08:33:04"));
	track[0].push(new TrackPoint(35.480957, 139.640509, 8.418, 11, 0, 0, "Sun May 24 2026 08:33:22"));
	track[0].push(new TrackPoint(35.480511, 139.639873, 8.494, 7, 0, 0, "Sun May 24 2026 08:34:06"));
	track[0].push(new TrackPoint(35.480480, 139.639875, 8.499, 7, 0, 0, "Sun May 24 2026 08:34:40"));
	track[0].push(new TrackPoint(35.480305, 139.639649, 8.527, 9, 0, 0, "Sun May 24 2026 08:34:53"));
	track[0].push(new TrackPoint(35.479856, 139.639226, 8.590, 10, 0, 0, "Sun May 24 2026 08:35:22"));
	track[0].push(new TrackPoint(35.479740, 139.639064, 8.610, 9, 0, 0, "Sun May 24 2026 08:35:31"));
	track[0].push(new TrackPoint(35.479547, 139.638827, 8.640, 8, 0, 0, "Sun May 24 2026 08:35:47"));
	track[0].push(new TrackPoint(35.479541, 139.638796, 8.643, 8, 0, 0, "Sun May 24 2026 08:36:04"));
	track[0].push(new TrackPoint(35.479296, 139.638627, 8.675, 5, 0, 0, "Sun May 24 2026 08:36:30"));
	track[0].push(new TrackPoint(35.478823, 139.638266, 8.737, 4, 0, 0, "Sun May 24 2026 08:37:00"));
	track[0].push(new TrackPoint(35.478640, 139.638033, 8.766, 6, 0, 0, "Sun May 24 2026 08:37:13"));
	track[0].push(new TrackPoint(35.478325, 139.637733, 8.811, 6, 0, 0, "Sun May 24 2026 08:37:35"));
	track[0].push(new TrackPoint(35.477949, 139.637330, 8.866, 4, 0, 0, "Sun May 24 2026 08:38:03"));
	track[0].push(new TrackPoint(35.477797, 139.637136, 8.891, 5, 0, 0, "Sun May 24 2026 08:38:16"));
	track[0].push(new TrackPoint(35.477176, 139.636500, 8.981, 4, 0, 0, "Sun May 24 2026 08:39:03"));
	track[0].push(new TrackPoint(35.476238, 139.635646, 9.111, 5, 0, 0, "Sun May 24 2026 08:40:08"));
	track[0].push(new TrackPoint(35.476154, 139.635554, 9.124, 5, 0, 0, "Sun May 24 2026 08:40:14"));
	track[0].push(new TrackPoint(35.476083, 139.635422, 9.138, 7, 0, 0, "Sun May 24 2026 08:40:21"));
	track[0].push(new TrackPoint(35.475935, 139.635292, 9.158, 9, 0, 0, "Sun May 24 2026 08:40:31"));
	track[0].push(new TrackPoint(35.475836, 139.635235, 9.171, 9, 0, 0, "Sun May 24 2026 08:40:38"));
	track[0].push(new TrackPoint(35.475688, 139.635125, 9.190, 9, 0, 0, "Sun May 24 2026 08:40:47"));
	track[0].push(new TrackPoint(35.475620, 139.635095, 9.198, 9, 0, 0, "Sun May 24 2026 08:40:51"));
	track[0].push(new TrackPoint(35.475388, 139.634890, 9.230, 9, 0, 0, "Sun May 24 2026 08:41:07"));
	track[0].push(new TrackPoint(35.475275, 139.634828, 9.243, 8, 0, 0, "Sun May 24 2026 08:41:14"));
	track[0].push(new TrackPoint(35.475136, 139.634686, 9.264, 8, 0, 0, "Sun May 24 2026 08:41:23"));
	track[0].push(new TrackPoint(35.474902, 139.634425, 9.299, 9, 0, 0, "Sun May 24 2026 08:41:41"));
	track[0].push(new TrackPoint(35.474657, 139.634234, 9.331, 12, 0, 0, "Sun May 24 2026 08:41:56"));
	track[0].push(new TrackPoint(35.474400, 139.634050, 9.365, 16, 0, 0, "Sun May 24 2026 08:42:12"));
	track[0].push(new TrackPoint(35.474245, 139.633893, 9.387, 16, 0, 0, "Sun May 24 2026 08:42:23"));
	track[0].push(new TrackPoint(35.473814, 139.633581, 9.443, 10, 0, 0, "Sun May 24 2026 08:42:49"));
	track[0].push(new TrackPoint(35.473739, 139.633483, 9.456, 9, 0, 0, "Sun May 24 2026 08:42:55"));
	track[0].push(new TrackPoint(35.473623, 139.633400, 9.471, 7, 0, 0, "Sun May 24 2026 08:43:02"));
	track[0].push(new TrackPoint(35.473512, 139.633267, 9.488, 6, 0, 0, "Sun May 24 2026 08:43:10"));
	track[0].push(new TrackPoint(35.473286, 139.633084, 9.518, 5, 0, 0, "Sun May 24 2026 08:43:28"));
	track[0].push(new TrackPoint(35.473223, 139.633053, 9.526, 5, 0, 0, "Sun May 24 2026 08:43:59"));
	track[0].push(new TrackPoint(35.472711, 139.632579, 9.598, 10, 0, 0, "Sun May 24 2026 08:44:39"));
	track[0].push(new TrackPoint(35.472621, 139.632450, 9.613, 9, 0, 0, "Sun May 24 2026 08:44:46"));
	track[0].push(new TrackPoint(35.472411, 139.632273, 9.642, 8, 0, 0, "Sun May 24 2026 08:44:58"));
	track[0].push(new TrackPoint(35.472216, 139.632015, 9.674, 8, 0, 0, "Sun May 24 2026 08:45:22"));
	track[0].push(new TrackPoint(35.471879, 139.631700, 9.721, 9, 0, 0, "Sun May 24 2026 08:45:44"));
	track[0].push(new TrackPoint(35.471798, 139.631565, 9.737, 10, 0, 0, "Sun May 24 2026 08:45:53"));
	track[0].push(new TrackPoint(35.470999, 139.630957, 9.842, 6, 0, 0, "Sun May 24 2026 08:46:47"));
	track[0].push(new TrackPoint(35.470748, 139.630679, 9.880, 7, 0, 0, "Sun May 24 2026 08:47:08"));
	track[0].push(new TrackPoint(35.470695, 139.630474, 9.900, 8, 0, 0, "Sun May 24 2026 08:47:17"));
	track[0].push(new TrackPoint(35.470695, 139.630339, 9.912, 9, 0, 0, "Sun May 24 2026 08:47:23"));
	track[0].push(new TrackPoint(35.470587, 139.629831, 9.960, 9, 0, 0, "Sun May 24 2026 08:47:45"));
	track[0].push(new TrackPoint(35.470632, 139.629697, 9.973, 10, 0, 0, "Sun May 24 2026 08:47:52"));
	track[0].push(new TrackPoint(35.470626, 139.629545, 9.987, 12, 0, 0, "Sun May 24 2026 08:47:59"));
	track[0].push(new TrackPoint(35.470670, 139.629363, 10.005, 13, 0, 0, "Sun May 24 2026 08:48:11"));
	track[0].push(new TrackPoint(35.470679, 139.629365, 10.006, 13, 0, 0, "Sun May 24 2026 08:48:24"));
	track[0].push(new TrackPoint(35.470676, 139.628155, 10.117, 11, 0, 0, "Sun May 24 2026 08:49:31"));
	track[0].push(new TrackPoint(35.470641, 139.627990, 10.133, 12, 0, 0, "Sun May 24 2026 08:49:40"));
	track[0].push(new TrackPoint(35.470610, 139.627931, 10.139, 12, 0, 0, "Sun May 24 2026 08:49:44"));
	track[0].push(new TrackPoint(35.470525, 139.627587, 10.172, 12, 0, 0, "Sun May 24 2026 08:50:01"));
	track[0].push(new TrackPoint(35.470559, 139.627448, 10.185, 11, 0, 0, "Sun May 24 2026 08:50:08"));
	track[0].push(new TrackPoint(35.470551, 139.627381, 10.192, 11, 0, 0, "Sun May 24 2026 08:50:14"));
	track[0].push(new TrackPoint(35.470588, 139.627295, 10.201, 10, 0, 0, "Sun May 24 2026 08:50:19"));
	track[0].push(new TrackPoint(35.470678, 139.627201, 10.214, 9, 0, 0, "Sun May 24 2026 08:50:28"));
	track[0].push(new TrackPoint(35.470875, 139.627075, 10.241, 6, 0, 0, "Sun May 24 2026 08:51:55"));
	track[0].push(new TrackPoint(35.470882, 139.627090, 10.242, 6, 0, 0, "Sun May 24 2026 08:52:36"));
	track[0].push(new TrackPoint(35.470890, 139.627022, 10.248, 5, 0, 0, "Sun May 24 2026 08:52:40"));
	track[0].push(new TrackPoint(35.471026, 139.626739, 10.278, 4, 0, 0, "Sun May 24 2026 08:52:57"));
	track[0].push(new TrackPoint(35.471095, 139.626686, 10.288, 4, 0, 0, "Sun May 24 2026 08:54:17"));
	track[0].push(new TrackPoint(35.471200, 139.626503, 10.309, 7, 0, 0, "Sun May 24 2026 08:54:23"));
	track[0].push(new TrackPoint(35.471215, 139.626453, 10.314, 8, 0, 0, "Sun May 24 2026 08:54:26"));
	track[0].push(new TrackPoint(35.470744, 139.626040, 10.378, 8, 0, 0, "Sun May 24 2026 08:54:54"));
	track[0].push(new TrackPoint(35.470692, 139.625934, 10.390, 8, 0, 0, "Sun May 24 2026 08:55:00"));
	track[0].push(new TrackPoint(35.470637, 139.625648, 10.418, 10, 0, 0, "Sun May 24 2026 08:55:46"));
	track[0].push(new TrackPoint(35.470627, 139.625082, 10.471, 14, 0, 0, "Sun May 24 2026 08:57:27"));
	track[0].push(new TrackPoint(35.470532, 139.624593, 10.518, 14, 0, 0, "Sun May 24 2026 08:58:19"));
	track[0].push(new TrackPoint(35.470534, 139.624513, 10.525, 14, 0, 0, "Sun May 24 2026 08:58:34"));
	track[0].push(new TrackPoint(35.470589, 139.624290, 10.547, 17, 0, 0, "Sun May 24 2026 08:58:52"));
	track[0].push(new TrackPoint(35.470536, 139.624046, 10.570, 20, 0, 0, "Sun May 24 2026 08:59:06"));
	track[0].push(new TrackPoint(35.470523, 139.623945, 10.580, 22, 0, 0, "Sun May 24 2026 08:59:13"));
	track[0].push(new TrackPoint(35.470440, 139.623797, 10.598, 23, 0, 0, "Sun May 24 2026 09:00:08"));
	track[0].push(new TrackPoint(35.470469, 139.623451, 10.630, 27, 0, 0, "Sun May 24 2026 09:00:40"));
	track[0].push(new TrackPoint(35.470368, 139.623138, 10.661, 29, 0, 0, "Sun May 24 2026 09:01:01"));
	track[0].push(new TrackPoint(35.470374, 139.623012, 10.673, 31, 0, 0, "Sun May 24 2026 09:01:10"));
	track[0].push(new TrackPoint(35.470321, 139.622841, 10.690, 32, 0, 0, "Sun May 24 2026 09:01:22"));
	track[0].push(new TrackPoint(35.470303, 139.622649, 10.707, 32, 0, 0, "Sun May 24 2026 09:01:36"));
	track[0].push(new TrackPoint(35.470220, 139.622360, 10.736, 27, 0, 0, "Sun May 24 2026 09:01:58"));
	track[0].push(new TrackPoint(35.470201, 139.622202, 10.751, 25, 0, 0, "Sun May 24 2026 09:02:09"));
	track[0].push(new TrackPoint(35.470227, 139.622101, 10.760, 25, 0, 0, "Sun May 24 2026 09:02:13"));
	track[0].push(new TrackPoint(35.470233, 139.621986, 10.772, 24, 0, 0, "Sun May 24 2026 09:03:12"));
	track[0].push(new TrackPoint(35.470077, 139.621507, 10.819, 22, 0, 0, "Sun May 24 2026 09:03:42"));
	track[0].push(new TrackPoint(35.469993, 139.620848, 10.880, 26, 0, 0, "Sun May 24 2026 09:04:12"));
	track[0].push(new TrackPoint(35.469977, 139.620640, 10.899, 26, 0, 0, "Sun May 24 2026 09:04:21"));
	track[0].push(new TrackPoint(35.469868, 139.620276, 10.934, 21, 0, 0, "Sun May 24 2026 09:04:37"));
	track[0].push(new TrackPoint(35.469849, 139.620152, 10.946, 19, 0, 0, "Sun May 24 2026 09:04:44"));
	track[0].push(new TrackPoint(35.469871, 139.619459, 11.009, 14, 0, 0, "Sun May 24 2026 09:05:16"));
	track[0].push(new TrackPoint(35.469864, 139.619367, 11.018, 13, 0, 0, "Sun May 24 2026 09:05:20"));
	track[0].push(new TrackPoint(35.469818, 139.619205, 11.033, 11, 0, 0, "Sun May 24 2026 09:05:28"));
	track[0].push(new TrackPoint(35.469814, 139.618884, 11.063, 8, 0, 0, "Sun May 24 2026 09:05:41"));
	track[0].push(new TrackPoint(35.469739, 139.618265, 11.120, 7, 0, 0, "Sun May 24 2026 09:06:08"));
	track[0].push(new TrackPoint(35.469712, 139.618137, 11.132, 7, 0, 0, "Sun May 24 2026 09:06:13"));
	track[0].push(new TrackPoint(35.469502, 139.617615, 11.185, 8, 0, 0, "Sun May 24 2026 09:06:40"));
	track[0].push(new TrackPoint(35.469344, 139.616992, 11.245, 13, 0, 0, "Sun May 24 2026 09:07:11"));
	track[0].push(new TrackPoint(35.469287, 139.616626, 11.279, 11, 0, 0, "Sun May 24 2026 09:07:24"));
	track[0].push(new TrackPoint(35.469204, 139.616218, 11.317, 6, 0, 0, "Sun May 24 2026 09:07:38"));
	track[0].push(new TrackPoint(35.469205, 139.615963, 11.340, 6, 0, 0, "Sun May 24 2026 09:07:47"));
	track[0].push(new TrackPoint(35.469179, 139.615861, 11.350, 5, 0, 0, "Sun May 24 2026 09:07:53"));
	track[0].push(new TrackPoint(35.469109, 139.615727, 11.365, 4, 0, 0, "Sun May 24 2026 09:07:59"));
	track[0].push(new TrackPoint(35.469082, 139.615595, 11.378, 4, 0, 0, "Sun May 24 2026 09:08:18"));
	track[0].push(new TrackPoint(35.469048, 139.615569, 11.383, 4, 0, 0, "Sun May 24 2026 09:08:33"));
	track[0].push(new TrackPoint(35.469022, 139.615611, 11.388, 4, 0, 0, "Sun May 24 2026 09:08:38"));
	track[0].push(new TrackPoint(35.468997, 139.615556, 11.394, 3, 0, 0, "Sun May 24 2026 09:08:44"));
	track[0].push(new TrackPoint(35.468983, 139.615376, 11.411, 2, 0, 0, "Sun May 24 2026 09:08:56"));
	track[0].push(new TrackPoint(35.468917, 139.615309, 11.420, 1, 0, 0, "Sun May 24 2026 09:09:02"));
	track[0].push(new TrackPoint(35.468731, 139.614863, 11.466, 4, 0, 0, "Sun May 24 2026 09:09:22"));
	track[0].push(new TrackPoint(35.468557, 139.614635, 11.495, 6, 0, 0, "Sun May 24 2026 09:09:34"));
	track[0].push(new TrackPoint(35.468483, 139.614568, 11.505, 7, 0, 0, "Sun May 24 2026 09:09:39"));
	track[0].push(new TrackPoint(35.468461, 139.614517, 11.510, 8, 0, 0, "Sun May 24 2026 09:09:42"));
	track[0].push(new TrackPoint(35.468300, 139.614389, 11.531, 9, 0, 0, "Sun May 24 2026 09:09:50"));
	track[0].push(new TrackPoint(35.468225, 139.614285, 11.544, 9, 0, 0, "Sun May 24 2026 09:09:57"));
	track[0].push(new TrackPoint(35.467682, 139.613866, 11.615, 8, 0, 0, "Sun May 24 2026 09:10:24"));
	track[0].push(new TrackPoint(35.467604, 139.613746, 11.629, 8, 0, 0, "Sun May 24 2026 09:10:33"));
	track[0].push(new TrackPoint(35.467462, 139.613640, 11.648, 8, 0, 0, "Sun May 24 2026 09:10:43"));
	track[0].push(new TrackPoint(35.467365, 139.613538, 11.662, 9, 0, 0, "Sun May 24 2026 09:10:50"));
	track[0].push(new TrackPoint(35.467143, 139.613449, 11.688, 8, 0, 0, "Sun May 24 2026 09:11:03"));
	track[0].push(new TrackPoint(35.466871, 139.613289, 11.722, 6, 0, 0, "Sun May 24 2026 09:11:16"));
	track[0].push(new TrackPoint(35.466614, 139.613107, 11.755, 5, 0, 0, "Sun May 24 2026 09:11:41"));
	track[0].push(new TrackPoint(35.466567, 139.613042, 11.763, 4, 0, 0, "Sun May 24 2026 09:11:47"));
	track[0].push(new TrackPoint(35.466140, 139.612824, 11.815, -1, 0, 0, "Sun May 24 2026 09:12:15"));
	track[0].push(new TrackPoint(35.465864, 139.612616, 11.851, 1, 0, 0, "Sun May 24 2026 09:12:33"));
	track[0].push(new TrackPoint(35.465709, 139.612471, 11.873, 2, 0, 0, "Sun May 24 2026 09:12:42"));
	track[0].push(new TrackPoint(35.465682, 139.612352, 11.884, 2, 0, 0, "Sun May 24 2026 09:12:47"));
	track[0].push(new TrackPoint(35.465539, 139.612137, 11.909, 3, 0, 0, "Sun May 24 2026 09:13:02"));
	track[0].push(new TrackPoint(35.465562, 139.612000, 11.924, 3, 0, 0, "Sun May 24 2026 09:15:19"));
	track[0].push(new TrackPoint(35.465584, 139.611958, 11.929, 3, 0, 0, "Sun May 24 2026 09:15:26"));
	track[0].push(new TrackPoint(35.465555, 139.611796, 11.945, 4, 0, 0, "Sun May 24 2026 09:16:16"));
	track[0].push(new TrackPoint(35.465538, 139.611773, 11.948, 4, 0, 0, "Sun May 24 2026 09:16:20"));
	track[0].push(new TrackPoint(35.465592, 139.611635, 11.961, 5, 0, 0, "Sun May 24 2026 09:16:34"));
	track[0].push(new TrackPoint(35.465306, 139.611446, 11.998, 7, 0, 0, "Sun May 24 2026 09:17:03"));
	track[0].push(new TrackPoint(35.465252, 139.611442, 12.004, 7, 0, 0, "Sun May 24 2026 09:17:08"));
	track[0].push(new TrackPoint(35.465089, 139.611306, 12.026, 6, 0, 0, "Sun May 24 2026 09:17:22"));
	track[0].push(new TrackPoint(35.465050, 139.611238, 12.034, 6, 0, 0, "Sun May 24 2026 09:17:26"));
	track[0].push(new TrackPoint(35.465008, 139.611201, 12.039, 6, 0, 0, "Sun May 24 2026 09:17:29"));
	track[0].push(new TrackPoint(35.464879, 139.610904, 12.070, 5, 0, 0, "Sun May 24 2026 09:17:46"));
	track[0].push(new TrackPoint(35.464725, 139.610686, 12.096, 5, 0, 0, "Sun May 24 2026 09:17:58"));
	track[0].push(new TrackPoint(35.464628, 139.610509, 12.116, 6, 0, 0, "Sun May 24 2026 09:18:07"));
	track[0].push(new TrackPoint(35.464343, 139.610175, 12.160, 8, 0, 0, "Sun May 24 2026 09:18:29"));
	track[0].push(new TrackPoint(35.464205, 139.610047, 12.179, 8, 0, 0, "Sun May 24 2026 09:18:39"));
	track[0].push(new TrackPoint(35.464058, 139.609892, 12.201, 9, 0, 0, "Sun May 24 2026 09:18:49"));
	track[0].push(new TrackPoint(35.463855, 139.609773, 12.226, 8, 0, 0, "Sun May 24 2026 09:19:01"));
	track[0].push(new TrackPoint(35.463452, 139.609272, 12.290, 8, 0, 0, "Sun May 24 2026 09:19:33"));
	track[0].push(new TrackPoint(35.463355, 139.609177, 12.304, 7, 0, 0, "Sun May 24 2026 09:19:40"));
	track[0].push(new TrackPoint(35.463173, 139.608945, 12.333, 8, 0, 0, "Sun May 24 2026 09:19:56"));
	track[0].push(new TrackPoint(35.463053, 139.608823, 12.350, 9, 0, 0, "Sun May 24 2026 09:20:05"));
	track[0].push(new TrackPoint(35.462714, 139.608604, 12.393, 9, 0, 0, "Sun May 24 2026 09:20:25"));
	track[0].push(new TrackPoint(35.462607, 139.608501, 12.408, 8, 0, 0, "Sun May 24 2026 09:20:33"));
	track[0].push(new TrackPoint(35.462245, 139.608236, 12.455, 8, 0, 0, "Sun May 24 2026 09:20:57"));
	track[0].push(new TrackPoint(35.462077, 139.608194, 12.474, 8, 0, 0, "Sun May 24 2026 09:21:06"));
	track[0].push(new TrackPoint(35.460713, 139.607452, 12.640, 7, 0, 0, "Sun May 24 2026 09:22:37"));
	track[0].push(new TrackPoint(35.460427, 139.607243, 12.677, 8, 0, 0, "Sun May 24 2026 09:22:56"));
	track[0].push(new TrackPoint(35.459740, 139.606633, 12.772, 8, 0, 0, "Sun May 24 2026 09:23:40"));
	track[0].push(new TrackPoint(35.459545, 139.606472, 12.799, 5, 0, 0, "Sun May 24 2026 09:24:36"));
	track[0].push(new TrackPoint(35.459460, 139.606450, 12.809, 4, 0, 0, "Sun May 24 2026 09:24:52"));
	track[0].push(new TrackPoint(35.458704, 139.605968, 12.904, 2, 0, 0, "Sun May 24 2026 09:25:46"));
	track[0].push(new TrackPoint(35.458257, 139.605742, 12.958, 5, 0, 0, "Sun May 24 2026 09:26:11"));
	track[0].push(new TrackPoint(35.457848, 139.605484, 13.009, 7, 0, 0, "Sun May 24 2026 09:26:52"));
	track[0].push(new TrackPoint(35.457732, 139.605447, 13.023, 7, 0, 0, "Sun May 24 2026 09:27:04"));
	track[0].push(new TrackPoint(35.457548, 139.605337, 13.046, 7, 0, 0, "Sun May 24 2026 09:27:22"));
	track[0].push(new TrackPoint(35.457535, 139.605298, 13.050, 7, 0, 0, "Sun May 24 2026 09:27:26"));
	track[0].push(new TrackPoint(35.457492, 139.605303, 13.054, 7, 0, 0, "Sun May 24 2026 09:27:32"));
	track[0].push(new TrackPoint(35.457374, 139.605246, 13.069, 8, 0, 0, "Sun May 24 2026 09:27:43"));
	track[0].push(new TrackPoint(35.457363, 139.605265, 13.071, 8, 0, 0, "Sun May 24 2026 09:27:48"));
	track[0].push(new TrackPoint(35.457183, 139.605163, 13.094, 10, 0, 0, "Sun May 24 2026 09:28:46"));
	track[0].push(new TrackPoint(35.456855, 139.604934, 13.136, 11, 0, 0, "Sun May 24 2026 09:29:25"));
	track[0].push(new TrackPoint(35.456418, 139.604740, 13.189, 7, 0, 0, "Sun May 24 2026 09:30:02"));
	track[0].push(new TrackPoint(35.456327, 139.604647, 13.202, 6, 0, 0, "Sun May 24 2026 09:30:11"));
	track[0].push(new TrackPoint(35.456179, 139.604600, 13.219, 5, 0, 0, "Sun May 24 2026 09:30:24"));
	track[0].push(new TrackPoint(35.455928, 139.604438, 13.251, 4, 0, 0, "Sun May 24 2026 09:30:48"));
	track[0].push(new TrackPoint(35.455757, 139.604366, 13.271, 5, 0, 0, "Sun May 24 2026 09:31:02"));
	track[0].push(new TrackPoint(35.455679, 139.604286, 13.282, 4, 0, 0, "Sun May 24 2026 09:31:12"));
	track[0].push(new TrackPoint(35.455480, 139.604183, 13.306, 4, 0, 0, "Sun May 24 2026 09:31:30"));
	track[0].push(new TrackPoint(35.455342, 139.604048, 13.326, 3, 0, 0, "Sun May 24 2026 09:31:47"));
	track[0].push(new TrackPoint(35.454853, 139.603764, 13.386, 3, 0, 0, "Sun May 24 2026 09:33:00"));
	track[0].push(new TrackPoint(35.454592, 139.603632, 13.419, 4, 0, 0, "Sun May 24 2026 09:33:23"));
	track[0].push(new TrackPoint(35.454495, 139.603551, 13.432, 5, 0, 0, "Sun May 24 2026 09:33:52"));
	track[0].push(new TrackPoint(35.454043, 139.603269, 13.489, 7, 0, 0, "Sun May 24 2026 09:34:36"));
	track[0].push(new TrackPoint(35.453938, 139.603265, 13.501, 6, 0, 0, "Sun May 24 2026 09:34:49"));
	track[0].push(new TrackPoint(35.453859, 139.603197, 13.512, 5, 0, 0, "Sun May 24 2026 09:35:03"));
	track[0].push(new TrackPoint(35.453859, 139.603218, 13.514, 5, 0, 0, "Sun May 24 2026 09:35:05"));
	track[0].push(new TrackPoint(35.453850, 139.603200, 13.516, 5, 0, 0, "Sun May 24 2026 09:35:11"));
	track[0].push(new TrackPoint(35.453869, 139.603177, 13.519, 6, 0, 0, "Sun May 24 2026 09:35:15"));
	track[0].push(new TrackPoint(35.453930, 139.603198, 13.526, 6, 0, 0, "Sun May 24 2026 09:35:20"));
	track[0].push(new TrackPoint(35.453935, 139.603220, 13.529, 6, 0, 0, "Sun May 24 2026 09:35:28"));
	track[0].push(new TrackPoint(35.453800, 139.603169, 13.545, 5, 0, 0, "Sun May 24 2026 09:35:38"));
	track[0].push(new TrackPoint(35.453721, 139.603120, 13.555, 5, 0, 0, "Sun May 24 2026 09:35:48"));
	track[0].push(new TrackPoint(35.453600, 139.603012, 13.572, 4, 0, 0, "Sun May 24 2026 09:36:19"));
	track[0].push(new TrackPoint(35.453573, 139.603018, 13.575, 4, 0, 0, "Sun May 24 2026 09:36:23"));
	track[0].push(new TrackPoint(35.453547, 139.603047, 13.587, 4, 0, 0, "Sun May 24 2026 09:37:47"));
	track[0].push(new TrackPoint(35.453515, 139.602962, 13.595, 4, 0, 0, "Sun May 24 2026 09:37:53"));
	track[0].push(new TrackPoint(35.453446, 139.602927, 13.604, 5, 0, 0, "Sun May 24 2026 09:38:00"));
	track[0].push(new TrackPoint(35.453382, 139.602972, 13.614, 4, 0, 0, "Sun May 24 2026 09:39:27"));
	track[0].push(new TrackPoint(35.453119, 139.602775, 13.649, 4, 0, 0, "Sun May 24 2026 09:39:48"));
	track[0].push(new TrackPoint(35.452939, 139.602676, 13.671, 2, 0, 0, "Sun May 24 2026 09:40:01"));
	track[0].push(new TrackPoint(35.452655, 139.602434, 13.710, 0, 0, 0, "Sun May 24 2026 09:40:22"));
	track[0].push(new TrackPoint(35.452215, 139.602089, 13.768, 1, 0, 0, "Sun May 24 2026 09:40:51"));
	track[0].push(new TrackPoint(35.452091, 139.601967, 13.786, 2, 0, 0, "Sun May 24 2026 09:41:00"));
	track[0].push(new TrackPoint(35.451970, 139.601902, 13.800, 1, 0, 0, "Sun May 24 2026 09:41:07"));
	track[0].push(new TrackPoint(35.451785, 139.601707, 13.828, 1, 0, 0, "Sun May 24 2026 09:41:21"));
	track[0].push(new TrackPoint(35.451537, 139.601534, 13.859, 1, 0, 0, "Sun May 24 2026 09:41:40"));
	track[0].push(new TrackPoint(35.451269, 139.601254, 13.899, 2, 0, 0, "Sun May 24 2026 09:42:26"));
	track[0].push(new TrackPoint(35.451123, 139.601138, 13.919, 3, 0, 0, "Sun May 24 2026 09:42:36"));
	track[0].push(new TrackPoint(35.451026, 139.601096, 13.930, 3, 0, 0, "Sun May 24 2026 09:42:41"));
	track[0].push(new TrackPoint(35.450931, 139.600996, 13.944, 4, 0, 0, "Sun May 24 2026 09:42:48"));
	track[0].push(new TrackPoint(35.450691, 139.600826, 13.975, 4, 0, 0, "Sun May 24 2026 09:43:04"));
	track[0].push(new TrackPoint(35.450374, 139.600513, 14.020, 3, 0, 0, "Sun May 24 2026 09:43:27"));
	track[0].push(new TrackPoint(35.450244, 139.600445, 14.036, 3, 0, 0, "Sun May 24 2026 09:43:35"));
	track[0].push(new TrackPoint(35.450121, 139.600319, 14.054, 3, 0, 0, "Sun May 24 2026 09:43:44"));
	track[0].push(new TrackPoint(35.449206, 139.599626, 14.174, 5, 0, 0, "Sun May 24 2026 09:44:45"));
	track[0].push(new TrackPoint(35.448953, 139.599365, 14.212, 9, 0, 0, "Sun May 24 2026 09:45:31"));
	track[0].push(new TrackPoint(35.448897, 139.599340, 14.219, 9, 0, 0, "Sun May 24 2026 09:45:37"));
	track[0].push(new TrackPoint(35.448527, 139.598992, 14.272, 9, 0, 0, "Sun May 24 2026 09:46:14"));
	track[0].push(new TrackPoint(35.448133, 139.598779, 14.320, 10, 0, 0, "Sun May 24 2026 09:46:37"));
	track[0].push(new TrackPoint(35.448056, 139.598752, 14.329, 11, 0, 0, "Sun May 24 2026 09:46:41"));
	track[0].push(new TrackPoint(35.447839, 139.598609, 14.356, 12, 0, 0, "Sun May 24 2026 09:46:54"));
	track[0].push(new TrackPoint(35.447742, 139.598510, 14.371, 12, 0, 0, "Sun May 24 2026 09:47:01"));
	track[0].push(new TrackPoint(35.447639, 139.598447, 14.383, 11, 0, 0, "Sun May 24 2026 09:47:08"));
	track[0].push(new TrackPoint(35.447433, 139.598270, 14.411, 11, 0, 0, "Sun May 24 2026 09:47:23"));
	track[0].push(new TrackPoint(35.447102, 139.598054, 14.453, 12, 0, 0, "Sun May 24 2026 09:47:46"));
	track[0].push(new TrackPoint(35.446941, 139.597859, 14.478, 13, 0, 0, "Sun May 24 2026 09:47:57"));
	track[0].push(new TrackPoint(35.446693, 139.597628, 14.513, 11, 0, 0, "Sun May 24 2026 09:48:19"));
	track[0].push(new TrackPoint(35.446460, 139.597536, 14.541, 9, 0, 0, "Sun May 24 2026 09:48:35"));
	track[0].push(new TrackPoint(35.446156, 139.597202, 14.586, 8, 0, 0, "Sun May 24 2026 09:49:07"));
	track[0].push(new TrackPoint(35.446038, 139.597114, 14.602, 8, 0, 0, "Sun May 24 2026 09:49:15"));
	track[0].push(new TrackPoint(35.445912, 139.596979, 14.621, 8, 0, 0, "Sun May 24 2026 09:49:25"));
	track[0].push(new TrackPoint(35.445779, 139.596873, 14.638, 8, 0, 0, "Sun May 24 2026 09:49:34"));
	track[0].push(new TrackPoint(35.445624, 139.596779, 14.657, 9, 0, 0, "Sun May 24 2026 09:49:43"));
	track[0].push(new TrackPoint(35.445095, 139.596346, 14.729, 8, 0, 0, "Sun May 24 2026 09:50:33"));
	track[0].push(new TrackPoint(35.444928, 139.596162, 14.754, 7, 0, 0, "Sun May 24 2026 09:50:46"));
	track[0].push(new TrackPoint(35.444605, 139.595941, 14.795, 5, 0, 0, "Sun May 24 2026 09:51:08"));
	track[0].push(new TrackPoint(35.444534, 139.595876, 14.805, 5, 0, 0, "Sun May 24 2026 09:51:15"));
	track[0].push(new TrackPoint(35.444445, 139.595835, 14.815, 5, 0, 0, "Sun May 24 2026 09:51:23"));
	track[0].push(new TrackPoint(35.444281, 139.595641, 14.841, 6, 0, 0, "Sun May 24 2026 09:51:43"));
	track[0].push(new TrackPoint(35.444141, 139.595535, 14.860, 7, 0, 0, "Sun May 24 2026 09:52:03"));
	track[0].push(new TrackPoint(35.444130, 139.595456, 14.867, 7, 0, 0, "Sun May 24 2026 09:52:20"));
	track[0].push(new TrackPoint(35.444110, 139.595483, 14.873, 7, 0, 0, "Sun May 24 2026 09:53:19"));
	track[0].push(new TrackPoint(35.444052, 139.595457, 14.880, 8, 0, 0, "Sun May 24 2026 09:53:38"));
	track[0].push(new TrackPoint(35.443996, 139.595496, 14.888, 7, 0, 0, "Sun May 24 2026 09:54:03"));
	track[0].push(new TrackPoint(35.444275, 139.594015, 15.026, 12, 0, 0, "Sun May 24 2026 09:55:38"));
	track[0].push(new TrackPoint(35.444269, 139.593978, 15.030, 12, 0, 0, "Sun May 24 2026 09:55:43"));
	track[0].push(new TrackPoint(35.444320, 139.593739, 15.052, 10, 0, 0, "Sun May 24 2026 09:55:58"));
	track[0].push(new TrackPoint(35.444427, 139.593284, 15.096, 8, 0, 0, "Sun May 24 2026 09:56:20"));
	track[0].push(new TrackPoint(35.444441, 139.593136, 15.114, 8, 0, 0, "Sun May 24 2026 09:56:56"));
	track[0].push(new TrackPoint(35.444697, 139.591894, 15.231, 7, 0, 0, "Sun May 24 2026 09:57:50"));
	track[0].push(new TrackPoint(35.445078, 139.590329, 15.381, 9, 0, 0, "Sun May 24 2026 10:00:45"));
	track[0].push(new TrackPoint(35.445085, 139.590126, 15.401, 7, 0, 0, "Sun May 24 2026 10:01:25"));
	track[0].push(new TrackPoint(35.445029, 139.590097, 15.408, 8, 0, 0, "Sun May 24 2026 10:01:30"));
	track[0].push(new TrackPoint(35.445029, 139.590017, 15.415, 8, 0, 0, "Sun May 24 2026 10:01:36"));
	track[0].push(new TrackPoint(35.445088, 139.589904, 15.428, 8, 0, 0, "Sun May 24 2026 10:05:39"));
	track[0].push(new TrackPoint(35.445127, 139.589777, 15.441, 7, 0, 0, "Sun May 24 2026 10:05:54"));
	track[0].push(new TrackPoint(35.445189, 139.589428, 15.473, 9, 0, 0, "Sun May 24 2026 10:06:19"));
	track[0].push(new TrackPoint(35.445185, 139.589296, 15.485, 10, 0, 0, "Sun May 24 2026 10:06:28"));
	track[0].push(new TrackPoint(35.445250, 139.589058, 15.508, 11, 0, 0, "Sun May 24 2026 10:06:45"));
	track[0].push(new TrackPoint(35.445281, 139.588855, 15.527, 13, 0, 0, "Sun May 24 2026 10:06:59"));
	track[0].push(new TrackPoint(35.445361, 139.588451, 15.565, 16, 0, 0, "Sun May 24 2026 10:07:35"));
	track[0].push(new TrackPoint(35.445378, 139.588432, 15.568, 16, 0, 0, "Sun May 24 2026 10:07:43"));
	track[0].push(new TrackPoint(35.445364, 139.588365, 15.575, 16, 0, 0, "Sun May 24 2026 10:07:59"));
	track[0].push(new TrackPoint(35.445662, 139.588355, 15.609, 11, 0, 0, "Sun May 24 2026 10:08:27"));
	track[0].push(new TrackPoint(35.445678, 139.588317, 15.613, 11, 0, 0, "Sun May 24 2026 10:08:36"));
	track[0].push(new TrackPoint(35.445679, 139.588340, 15.615, 11, 0, 0, "Sun May 24 2026 10:08:41"));
	track[0].push(new TrackPoint(35.445629, 139.588302, 15.622, 11, 0, 0, "Sun May 24 2026 10:08:47"));
	track[0].push(new TrackPoint(35.445582, 139.588108, 15.640, 12, 0, 0, "Sun May 24 2026 10:08:56"));
	track[0].push(new TrackPoint(35.445606, 139.587731, 15.675, 11, 0, 0, "Sun May 24 2026 10:09:15"));
	track[0].push(new TrackPoint(35.445618, 139.586879, 15.753, 13, 0, 0, "Sun May 24 2026 10:10:06"));
	track[0].push(new TrackPoint(35.445632, 139.586716, 15.768, 13, 0, 0, "Sun May 24 2026 10:10:13"));
	track[0].push(new TrackPoint(35.445679, 139.586588, 15.780, 13, 0, 0, "Sun May 24 2026 10:10:20"));
	track[0].push(new TrackPoint(35.445695, 139.586227, 15.813, 11, 0, 0, "Sun May 24 2026 10:10:36"));
	track[0].push(new TrackPoint(35.445742, 139.585826, 15.850, 9, 0, 0, "Sun May 24 2026 10:10:54"));
	track[0].push(new TrackPoint(35.445849, 139.585142, 15.914, 12, 0, 0, "Sun May 24 2026 10:11:24"));
	track[0].push(new TrackPoint(35.445977, 139.583926, 16.026, 14, 0, 0, "Sun May 24 2026 10:12:17"));
	track[0].push(new TrackPoint(35.445977, 139.582201, 16.183, 18, 0, 0, "Sun May 24 2026 10:13:38"));
	track[0].push(new TrackPoint(35.446012, 139.581789, 16.221, 15, 0, 0, "Sun May 24 2026 10:13:58"));
	track[0].push(new TrackPoint(35.446016, 139.581657, 16.233, 13, 0, 0, "Sun May 24 2026 10:14:04"));
	track[0].push(new TrackPoint(35.446237, 139.580698, 16.324, 13, 0, 0, "Sun May 24 2026 10:14:48"));
	track[0].push(new TrackPoint(35.446427, 139.579997, 16.391, 15, 0, 0, "Sun May 24 2026 10:15:23"));
	track[0].push(new TrackPoint(35.446600, 139.579298, 16.458, 17, 0, 0, "Sun May 24 2026 10:15:56"));
	track[0].push(new TrackPoint(35.446660, 139.578948, 16.491, 20, 0, 0, "Sun May 24 2026 10:16:41"));
	track[0].push(new TrackPoint(35.446605, 139.578898, 16.499, 20, 0, 0, "Sun May 24 2026 10:16:45"));
	track[0].push(new TrackPoint(35.446551, 139.578765, 16.512, 20, 0, 0, "Sun May 24 2026 10:16:52"));
	track[0].push(new TrackPoint(35.446513, 139.578752, 16.517, 20, 0, 0, "Sun May 24 2026 10:16:56"));
	track[0].push(new TrackPoint(35.446145, 139.578424, 16.568, 21, 0, 0, "Sun May 24 2026 10:17:34"));
	track[0].push(new TrackPoint(35.446012, 139.578358, 16.584, 21, 0, 0, "Sun May 24 2026 10:17:54"));
	track[0].push(new TrackPoint(35.445826, 139.578196, 16.609, 21, 0, 0, "Sun May 24 2026 10:18:10"));
	track[0].push(new TrackPoint(35.445662, 139.578109, 16.629, 21, 0, 0, "Sun May 24 2026 10:18:26"));
	track[0].push(new TrackPoint(35.445620, 139.577814, 16.656, 23, 0, 0, "Sun May 24 2026 10:18:42"));
	track[0].push(new TrackPoint(35.445614, 139.577660, 16.670, 24, 0, 0, "Sun May 24 2026 10:18:50"));
	track[0].push(new TrackPoint(35.445591, 139.577575, 16.679, 25, 0, 0, "Sun May 24 2026 10:18:56"));
	track[0].push(new TrackPoint(35.445523, 139.577471, 16.691, 26, 0, 0, "Sun May 24 2026 10:19:03"));
	track[0].push(new TrackPoint(35.445477, 139.577350, 16.703, 27, 0, 0, "Sun May 24 2026 10:19:11"));
	track[0].push(new TrackPoint(35.445410, 139.577302, 16.712, 28, 0, 0, "Sun May 24 2026 10:19:16"));
	track[0].push(new TrackPoint(35.445344, 139.577190, 16.724, 28, 0, 0, "Sun May 24 2026 10:19:24"));
	track[0].push(new TrackPoint(35.445311, 139.577025, 16.740, 29, 0, 0, "Sun May 24 2026 10:19:34"));
	track[0].push(new TrackPoint(35.444974, 139.576459, 16.804, 29, 0, 0, "Sun May 24 2026 10:20:16"));
	track[0].push(new TrackPoint(35.444449, 139.576037, 16.875, 39, 0, 0, "Sun May 24 2026 10:21:10"));
	track[0].push(new TrackPoint(35.444268, 139.575919, 16.898, 44, 0, 0, "Sun May 24 2026 10:21:27"));
	track[0].push(new TrackPoint(35.443934, 139.575805, 16.937, 47, 0, 0, "Sun May 24 2026 10:21:52"));
	track[0].push(new TrackPoint(35.443836, 139.575796, 16.948, 48, 0, 0, "Sun May 24 2026 10:22:00"));
	track[0].push(new TrackPoint(35.443717, 139.575757, 16.962, 49, 0, 0, "Sun May 24 2026 10:22:10"));
	track[0].push(new TrackPoint(35.443527, 139.575611, 16.987, 51, 0, 0, "Sun May 24 2026 10:22:54"));
	track[0].push(new TrackPoint(35.443107, 139.575020, 17.058, 53, 0, 0, "Sun May 24 2026 10:23:28"));
	track[0].push(new TrackPoint(35.442650, 139.574300, 17.142, 56, 0, 0, "Sun May 24 2026 10:24:12"));
	track[0].push(new TrackPoint(35.442414, 139.574044, 17.177, 58, 0, 0, "Sun May 24 2026 10:24:32"));
	track[0].push(new TrackPoint(35.442355, 139.574005, 17.184, 59, 0, 0, "Sun May 24 2026 10:24:37"));
	track[0].push(new TrackPoint(35.442315, 139.573998, 17.189, 60, 0, 0, "Sun May 24 2026 10:24:40"));
	track[0].push(new TrackPoint(35.441601, 139.573185, 17.298, 65, 0, 0, "Sun May 24 2026 10:25:45"));
	track[0].push(new TrackPoint(35.441571, 139.573077, 17.308, 65, 0, 0, "Sun May 24 2026 10:25:51"));
	track[0].push(new TrackPoint(35.441467, 139.572975, 17.323, 64, 0, 0, "Sun May 24 2026 10:26:00"));
	track[0].push(new TrackPoint(35.441367, 139.572911, 17.336, 63, 0, 0, "Sun May 24 2026 10:26:08"));
	track[0].push(new TrackPoint(35.441309, 139.572830, 17.346, 63, 0, 0, "Sun May 24 2026 10:26:15"));
	track[0].push(new TrackPoint(35.440941, 139.572641, 17.391, 61, 0, 0, "Sun May 24 2026 10:26:47"));
	track[0].push(new TrackPoint(35.440464, 139.572560, 17.444, 62, 0, 0, "Sun May 24 2026 10:27:25"));
	track[0].push(new TrackPoint(35.440248, 139.572579, 17.468, 63, 0, 0, "Sun May 24 2026 10:27:39"));
	track[0].push(new TrackPoint(35.440097, 139.572535, 17.486, 65, 0, 0, "Sun May 24 2026 10:27:51"));
	track[0].push(new TrackPoint(35.439890, 139.572421, 17.511, 66, 0, 0, "Sun May 24 2026 10:28:07"));
	track[0].push(new TrackPoint(35.439800, 139.572331, 17.524, 67, 0, 0, "Sun May 24 2026 10:28:17"));
	track[0].push(new TrackPoint(35.439613, 139.571997, 17.561, 66, 0, 0, "Sun May 24 2026 10:28:43"));
	track[0].push(new TrackPoint(35.439569, 139.571842, 17.576, 66, 0, 0, "Sun May 24 2026 10:28:53"));
	track[0].push(new TrackPoint(35.439464, 139.571610, 17.600, 67, 0, 0, "Sun May 24 2026 10:29:11"));
	track[0].push(new TrackPoint(35.439381, 139.571335, 17.627, 65, 0, 0, "Sun May 24 2026 10:29:29"));
	track[0].push(new TrackPoint(35.439314, 139.571192, 17.642, 64, 0, 0, "Sun May 24 2026 10:29:39"));
	track[0].push(new TrackPoint(35.439086, 139.570926, 17.677, 65, 0, 0, "Sun May 24 2026 10:30:01"));
	track[0].push(new TrackPoint(35.438838, 139.570428, 17.730, 68, 0, 0, "Sun May 24 2026 10:30:36"));
	track[0].push(new TrackPoint(35.438636, 139.570101, 17.768, 70, 0, 0, "Sun May 24 2026 10:31:02"));
	track[0].push(new TrackPoint(35.438426, 139.569930, 17.796, 71, 0, 0, "Sun May 24 2026 10:31:21"));
	track[0].push(new TrackPoint(35.438277, 139.569766, 17.818, 71, 0, 0, "Sun May 24 2026 10:31:37"));
	track[0].push(new TrackPoint(35.438168, 139.569681, 17.833, 70, 0, 0, "Sun May 24 2026 10:31:46"));
	track[0].push(new TrackPoint(35.437932, 139.569544, 17.862, 68, 0, 0, "Sun May 24 2026 10:32:07"));
	track[0].push(new TrackPoint(35.437304, 139.569321, 17.935, 68, 0, 0, "Sun May 24 2026 10:32:51"));
	track[0].push(new TrackPoint(35.437112, 139.569170, 17.961, 70, 0, 0, "Sun May 24 2026 10:33:09"));
	track[0].push(new TrackPoint(35.437087, 139.569127, 17.965, 70, 0, 0, "Sun May 24 2026 10:33:13"));
	track[0].push(new TrackPoint(35.437033, 139.568753, 18.000, 72, 0, 0, "Sun May 24 2026 10:33:36"));
	track[0].push(new TrackPoint(35.437094, 139.568455, 18.028, 75, 0, 0, "Sun May 24 2026 10:33:56"));
	track[0].push(new TrackPoint(35.437095, 139.568388, 18.035, 77, 0, 0, "Sun May 24 2026 10:34:04"));
	track[0].push(new TrackPoint(35.437056, 139.568388, 18.040, 76, 0, 0, "Sun May 24 2026 10:34:16"));
	track[0].push(new TrackPoint(35.436959, 139.568026, 18.074, 78, 0, 0, "Sun May 24 2026 10:34:39"));
	track[0].push(new TrackPoint(35.436916, 139.567916, 18.085, 77, 0, 0, "Sun May 24 2026 10:34:47"));
	track[0].push(new TrackPoint(35.436895, 139.567808, 18.096, 77, 0, 0, "Sun May 24 2026 10:34:54"));
	track[0].push(new TrackPoint(35.436811, 139.567480, 18.127, 75, 0, 0, "Sun May 24 2026 10:35:18"));
	track[0].push(new TrackPoint(35.436775, 139.567419, 18.134, 74, 0, 0, "Sun May 24 2026 10:35:25"));
	track[0].push(new TrackPoint(35.436740, 139.567281, 18.148, 74, 0, 0, "Sun May 24 2026 10:36:12"));
	track[0].push(new TrackPoint(35.436604, 139.567113, 18.171, 74, 0, 0, "Sun May 24 2026 10:38:13"));
	track[0].push(new TrackPoint(35.436559, 139.567097, 18.176, 74, 0, 0, "Sun May 24 2026 10:38:21"));
	track[0].push(new TrackPoint(35.436358, 139.566646, 18.223, 74, 0, 0, "Sun May 24 2026 10:39:02"));
	track[0].push(new TrackPoint(35.435779, 139.566431, 18.291, 70, 0, 0, "Sun May 24 2026 10:40:01"));
	track[0].push(new TrackPoint(35.434782, 139.565660, 18.424, 55, 0, 0, "Sun May 24 2026 10:41:21"));
	track[0].push(new TrackPoint(35.434730, 139.565638, 18.430, 55, 0, 0, "Sun May 24 2026 10:41:24"));
	track[0].push(new TrackPoint(35.434563, 139.565507, 18.452, 54, 0, 0, "Sun May 24 2026 10:41:35"));
	track[0].push(new TrackPoint(35.434274, 139.565205, 18.494, 55, 0, 0, "Sun May 24 2026 10:41:56"));
	track[0].push(new TrackPoint(35.434097, 139.564996, 18.522, 57, 0, 0, "Sun May 24 2026 10:42:12"));
	track[0].push(new TrackPoint(35.433980, 139.564898, 18.538, 59, 0, 0, "Sun May 24 2026 10:42:21"));
	track[0].push(new TrackPoint(35.433747, 139.564756, 18.568, 63, 0, 0, "Sun May 24 2026 10:42:45"));
	track[0].push(new TrackPoint(35.433114, 139.564639, 18.639, 65, 0, 0, "Sun May 24 2026 10:43:41"));
	track[0].push(new TrackPoint(35.432924, 139.564561, 18.662, 66, 0, 0, "Sun May 24 2026 10:43:59"));
	track[0].push(new TrackPoint(35.432648, 139.564421, 18.696, 68, 0, 0, "Sun May 24 2026 10:44:28"));
	track[0].push(new TrackPoint(35.432652, 139.564406, 18.697, 68, 0, 0, "Sun May 24 2026 10:44:37"));
	track[0].push(new TrackPoint(35.432614, 139.564384, 18.702, 68, 0, 0, "Sun May 24 2026 10:45:06"));
	track[0].push(new TrackPoint(35.432576, 139.564395, 18.707, 69, 0, 0, "Sun May 24 2026 10:45:39"));
	track[0].push(new TrackPoint(35.432364, 139.564349, 18.730, 70, 0, 0, "Sun May 24 2026 10:46:01"));
	track[0].push(new TrackPoint(35.431870, 139.564093, 18.791, 66, 0, 0, "Sun May 24 2026 10:46:48"));
	track[0].push(new TrackPoint(35.431754, 139.563992, 18.806, 65, 0, 0, "Sun May 24 2026 10:46:58"));
	track[0].push(new TrackPoint(35.431347, 139.563462, 18.873, 68, 0, 0, "Sun May 24 2026 10:47:32"));
	track[0].push(new TrackPoint(35.431149, 139.563331, 18.898, 67, 0, 0, "Sun May 24 2026 10:47:45"));
	track[0].push(new TrackPoint(35.430619, 139.563184, 18.958, 66, 0, 0, "Sun May 24 2026 10:48:17"));
	track[0].push(new TrackPoint(35.430479, 139.563116, 18.975, 66, 0, 0, "Sun May 24 2026 10:48:25"));
	track[0].push(new TrackPoint(35.430303, 139.563086, 18.995, 66, 0, 0, "Sun May 24 2026 10:48:35"));
	track[0].push(new TrackPoint(35.429718, 139.563178, 19.061, 66, 0, 0, "Sun May 24 2026 10:49:09"));
	track[0].push(new TrackPoint(35.429372, 139.563076, 19.100, 66, 0, 0, "Sun May 24 2026 10:49:30"));
	track[0].push(new TrackPoint(35.429087, 139.562966, 19.134, 62, 0, 0, "Sun May 24 2026 10:49:47"));
	track[0].push(new TrackPoint(35.428926, 139.562944, 19.152, 60, 0, 0, "Sun May 24 2026 10:49:57"));
	track[0].push(new TrackPoint(35.428708, 139.563014, 19.177, 60, 0, 0, "Sun May 24 2026 10:50:10"));
	track[0].push(new TrackPoint(35.428260, 139.563221, 19.231, 63, 0, 0, "Sun May 24 2026 10:50:36"));
	track[0].push(new TrackPoint(35.428167, 139.563212, 19.241, 64, 0, 0, "Sun May 24 2026 10:50:41"));
	track[0].push(new TrackPoint(35.428046, 139.563152, 19.255, 64, 0, 0, "Sun May 24 2026 10:50:48"));
	track[0].push(new TrackPoint(35.427888, 139.562990, 19.278, 62, 0, 0, "Sun May 24 2026 10:51:00"));
	track[0].push(new TrackPoint(35.427806, 139.562817, 19.297, 61, 0, 0, "Sun May 24 2026 10:51:11"));
	track[0].push(new TrackPoint(35.427674, 139.562313, 19.346, 55, 0, 0, "Sun May 24 2026 10:51:48"));
	track[0].push(new TrackPoint(35.427661, 139.562317, 19.347, 55, 0, 0, "Sun May 24 2026 10:51:51"));
	track[0].push(new TrackPoint(35.427648, 139.562143, 19.364, 53, 0, 0, "Sun May 24 2026 10:52:20"));
	track[0].push(new TrackPoint(35.427720, 139.561658, 19.410, 45, 0, 0, "Sun May 24 2026 10:53:07"));
	track[0].push(new TrackPoint(35.427613, 139.561623, 19.422, 44, 0, 0, "Sun May 24 2026 10:53:24"));
	track[0].push(new TrackPoint(35.427555, 139.561584, 19.430, 43, 0, 0, "Sun May 24 2026 10:53:30"));
	track[0].push(new TrackPoint(35.427542, 139.561493, 19.438, 42, 0, 0, "Sun May 24 2026 10:53:37"));
	track[0].push(new TrackPoint(35.427522, 139.561451, 19.443, 41, 0, 0, "Sun May 24 2026 10:53:41"));
	track[0].push(new TrackPoint(35.427517, 139.561374, 19.450, 40, 0, 0, "Sun May 24 2026 10:53:47"));
	track[0].push(new TrackPoint(35.427457, 139.561315, 19.459, 39, 0, 0, "Sun May 24 2026 10:53:54"));
	track[0].push(new TrackPoint(35.427293, 139.561262, 19.478, 36, 0, 0, "Sun May 24 2026 10:54:10"));
	track[0].push(new TrackPoint(35.427262, 139.561161, 19.488, 34, 0, 0, "Sun May 24 2026 10:54:17"));
	track[0].push(new TrackPoint(35.427271, 139.561107, 19.493, 34, 0, 0, "Sun May 24 2026 10:54:20"));
	track[0].push(new TrackPoint(35.427254, 139.560963, 19.507, 33, 0, 0, "Sun May 24 2026 10:54:28"));
	track[0].push(new TrackPoint(35.427199, 139.560853, 19.519, 31, 0, 0, "Sun May 24 2026 10:54:35"));
	track[0].push(new TrackPoint(35.427006, 139.560729, 19.543, 29, 0, 0, "Sun May 24 2026 10:54:50"));
	track[0].push(new TrackPoint(35.426925, 139.560692, 19.553, 28, 0, 0, "Sun May 24 2026 10:54:55"));
	track[0].push(new TrackPoint(35.426360, 139.560287, 19.626, 27, 0, 0, "Sun May 24 2026 10:55:33"));
	track[0].push(new TrackPoint(35.425989, 139.560144, 19.670, 25, 0, 0, "Sun May 24 2026 10:55:55"));
	track[0].push(new TrackPoint(35.425949, 139.560121, 19.675, 25, 0, 0, "Sun May 24 2026 10:55:59"));
	track[0].push(new TrackPoint(35.425561, 139.560028, 19.719, 25, 0, 0, "Sun May 24 2026 10:56:20"));
	track[0].push(new TrackPoint(35.424708, 139.559686, 19.819, 21, 0, 0, "Sun May 24 2026 10:57:11"));
	track[0].push(new TrackPoint(35.424623, 139.559629, 19.830, 21, 0, 0, "Sun May 24 2026 10:57:16"));
	track[0].push(new TrackPoint(35.424458, 139.559415, 19.856, 20, 0, 0, "Sun May 24 2026 10:57:30"));
	track[0].push(new TrackPoint(35.424442, 139.559253, 19.871, 21, 0, 0, "Sun May 24 2026 10:57:37"));
	track[0].push(new TrackPoint(35.424399, 139.559075, 19.888, 21, 0, 0, "Sun May 24 2026 10:57:45"));
	track[0].push(new TrackPoint(35.424324, 139.559026, 19.898, 22, 0, 0, "Sun May 24 2026 10:57:52"));
	track[0].push(new TrackPoint(35.424199, 139.558833, 19.920, 23, 0, 0, "Sun May 24 2026 10:58:13"));
	track[0].push(new TrackPoint(35.424003, 139.558687, 19.946, 22, 0, 0, "Sun May 24 2026 10:58:35"));
	track[0].push(new TrackPoint(35.423266, 139.558474, 20.030, 24, 0, 0, "Sun May 24 2026 10:59:19"));
	track[0].push(new TrackPoint(35.422821, 139.558246, 20.084, 22, 0, 0, "Sun May 24 2026 10:59:47"));
	track[0].push(new TrackPoint(35.422228, 139.557841, 20.159, 21, 0, 0, "Sun May 24 2026 11:00:24"));
	track[0].push(new TrackPoint(35.421746, 139.557453, 20.224, 23, 0, 0, "Sun May 24 2026 11:00:57"));
	track[0].push(new TrackPoint(35.421326, 139.557204, 20.276, 22, 0, 0, "Sun May 24 2026 11:01:25"));
	track[0].push(new TrackPoint(35.421303, 139.557221, 20.279, 22, 0, 0, "Sun May 24 2026 11:01:27"));
	track[0].push(new TrackPoint(35.421285, 139.557378, 20.293, 22, 0, 0, "Sun May 24 2026 11:01:47"));
	track[0].push(new TrackPoint(35.421213, 139.557299, 20.304, 22, 0, 0, "Sun May 24 2026 11:02:10"));
	track[0].push(new TrackPoint(35.420925, 139.556775, 20.362, 20, 0, 0, "Sun May 24 2026 11:02:37"));
	track[0].push(new TrackPoint(35.420858, 139.556624, 20.378, 20, 0, 0, "Sun May 24 2026 11:02:44"));
	track[0].push(new TrackPoint(35.420823, 139.556462, 20.393, 20, 0, 0, "Sun May 24 2026 11:02:53"));
	track[0].push(new TrackPoint(35.420836, 139.556283, 20.409, 20, 0, 0, "Sun May 24 2026 11:03:02"));
	track[0].push(new TrackPoint(35.420906, 139.555943, 20.441, 21, 0, 0, "Sun May 24 2026 11:03:17"));
	track[0].push(new TrackPoint(35.420955, 139.555509, 20.481, 20, 0, 0, "Sun May 24 2026 11:03:37"));
	track[0].push(new TrackPoint(35.420950, 139.555097, 20.518, 18, 0, 0, "Sun May 24 2026 11:03:56"));
	track[0].push(new TrackPoint(35.420917, 139.554878, 20.539, 18, 0, 0, "Sun May 24 2026 11:04:07"));
	track[0].push(new TrackPoint(35.420920, 139.554243, 20.597, 19, 0, 0, "Sun May 24 2026 11:04:37"));
	track[0].push(new TrackPoint(35.420855, 139.553777, 20.639, 19, 0, 0, "Sun May 24 2026 11:04:59"));
	track[0].push(new TrackPoint(35.420837, 139.553449, 20.670, 18, 0, 0, "Sun May 24 2026 11:05:18"));
	track[0].push(new TrackPoint(35.420805, 139.553351, 20.679, 18, 0, 0, "Sun May 24 2026 11:05:26"));
	track[0].push(new TrackPoint(35.420580, 139.553060, 20.715, 18, 0, 0, "Sun May 24 2026 11:05:49"));
	track[0].push(new TrackPoint(35.420174, 139.552462, 20.786, 21, 0, 0, "Sun May 24 2026 11:06:27"));
	track[0].push(new TrackPoint(35.420070, 139.551946, 20.835, 21, 0, 0, "Sun May 24 2026 11:06:54"));
	track[0].push(new TrackPoint(35.419947, 139.551524, 20.875, 23, 0, 0, "Sun May 24 2026 11:07:17"));
	track[0].push(new TrackPoint(35.419954, 139.550791, 20.943, 25, 0, 0, "Sun May 24 2026 11:07:54"));
	track[0].push(new TrackPoint(35.419909, 139.550506, 20.969, 26, 0, 0, "Sun May 24 2026 11:08:08"));
	track[0].push(new TrackPoint(35.419821, 139.550278, 20.992, 26, 0, 0, "Sun May 24 2026 11:08:18"));
	track[0].push(new TrackPoint(35.419705, 139.550137, 21.010, 26, 0, 0, "Sun May 24 2026 11:08:27"));
	track[0].push(new TrackPoint(35.419616, 139.550055, 21.023, 27, 0, 0, "Sun May 24 2026 11:08:33"));
	track[0].push(new TrackPoint(35.419076, 139.549426, 21.106, 28, 0, 0, "Sun May 24 2026 11:09:15"));
	track[0].push(new TrackPoint(35.418584, 139.549088, 21.168, 26, 0, 0, "Sun May 24 2026 11:09:46"));
	track[0].push(new TrackPoint(35.418402, 139.548879, 21.196, 25, 0, 0, "Sun May 24 2026 11:09:58"));
	track[0].push(new TrackPoint(35.418231, 139.548604, 21.228, 24, 0, 0, "Sun May 24 2026 11:10:13"));
	track[0].push(new TrackPoint(35.418000, 139.548365, 21.261, 22, 0, 0, "Sun May 24 2026 11:10:30"));
	track[0].push(new TrackPoint(35.417798, 139.548104, 21.294, 20, 0, 0, "Sun May 24 2026 11:10:47"));
	track[0].push(new TrackPoint(35.417076, 139.546851, 21.434, 21, 0, 0, "Sun May 24 2026 11:12:19"));
	track[0].push(new TrackPoint(35.416747, 139.546347, 21.493, 21, 0, 0, "Sun May 24 2026 11:12:48"));
	track[0].push(new TrackPoint(35.416042, 139.545341, 21.613, 21, 0, 0, "Sun May 24 2026 11:13:46"));
	track[0].push(new TrackPoint(35.415788, 139.544920, 21.661, 18, 0, 0, "Sun May 24 2026 11:14:10"));
	track[0].push(new TrackPoint(35.415104, 139.543551, 21.807, 26, 0, 0, "Sun May 24 2026 11:15:23"));
	track[0].push(new TrackPoint(35.414908, 139.543218, 21.845, 26, 0, 0, "Sun May 24 2026 11:15:41"));
	track[0].push(new TrackPoint(35.414835, 139.543055, 21.862, 25, 0, 0, "Sun May 24 2026 11:15:52"));
	track[0].push(new TrackPoint(35.414741, 139.542922, 21.878, 25, 0, 0, "Sun May 24 2026 11:16:06"));
	track[0].push(new TrackPoint(35.414671, 139.542889, 21.886, 24, 0, 0, "Sun May 24 2026 11:16:12"));
	track[0].push(new TrackPoint(35.414419, 139.542606, 21.925, 21, 0, 0, "Sun May 24 2026 11:16:40"));
	track[0].push(new TrackPoint(35.413599, 139.542052, 22.029, 17, 0, 0, "Sun May 24 2026 11:18:02"));
	track[0].push(new TrackPoint(35.413513, 139.541979, 22.041, 17, 0, 0, "Sun May 24 2026 11:18:10"));
	track[0].push(new TrackPoint(35.413223, 139.541928, 22.074, 18, 0, 0, "Sun May 24 2026 11:18:34"));
	track[0].push(new TrackPoint(35.412840, 139.541792, 22.118, 19, 0, 0, "Sun May 24 2026 11:19:07"));
	track[0].push(new TrackPoint(35.412654, 139.541775, 22.139, 19, 0, 0, "Sun May 24 2026 11:19:23"));
	track[0].push(new TrackPoint(35.412504, 139.541864, 22.157, 19, 0, 0, "Sun May 24 2026 11:19:37"));
	track[0].push(new TrackPoint(35.412014, 139.541995, 22.213, 17, 0, 0, "Sun May 24 2026 11:20:13"));
	track[0].push(new TrackPoint(35.411863, 139.542019, 22.230, 17, 0, 0, "Sun May 24 2026 11:20:23"));
	track[0].push(new TrackPoint(35.411672, 139.542004, 22.251, 17, 0, 0, "Sun May 24 2026 11:20:41"));
	track[0].push(new TrackPoint(35.411624, 139.542030, 22.257, 16, 0, 0, "Sun May 24 2026 11:20:45"));
	track[0].push(new TrackPoint(35.411539, 139.542041, 22.267, 16, 0, 0, "Sun May 24 2026 11:20:52"));
	track[0].push(new TrackPoint(35.411419, 139.542005, 22.281, 17, 0, 0, "Sun May 24 2026 11:21:02"));
	track[0].push(new TrackPoint(35.411325, 139.541938, 22.293, 17, 0, 0, "Sun May 24 2026 11:21:10"));
	track[0].push(new TrackPoint(35.411281, 139.541840, 22.303, 17, 0, 0, "Sun May 24 2026 11:21:24"));
	track[0].push(new TrackPoint(35.411174, 139.541770, 22.317, 16, 0, 0, "Sun May 24 2026 11:21:45"));
	track[0].push(new TrackPoint(35.411122, 139.540544, 22.428, 17, 0, 0, "Sun May 24 2026 11:22:47"));
	track[0].push(new TrackPoint(35.411008, 139.540132, 22.468, 16, 0, 0, "Sun May 24 2026 11:23:07"));
	track[0].push(new TrackPoint(35.410925, 139.540064, 22.479, 15, 0, 0, "Sun May 24 2026 11:23:13"));
	track[0].push(new TrackPoint(35.409942, 139.539709, 22.594, 19, 0, 0, "Sun May 24 2026 11:24:11"));
	track[0].push(new TrackPoint(35.409735, 139.539664, 22.617, 19, 0, 0, "Sun May 24 2026 11:24:23"));
	track[0].push(new TrackPoint(35.409597, 139.539652, 22.632, 19, 0, 0, "Sun May 24 2026 11:24:31"));
	track[0].push(new TrackPoint(35.408956, 139.539380, 22.709, 21, 0, 0, "Sun May 24 2026 11:25:34"));
	track[0].push(new TrackPoint(35.408705, 139.539214, 22.740, 21, 0, 0, "Sun May 24 2026 11:25:50"));
	track[0].push(new TrackPoint(35.408539, 139.539057, 22.764, 20, 0, 0, "Sun May 24 2026 11:26:03"));
	track[0].push(new TrackPoint(35.408293, 139.538732, 22.804, 19, 0, 0, "Sun May 24 2026 11:26:26"));
	track[0].push(new TrackPoint(35.408213, 139.538650, 22.816, 19, 0, 0, "Sun May 24 2026 11:26:33"));
	track[0].push(new TrackPoint(35.407992, 139.538389, 22.850, 18, 0, 0, "Sun May 24 2026 11:26:54"));
	track[0].push(new TrackPoint(35.407680, 139.538260, 22.887, 18, 0, 0, "Sun May 24 2026 11:27:13"));
	track[0].push(new TrackPoint(35.407211, 139.538184, 22.939, 17, 0, 0, "Sun May 24 2026 11:27:40"));
	track[0].push(new TrackPoint(35.407099, 139.538193, 22.952, 17, 0, 0, "Sun May 24 2026 11:27:48"));
	track[0].push(new TrackPoint(35.406794, 139.538101, 22.987, 16, 0, 0, "Sun May 24 2026 11:28:05"));
	track[0].push(new TrackPoint(35.406524, 139.537911, 23.021, 16, 0, 0, "Sun May 24 2026 11:28:21"));
	track[0].push(new TrackPoint(35.406422, 139.537788, 23.038, 17, 0, 0, "Sun May 24 2026 11:29:09"));
	track[0].push(new TrackPoint(35.406380, 139.537759, 23.044, 17, 0, 0, "Sun May 24 2026 11:29:12"));
	track[0].push(new TrackPoint(35.406318, 139.537675, 23.054, 17, 0, 0, "Sun May 24 2026 11:29:18"));
	track[0].push(new TrackPoint(35.406203, 139.537581, 23.069, 16, 0, 0, "Sun May 24 2026 11:29:29"));
	track[0].push(new TrackPoint(35.405908, 139.537302, 23.112, 15, 0, 0, "Sun May 24 2026 11:30:59"));
	track[0].push(new TrackPoint(35.405759, 139.537073, 23.139, 13, 0, 0, "Sun May 24 2026 11:31:16"));
	track[0].push(new TrackPoint(35.405700, 139.537016, 23.147, 13, 0, 0, "Sun May 24 2026 11:31:32"));
	track[0].push(new TrackPoint(35.405583, 139.536869, 23.166, 13, 0, 0, "Sun May 24 2026 11:31:48"));
	track[0].push(new TrackPoint(35.405388, 139.536756, 23.190, 15, 0, 0, "Sun May 24 2026 11:32:06"));
	track[0].push(new TrackPoint(35.405216, 139.536679, 23.214, 16, 0, 0, "Sun May 24 2026 11:33:30"));
	track[0].push(new TrackPoint(35.405016, 139.536706, 23.236, 17, 0, 0, "Sun May 24 2026 11:33:48"));
	track[0].push(new TrackPoint(35.404463, 139.536657, 23.298, 17, 0, 0, "Sun May 24 2026 11:34:37"));
	track[0].push(new TrackPoint(35.404185, 139.536852, 23.334, 16, 0, 0, "Sun May 24 2026 11:35:01"));
	track[0].push(new TrackPoint(35.403955, 139.537025, 23.364, 15, 0, 0, "Sun May 24 2026 11:35:25"));
	track[0].push(new TrackPoint(35.403746, 139.537010, 23.389, 15, 0, 0, "Sun May 24 2026 11:35:42"));
	track[0].push(new TrackPoint(35.403565, 139.536942, 23.410, 15, 0, 0, "Sun May 24 2026 11:35:54"));
	track[0].push(new TrackPoint(35.403533, 139.536898, 23.415, 15, 0, 0, "Sun May 24 2026 11:35:57"));
	track[0].push(new TrackPoint(35.403469, 139.536865, 23.423, 15, 0, 0, "Sun May 24 2026 11:36:03"));
	track[0].push(new TrackPoint(35.403275, 139.536698, 23.449, 16, 0, 0, "Sun May 24 2026 11:36:18"));
	track[0].push(new TrackPoint(35.403252, 139.536707, 23.452, 16, 0, 0, "Sun May 24 2026 11:36:21"));
	track[0].push(new TrackPoint(35.403192, 139.536660, 23.460, 16, 0, 0, "Sun May 24 2026 11:36:27"));
	track[0].push(new TrackPoint(35.403159, 139.536653, 23.464, 15, 0, 0, "Sun May 24 2026 11:36:33"));
	track[0].push(new TrackPoint(35.403144, 139.536607, 23.468, 15, 0, 0, "Sun May 24 2026 11:36:38"));
	track[0].push(new TrackPoint(35.402984, 139.536450, 23.491, 15, 0, 0, "Sun May 24 2026 11:37:23"));
	track[0].push(new TrackPoint(35.402892, 139.536301, 23.508, 16, 0, 0, "Sun May 24 2026 11:37:38"));
	track[0].push(new TrackPoint(35.402770, 139.535975, 23.541, 15, 0, 0, "Sun May 24 2026 11:38:05"));
	track[0].push(new TrackPoint(35.402715, 139.535882, 23.552, 15, 0, 0, "Sun May 24 2026 11:38:12"));
	track[0].push(new TrackPoint(35.402591, 139.535738, 23.571, 15, 0, 0, "Sun May 24 2026 11:38:26"));
	track[0].push(new TrackPoint(35.402597, 139.535624, 23.581, 14, 0, 0, "Sun May 24 2026 11:38:35"));
	track[0].push(new TrackPoint(35.402517, 139.535508, 23.595, 14, 0, 0, "Sun May 24 2026 11:38:43"));
	track[0].push(new TrackPoint(35.402455, 139.535461, 23.603, 14, 0, 0, "Sun May 24 2026 11:38:55"));
	track[0].push(new TrackPoint(35.402397, 139.535333, 23.619, 13, 0, 0, "Sun May 24 2026 11:39:31"));
	track[0].push(new TrackPoint(35.402455, 139.535177, 23.635, 13, 0, 0, "Sun May 24 2026 11:39:43"));
	track[0].push(new TrackPoint(35.402407, 139.534814, 23.668, 13, 0, 0, "Sun May 24 2026 11:40:09"));
	track[0].push(new TrackPoint(35.402351, 139.534524, 23.696, 13, 0, 0, "Sun May 24 2026 11:40:31"));
	track[0].push(new TrackPoint(35.402104, 139.534131, 23.743, 14, 0, 0, "Sun May 24 2026 11:41:58"));
	track[0].push(new TrackPoint(35.402014, 139.533926, 23.764, 15, 0, 0, "Sun May 24 2026 11:42:27"));
	track[0].push(new TrackPoint(35.401979, 139.533876, 23.770, 15, 0, 0, "Sun May 24 2026 11:42:32"));
	track[0].push(new TrackPoint(35.401763, 139.533404, 23.820, 17, 0, 0, "Sun May 24 2026 11:43:26"));
	track[0].push(new TrackPoint(35.401820, 139.533376, 23.827, 18, 0, 0, "Sun May 24 2026 11:43:36"));
	track[0].push(new TrackPoint(35.402046, 139.533362, 23.853, 19, 0, 0, "Sun May 24 2026 11:43:57"));
	track[0].push(new TrackPoint(35.402050, 139.533389, 23.855, 19, 0, 0, "Sun May 24 2026 11:44:02"));
	track[0].push(new TrackPoint(35.401984, 139.533341, 23.864, 19, 0, 0, "Sun May 24 2026 11:44:17"));
	track[0].push(new TrackPoint(35.401929, 139.533335, 23.870, 19, 0, 0, "Sun May 24 2026 11:44:22"));
	track[0].push(new TrackPoint(35.401835, 139.533252, 23.888, 18, 0, 0, "Sun May 24 2026 11:45:16"));
	drawTrack(0, '#FF0000', 3, 0.70);
}

function TrackPoint(lat, lon, dist, height, hr, cad, time) {
	this.latlng = L.latLng(lat, lon);
	this.dist = parseFloat(dist);
	this.height = parseInt(height);
	this.hr = parseInt(hr);
	this.cad = parseInt(cad);
	this.time = new Date(time);
}

function drawTrack(n, color, width, opacity) {
	var tp = new Array();
	var i;
	for (i=0; i<track[n].length; i++) {
		tp.push(track[n][i].latlng);
	}

	var trackPath = L.polyline(tp, {
		color: color,
		opacity: opacity,
		weight: width
	});

	trackPath.addTo(map);
}

function drawRoute(color, width, opacity) {
	var routePath = L.polyline(route, {
		color: color,
		opacity: opacity,
		weight: width
	});

	routePath.addTo(map);
}

function drawWaypoints(showDate, showTime, showLocation, showHeight) {
	var i;
	for (i=0; i<waypoints.length; i++) {
		markers[i] = createMarker(waypoints[i], showDate, showTime, showLocation, showHeight);
	}
}

function setIcon() {
	var imgPath = "https://maps.google.com/mapfiles/ms/icons/";

	var MyIcon = L.Icon.extend({
		options: {
			shadowUrl: imgPath + "msmarker.shadow.png",
			iconSize:     [32, 32],
			shadowSize:   [59, 32],
			iconAnchor:   [16, 31],
			shadowAnchor: [16, 31],
			popupAnchor:  [0, -32]
		}
	});

	markerIcon[0] = new MyIcon({iconUrl: imgPath + "red.png"});
	markerIcon[1] = new MyIcon({iconUrl: imgPath + "orange.png"});
	markerIcon[2] = new MyIcon({iconUrl: imgPath + "yellow.png"});
	markerIcon[3] = new MyIcon({iconUrl: imgPath + "green.png"});
	markerIcon[4] = new MyIcon({iconUrl: imgPath + "blue.png"});
	markerIcon[5] = new MyIcon({iconUrl: imgPath + "pink.png"});
	markerIcon[6] = new MyIcon({iconUrl: imgPath + "lightblue.png"});
	markerIcon[7] = new MyIcon({iconUrl: imgPath + "red-dot.png"});
	markerIcon[8] = new MyIcon({iconUrl: imgPath + "orange-dot.png"});
	markerIcon[9] = new MyIcon({iconUrl: imgPath + "yellow-dot.png"});
	markerIcon[10] = new MyIcon({iconUrl: imgPath + "green-dot.png"});
	markerIcon[11] = new MyIcon({iconUrl: imgPath + "blue-dot.png"});
	markerIcon[12] = new MyIcon({iconUrl: imgPath + "pink-dot.png"});
	markerIcon[13] = new MyIcon({iconUrl: imgPath + "ltblue-dot.png"});
}

function MarkerInfo(lat, lon, height, date, time, icon, name, image, url, desc, largeImage) {
	this.point = L.latLng(parseFloat(lat), parseFloat(lon));
	this.height = parseInt(height);
	this.date = date;
	this.time = time;
	this.icon = icon;
	this.name = name;
	this.image = image;
	this.url = url;
	this.desc = desc;
	this.largeImage = largeImage;
}
MarkerInfo.prototype.getHtml = MarkerInfo_getHtml;

function MarkerInfo_getHtml(showDate, showTime, showLocation, showHeight, imageLoaded) {
	var html;

	html = '<div class="marker">';
	html += '<div class="marker_subject">' + this.name + '</div>';
	if (showDate || showTime) {
		html += '<div class="marker_time">';
		if (showDate) {
			html += this.date;
		}
		if (showTime) {
			if (showDate) {
				html += '&nbsp;';
			}
			html += this.time;
		}
		html += '</div>';
	}
	if (showLocation || showHeight) {
		html += '<div class="marker_location">';
		if (showLocation) {
			var prefix_lat = (this.point.lat >= 0) ? 'N' : 'S';
			var prefix_lon = (this.point.lng >= 0) ? 'E' : 'W';
			html += '(' + prefix_lat + Math.abs(this.point.lat).toFixed(6) + ', ' + prefix_lon + Math.abs(this.point.lng).toFixed(6) + ')';
		}
		if (showHeight) {
			if (showLocation) {
				html += '&nbsp;';
			}
			html += '高度' + this.height + 'm';
		}
		html += '</div>';
	}
	if (this.image != '') {
		var ext = getFileExt(this.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			if (imageLoaded) {
				if (this.largeImage != '') {
					html += '<div class="marker_image"><a href="' + this.largeImage + '" target="largeImage"><img src="' + this.image + '" /></a></div>';
				}
				else {
					html += '<div class="marker_image"><img src="' + this.image + '" /></div>';
				}
			}
		}
		else {
			html += '<div class="marker_url"><a href="' + this.image + '" target="refer">関連ファイル</a></div>';
		}
	}
	if (this.url != '') {
		html += '<div class="marker_url"><a href="' + this.url + '" target="refer">関連リンク</a></div>';
	}
	if (this.desc != '') {
		html += '<div class="marker_desc">' + this.desc + '</div>';
	}
	html += '</div>';

	return html;
}

function createMarker(markerInfo, showDate, showTime, showLocation, showHeight) {
	var marker = L.marker(markerInfo.point, {
		title: markerInfo.name,
		icon: markerIcon[markerInfo.icon],
	}).addTo(map);

	if (markerInfo.image != "") {
		var ext = getFileExt(markerInfo.image);
		if (ext == 'jpg' || ext == 'jpeg' || ext == 'gif' || ext == 'png') {
			var image = new Image();
			image.src = markerInfo.image;
			if (image.complete) {
				marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
			}
			else {
				image.onload = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, true), {maxWidth: 900});
				}
				image.onerror = function() {
					marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
				}
			}
		}
		else {
			marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
		}
	}
	else {
		marker.bindPopup(markerInfo.getHtml(showDate, showTime, showLocation, showHeight, false), {maxWidth: 900});
	}

	return marker;
}

function popupMarker(num) {
	markers[num].fireEvent("click");
}

function getFileExt(filepath) {
	var strArray = filepath.split('.');
	return strArray[strArray.length - 1].toLowerCase();
}

function paddingZero(value, n) {
	// n < 13
	var str = value + "";
	str = "0000000000000".substr(0, (n - str.length)) + str;

	return str;
}

function paddingSpace(value, n) {
	// n < 11
	var str = value + "";
	str = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".substr(0, 6 * (n - str.length)) + str;

	return str;
}

function getBrowser() {
	var agent = navigator.userAgent;

	if (agent.indexOf('Safari') >= 0) {
		return 'Safari';
	}
	else if (agent.indexOf('Opera') >= 0) {
		return 'Opera';
	}
	else if (agent.indexOf('Gecko') >= 0) {
		return 'Mozilla';
	}
	else if (agent.indexOf('MSIE') >= 0) {
		return 'MSIE';
	}
	else {
		return 'other';
	}
}

function playRoute() {
	var count = 0;
	for (i=0; i<track.length; i++) {
		count += track[i].length;
	}

	if (count > 1 && !playing) {
		centerPointer.addTo(map);

		if (showMeterPanel) {
			infoPanel = new InfoPanel();
			map.addControl(infoPanel);
		}

		playing = true;
		goForward();
	}
}

function goForward() {
	var waittime;
	var pos = track[currTrack][currPoint].latlng;
	map.panTo(pos);
	centerPointer.setLatLng(pos);

	if (showMeterPanel) {
		displayInfoPanel(currTrack, currPoint);
	}

	if (currPoint < track[currTrack].length - 1) {
		if (realTimePlay) {
			waittime = track[currTrack][currPoint+1].time.getTime() - track[currTrack][currPoint].time.getTime();
			waittime /= parseFloat(document.getElementById("playSpeed").value);
		}
		else {
			waittime = 1000 / parseFloat(document.getElementById("playSpeed").value);
		}
		currPoint++;
	}
	else {
		if (currTrack < track.length - 1) {
			waittime = 1000;
			currTrack++;
			currPoint = 0;
		}
		else {
			window.clearTimeout(playTimer);
			playing = false;
			centerPointer.remove();

			if (showMeterPanel) {
				map.removeControl(infoPanel);
			}

			return;
		}
	}
	playTimer = window.setTimeout("goForward()", waittime);
}

function stopRoute() {
	if (playing) {
		window.clearTimeout(playTimer);
		playing = false;
		centerPointer.remove();

		if (showMeterPanel) {
			map.removeControl(infoPanel);
		}
	}
}

function rewindRoute() {
	currTrack = 0;
	currPoint = 0;
	map.panTo(track[currTrack][currPoint].latlng);
}

function prevTrack() {
	if (currTrack > 0) {
		currTrack--;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

function nextTrack() {
	if (currTrack < track.length - 1) {
		currTrack++;
		currPoint = 0;
		map.panTo(track[currTrack][currPoint].latlng);
	}
}

var InfoPanel = L.Control.extend({
	options: {
        	position: "bottomright"
	},

	onAdd: function(map) {
		var container = document.createElement('div');
		container.style.padding = '5px';

		var outerFrame = document.createElement('div');
		outerFrame.style.width = '240px';
		outerFrame.style.height = '70px';
		if (getBrowser() == 'MSIE') {
			outerFrame.style.backgroundColor = '#FFFFFF';
		}
		else {
			outerFrame.style.backgroundColor = 'rgba(255, 255, 255, 0.65)';
		}
		outerFrame.style.border = '1px solid black';
		outerFrame.innerHTML = '<div id="time"></div><div id="speed"></div><div id="height"></div>';
		container.appendChild(outerFrame);
		return container;
	},

	writeTime: function(date) {
		var hour = paddingZero(date.getHours(), 2);
		var min = paddingZero(date.getMinutes(), 2);
		var sec = paddingZero(date.getSeconds(), 2);
		var timePanel = document.getElementById("time");
		timePanel.innerHTML = '時刻：' + hour + ':' + min + ':' + sec;
	},

	writeSpeed: function(distance, speed) {
		var speedPanel = document.getElementById("speed");
		var distStr = paddingSpace(distance.toFixed(2), 7);
		var speedStr = paddingSpace(speed.toFixed(1), 6);
		speedPanel.innerHTML = '距離：' + distStr + 'km&nbsp;&nbsp;速度：' + speedStr + 'km/h';
	},

	writeHeight: function(height, gradient) {
		var heightStr = paddingSpace(height, 5);
		var gradStr = paddingSpace(Math.abs(gradient).toFixed(1), 4);
		if (gradient >= 0) {
			gradStr = '↑' + gradStr;
		}
		else {
			gradStr = '↓' + gradStr;
		}
		var heightPanel = document.getElementById("height");
		heightPanel.innerHTML = '高度：' + heightStr + 'm&nbsp;&nbsp;勾配：' + gradStr + '%';
	}
});

function displayInfoPanel(ntrack, npoint) {
	infoPanel.writeTime(track[ntrack][npoint].time);
	
	var distance = 0;
	var speed = 0;
	var timespan;
	var gradient = 0;
	var elevation;
	if (npoint > 0) {
		distance = track[ntrack][npoint].dist - track[ntrack][npoint - 1].dist;
		timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint - 1].time.getTime();
		elevation = track[ntrack][npoint].height - track[ntrack][npoint - 1].height;
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
		if (distance > 0) {
			gradient = elevation / distance / 10;
		}
	}
	speed = Math.round(speed * 10) / 10;

	infoPanel.writeSpeed(track[ntrack][npoint].dist,speed);
	infoPanel.writeHeight(track[ntrack][npoint].height,gradient);
}

function calcSpeed(ntrack, npoint) {
	var speed = 0;
	if (npoint > 0) {
		var distance = track[ntrack][npoint].dist - track[ntrack][npoint-1].dist;
		var timespan = track[ntrack][npoint].time.getTime() - track[ntrack][npoint-1].time.getTime();
		if (timespan > 0) {
			speed = 3600000 * distance / timespan;
		}
	}

	return speed;
}
